### ISSUE TITLE
微调minicpmv2时cpu占用率超高

### ISSUE THREAD

**Issue by strawhatboy** [modelscope/ms-swift#1008]
**Describe the bug**
使用swift sft命令指定dataset 和val_dataset 进行微调:
```bash
CUDA_VISIBLE_DEVICES=0 swift sft --model_type minicpm-v-v2-chat
```
20 个核心全部占用60%左右
![image](https://github.com/modelscope/swift/assets/2800905/ee1f76d8-c434-4507-b41b-89c1d3bb6004)

**Your hardware and system info**
CUDA：12.2
系统：Ubuntu22.04
GPU：RTX4090
Torch：2.2.2

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
用最新代码试试，感觉不复现的说
