### ISSUE TITLE
bitsandbytes was compiled without GPU support

### ISSUE THREAD

**Issue by stellarxxu** [modelscope/ms-swift#1031]
I have installed cudatoolkit12.2 in Windows 11. 

I followed the instructions to install "pip install 'ms-swift[all]' -U" in the conda environment. 

The installation was successful and I can start the webui normally. However, when I start it, it prompts "The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable." After entering the webui, I found that there is only cpu. 

Can you tell me which version of cudatoolkit I need to install?

<img width="1081" alt="image" src="https://github.com/modelscope/swift/assets/130619567/ff657afb-4ddf-42c6-8879-0cbcc980ae56">

**Comment by tastelikefeet** [comment]
Seems your torch version is not compatible with CUDA driver
check 
`python -c 'import torch; torch.cuda.is_available()'`
