### ISSUE TITLE
swift微调多模态大模型后，比如Intern VL 1.5，可以使用lmdeploy部署吗？

### ISSUE THREAD

**Issue by wangdong1992** [modelscope/ms-swift#1033]

**Comment by Jintao-Huang** [comment]
已经支持多模态部署：https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/MLLM%E9%83%A8%E7%BD%B2%E6%96%87%E6%A1%A3.md

**Comment by Jintao-Huang** [comment]
imdeploy的接入还要再等等，现在是原生pytorch

**Comment by tastelikefeet** [comment]
已支持lmdeploy
