### ISSUE TITLE
如何批量导出MS数据集为swift能加载的格式

### ISSUE THREAD

**Issue by WSC741606** [modelscope/ms-swift#1041]
如题，离线训练模型需要先在有网的地方下载后迁移，但是迁移后镜像加载的swift默认读取位置不在用户文件夹下，我要怎么把数据迁移过去？能怎么把ModelScope的数据集导出成jsonl或者csv格式，从而能从自定义数据集的模式加载？

**Comment by wangxingjun778** [comment]
尝试使用如下命令：
