### ISSUE TITLE
随机初始化预训练

### ISSUE THREAD

**Issue by JiwenJ** [modelscope/ms-swift#1045]
请问目前支持随机初始化预训练吗

**Comment by tastelikefeet** [comment]
可以参考自定义模型：https://swift.readthedocs.io/zh-cn/latest/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.html#id6
另外，我们目前支持了megatron预训练：
https://swift.readthedocs.io/zh-cn/latest/LLM/Megatron%E8%AE%AD%E7%BB%83%E6%96%87%E6%A1%A3.html
