### ISSUE TITLE
不太明白Lisa为何能够节省显存，希望能够帮忙解答

### ISSUE THREAD

**Issue by ymsdu2004** [modelscope/ms-swift#1056]
lisa虽然每次训练的参数量变小了，但是因为整个训练过程中所有层都可能参与训练，所以在optimzer中维护了所有的参数及其优化器状态，所以相对普通的full sft，lisa并没有节省显存？除非对optimzer进行改造，但是代码中并没有看到任何optimizer相关的改动。

**Comment by tastelikefeet** [comment]
full之后lisa会随机激活部分层，因此其它层处于freeze状态，显存就会减小
