### ISSUE TITLE
[Help]请问MiniCPM2.5支持Web端交互推理吗？

### ISSUE THREAD

**Issue by Egber1t** [modelscope/ms-swift#1060]
用vllm如下命令，显示不支持MiniCPM-2.5
CUDA_VISIBLE_DEVICES=0 swift app-ui --model_type minicpm-v-v2_5-chat--infer_backend vllm
然后在swift的gradio端口中也没有找到如何进行粘贴或者上传图片，进行推理，求解答谢谢！

**Comment by wangdong1992** [comment]
me too

**Comment by tastelikefeet** [comment]
支持，请使用最新版本
