### ISSUE TITLE
又测了下，您说的最新的代码是指加了if batch[0].get('pixel_values') is not None:这个判断语句吗，在batch>1的情况下，还是会出现keyerror的

### ISSUE THREAD

**Issue by qzDiao** [modelscope/ms-swift#1061]
又测了下，您说的最新的代码是指加了if batch[0].get('pixel_values') is not None:这个判断语句吗，在batch>1的情况下，还是会出现keyerror的

_Originally posted by @qzDiao in https://github.com/modelscope/swift/issues/1051#issuecomment-2146418749_

**Comment by tastelikefeet** [comment]
使用最新代码试一下，应该都修复了
