### ISSUE TITLE
swift训练minicpm-v如何设置grounding格式

### ISSUE THREAD

**Issue by daihuidai** [modelscope/ms-swift#1077]
你好，在minicpm-v官方中设置目标坐标点可以使用下面的方式添加：
1. <point>x1 y1</point>
2. <box>xmin ymin xmax ymax<box>
3. <quad>x1 y1 x2 y2 x3 y3 x4 y4<quad>

请问使用swift来微调minicpm-v的训练集中应该按照什么格式来设置相关坐标点呢

**Comment by tastelikefeet** [comment]
能否给一下minicpm-v设置grounding的来源？
我看到的是：https://github.com/OpenBMB/MiniCPM-V/issues/202
似乎不太支持grounding

**Comment by daihuidai** [comment]
@tastelikefeet 下载的huggingface模型文件中的py文件有对定位框特殊字符的处理代码。
而且他们官网的issue中有个内部成员给出了对框的设计，我上面就是参考py文件和那个人的建议
