### ISSUE TITLE
请问有多模态模型可以实现few-shot（in-context）数据的微调吗？

### ISSUE THREAD

**Issue by waltonfuture** [modelscope/ms-swift#1094]
如题。

**Comment by waltonfuture** [comment]
@Jintao-Huang 作者您好！我看到只有部分多模态模型可以支持in-context输入。请问可以支持更多模型的in-context输入吗？谢谢！

**Comment by tastelikefeet** [comment]
in-context我理解应该是数据集的配置吧，理论上所有的模型都可以支持的
