### ISSUE TITLE
关于VLM的评测支持

### ISSUE THREAD

**Issue by Wimen** [modelscope/ms-swift#1117]
文档里在评测模块提到支持两种pattern的评测集：选择题格式的CEval和问答题格式的General-QA，General-QA的格式暂不包含对图片的支持，请问后续计划加入VLM的评测功能吗

**Comment by wangxingjun778** [comment]
计划6月下旬会增加多模态评测的支持。

**Comment by tastelikefeet** [comment]
已经支持，请使用最新版本

**Comment by dashengge** [comment]
想问一下generalQA的测评只支持jsonl格式吗，因为我目前没看见关于VLM的自定义数据集测评：https://swift.readthedocs.io/zh-cn/latest/Instruction/%E8%AF%84%E6%B5%8B.html
