### ISSUE TITLE
能否基于lora或llamapro实现增量学习

### ISSUE THREAD

**Issue by QDPeng** [modelscope/ms-swift#1123]
**Describe the feature**

1. 首先用A数据和基础模型（qwen1.5-4b）进行lora微调训练，然后融合导出
2. 然后使用融合后的基础模型和B数据再次lora微调训练，最后融合导出
3. 最后导出后的增量模型能够同时拥有A和B数据领域的知识

目前测试没有实际效果

不知道能否实现这种增量训练？
谢谢

**Comment by tastelikefeet** [comment]
可以的，只需要训练两次：
1. --sft_type lora，使用A数据训练，训练后merge_lora
2. --sft_type lora，使用B数据训练，训练后merge_lora
llamapro目前还不支持合并操作，lora是可以的。
还有一种方法，就是AB数据直接混合，一起训练也没问题。
说的没有效果具体是指？

**Comment by QDPeng** [comment]
请问你用的是哪个模型？我用qwen1.5-4b-chat模型，数据是lawyer-zh和cot-zh，分别取了5千条进行微调测试，效果不理想

> 可以的，只需要训练两次：
> 
> 1. --sft_type lora，使用A数据训练，训练后merge_lora
> 2. --sft_type lora，使用B数据训练，训练后merge_lora
>    llamapro目前还不支持合并操作，lora是可以的。
>    还有一种方法，就是AB数据直接混合，一起训练也没问题。
>    说的没有效果具体是指？

**Comment by tastelikefeet** [comment]
4b模型太小了，而且5000条也少，尝试用更大的模型和更多的数据

**Comment by tastelikefeet** [comment]
另外llamapro模型已经支持在swift export中进行合并

**Comment by xiaoxuanyo** [comment]
> 另外llamapro模型已经支持在swift export中进行合并

你好 请问下llamapro的模型怎么融合导出呀
