### ISSUE TITLE
Process hang with futex(0x7f403c0199d0, FUTEX_WAIT, 14826, NULL

### ISSUE THREAD

**Issue by QiMingChina** [modelscope/ms-swift#1128]
硬件信息：
![image](https://github.com/modelscope/swift/assets/48780003/8dd13a05-f881-4eb1-85d0-0f2343c04cfd)

环境信息：
Python 3.11.9
torch 2.1.1
CUDA 12.1
ms-swift 2.2.0.dev0

执行脚本：
```
CUDA_VISIBLE_DEVICES=1 swift sft \
    --model_type chinese-llama-2-7b \
    --model_id_or_path /data/public/qim/model/chinese-llama-2-7b \
    --dataset school-math-zh \
    --output_dir /data/public/qim/script/swift/sft \
```

现象：
![image](https://github.com/modelscope/swift/assets/48780003/f65350e4-df8b-462a-9515-3dbae54f242a)
卡在这里长时间没反应

查看进程
![image](https://github.com/modelscope/swift/assets/48780003/57b63b50-200a-4308-ae80-73e655832eaf)

追踪进程：
strace -p 14770
![image](https://github.com/modelscope/swift/assets/48780003/01ac79d8-99db-468e-bc7a-c7f064593afb)
strace -p 9471
![image](https://github.com/modelscope/swift/assets/48780003/e8de8da6-c441-4779-a49d-b20a3f3b8b74)

**Comment by tastelikefeet** [comment]
这个问题比较奇怪，仍然能复现吗?

**Comment by slin000111** [comment]
没有复现，可能是机器的原因
