### ISSUE TITLE
请问swift训练MiniCPM-v2.0时应该如何制作带坐标的数据集

### ISSUE THREAD

**Issue by daihuidai** [modelscope/ms-swift#1137]
请问应该如何制作定位目标的数据集，坐标是**如何归一化**，通过什么**标志符加载**，例如 box> x y x y </box，还是其它什么方式呢？
不知道是否可以给个简单的代码样例。

**Comment by tastelikefeet** [comment]
目前看起来minicpm本身并不支持：https://github.com/OpenBMB/MiniCPM-V/issues/202
