### ISSUE TITLE
量化训练qwen2-72b-instruct 的权重突入中断

### ISSUE THREAD

**Issue by lxb0425** [modelscope/ms-swift#1151]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
使用2*A100对wen2-72b-instruct训练，完成后执行量化4位命令，一直无故中断，同步看显存还有很多
执行命令CUDA_VISIBLE_DEVICES=0,1 swift export     --ckpt_dir '/workspace/sdata/qwen2-72b-instruct/v1-20240613-072850/checkpoint-132/'     --merge_lora true --quant_bits 4     --load_dataset_config true --quant_method gptq
![image](https://github.com/modelscope/swift/assets/50564015/9db1be72-cc0f-4b1b-83ea-d3b7f56057a0)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

cuda=12.1
**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
增加OMP_NUM_THREADS=14环境变量试一下
