### ISSUE TITLE
GLM4v使用Lora模型微调后，merge模型后运行报错，

### ISSUE THREAD

**Issue by hyyuan123** [modelscope/ms-swift#1163]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

使用CUDA_VISIBLE_DEVICES=0 swift infer     --ckpt_dir output/glm4v-9b-chat/v1-20240617-191301/checkpoint-150-merged/     --load_dataset_config true 运行程序，报错：
![image](https://github.com/modelscope/swift/assets/38377775/cd700b0f-5fc0-4dd1-8906-983595291b69)
但是直接使用命令CUDA_VISIBLE_DEVICES=0 swift infer     --ckpt_dir output/glm4v-9b-chat/v1-20240617-191301/checkpoint-150   --load_dataset_config true 运行程序，则正常运行，没有报错
之前使用框架训练internvl-v1.5版本的模型，训练和测试均无问题，想问一下出现问题的原因。怎么修改

**Comment by tastelikefeet** [comment]
用的swift版本是什么

**Comment by XuRui314** [comment]
请问你的loss是正常的吗

https://github.com/modelscope/swift/issues/1091#issuecomment-2157788336

**Comment by WEIC-7** [comment]
请问这个问题解决了吗，我也遇上了这个问题。
我是参考：
**https://github.com/We-IOT/chatglm3_6b_finetune/blob/main/model_export_hf..py** 进行lora后模型合并。
合并后模型推理正常，但是继续微调时会出现同样的错误。

**Comment by WEIC-7** [comment]
> 请问这个问题解决了吗，我也遇上了这个问题。 我是参考： **https://github.com/We-IOT/chatglm3_6b_finetune/blob/main/model_export_hf..py** 进行lora后模型合并。 合并后模型推理正常，但是继续微调时会出现同样的错误。

已经解决，需要注意合并后的tokenizer_config.json 中image_size 参数，如果没有需要加上

**Comment by Jintao-Huang** [comment]
GLM4v的微调请使用swift>=2.2
