### ISSUE TITLE
关于"自我认知微调最佳实践"和"自定义模型和数据集"的说明优化

### ISSUE THREAD

**Issue by ivandgetic** [modelscope/ms-swift#1176]
感觉文档写的不错，但是还有一些内容对新手不太友好。
在“自我认知微调最佳实践”里面，有使用python进行 微调前推理→微调→微调后推理 的操作，确实可以让他回答我是小黄。
但是案例里面的穿插着使用数据集，这个数据集是要上网下载的，如果使用自定义数据集，要去看"自定义模型和数据集"。
结果看完"自定义模型和数据集"，完全不知道这两者要怎么结合起来
希望增加一篇  微调前推理→微调自定义数据集→微调后推理  的内容，且数据集是在本地的，这样不仅仅可以问他“你是谁”，还可以针对性的微调，比如设定 RTX4090D售价12999元的自定义数据集，然后问他RTX4090D多少钱，或者问12999元价位的是哪款显卡

**Comment by tastelikefeet** [comment]
我理解一下，是需要使用自定义数据集进行自我认知微调吗

**Comment by ivandgetic** [comment]
算是吧，就是可以问他RTX4090D的售价，以及根据售价反推出来时RTX4090D，然后也可以问他4080、4070，甚至3090显卡等。
可以通过型号回答出价格，亦可通过价格回答出显卡型号。

**Comment by tastelikefeet** [comment]
后来有个解释自定义数据集的视频：https://swift.readthedocs.io/zh-cn/latest/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.html
可以参考这个
