### ISSUE TITLE
glm4v微调到一半会显示网络问题，请问有其他加载本地输入的方法吗

### ISSUE THREAD

**Issue by Nanuion** [modelscope/ms-swift#1185]
Max retries exceeded with url: /coco/2014/val2014/COCO_val2014_000000151651.jpg (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdd12b502e0>: Failed to establish a new connection: [Errno 99] Cannot assign requested address'

**Comment by tastelikefeet** [comment]
使用的是什么数据集呢

**Comment by Summer-nan** [comment]
coco-en-2-mini 这个数据集

**Comment by tastelikefeet** [comment]
感觉是这个jpg本地不存在，后来我们重构了一版本数据集加载逻辑，可以重新试一下，如果仍然有问题可以打开此issue
