### ISSUE TITLE
Qwen-VL-Chat全参精调后无法输出eos_token

### ISSUE THREAD

**Issue by zodiacg** [modelscope/ms-swift#1215]
**Describe the bug**
对Qwen-VL-Chat进行全参微调（冻结visual部分，训练模块：`transformer.visual.proj transformer.visual.attn_pool transformer.h transformer.ln_f transformer.wte lm_head`），模型丧失输出eos_token能力，在正常回复后开始输出随机内容。

**Your hardware and system info**
CUDA 11.8
ms-swift: 2.1.0
transformers: 4.40.2

**Additional context**
* 之前版本使用swift训练正常（不太确定是2.0.1还是2.0.5或更早版本了，sft_args里只记录了transformers的版本）。
* 当前版本如果只训练``transformer.visual.proj transformer.visual.attn_pool`能够部分保持正常。
* 检查了训练数据集截断情况和数据处理情况，确定最后输入模型的input_ids和labels中均包含且仅包含一个eos_token。
* 目前在尝试冻结transformer.wte lm_head进行训练，但因为训练数据包含比较丰富的领域内容，应当只是权宜之计。

**Comment by tastelikefeet** [comment]
请问训练使用的数据集是图文对数据集吗？还是图文对数据集+文本数据集混合呢

**Comment by zodiacg** [comment]
> 请问训练使用的数据集是图文对数据集吗？还是图文对数据集+文本数据集混合呢

图文对+文本混合。但考虑到Qwen-VL-Chat的图像载入方式……这个应该不会有影响？之前混合训过一次也是正常的

**Comment by tastelikefeet** [comment]
我用图文对训练了一遍qwen-vl-chat，并没有出现eos_token不输出的问题。。
![20240628111350](https://github.com/modelscope/swift/assets/58414341/c540504d-5612-4466-8543-18138c259ed4)

**Comment by tastelikefeet** [comment]
用的是最新的代码，完整命令行是这样的：
```shell
NPROC_PER_NODE=4 \
swift sft \
    --model_type qwen-vl-chat \
    --sft_type full \
    --template_type AUTO \
    --dtype AUTO \
    --output_dir output \
    --dataset llava-instruct-150k#100000 \
    --train_dataset_sample -1 \
    --num_train_epochs 1 \
    --max_length 4096 \
    --check_dataset_strategy warning \
    --gradient_checkpointing true \
    --batch_size 2 \
    --weight_decay 0.1 \
    --learning_rate 5e-5 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 500 \
    --save_steps 500 \
    --save_total_limit 4 \
    --logging_steps 10 \
    --use_flash_attn true \
    --ddp_find_unused_parameters true \
    --freeze_parameters 1.0 \
    --deepspeed default-zero3 \
    --additional_trainable_parameters transformer.visual.proj transformer.visual.attn_pool transformer.h transformer.ln_f transformer.wte lm_head
```
