### ISSUE TITLE
之前用命令进行chatglm3进行swif训练，能够训练成功现在训练一会就报错内存已经满了 是什么原因

### ISSUE THREAD

**Issue by CmyLjj** [modelscope/ms-swift#1230]
**Describe the bug**
[ERROR:swift] There are error run git command.
/data2/caomy/envs/llm_inference/lib/python3.10/site-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False)
  warnings.warn(
[INFO:swift] The SftArguments will be saved in: /data1/caomy/Html_infomation_extract/finetune_task1_task3/output/data_task3_total_swif_20240626/chatglm3-6b/v0-20240626-155144/sft_args.json
[INFO:swift] The Seq2SeqTrainingArguments will be saved in: /data1/caomy/Html_infomation_extract/finetune_task1_task3/output/data_task3_total_swif_20240626/chatglm3-6b/v0-20240626-155144/training_args.json
[INFO:swift] The logging file will be saved in: /data1/caomy/Html_infomation_extract/finetune_task1_task3/output/data_task3_total_swif_20240626/chatglm3-6b/v0-20240626-155144/logging.jsonl
{'loss': 0.9921875, 'acc': 0.85889566, 'learning_rate': 1.5e-07, 'epoch': 0.0, 'global_step': 1}                                                                                                                                        
Train:   0%|▎                                                                                                                                                                                      | 32/21820 [00:10<1:43:14,  3.52it/s]Traceback (most recent call last):
  File "/data1/caomy/Html_infomation_extract/finetune_task1_task3/llm_sft.py", line 6, in <module>
    output = sft_main()
  File "/data2/caomy/envs/llm_inference/lib/python3.10/site-packages/swift/utils/run_utils.py", line 31, in x_main
    result = llm_x(args, **kwargs)
  File "/data2/caomy/envs/llm_inference/lib/python3.10/site-packages/swift/llm/sft.py", line 277, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/data2/caomy/envs/llm_inference/lib/python3.10/site-packages/swift/trainers/trainers.py", line 44, in train
    super().train(*args, **kwargs)
  File "/data2/caomy/envs/llm_inference/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/data2/caomy/envs/llm_inference/lib/python3.10/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data2/caomy/envs/llm_inference/lib/python3.10/site-packages/transformers/trainer.py", line 2781, in training_step
    self.accelerator.backward(loss)
  File "/data2/caomy/envs/llm_inference/lib/python3.10/site-packages/accelerate/accelerator.py", line 2001, in backward
    loss.backward(**kwargs)
  File "/data2/caomy/envs/llm_inference/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/data2/caomy/envs/llm_inference/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 9.64 GiB. GPU 0 has a total capacty of 23.65 GiB of which 9.37 GiB is free. Including non-PyTorch memory, this process has 14.27 GiB memory in use. Of the allocated memory 13.14 GiB is allocated by PyTorch, and 687.95 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Your hardware and system info**

# Experimental environment: V100, A10, 3090
# 16GB GPU memory
zheh
CUDA_VISIBLE_DEVICES=2 \
python llm_sft.py \
    --model_id_or_path ZhipuAI/chatglm3-6b \
    --model_cache_dir /data2/common/pretrain_models/chatglm3-6b \
    --model_revision master \
    --sft_type lora \
    --tuner_backend swift \
    --template_type chatglm3 \
    --dtype AUTO \
    --output_dir output/data_task3_total_swif_20240626 \
    --custom_train_dataset_path /data1/caomy/chatglm3-demo/finetune_demo/data/train.jsonl \
    --custom_val_dataset_path /data1/caomy/chatglm3-demo/finetune_demo/data/dev.jsonl \
    --train_dataset_sample -1 \
    --num_train_epochs 10 \
    --max_length 5080 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.1 \
    --lora_target_modules DEFAULT \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 1 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --max_new_tokens 512 \
    --eval_steps 2000 \
    --save_steps 200 \
    --save_total_limit 50 \
    --logging_steps 100 \
    --push_to_hub false \
    --hub_model_id chatglm3-6b-lora \
    --hub_private_repo true \
    --hub_token 'your-sdk-token' \

#    swift merge-lora --ckpt_dir '/data1/caomy/chatglm3-demo/finetune_demo/output/data_tid_8000_swif_20240423/chatglm3-6b/v1-20240424-153254/checkpoint-4000' --model_cache_dir '/data2/common/pretrain_models/chatglm3-6b' --save_safetensors False

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
padding方式是longest，因此batch中最长的sequence会导致显存使用增加
考虑缩小--max_length 参数
