### ISSUE TITLE
The acc is different when infering a glm4v model trained based on the Tutorial

### ISSUE THREAD

**Issue by woaipichuli** [modelscope/ms-swift#1258]
I trained a model based on the Tutorial
https://github.com/modelscope/swift/blob/main/docs/source_en/Multi-Modal/glm4v-best-practice.md

the acc on eval dataset is 0.86 and the task is to do choice question. Why the acc is quite different and many answer is wrong when inferring?

train command:
CUDA_VISIBLE_DEVICES=0 swift sft     --model_id_or_path glm-4v-9b --model_type glm4v-9b-chat     --batch_size 32    --num_train_epochs 2 --dataset dataset/test/train.jsonl --val_dataset dataset/test/train.jsonl

infer command:
CUDA_VISIBLE_DEVICES=0 swift infer \
    --ckpt_dir output/glm4v-9b-chat/v12-20240629-123943/checkpoint-600 \
    --load_dataset_config true

**Comment by Jintao-Huang** [comment]
Is the main branch being used?
