### ISSUE TITLE
Not working with python virtualenv

### ISSUE THREAD

**Issue by heinrichI** [modelscope/ms-swift#1266]
**Describe the bug**
I'm creating a virtual environment, like: python -m venv myenv. Installing dependencies. Installing ms-swift. And for any action there are a lot of errors, since the python installed on the system is launched, and since ms-swift is not installed in it, nothing will start. And even if I correct the path at startup, there is still an error, because the command line is being parsed like this function: parse_info_from_cmdline.

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
Windows 10, python 3.10, torch 2.3.1+cu121

**Comment by tastelikefeet** [comment]
Is there any detail error logs?
Meanwhile, we suggest to use conda/miniconda/miniforge to create a virtual env indead if possible.
