### ISSUE TITLE
微调模型报错

### ISSUE THREAD

**Issue by eagleLiu82** [modelscope/ms-swift#1296]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
运行命令：
CUDA_VISIBLE_DEVICES=0 \
swift sft \
    --model_type qwen1half-7b-chat \
    --dataset blossom-math-zh \
    --num_train_epochs 5 \
    --sft_type lora \
    --output_dir output
![20240704-193707](https://github.com/modelscope/swift/assets/20007468/415c000e-9a6a-4e04-8436-29009bcedee0)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
显存不够
