### ISSUE TITLE
可否缓存预处理后的数据集？

### ISSUE THREAD

**Issue by zodiacg** [modelscope/ms-swift#1315]
**Describe the feature**
目前swift会在训练前对各个样本进行预处理。能否对预处理后的数据集进行缓存以减少重训练时在数据处理上消耗的时间？

我编写了一个自定义的多模态模型，因为采用以token代表图像的方法，使用懒处理会有可能出现不恰当位置截断或因为超长而爆显存的风险，所以需要训练前预处理。由于在预处理过程中需要获取图像信息，预处理过程比较慢。之前用xtuner训练llava时有类似问题，xtuner提供了缓存llava预处理训练集的方式。

虽然预处理过程和使用的数据集、模型和tokenizer参数强绑定，但这部分其实可以交由用户负责维护和确保一致性。

**Paste any useful information**
https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/llava_offline.md

**Additional context**
可否考虑增加batch级处理/预处理/懒处理选项？transformers的tokenizer/processor等设计普遍适用于batch处理

**Comment by tastelikefeet** [comment]
已支持 #1319

**Comment by zodiacg** [comment]
升级后尝试报了别的错误，我开个新issue吧

**Comment by oasis-0927** [comment]
swift 2.6.1 增加命令行参数好像对自定义数据集不生效？

**Comment by tastelikefeet** [comment]
2.x版本需要指定环境变量DATASET_ENABLE_CACHE=True，可能的话建议使用3.x版本

**Comment by PokeLu** [comment]
> 2.x版本需要指定环境变量DATASET_ENABLE_CACHE=True，可能的话建议使用3.x版本

请问一下3.0对应应该怎么写？
