### ISSUE TITLE
VLM是否支持并行推理？

### ISSUE THREAD

**Issue by youjiaSHTU** [modelscope/ms-swift#1330]
**Describe the feature**
Please describe the feature requested here(请在这里描述需求)

目前infer的方式和deploy部署，都是串行的。是否有某种方式可以实现并行对多条数据进行同时处理（为了加快速度）。
例如，我需要使用一个自己训练的模型（minicpm-v2.5-chat），对大约一万条文字提问+每个提问对应的一张图片进行推理并保存结果，最快的方式是什么？

**Comment by gjd2017** [comment]
同问，多模态大模型批量推理

**Comment by dengruoqing** [comment]
同问，目前swift支持minicpm-v2.5-chat的多卡推理吗？

**Comment by tastelikefeet** [comment]
目前已经支持了LmDeploy的多卡推理：
https://swift.readthedocs.io/zh-cn/latest/Multi-Modal/LmDeploy%E6%8E%A8%E7%90%86%E5%8A%A0%E9%80%9F%E6%96%87%E6%A1%A3.html
