### ISSUE TITLE
support VLLM for glm4v

### ISSUE THREAD

**Issue by demoninpiano** [modelscope/ms-swift#1337]
有啥办法，比如照vllm文档可以快速支持glm4v的vllm部署吗？

**Comment by Jintao-Huang** [comment]
vllm不支持glm4v. 可以试试lmdeploy.

swift也正在接这一推理加速框架，估计2天后merge入main

**Comment by Jintao-Huang** [comment]
已经支持vllm & vlm. 不过还是vllm目前不支持glm4v
