### ISSUE TITLE
CogVLM2 Video

### ISSUE THREAD

**Issue by josephzpng** [modelscope/ms-swift#1339]
**Describe the bug**

File "/home/hadoop-vacv/.cache/huggingface/modules/transformers_modules/cogvlm2-video-llama3-chat/visual.py", line 78, in forward
    output = self.dense(out.view(B, L, -1))
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

<img width="1364" alt="截屏2024-07-09 16 57 03" src="https://github.com/modelscope/swift/assets/90088227/7682e455-0705-4922-914c-32afcf75eb7f">

**Comment by Jintao-Huang** [comment]
The error is in the model file. Try upgrading torch to see if it resolves the issue.

**Comment by josephzpng** [comment]
Thank you for your reply. The old problem has been solved, but a new problem has arisen.
<img width="438" alt="截屏2024-07-10 15 47 24" src="https://github.com/modelscope/swift/assets/90088227/384bade3-9359-4f6f-8aad-43804c19c961">

I located the problem in the '_sample' function in transformers/generation/utils.py 
<img width="591" alt="截屏2024-07-10 15 50 12" src="https://github.com/modelscope/swift/assets/90088227/1431d913-78b6-4a92-ad23-3f33e52a1465">

But I don't know how to deal with it, 'llava-next-video-7b-instruct' uses transformers=4.2.0, which runs smoothly, but there is a problem with 'cogvlm2_video_13b_chat', which uses 4.1.0 as required.
Looking forward to your reply!

**Comment by josephzpng** [comment]
Thank you for your reply. The old problem has been solved, but a new problem has arisen.
<img width="438" alt="截屏2024-07-10 15 47 24" src="https://github.com/modelscope/swift/assets/90088227/384bade3-9359-4f6f-8aad-43804c19c961">

I located the problem in the '_sample' function in transformers/generation/utils.py 
<img width="591" alt="截屏2024-07-10 15 50 12" src="https://github.com/modelscope/swift/assets/90088227/1431d913-78b6-4a92-ad23-3f33e52a1465">

But I don't know how to deal with it, 'llava-next-video-7b-instruct' uses transformers=4.2.0, which runs smoothly, but there is a problem with 'cogvlm2_video_13b_chat', which uses 4.1.0 as required.
Looking forward to your reply!

**Comment by Jintao-Huang** [comment]
cogvlm2_video_13b_chat please use transformers==4.41.*

**Comment by josephzpng** [comment]
> cogvlm2_video_13b_chat please use transformers==4.41.*

Yes, I am using 4.41.0, but it still doesn't work. The torch version is 2.3.0+cuda118
