### ISSUE TITLE
关于agent微调数据问题

### ISSUE THREAD

**Issue by ccp123456789** [modelscope/ms-swift#1351]
请问这个数据集是不是质量很差https://modelscope.cn/datasets/iic/MSAgent-Bench
比如：
![image](https://github.com/modelscope/swift/assets/148857080/f624931c-de08-49d9-8075-52c068e11346)

很多都是这种，tools里面没有参数，但是答案里面却有。就像这个artist，前面定义的工具里面压根没有这个参数

**Comment by tastelikefeet** [comment]
建议看下这两个数据集：https://modelscope.cn/datasets/iic/ms_agent
和https://modelscope.cn/datasets/iic/MSAgent-Pro
这两个在swift中是支持的：https://swift.readthedocs.io/zh-cn/latest/LLM/%E6%94%AF%E6%8C%81%E7%9A%84%E6%A8%A1%E5%9E%8B%E5%92%8C%E6%95%B0%E6%8D%AE%E9%9B%86.html

**Comment by ccp123456789** [comment]
> 建议看下这两个数据集：https://modelscope.cn/datasets/iic/ms_agent 和https://modelscope.cn/datasets/iic/MSAgent-Pro 这两个在swift中是支持的：https://swift.readthedocs.io/zh-cn/latest/LLM/%E6%94%AF%E6%8C%81%E7%9A%84%E6%A8%A1%E5%9E%8B%E5%92%8C%E6%95%B0%E6%8D%AE%E9%9B%86.html

有针对qwen2 function call风格的数据吗？ 目前来看，数据标注的function call语料都是react风格。

**Comment by reallm** [comment]
@tastelikefeet 自定义数据集和[ms_agent](https://modelscope.cn/datasets/iic/ms_agent)格式保持一致可以正常微调吗？内部会自动屏蔽Observation的Loss吗？还是需要自己改写为tool role？

**Comment by davidluciolu** [comment]
请问swift是否支持agent的推理？包括如何在框架下定义tool，以及推理时的多轮逻辑等。请问有人试过吗？谢谢！🙏
