### ISSUE TITLE
NPU微调报错AssertionError: Torch not compiled with CUDA enabled ，模型时qwen-7b-chat

### ISSUE THREAD

**Issue by ninglonglong** [modelscope/ms-swift#1353]
![image](https://github.com/modelscope/swift/assets/173690046/5ecb2c62-74ba-48f5-92bc-4a8801900630)

使用swift微调npu报错，求助

**Comment by tastelikefeet** [comment]
依赖可能要重新安装一下：https://swift.readthedocs.io/zh-cn/latest/LLM/NPU%E6%8E%A8%E7%90%86%E4%B8%8E%E5%BE%AE%E8%B0%83%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.html
