### ISSUE TITLE
脚本使用问题

### ISSUE THREAD

**Issue by taiji01** [modelscope/ms-swift#1358]
使用SWIFT_UI_LANG=en swift web-ui ，出现Running on local URL:  http://127.0.0.1:7860  但是点击后出现已拒绝连接；
在使用脚本训练模型时，如何自定义数据集。

**Comment by tastelikefeet** [comment]
使用netstat -an | grep 7860来查看7860端口监听的状态

**Comment by tastelikefeet** [comment]
自定义数据集请查看这篇文档：https://swift.readthedocs.io/zh-cn/latest/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.html#id3

**Comment by taiji01** [comment]
使用notebook ，输入以下命令：
git clone https://github.com/modelscope/swift.git
cd swift
pip install -e '.[llm]'

然后想要可视化训练界面，使用 SWIFT_UI_LANG=en swift web-ui
之后出现run sh: `python /mnt/workspace/swift/swift/cli/web_ui.py`
2024-07-12 17:36:01.587079: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-12 17:36:02.799902: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[INFO:swift] Successfully registered `/mnt/workspace/swift/swift/llm/data/dataset_info.json`
Running on local URL:  http://127.0.0.1:7861
点击连接显示拒绝连接
如何修改？

**Comment by tastelikefeet** [comment]
如果从其他机器连接考虑使用--host 0.0.0.0参数
如果是本机连接考虑本地网络是否通畅，有时候会见到这种问题，一般都是本地网络连接不太对

**Comment by unikok** [comment]
你好，在一个没有网络的服务器跑，把网址改成了自己的服务器的端口号，还是打不开
