### ISSUE TITLE
可以支持自定义评测集合与评测指标吗

### ISSUE THREAD

**Issue by fly-dragon211** [modelscope/ms-swift#1374]
**Describe the feature**
Please describe the feature requested here(请在这里描述需求)
支持自定义评测集合，比如我想让模型生成一系列 tag，这其实是一个多标签问题，评测使用 Jaccard 相似度或者准确率召回率等等，希望能够支持。

**Comment by Yunnglin** [comment]
可以尝试使用原始的[eval_scope](https://github.com/modelscope/eval-scope)库，并继承[llmuses.benchmarks.data_adapter.DataAdapter](https://github.com/modelscope/eval-scope/blob/410b699d1205d598a606ac372c6dd26b315ad17e/llmuses/benchmarks/data_adapter.py#L14)类来实现自定义的评测数据集和指标。

对于swift的自定义评测集合与评测指标支持后续将继续开发。
