### ISSUE TITLE
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

### ISSUE THREAD

**Issue by wellhowtosay** [modelscope/ms-swift#1387]
**Describe the bug**

pip install 'ms-swift[all]'==2.2.1

**Your hardware and system info**
Python 3.11.9

**Comment by Jintao-Huang** [comment]
报错的上下文信息或者截图看一下

**Comment by wellhowtosay** [comment]
> 报错的上下文信息或者截图看一下

Collecting pyext
  Downloading https://repo.huaweicloud.com/repository/pypi/packages/b0/be/9b6005ac644aaef022527ce49617263379e49dbdbd433d1d3dd66d71f570/pyext-0.7.tar.gz (7.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /luka-work/miniconda3/envs/llm/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gylm4e3u/pyext/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gylm4e3u/pyext/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-gylm4e3u/pyext/pip-egg-info
         cwd: /tmp/pip-install-gylm4e3u/pyext/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gylm4e3u/pyext/setup.py", line 6, in <module>
        import pyext
      File "/tmp/pip-install-gylm4e3u/pyext/pyext.py", line 117, in <module>
        oargspec = inspect.getargspec
                   ^^^^^^^^^^^^^^^^^^
    AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 24.1.2 is available.
You should consider upgrading via the '/luka-work/miniconda3/envs/llm/bin/python -m pip install --upgrade pip' command.

**Comment by Jintao-Huang** [comment]
pip install ms-swift[llm]

**Comment by ImcwjHere** [comment]
> pip install ms-swift[llm]

此原因为python3.7之后对于getargspec不再支持，将getargspec改为getfullargspec即可正常运行。
参考：https://github.com/bojone/bert4keras/issues/513
希望可以修复一下

**Comment by Yunnglin** [comment]
可以尝试降级python版本，3.10版本经测试可以正常安装

**Comment by Jintao-Huang** [comment]
python<3.11
