### ISSUE TITLE
An error in the inference of glm4v-9b-vhat

### ISSUE THREAD

**Issue by xdaiycl** [modelscope/ms-swift#1422]
run sh: `python /root/autodl-tmp/Code/swift-main/swift/cli/infer.py --model_type glm4v-9b-chat --ckpt_dir ./output/glm4v-9b-chat/v2-20240716-140854/checkpoint-2400/ --load_dataset_config true --show_dataset_sample -1`
2024-07-17 14:58:13,148 - modelscope - INFO - PyTorch version 2.3.0+cu121 Found.
2024-07-17 14:58:13,149 - modelscope - INFO - Loading ast index from /root/autodl-tmp/Cache/ast_indexer
2024-07-17 14:58:13,323 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 587c3d22a438ec657c7c116491963cc0 and a total number of 980 components indexed
[INFO:swift] Successfully registered `/root/autodl-tmp/Code/swift-main/swift/llm/data/dataset_info.json`
[INFO:swift] Start time of running main: 2024-07-17 14:58:14.418539
[INFO:swift] ckpt_dir: /root/autodl-tmp/Code/swift-main/output/glm4v-9b-chat/v2-20240716-140854/checkpoint-2400
[INFO:swift] Setting model_info['revision']: master
[INFO:swift] Setting self.eval_human: False
[INFO:swift] Setting overwrite_generation_config: True
[INFO:swift] args: InferArguments(model_type='glm4v-9b-chat', model_id_or_path='ZhipuAI/glm-4v-9b', model_revision='master', sft_type='lora', template_type='glm4v', infer_backend='pt', ckpt_dir='/root/autodl-tmp/Code/swift-main/output/glm4v-9b-chat/v2-20240716-140854/checkpoint-2400', load_args_from_ckpt_dir=True, load_dataset_config=True, eval_human=False, seed=42, dtype='bf16', dataset=['/root/autodl-tmp/Dataset/DatasetGeneration/SwiftFormat/TalTabNet/StructurePrediction/train.json'], val_dataset=['/root/autodl-tmp/Dataset/DatasetGeneration/SwiftFormat/TalTabNet/StructurePrediction/val.json'], dataset_seed=42, dataset_test_ratio=0.01, show_dataset_sample=-1, save_result=True, system=None, tools_prompt='react_en', max_length=None, truncation_strategy='delete', check_dataset_strategy='none', model_name=[None, None], model_author=[None, None], quant_method=None, quantization_bit=0, hqq_axis=0, hqq_dynamic_config_path=None, bnb_4bit_comp_dtype='bf16', bnb_4bit_quant_type='nf4', bnb_4bit_use_double_quant=True, bnb_4bit_quant_storage=None, max_new_tokens=2048, do_sample=True, temperature=0.3, top_k=20, top_p=0.7, repetition_penalty=1.0, num_beams=1, stop_words=None, rope_scaling=None, use_flash_attn=None, ignore_args_error=False, stream=True, merge_lora=False, merge_device_map='cpu', save_safetensors=True, overwrite_generation_config=True, verbose=None, local_repo_path=None, custom_register_path=None, custom_dataset_info=None, device_map_config_path=None, gpu_memory_utilization=0.9, tensor_parallel_size=1, max_model_len=None, disable_custom_all_reduce=True, enforce_eager=False, vllm_enable_lora=False, vllm_max_lora_rank=16, lora_modules=[], self_cognition_sample=0, train_dataset_sample=-1, val_dataset_sample=None, safe_serialization=None, model_cache_dir=None, merge_lora_and_save=None, custom_train_dataset_path=[], custom_val_dataset_path=[], vllm_lora_modules=None)
[INFO:swift] Global seed set to 42
[INFO:swift] device_count: 1
[INFO:swift] Downloading the model from ModelScope Hub, model_id: ZhipuAI/glm-4v-9b
[INFO:swift] Loading the model using model_dir: /root/autodl-tmp/Cache/hub/ZhipuAI/glm-4v-9b
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[INFO:swift] model_kwargs: {'device_map': 'cuda:0'}
Loading checkpoint shards:   0%|                                                                                                                                                       Loading checkpoint shards:   7%|██████████▌                                                                                                                                            Loading checkpoint shards:  13%|█████████████████████▏                                                                                                                                 Loading checkpoint shards:  20%|███████████████████████████████▊                                                                                                                       Loading checkpoint shards:  27%|██████████████████████████████████████████▍                                                                                                            Loading checkpoint shards:  33%|█████████████████████████████████████████████████████                                                                                                  Loading checkpoint shards:  40%|███████████████████████████████████████████████████████████████▌                                                                                       Loading checkpoint shards:  47%|██████████████████████████████████████████████████████████████████████████▏                                                                            Loading checkpoint shards:  53%|████████████████████████████████████████████████████████████████████████████████████▊                                                                  Loading checkpoint shards:  60%|███████████████████████████████████████████████████████████████████████████████████████████████▍                                                       Loading checkpoint shards:  67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                             Loading checkpoint shards:  73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                   Loading checkpoint shards:  80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                        Loading checkpoint shards:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              Loading checkpoint shards:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍   Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:16<00:00,  1.07s/it]
[INFO:swift] model.max_model_len: 8192
[INFO:swift] model_config: ChatGLMConfig {
  "_name_or_path": "/root/autodl-tmp/Cache/hub/ZhipuAI/glm-4v-9b",
  "add_bias_linear": false,
  "add_qkv_bias": true,
  "apply_query_key_layer_scaling": true,
  "apply_residual_connection_post_layernorm": false,
  "architectures": [
    "ChatGLMModel"
  ],
  "attention_dropout": 0.0,
  "attention_softmax_in_fp32": true,
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForCausalLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSequenceClassification": "modeling_chatglm.ChatGLMForSequenceClassification"
  },
  "bias_dropout_fusion": true,
  "boi_token_id": 151339,
  "classifier_dropout": null,
  "eoi_token_id": 151340,
  "eos_token_id": [
    151329,
    151336,
    151338
  ],
  "ffn_hidden_size": 13696,
  "fp32_residual_connection": false,
  "hidden_dropout": 0.0,
  "hidden_size": 4096,
  "kv_channels": 128,
  "layernorm_epsilon": 1.5625e-07,
  "model_type": "chatglm",
  "multi_query_attention": true,
  "multi_query_group_num": 2,
  "num_attention_heads": 32,
  "num_layers": 40,
  "original_rope": true,
  "pad_token_id": 151329,
  "padded_vocab_size": 151552,
  "post_layer_norm": true,
  "pre_seq_len": null,
  "prefix_projection": false,
  "rmsnorm": true,
  "rope_ratio": 1,
  "seq_length": 8192,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.41.2",
  "use_cache": true,
  "vision_config": {
    "dropout_prob": 0.0,
    "hidden_act": "gelu",
    "hidden_size": 1792,
    "image_size": 1120,
    "in_channels": 3,
    "intermediate_size": 15360,
    "layer_norm_eps": 1e-06,
    "num_heads": 16,
    "num_hidden_layers": 63,
    "num_positions": 6401,
    "patch_size": 14,
    "scaling_factor": 8
  },
  "vocab_size": 151552
}

[INFO:swift] generation_config: GenerationConfig {
  "do_sample": true,
  "eos_token_id": 151329,
  "max_new_tokens": 2048,
  "pad_token_id": 151329,
  "temperature": 0.3,
  "top_k": 20,
  "top_p": 0.7
}

[INFO:swift] [base_model.model.transformer.embedding.word_embeddings.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.0.input_layernorm.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.0.self_attention.query_key_value.base_layer.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.0.self_attention.query_key_value.base_layer.bias]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.0.self_attention.query_key_value.lora_A.default.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.0.self_attention.query_key_value.lora_B.default.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.0.self_attention.dense.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.0.post_attention_layernorm.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.0.mlp.dense_h_to_4h.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.0.mlp.dense_4h_to_h.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.1.input_layernorm.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.1.self_attention.query_key_value.base_layer.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.1.self_attention.query_key_value.base_layer.bias]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.1.self_attention.query_key_value.lora_A.default.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.1.self_attention.query_key_value.lora_B.default.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.1.self_attention.dense.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.1.post_attention_layernorm.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.1.mlp.dense_h_to_4h.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.1.mlp.dense_4h_to_h.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] [base_model.model.transformer.encoder.layers.2.input_layernorm.weight]: requires_grad=False, dtype=torch.bfloat16, device=cuda:0
[INFO:swift] ...
[INFO:swift] PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): ChatGLMForConditionalGeneration(
      (transformer): ChatGLMModel(
        (embedding): Embedding(
          (word_embeddings): Embedding(151552, 4096)
        )
        (rotary_pos_emb): RotaryEmbedding()
        (encoder): GLMTransformer(
          (layers): ModuleList(
            (0-39): 40 x GLMBlock(
              (input_layernorm): RMSNorm()
              (self_attention): SelfAttention(
                (query_key_value): lora.Linear(
                  (base_layer): Linear(in_features=4096, out_features=4608, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=4096, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=4608, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                )
                (core_attention): CoreAttention(
                  (attention_dropout): Dropout(p=0.0, inplace=False)
                )
                (dense): Linear(in_features=4096, out_features=4096, bias=False)
              )
              (post_attention_layernorm): RMSNorm()
              (mlp): MLP(
                (dense_h_to_4h): Linear(in_features=4096, out_features=27392, bias=False)
                (dense_4h_to_h): Linear(in_features=13696, out_features=4096, bias=False)
              )
            )
          )
          (final_layernorm): RMSNorm()
        )
        (output_layer): Linear(in_features=4096, out_features=151552, bias=False)
        (vision): EVA2CLIPModel(
          (patch_embedding): PatchEmbedding(
            (proj): Conv2d(3, 1792, kernel_size=(14, 14), stride=(14, 14))
            (position_embedding): Embedding(6401, 1792)
          )
          (transformer): Transformer(
            (layers): ModuleList(
              (0-62): 63 x TransformerLayer(
                (input_layernorm): LayerNorm((1792,), eps=1e-06, elementwise_affine=True)
                (attention): Attention(
                  (query_key_value): Linear(in_features=1792, out_features=5376, bias=True)
                  (dense): Linear(in_features=1792, out_features=1792, bias=True)
                  (output_dropout): Dropout(p=0.0, inplace=False)
                )
                (mlp): MLP(
                  (activation_fn): GELUActivation()
                  (fc1): Linear(in_features=1792, out_features=15360, bias=True)
                  (fc2): Linear(in_features=15360, out_features=1792, bias=True)
                )
                (post_attention_layernorm): LayerNorm((1792,), eps=1e-06, elementwise_affine=True)
              )
            )
          )
          (linear_proj): GLU(
            (linear_proj): Linear(in_features=4096, out_features=4096, bias=False)
            (norm1): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
            (act1): GELU(approximate='none')
            (dense_h_to_4h): Linear(in_features=4096, out_features=13696, bias=False)
            (gate_proj): Linear(in_features=4096, out_features=13696, bias=False)
            (dense_4h_to_h): Linear(in_features=13696, out_features=4096, bias=False)
          )
          (conv): Conv2d(1792, 4096, kernel_size=(2, 2), stride=(2, 2))
        )
      )
    )
  )
)
[INFO:swift] PeftModelForCausalLM: 13909.1062M Params (0.0000M Trainable [0.0000%]), 0.0000M Buffers.
[INFO:swift] system: None
[INFO:swift] val_dataset: Dataset({
    features: ['query', 'response', 'images'],
    num_rows: 3200
})
[INFO:swift] Setting args.verbose: False
[INFO:swift] Setting args.stream: False
  0%|                                                                                                                                                                                    0%|                                                                                                                                                                                                | 0/3200 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/Code/swift-main/swift/cli/infer.py", line 5, in <module>
    infer_main()
  File "/root/autodl-tmp/Code/swift-main/swift/utils/run_utils.py", line 27, in x_main
    result = llm_x(args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/Code/swift-main/swift/llm/infer.py", line 527, in llm_infer
    response, _ = inference(
                  ^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/Code/swift-main/swift/llm/utils/utils.py", line 778, in inference
    generate_ids = model.generate(streamer=streamer, **inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/peft/peft_model.py", line 1491, in generate
    outputs = self.base_model.generate(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/transformers/generation/utils.py", line 1758, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/transformers/generation/utils.py", line 2449, in _sample
    model_kwargs = self._update_model_kwargs_for_generation(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 1088, in _update_model_kwargs_for_generation
    cache_name, cache = self._extract_past_from_model_output(
    ^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)

**Comment by MisakaMikoto-o** [comment]
遇到了同样的问题，在微调完glm4v-9b-chat模型用
```
CUDA_VISIBLE_DEVICES=0 swift infer \
    --ckpt_dir output/glm4v-9b-chat/vx-xxx/checkpoint-xxx \
    --load_dataset_config true \
```
调用模型进行推理时报的这个错ValueError: too many values to unpack (expected 2)

**Comment by tastelikefeet** [comment]
使用main分支，transformers升级到最新
-------
Use swift main branch, update transformers to the latest version

**Comment by MisakaMikoto-o** [comment]
> ## 使用main分支，transformers升级到最新
> Use swift main branch, update transformers to the latest version

使用的是main分支，用的这个官方命令安装的：```
git clone https://github.com/modelscope/swift.git
cd swift
pip install -e '.[llm]'
```
transformers升级到最新后运行报错：
```
run sh: `python /content/drive/MyDrive/glm/swift/swift/cli/infer.py --model_type glm4v-9b-chat`
2024-07-17 09:41:08.199920: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-17 09:41:08.251567: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-17 09:41:08.251623: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-17 09:41:08.253173: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-17 09:41:08.261113: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-17 09:41:09.424021: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[INFO:swift] Successfully registered `/content/drive/MyDrive/glm/swift/swift/llm/data/dataset_info.json`
[INFO:swift] Start time of running main: 2024-07-17 09:41:12.009006
[INFO:swift] ckpt_dir: None
[INFO:swift] Due to `ckpt_dir` being `None`, `load_args_from_ckpt_dir` is set to `False`.
Traceback (most recent call last):
  File "/content/drive/MyDrive/glm/swift/swift/cli/infer.py", line 5, in <module>
    infer_main()
  File "/content/drive/MyDrive/glm/swift/swift/utils/run_utils.py", line 21, in x_main
    args, remaining_argv = parse_args(args_class, argv)
  File "/content/drive/MyDrive/glm/swift/swift/utils/utils.py", line 112, in parse_args
    args, remaining_args = parser.parse_args_into_dataclasses(argv, return_remaining_strings=True)
  File "/usr/local/lib/python3.10/dist-packages/transformers/hf_argparser.py", line 339, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 76, in __init__
  File "/content/drive/MyDrive/glm/swift/swift/llm/utils/argument.py", line 1181, in __post_init__
    self.set_model_type()
  File "/content/drive/MyDrive/glm/swift/swift/llm/utils/argument.py", line 434, in set_model_type
    require_version(require)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: transformers<4.42 is required for a normal functioning of this module, but found transformers==4.42.4.
```

**Comment by xdaiycl** [comment]
The problem is solved. Thank you.

**Comment by tastelikefeet** [comment]
> > ## 使用main分支，transformers升级到最新
> > Use swift main branch, update transformers to the latest version
> 
> 使用的是main分支，用的这个官方命令安装的：
> 
> ```
> git clone https://github.com/modelscope/swift.git
> cd swift
> pip install -e '.[llm]'
> ```
> 
> transformers升级到最新后运行报错：
> 
> ```
> run sh: `python /content/drive/MyDrive/glm/swift/swift/cli/infer.py --model_type glm4v-9b-chat`
> 2024-07-17 09:41:08.199920: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
> 2024-07-17 09:41:08.251567: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
> 2024-07-17 09:41:08.251623: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
> 2024-07-17 09:41:08.253173: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
> 2024-07-17 09:41:08.261113: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2024-07-17 09:41:09.424021: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
> [INFO:swift] Successfully registered `/content/drive/MyDrive/glm/swift/swift/llm/data/dataset_info.json`
> [INFO:swift] Start time of running main: 2024-07-17 09:41:12.009006
> [INFO:swift] ckpt_dir: None
> [INFO:swift] Due to `ckpt_dir` being `None`, `load_args_from_ckpt_dir` is set to `False`.
> Traceback (most recent call last):
>   File "/content/drive/MyDrive/glm/swift/swift/cli/infer.py", line 5, in <module>
>     infer_main()
>   File "/content/drive/MyDrive/glm/swift/swift/utils/run_utils.py", line 21, in x_main
>     args, remaining_argv = parse_args(args_class, argv)
>   File "/content/drive/MyDrive/glm/swift/swift/utils/utils.py", line 112, in parse_args
>     args, remaining_args = parser.parse_args_into_dataclasses(argv, return_remaining_strings=True)
>   File "/usr/local/lib/python3.10/dist-packages/transformers/hf_argparser.py", line 339, in parse_args_into_dataclasses
>     obj = dtype(**inputs)
>   File "<string>", line 76, in __init__
>   File "/content/drive/MyDrive/glm/swift/swift/llm/utils/argument.py", line 1181, in __post_init__
>     self.set_model_type()
>   File "/content/drive/MyDrive/glm/swift/swift/llm/utils/argument.py", line 434, in set_model_type
>     require_version(require)
>   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/versions.py", line 111, in require_version
>     _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
>   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/versions.py", line 44, in _compare_versions
>     raise ImportError(
> ImportError: transformers<4.42 is required for a normal functioning of this module, but found transformers==4.42.4.
> ```

swift版本更新下，我们今天去掉了<4.42这个限制

**Comment by MisakaMikoto-o** [comment]
> > > ## 使用main分支，transformers升级到最新
> > > Use swift main branch, update transformers to the latest version
> > 
> > 
> > 使用的是main分支，用的这个官方命令安装的：
> > ```
> > git clone https://github.com/modelscope/swift.git
> > cd swift
> > pip install -e '.[llm]'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > transformers升级到最新后运行报错：
> > ```
> > run sh: `python /content/drive/MyDrive/glm/swift/swift/cli/infer.py --model_type glm4v-9b-chat`
> > 2024-07-17 09:41:08.199920: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
> > 2024-07-17 09:41:08.251567: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
> > 2024-07-17 09:41:08.251623: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
> > 2024-07-17 09:41:08.253173: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
> > 2024-07-17 09:41:08.261113: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> > To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> > 2024-07-17 09:41:09.424021: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
> > [INFO:swift] Successfully registered `/content/drive/MyDrive/glm/swift/swift/llm/data/dataset_info.json`
> > [INFO:swift] Start time of running main: 2024-07-17 09:41:12.009006
> > [INFO:swift] ckpt_dir: None
> > [INFO:swift] Due to `ckpt_dir` being `None`, `load_args_from_ckpt_dir` is set to `False`.
> > Traceback (most recent call last):
> >   File "/content/drive/MyDrive/glm/swift/swift/cli/infer.py", line 5, in <module>
> >     infer_main()
> >   File "/content/drive/MyDrive/glm/swift/swift/utils/run_utils.py", line 21, in x_main
> >     args, remaining_argv = parse_args(args_class, argv)
> >   File "/content/drive/MyDrive/glm/swift/swift/utils/utils.py", line 112, in parse_args
> >     args, remaining_args = parser.parse_args_into_dataclasses(argv, return_remaining_strings=True)
> >   File "/usr/local/lib/python3.10/dist-packages/transformers/hf_argparser.py", line 339, in parse_args_into_dataclasses
> >     obj = dtype(**inputs)
> >   File "<string>", line 76, in __init__
> >   File "/content/drive/MyDrive/glm/swift/swift/llm/utils/argument.py", line 1181, in __post_init__
> >     self.set_model_type()
> >   File "/content/drive/MyDrive/glm/swift/swift/llm/utils/argument.py", line 434, in set_model_type
> >     require_version(require)
> >   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/versions.py", line 111, in require_version
> >     _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
> >   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/versions.py", line 44, in _compare_versions
> >     raise ImportError(
> > ImportError: transformers<4.42 is required for a normal functioning of this module, but found transformers==4.42.4.
> > ```
> 
> swift版本更新下，我们今天去掉了<4.42这个限制

没问题了，谢谢
