### ISSUE TITLE
支持对NPU AWQ量化的模型推理部署吗？

### ISSUE THREAD

**Issue by czs1886** [modelscope/ms-swift#1429]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
取决于NPU对AWQ模型的支持，swift本身是支持的
