### ISSUE TITLE
get_dataset 函数报错，疑似是加载数据太多导致

### ISSUE THREAD

**Issue by Adam-fei** [modelscope/ms-swift#1453]
尝试对 qwen2 7b 做 continue pre-training，于是下载了一批数据。 配置好 dataset.json 之后，在小数据集上可以进行训练并保存ckpt，表明数据链路没问题。
但加载全量数据时，加载到某个文件时会报如下的错误。尝试多次后，猜想是加载的数据过多导致的，内存爆了？ (报错信息如下，单机八卡执行)。

想问下
1. swift的执行逻辑是一次性将所有数据读到内存里吗？如果是的话，这样做的必要性是？
2. 如果希望大量数据(500G左右)做 continue pre-train 的话，基于 swift 的原生框架能做到吗？ 不行的话，我需要自行修改什么代码吗？

> `[INFO:swift] dataset.py2474 load_dataset_from_local processing: /马赛克/datasets/chinesewebtext/data/processed_data/2023-23part-0010_processed.jsonl
W0720 16:58:25.611000 140386850924352 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 512072 closing signal SIGTERM
W0720 16:58:25.675000 140386850924352 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 512074 closing signal SIGTERM
W0720 16:58:25.675000 140386850924352 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 512075 closing signal SIGTERM
W0720 16:58:25.675000 140386850924352 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 512076 closing signal SIGTERM
W0720 16:58:25.676000 140386850924352 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 512077 closing signal SIGTERM
W0720 16:58:25.676000 140386850924352 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 512078 closing signal SIGTERM
W0720 16:58:25.676000 140386850924352 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 512079 closing signal SIGTERM
E0720 16:58:39.323000 140386850924352 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: -9) local_rank: 1 (pid: 512073) of binary: /马赛克/swift/bin/python
Traceback (most recent call last):
  File "/马赛克/swift/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/马赛克/swift/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/马赛克/swift/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in <module>
    main()
  File "/马赛克/swift/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/马赛克/swift/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/马赛克/swift/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/马赛克/swift/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/马赛克/swift/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

/马赛克/swift/swift/cli/sft.py FAILED

Failures:  <NO_OTHER_FAILURES>

Root Cause (first observed failure):
[0]:
  time      : 2024-07-20_16:58:25
  host      : a800bcctest0087-bd.bce.kwaidc.com
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 512073)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 512073

`

**Comment by Jintao-Huang** [comment]
500GB数据 使用8卡训练 感觉不太够啊, 估计需要几个月以上了

感觉报错信息像是内存溢出了嘛

**Comment by Adam-fei** [comment]
> 500GB数据 使用8卡训练 感觉不太够啊, 估计需要几个月以上了
> 
> 感觉报错信息像是内存溢出了嘛

只是在跑通流程啦，正式训练会上多机的。 只是在多机多卡的情况下，发现报错的位置和内容和单机一样，就用单机debug了，方便些。
报错是内存溢出的话，那证实了我的猜想。 这个框架是一次性加载所有数据进内存是吗？ 请问有没有更优雅的方法可以加载数据呢？ 多谢 :)

**Comment by Jintao-Huang** [comment]
> 顺便补充一下，我使用的训练机器是有 900G 的内存，但加载的文本数据到70G就报错退出了
> 
> 具体来说，我的错误发生在 /./swift/swift/llm/utils/dataset.py 的 load_dataset_from_local 函数里，循环加载数据的期间报错

是的，目前是加载全部数据的，不过可以设置lazy_tokenize在训练时进行tokenize.
可以看看 具体的报错信息不, 使用单卡读取数据集可以看的清楚一些

**Comment by Adam-fei** [comment]
> > 顺便补充一下，我使用的训练机器是有 900G 的内存，但加载的文本数据到70G就报错退出了
> > 具体来说，我的错误发生在 /./swift/swift/llm/utils/dataset.py 的 load_dataset_from_local 函数里，循环加载数据的期间报错
> 
> 是的，目前是加载全部数据的，不过可以设置lazy_tokenize在训练时进行tokenize. 可以看看 具体的报错信息不, 使用单卡读取数据集可以看的清楚一些

🥶 单卡运行，程序安全度过了之前反复无法加载成功的那道线，现在多加载了更多的数据文件，依然没报错。 是不是多卡运行的问题，重复加载了数据集好几次？

以下是我单机多卡和单机单卡的启动脚本：
**单机多卡**

> nohup python -m torch.distributed.run \
    --nproc_per_node=8 --nnodes=1 --node_rank=0 --master_addr=$master_addr --master_port=$master_port \
    /马赛克/swift/swift/cli/sft.py --model_type qwen2-7b \
    --model_id_or_path /马赛克/Models/Qwen2-7B --sft_type full --train_dataset_sample -1 --eval_steps 1000 --template_type qwen \
    --output_dir /马赛克/models_output --num_train_epochs 1 --max_length 4096 --learning_rate 1e-5 --use_flash_attn true --save_only_model true \
    --dataset continue_pretrain_dataset_ --preprocess_num_proc 1 --save_on_each_node false --ddp_backend=nccl --deepspeed default-zero2 > log.txt 2>&1&

单机多卡的内存报错如一楼所示。

**单机单卡**
> nohup python \
    /马赛克/swift/swift/cli/sft.py --model_type qwen2-7b \
    --model_id_or_path /马赛克/Models/Qwen2-7B --sft_type full --train_dataset_sample -1 --eval_steps 1000 --template_type qwen \
    --output_dir /马赛克/models_output --num_train_epochs 1 --max_length 4096 --learning_rate 1e-5 --use_flash_attn true --save_only_model true \
    --dataset continue_pretrain_dataset_ --preprocess_num_proc 1 --save_on_each_node false > log.txt 2>&1&

单机单卡加载了比之前多的多的数据文件，目前仍未报错。明早起来看看

**Comment by Adam-fei** [comment]
运行了一天，update 一下进展：
在使用单机单卡运行的时候，加载的数据远远超过了单机多卡or多机多卡的时候。
初步可以判定就是多卡运行时加载数据有问题。
能排查修复一下吗？

**Comment by ericzhou571** [comment]
@Adam-fei 我们也遇到了同样的问题，根据你定位到的load_dataset_from_local函数的问题，做了进一步分析，定位下来这个函数有很多冗余的不必要的等价于数据拷贝的操作，不确定你单卡的时候是不是因为CPU内存跟多卡的CPU内存是一样的所以产生单卡work，多卡不work的情况，因为按照之前对deepseed的了解，多卡并行会起多个进程，可能会多次执行这个函数，导致有几个卡，数据的拷贝就是单卡的多少倍导致的。

https://github.com/modelscope/swift/blob/ebfb636bc1c4a22803174ce8ef1621ab7187087d/swift/llm/utils/dataset.py#L2572-L2598
上述代码加载.json文件的时候是否对于内存的消耗过大？且似乎有很大的内存优化空间？
具体拆分内存的使用情况：

首先假设数据集的大小为X GB，不考虑数据集存储大小是否经过压缩

1. 下面这部分首先完整的加载json文件到内存得到obj_list，总内存占用为数据为 1X
https://github.com/modelscope/swift/blob/ebfb636bc1c4a22803174ce8ef1621ab7187087d/swift/llm/utils/dataset.py#L2588-L2590
2. 下面这部分代码把obj_list转为df（pandas dataframe），且最终是调用DataFrame.from_dict(data_dict)实现的，实际创建了一个全新的内存空间存储数据集，此时内存占用约为 2X
https://github.com/modelscope/swift/blob/ebfb636bc1c4a22803174ce8ef1621ab7187087d/swift/llm/utils/dataset.py#L2591 
https://github.com/modelscope/swift/blob/ebfb636bc1c4a22803174ce8ef1621ab7187087d/swift/utils/np_utils.py#L21 

3.这部分里df.to_dict(orient='list')由重新开辟了内存空间存储一份数据集的完整拷贝，此时内存使用来到了3X， huggingface的Dataset倾向于重新copy一份数据，虽然并没有显式的创建一个变量存储df.to_dict(orient='list')，但是在dataset创建过程中，这部分数据一直占用内存，此时内存占用的峰值会来到4X
https://github.com/modelscope/swift/blob/ebfb636bc1c4a22803174ce8ef1621ab7187087d/swift/llm/utils/dataset.py#L2596

结合这个issue来看，9G下报错，2.7G可行，总cpu内存为32G，按照我们的估算，9G数据集峰值为36G，很明显会在开始训练之前就RAM OOM了

目前未查看sft在deepspeed情况下的启动脚本，不确定这段代码会不会再每个进程里单独运行一次，如果运行一次，那么内存占用可能会是 GPU_number * 4 * X，考虑到典型的8卡场景下，比如10G数据（假设未压缩），最少内存占用则来到320G

@Jintao-Huang 不确定大佬这么写四次数据拷贝是否有什么其他的考量，如果没有的话是否考虑可以优化一下dataset的ram性能。

**Comment by Jintao-Huang** [comment]
好的... 令人忧伤, 我先修复一下

**Comment by Jintao-Huang** [comment]
先简单修复了一版本，再试试呢

**Comment by Adam-fei** [comment]
> 先简单修复了一版本，再试试呢

nice，和我目前采用的解决方法一致，直接跳过了中间步骤。在这种方法下多机加载数据没问题。

**Comment by Jintao-Huang** [comment]
好的 感谢反馈🌹

**Comment by ericzhou571** [comment]
感谢大佬的快速修复 @Jintao-Huang 
另外咱们有可能支持一下流式数据集处理嘛？，比如对jsonl格式，不然如果数据集持续增大，一个八卡整机上至少也有完整的8份数据拷贝，对于内存的压力仍然很大。如果有需要可以开一个单独的issue。

**Comment by tastelikefeet** [comment]
流式处理已支持 --streaming true
