### ISSUE TITLE
function call微调数据格式

### ISSUE THREAD

**Issue by ccp123456789** [modelscope/ms-swift#1458]
请问微调数据格式参考文档，是要固定训练和推理的prompt吗？ 比如react_en,react_cn,tool_bench这几种格式，保持训练推理一致？ 那如何评测对比和开源模型的效果，因为开源模型不一定是按照这个格式来的，无法对比评测

**Comment by tastelikefeet** [comment]
训练prompt固定后，推理需要按照训练prompt进行
而训练本身的prompt是可以调节的
一般开源模型会按照toolbench进行训练，可以使用toolbench格式和开源模型进行对比评测
swift也会马上支持toolbench的agent评测能力
