### ISSUE TITLE
swift可以训练量化之后的模型吗，比如modelscope里面的awq或者gptq量化之后的模型

### ISSUE THREAD

**Issue by LIUKAI0815** [modelscope/ms-swift#1472]
因为在训练的时候，加载没有量化的模型，训练完再量化资源不够。可以直接训练官方量化后的模型吗

**Comment by LIUKAI0815** [comment]
如果训练完之后，可以merge lora 吗

**Comment by Jintao-Huang** [comment]
可以训练，但是训练完之后没办法merge-lora.

**Comment by JiaXinLI98** [comment]
> 可以训练，但是训练完之后没办法merge-lora.

能用full的方式训练吗

**Comment by LIUKAI0815** [comment]
这种情况下我理解应该就只能用QLORA训练了。因为单纯的lora训练就已经是加载16位了，而量化后的awq就是int4了，这样训练的精度就对应不上了。full全量训练应该就不更行了，这是我的理解

**Comment by LIUKAI0815** [comment]
@Jintao-Huang 直接用默认的lora训练awq模型吗，默认的lora加载的是16/32位把？

**Comment by tastelikefeet** [comment]
支持的，QLoRA训练
