### ISSUE TITLE
The deployment of llama3.1-405b-instruct

### ISSUE THREAD

**Issue by Jintao-Huang** [modelscope/ms-swift#1484]

**Comment by Jintao-Huang** [comment]
推理: 
8 * 80GiB A100
```shell
swift infer --model_type llama3_1-405b-instruct-fp8 \
    --tensor_parallel_size 8 --gpu_memory_utilization 0.9 --max_model_len 65536
```

推理效果:
```python
"""
<<< 你好
你好！😊有什么可以帮你的吗？
--------------------------------------------------
<<< 你是谁
我是一个人工智能语言模型，名叫LLaMA。我的主要功能是与用户进行自然语言对话，回答问题，提供信息和帮助。
--------------------------------------------------
<<< 睡不着觉怎么办
睡不着觉确实很烦恼！ 😴以下是一些可能有帮助的建议：

1. **建立睡眠习惯**：每天在同一时间上床和起床，帮助你的身体形成固定的睡眠模式。
2. **创造睡眠环境**：确保你的卧室安静、黑暗、凉爽，投资一个舒适的床垫和枕头。
3. **放松技巧**：尝试深呼吸、冥想、瑜伽或其他放松方法来帮助你放松身心。
4. **避免刺激**：在睡前避免使用电子设备、看电视、玩游戏或进行其他刺激活动。
5. **运动和锻炼**：定期运动可以帮助改善睡眠质量，但避免在睡前进行剧烈运动。
6. **避免咖啡和酒精**：这两种物质可以干扰睡眠，尤其是在睡前几个小时内。
7. **尝试渐进式肌肉放松**：从头到脚逐渐放松你的肌肉，可以帮助你放松和入睡。
8. **写日记**：写下你的想法和感受，可以帮助你清理脑海和放松。
9. **听音乐**：听一些轻松的音乐或自然声音，可以帮助你放松和入睡。
10. **如果问题持续**：如果你持续睡不着觉，可能需要咨询医生或睡眠专家来寻找根本原因和解决方案。

希望这些建议对你有帮助！ 😊
--------------------------------------------------
"""
```


部署: 
```
swift deploy --model_type llama3_1-405b-instruct-fp8 \
    --tensor_parallel_size 8 --gpu_memory_utilization 0.9 --max_model_len 65536
```

**Comment by zzhangpurdue** [comment]
awesome work，great job guys.

**Comment by zhangfan-algo** [comment]
vllm版本多少可以用啊

**Comment by Jintao-Huang** [comment]
> vllm版本多少可以用啊

vllm>=0.5.3.post1

**Comment by zhangfan-algo** [comment]
还是有问题

**Comment by zhangfan-algo** [comment]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/apps1/zhangfan/anaconda3/envs/new_swift/lib/python3.10/site-packages/swift/cli/deploy.py", line 5, in <module>
[rank0]:     deploy_main()
[rank0]:   File "/apps1/zhangfan/anaconda3/envs/new_swift/lib/python3.10/site-packages/swift/utils/run_utils.py", line 32, in x_main
[rank0]:     result = llm_x(args, **kwargs)
[rank0]:   File "/apps1/zhangfan/anaconda3/envs/new_swift/lib/python3.10/site-packages/swift/llm/deploy.py", line 778, in llm_deploy
[rank0]:     llm_engine, template = prepare_vllm_engine_template(args, use_async=True)
[rank0]:   File "/apps1/zhangfan/anaconda3/envs/new_swift/lib/python3.10/site-packages/swift/llm/utils/vllm_utils.py", line 577, in prepare_vllm_engine_template
[rank0]:     llm_engine = get_vllm_engine(
[rank0]:   File "/apps1/zhangfan/anaconda3/envs/new_swift/lib/python3.10/site-packages/swift/llm/utils/vllm_utils.py", line 122, in get_vllm_engine
[rank0]:     llm_engine = llm_engine_cls.from_engine_args(engine_args)
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/engine/async_llm_engine.py", line 601, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/engine/async_llm_engine.py", line 511, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/engine/async_llm_engine.py", line 682, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/engine/llm_engine.py", line 259, in __init__
[rank0]:     self.model_executor = executor_class(
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/executor/multiproc_gpu_executor.py", line 215, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/executor/distributed_gpu_executor.py", line 25, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/executor/executor_base.py", line 48, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/executor/multiproc_gpu_executor.py", line 138, in _init_executor
[rank0]:     self._run_workers("load_model",
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/executor/multiproc_gpu_executor.py", line 192, in _run_workers
[rank0]:     driver_worker_output = driver_worker_method(*args, **kwargs)
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/worker/worker.py", line 151, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/worker/model_runner.py", line 888, in load_model
[rank0]:     self.model = get_model(model_config=self.model_config,
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/model_executor/model_loader/__init__.py", line 21, in get_model
[rank0]:     return loader.load_model(model_config=model_config,
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/model_executor/model_loader/loader.py", line 349, in load_model
[rank0]:     model.load_weights(
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/model_executor/models/llama.py", line 471, in load_weights
[rank0]:     for name, loaded_weight in weights:
[rank0]:   File "/mnt/pfs/zhangfan/study_info/swift_0807/vllm/vllm/model_executor/model_loader/weight_utils.py", line 395, in safetensors_weights_iterator
[rank0]:     param = f.get_tensor(name)
[rank0]: safetensors_rust.SafetensorError: Dtype not understood: F8_E4M3
