### ISSUE TITLE
flashattention3

### ISSUE THREAD

**Issue by wangli68** [modelscope/ms-swift#1493]
**Describe the feature**
Please describe the feature requested here(请在这里描述需求)
flashattention3 has been released, when will it be supported？

**Paste any useful information**
Paste any useful information, including papers, github links, etc.(请在这里描述其他有用的信息，比如相关的论文地址，github链接等)

**Additional context**
Add any other context or information here(其他信息可以写在这里)

**Comment by tastelikefeet** [comment]
We will support flash-attention-3 as soon as any model supports it in transformers.
