### ISSUE TITLE
InternVL2的grounding任务自定义数据集如何一个prompt里融合多个<box>或<ref-object>

### ISSUE THREAD

**Issue by Harley-Sun** [modelscope/ms-swift#1532]
<img width="970" alt="image" src="https://github.com/user-attachments/assets/6b9df7fb-d004-4ff8-80d0-b82f89401e71">
doc链接：https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/internvl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md
例子中给出了grounding任务数据集的格式，请问如果一个query中想同时向多个box提问，该用什么格式来写呢？bbox1 bbox2 ...这种么？如果没有现成方案的话，那么应该在源码的哪里实现呢，暂时还没找到数据格式转换的代码在哪里...

**Comment by Harley-Sun** [comment]
呼叫大佬们
@wuwujay @anw90 @chuanzhubin @wenmengzhou

**Comment by tastelikefeet** [comment]
支持多个<bbox><bbox>的，只需要后面的objects和前面的数量相等即可

**Comment by yhpwsid** [comment]
> 支持多个的，只需要后面的objects和前面的数量相等即可

@tastelikefeet  请问后面的objects和前面的什么数量相等
