### ISSUE TITLE
No module named 'swift.cli.main'问题

### ISSUE THREAD

**Issue by Neko1996** [modelscope/ms-swift#1536]
想使用swift序列化并行的功能，按照文档中的方法2 git clone的方式安装了swift。后安装swift[seq_parallel]，再运行swift web-ui遇到错误。尝试过直接执行web-ui脚本，也不行。不知道是安装seq-parallel的问题还是其他问题。

![a](https://github.com/user-attachments/assets/9f99b9cb-228d-4593-b8cb-f4bb56ab54dc)
执行命令如下
创建环境
python3 -m venv swift-env 
source swift-env/bin/activate

按照官方文档2安装swift
git clone https://github.com/modelscope/swift.git
cd swift
pip install -e '.[llm]'

模型并行包XTuner
pip install 'swift[seq_parallel]'

启动ui
swift web-ui

**Comment by Neko1996** [comment]
也尝试了命令方式CUDA_VISIBLE_DEVICES=0,1 swift sft --model_type LLaMA3.1 --dataset dark_train_corpus --num_train_epochs 1 --sft_type lora --output_dir output，依然报错No module named 'swift.cli.main'

**Comment by Jintao-Huang** [comment]
你看看 python 和 python3是不是不同的 “python”

**Comment by tastelikefeet** [comment]
尝试python启动后
import swift.ui
试一下
如果没有问题讲道理不会出现上面的报错
如果有问题可以重新打开issue

**Comment by Qweeeeeeek** [comment]
遇到同样问题，怎么解决啊
![Uploading QQ图片20241214215037.png…]()
