### ISSUE TITLE
device_map error for internVL2.0, trained on multi-node

### ISSUE THREAD

**Issue by lrj16** [modelscope/ms-swift#1538]
I use multi-node to train internVL2.0, this is my script:

----------------------------
GPUS_PER_NODE=8

NNODES=$WORLD_SIZE
NODE_RANK=$RANK
MASTER_ADDR=$MASTER_ADDR
MASTER_PORT=$MASTER_PORT
NPROC_PER_NODE=$GPUS_PER_NODE

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
swift sft \
    --model_type internvl2-8b \
    --dataset data-path \
    --model_id_or_path model-path \
    --output_dir out-path \
    --batch_size 3 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --gradient_checkpointing true \
    --use_flash_attn true \
    --num_train_epochs 5 \
    --save_strategy "steps" \
    --save_steps 5000 \
    --sft_type "lora" \
    --save_total_limit 50 \
    --max_length 5120 
----------------------------

Here is an error:
----------------------------
You can't train a model that has been loaded with `device_map='auto'` in any distributed mode. Please rerun your script specifying `--num_processes=1` or by launching with `python {{myscript.py}}`
----------------------------

Any one who knows how to solve this error?  Thanks very much.

**Comment by tastelikefeet** [comment]
check our readme:https://github.com/modelscope/ms-swift?tab=readme-ov-file#multi-node-multi-gpu
I do think you need to add '\' after the env variables:
`NPROC_PER_NODE=$GPUS_PER_NODE \`
