### ISSUE TITLE
swift pt命令报错，把缓存的数据集全删了重新下载 还是报错

### ISSUE THREAD

**Issue by ArtificialZeng** [modelscope/ms-swift#1544]
**Describe the bug**
Downloading data: 238MB [00:04, 50.7MB/s]
[INFO:modelscope] storing https://www.modelscope.cn/api/v1/datasets/swift/chinese-c4/repo?Source=SDK&Revision=master&FilePath=data%2Fchinese-c4-0095-of-0096.jsonl.zst in cache at /home/apus/.cache/modelscope/hub/datasets/downloads/6a7c2b63616521fb647938b845e8dcd292ffb01342f2c58f869214a6a47289fe
[INFO:modelscope] creating metadata file for /home/apus/.cache/modelscope/hub/datasets/downloads/6a7c2b63616521fb647938b845e8dcd292ffb01342f2c58f869214a6a47289fe

Generating train split: 0 examples [00:00, ? examples/s]
Generating train split: 19255347 examples [03:14, 97585.27 examples/s]
Generating train split: 19271505 examples [03:14, 96790.75 examples/s]
Generating train split: 19273007 examples [03:14, 99111.74 examples/s]
[INFO:modelscope] Context manager of ms-dataset exited.
Using the latest cached version of the dataset since swift/chinese-c4 couldn't be found on the Hugging Face Hub
[INFO:modelscope] Context manager of ms-dataset exited.
[ERROR:swift] Dataset swift/chinese-c4 load failed: subset_name=default,split=train with error: Couldn't find cache for swift/chinese-c4 for config 'default'
Available configs in the cache: ['default-1fc53a3c66964980']
[rank5]: Traceback (most recent call last):
[rank5]:   File "/data/zengzijian/Projects/LLaMA-Factory-202407/swift/swift/cli/sft.py", line 5, in <module>
[rank5]:     sft_main()
[rank5]:   File "/data/zengzijian/Projects/LLaMA-Factory-202407/swift/swift/utils/run_utils.py", line 27, in x_main
[rank5]:     result = llm_x(args, **kwargs)
[rank5]:   File "/data/zengzijian/Projects/LLaMA-Factory-202407/swift/swift/llm/sft.py", line 258, in llm_sft
[rank5]:     train_dataset, val_dataset = _get_train_val_dataset(args)
[rank5]:   File "/data/zengzijian/Projects/LLaMA-Factory-202407/swift/swift/llm/sft.py", line 30, in _get_train_val_dataset
[rank5]:     train_dataset, val_dataset = get_dataset(
[rank5]:   File "/data/zengzijian/Projects/LLaMA-Factory-202407/swift/swift/llm/utils/dataset.py", line 2488, in get_dataset
[rank5]:     dataset = get_function(
[rank5]:   File "/data/zengzijian/Projects/LLaMA-Factory-202407/swift/swift/llm/utils/dataset.py", line 429, in get_dataset_from_repo
[rank5]:     dataset = load_ms_dataset(dataset_id, subset_split_list, use_hf)
[rank5]:   File "/data/zengzijian/Projects/LLaMA-Factory-202407/swift/swift/llm/utils/dataset.py", line 353, in load_ms_dataset
[rank5]:     return concatenate_datasets(dataset_list)
[rank5]:   File "/home/apus/mambaforge/envs/etuning4/lib/python3.10/site-packages/datasets/combine.py", line 188, in concatenate_datasets
[rank5]:     raise ValueError("Unable to concatenate an empty list of datasets.")
[rank5]: ValueError: Unable to concatenate an empty list of datasets.
Using the latest cached version of the dataset since swift/chinese-c4 couldn't be found on the Hugging Face Hub
[INFO:modelscope] Context manager of ms-dataset exited.
[ERROR:swift] Dataset swift/chinese-c4 load failed: subset_name=default,split=train with error: Couldn't find cache for swift/chinese-c4 for config 'default'
Available configs in the cache: ['default-1fc53a3c66964980']
[rank1]: Traceback (most recent call last):
[rank1]:   File "/data/zengzijian/Projects/LLaMA-Factory-202407/swift/swift/cli/sft.py", line 5, in <module>
[rank1]:     sft_main()
[rank1]:   File "/data/zengzijian/Projects/LLaMA-Factory-202407/swift/swift/utils/run_utils.py", line 27, in x_main
[rank1]:     result = llm_x(args, **kwargs)
[rank1]:   File "/data/zengzijian/Projects/LLaMA-Factory-202407/swift/swift/llm/sft.py", line 258, in llm_sft
[rank1]:     train_dataset, val_dataset = _get_train_val_dataset(args)
[rank1]:   File "/data/zengzijian/Projects/LLaMA-Factory-202407/swift/swift/llm/sft.py", line 30, in _get_train_val_dataset
[rank1]:     train_dataset, val_dataset = get_dataset(
[rank1]:   File "/data/zengzijian/Projects/LLaMA-Factory-202407/swift/swift/llm/utils/dataset.py", line 2488, in get_dataset
[rank1]:     dataset = get_function(
[rank1]:   File "/data/zengzijian/Projects/LLaMA-Factory-202407/swift/swift/llm/utils/dataset.py", line 429, in get_dataset_from_repo
[rank1]:     dataset = load_ms_dataset(dataset_id, subset_split_list, use_hf)
[rank1]:   File "/data/zengzijian/Projects/LLaMA-Factory-202407/swift/swift/llm/utils/dataset.py", line 353, in load_ms_dataset
[rank1]:     return concatenate_datasets(dataset_list)
[rank1]:   File "/home/apus/mambaforge/envs/etuning4/lib/python3.10/site-packages/datasets/combine.py", line 188, in concatenate_datasets
[rank1]:     raise ValueError("Unable to concatenate an empty list of datasets.")
[rank1]: ValueError: Unable to concatenate an empty list of datasets.
Using the latest cached version of the dataset since swift/chinese-c4 couldn't be found on the Hugging Face Hub
[INFO:modelscope] Context manager of ms-dataset exited.
[ERROR:swift] Dataset swift/chinese-c4 load failed: subset_name=default,split=train with error: Couldn't find cache for swift/chinese-c4 for config 'default'
Available configs in the cache: ['default-1fc53a3c66964980']

What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
哈咯，拉取一下modelscope的main分支进行实验试试呢
