### ISSUE TITLE
GLM 4V 9B RuntimeError: Expected all tensors to be on the same device, but found at least two devices

### ISSUE THREAD

**Issue by nico2rdj** [modelscope/ms-swift#1547]
Hello,

Do you know how to resolve this issue?

CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft     --model_type glm4v-9b-chat     --model_id_or_path /srv/models/models00/hf/glm4v9b/     --dataset "public_glm4_grouding_train_v5_swift.json"  --dataset_test_ratio 0.1    --num_train_epochs 4     --max_length 1024     --lora_target_modules ALL

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:3! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

Best regards,

**Comment by Jintao-Huang** [comment]
hello

How about adding NPROC_PER_NODE=4 and `--deepspeed default-zero2`?

**Comment by nico2rdj** [comment]
Hello

I get "DeepSpeed is not compatible with MP"

But reducing the number of gpus got it work fine (it might appear when more gpus than needed)

Thank you for your reactivity! :)
