### ISSUE TITLE
florence最佳实践问题咨询

### ISSUE THREAD

**Issue by danxuan2022** [modelscope/ms-swift#1583]
**Describe the bug**
 bbox 坐标 建议给四个整数（而非float型），分别是x_min,y_min,x_max,y_max四个值，这里的四个值分别是标注的目标的左上角和右下角的两个坐标值吗？
![image](https://github.com/user-attachments/assets/ec73a0a8-9b41-48a6-9295-9a165046a3da)

**Comment by hjh0119** [comment]
左下角和右上角坐标

**Comment by danxuan2022** [comment]
> 左下角和右上角坐标

好的了解了多谢，如果一张图上有多个目标的话是将数据集copy多份吗？
{"query": "Find object1", "response": "<bbox>", "images": ["/coco2014/train2014/COCO_train2014_000000001507.jpg"], "objects": "[{\"caption\": \"guy in red\", \"bbox\": [138, 136, 235, 359], \"bbox_type\": \"real\", \"image\": 0}]" }
{"query": "Find object2", "response": "<bbox>", "images": ["/coco2014/train2014/COCO_train2014_000000001507.jpg"], "objects": "[{\"caption\": \"guy in red\", \"bbox\": [138, 136, 235, 359], \"bbox_type\": \"real\", \"image\": 0}]" }
