### ISSUE TITLE
will early stopping be supported in the coming versions？

### ISSUE THREAD

**Issue by XiaoMaGe-hero** [modelscope/ms-swift#1601]
**Describe the feature**
Please describe the feature requested here(请在这里描述需求)

**Paste any useful information**
Paste any useful information, including papers, github links, etc.(请在这里描述其他有用的信息，比如相关的论文地址，github链接等)

**Additional context**
Add any other context or information here(其他信息可以写在这里)

**Comment by tastelikefeet** [comment]
eval_loss is not a very accurate metric to evaluate the model over-fitting, we suggest to set a proper epoch number
