### ISSUE TITLE
GLM4V运行时报错

### ISSUE THREAD

**Issue by det-tu** [modelscope/ms-swift#1611]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
命令：CUDA_VISIBLE_DEVICES=0 swift infer --model_type glm4v-9b-chat --model_id_or_path ../MLLM/GLM4V-9b --template_type glm4v
报错：AssertionError: failed to match chat template, please explicit set chat_template_config
![image](https://github.com/user-attachments/assets/740dadd1-0382-4054-ac88-766f0aad5a5f)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

![image](https://github.com/user-attachments/assets/4a86d682-629a-4d5d-bfaf-b501d27beb11)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
lmdeploy是什么版本

**Comment by det-tu** [comment]
> lmdeploy是什么版本

lmdeploy是0.5.2，swift是2.3.0.dev0

**Comment by det-tu** [comment]
> lmdeploy是什么版本

请问下是版本问题吗，看文档里没写swift对应该装哪个版本的lmdeploy

**Comment by demoninpiano** [comment]
我用swift2.4.0.dev0， lmdeploy=0.5.3也没办法跑通glm4v 的lmdeploy inference代码

问题是AttributeError: 'AsyncEngine' object has no attribute 'vl_encoder'
看了下lmdeploy代码， 应该是lmdeploy没有成功建立vlAsyncEngine这个类

**Comment by Jintao-Huang** [comment]
> **Describe the bug** What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图) 命令：CUDA_VISIBLE_DEVICES=0 swift infer --model_type glm4v-9b-chat --model_id_or_path ../MLLM/GLM4V-9b --template_type glm4v 报错：AssertionError: failed to match chat template, please explicit set chat_template_config ![image](https://private-user-images.githubusercontent.com/26542172/355459008-740dadd1-0382-4054-ac88-766f0aad5a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDg3OTIsIm5iZiI6MTcyNDIwODQ5MiwicGF0aCI6Ii8yNjU0MjE3Mi8zNTU0NTkwMDgtNzQwZGFkZDEtMDM4Mi00MDU0LWFjODgtNzY2ZjBhYWQ1YTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAyNDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwODRiMzI3ZmNkMmU1NjNlNWU5NDVmMTg5NWQzNzgyZDU4NmQ1NWQ4MWZjMmQ2YTQ0NmNkYWRhMmIwNjkzYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wEzYXTxfRr2XMWI2_4OvLbNF7ha9SG_4jKgp6HalBVQ)
> 
> **Your hardware and system info** Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
> 
> ![image](https://private-user-images.githubusercontent.com/26542172/355459348-4a86d682-629a-4d5d-bfaf-b501d27beb11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDg3OTIsIm5iZiI6MTcyNDIwODQ5MiwicGF0aCI6Ii8yNjU0MjE3Mi8zNTU0NTkzNDgtNGE4NmQ2ODItNjI5YS00ZDVkLWJmYWYtYjUwMWQyN2JlYjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAyNDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMWFiYTZhZDYzNjgxYTQzYTk1NjUxMWQ3MmJiNzMzNzNkNDlkNzJmNzUwZmQ3Mzc0ZjAzNDczNjE4ZTczNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VjoDkl1ZPSF85IdE_hUj9DZ8jv53MfLUsDpubRC-nXA)
> 
> **Additional context** Add any other context about the problem here(在这里补充其他信息)

这个问题已经修复了

**Comment by Aanlifire** [comment]
> > **Describe the bug** What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图) 命令：CUDA_VISIBLE_DEVICES=0 swift infer --model_type glm4v-9b-chat --model_id_or_path ../MLLM/GLM4V-9b --template_type glm4v 报错：AssertionError: failed to match chat template, please explicit set chat_template_config ![image](https://private-user-images.githubusercontent.com/26542172/355459008-740dadd1-0382-4054-ac88-766f0aad5a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDg3OTIsIm5iZiI6MTcyNDIwODQ5MiwicGF0aCI6Ii8yNjU0MjE3Mi8zNTU0NTkwMDgtNzQwZGFkZDEtMDM4Mi00MDU0LWFjODgtNzY2ZjBhYWQ1YTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAyNDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwODRiMzI3ZmNkMmU1NjNlNWU5NDVmMTg5NWQzNzgyZDU4NmQ1NWQ4MWZjMmQ2YTQ0NmNkYWRhMmIwNjkzYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wEzYXTxfRr2XMWI2_4OvLbNF7ha9SG_4jKgp6HalBVQ)
> > **Your hardware and system info** Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
> > ![image](https://private-user-images.githubusercontent.com/26542172/355459348-4a86d682-629a-4d5d-bfaf-b501d27beb11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDg3OTIsIm5iZiI6MTcyNDIwODQ5MiwicGF0aCI6Ii8yNjU0MjE3Mi8zNTU0NTkzNDgtNGE4NmQ2ODItNjI5YS00ZDVkLWJmYWYtYjUwMWQyN2JlYjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAyNDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMWFiYTZhZDYzNjgxYTQzYTk1NjUxMWQ3MmJiNzMzNzNkNDlkNzJmNzUwZmQ3Mzc0ZjAzNDczNjE4ZTczNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VjoDkl1ZPSF85IdE_hUj9DZ8jv53MfLUsDpubRC-nXA)
> > **Additional context** Add any other context about the problem here(在这里补充其他信息)
> 
> 这个问题已经修复了

你好，想问一下你是怎么解决的问题吗，我也遇到了一样的问题
