### ISSUE TITLE
florence最佳实践问题咨询

### ISSUE THREAD

**Issue by danxuan2022** [modelscope/ms-swift#1621]
![image](https://github.com/user-attachments/assets/d3e4d1aa-a583-47fe-b278-50767ef6d8b1)

**Comment by tastelikefeet** [comment]
视频介绍在这里：https://swift.readthedocs.io/zh-cn/latest/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.html
实际location是这样的：
![image](https://github.com/user-attachments/assets/8259ea4d-1dd5-474c-92af-552a1d6910f7)
