### ISSUE TITLE
你好，想问下swift中template.py文件，怎么样和指令微调一起使用呢？

### ISSUE THREAD

**Issue by fang-siqi** [modelscope/ms-swift#1623]
我刚刚查询了swift的文档，发现对于template.py介绍的比较少，而我目前正在做指令微调，不知道指令微调的template该怎么使用，可否详细给一个资料，比如
`instruction = tokenizer(f"<|im_start|>system\n <|im_end|>\n<|im_start|>user\n{example['instruction'] + example['input']}<|im_end|>\n<|im_start|>assistant\n", add_special_tokens=False)`
类似于这种，该如何使用template模板进行微调。

**Comment by fang-siqi** [comment]
以及数据集处理的话，处理数据集的process_func，又应该如何定义呢？

**Comment by tastelikefeet** [comment]
这部分我们后面会做一次整体重构，到时候文档会给的更清晰
目前依赖于开发者自行读一下代码
process_func的话，可以参考：https://swift.readthedocs.io/zh-cn/latest/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.html
