### ISSUE TITLE
florence模型微调报错

### ISSUE THREAD

**Issue by danxuan2022** [modelscope/ms-swift#1624]
swift使用2.2分支编译，bbox我这边确认是int类型，辛苦大佬帮忙看下～
![image](https://github.com/user-attachments/assets/2ee29698-f9b0-491d-8cfa-d74981071853)

![image](https://github.com/user-attachments/assets/73edd5b7-38f4-4a84-adda-28bac8e6fe99)

**Comment by danxuan2022** [comment]
在main分之上重新编译了一下swift，上面问题解决了，但是报了一个新的问题
![image](https://github.com/user-attachments/assets/3704fce3-6858-498c-b698-1878c4c6a4b9)
数据集是本地jsonl，大概几十个图像json
![image](https://github.com/user-attachments/assets/ce2fbea2-6bb7-491a-b9f3-2420b9c86476)

**Comment by danxuan2022** [comment]
我将images

> 在main分之上重新编译了一下swift，上面问题解决了，但是报了一个新的问题 ![image](https://private-user-images.githubusercontent.com/107532297/355767420-3704fce3-6858-498c-b698-1878c4c6a4b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODM1MDAsIm5iZiI6MTcyMzA4MzIwMCwicGF0aCI6Ii8xMDc1MzIyOTcvMzU1NzY3NDIwLTM3MDRmY2UzLTY4NTgtNDk4Yy1iNjk4LTE4NzhjNGM2YTRiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwMjEzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMThhMGM3N2VhNDE1YjE2N2IxYWQ0NGVhOTBhZjhmNjBjNzQ4N2RkNWI4ZTU2NjE4YWU1M2UwZDZiYzNiZWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tJ_6UPzAkegJGXCz7w5lwN_ll3SlHJmxBm99ByGKhco) 数据集是本地jsonl，大概几十个图像json ![image](https://private-user-images.githubusercontent.com/107532297/355767769-ce2fbea2-6bb7-491a-b9f3-2420b9c86476.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODM1MDAsIm5iZiI6MTcyMzA4MzIwMCwicGF0aCI6Ii8xMDc1MzIyOTcvMzU1NzY3NzY5LWNlMmZiZWEyLTZiYjctNDkxYS1iOWYzLTI0MjBiOWM4NjQ3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwMjEzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTRmMWY0NmRiMTNjZTQ5OGNjM2ZhZGM0NDA5MDBmMDYzYWI0NjhmNDZkOTNmYzhmODk5YzNhYTE2MzJmNjc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tilKUo7erazqpJrgz5X_VYFP4GSCEnu2xg9NxKhky3E)

将所有imges都idx都设置为0可以微调

**Comment by tastelikefeet** [comment]
首先images的问题，images的idx需要符合你的images字段的图片数量，这个是用来标识你的bbox隶属于哪个图片的
其次是object的index只能是int的问题，我强烈怀疑是之前的bug，请用最新代码试一下

**Comment by tastelikefeet** [comment]
如果有问题请重新打开这个issue
