### ISSUE TITLE
swift swift-ui error: unable to invoke subcommand: swift-web-ui (No such file or directory)

### ISSUE THREAD

**Issue by zhaoxianxin** [modelscope/ms-swift#1629]
(swift) tyzl@tyzl-zxx-m1pro ~ % cd swift 
(swift) tyzl@tyzl-zxx-m1pro swift % ls
CODE_OF_CONDUCT.md	LICENSE			README.md		docs			requirements		scripts			swift
CONTRIBUTING.md		MANIFEST.in		README_CN.md		examples		requirements.txt	setup.cfg		tests
CONTRIBUTING_CN.md	Makefile		asset			ms_swift.egg-info	resources		setup.py		tools
(swift) tyzl@tyzl-zxx-m1pro swift % swift --version
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
(swift) tyzl@tyzl-zxx-m1pro swift % swift web-ui
error: unable to invoke subcommand: swift-web-ui (No such file or directory)

**Comment by tastelikefeet** [comment]
Because your mac has two swift: 
one is ours
one is the Apple language 'swift'...

**Comment by herandy** [comment]
So the workaround is to use the full path from your python bin directory where the new swift is put, so on mine it looks like `/Users/amir/mambaforge/bin/swift` for example
