### ISSUE TITLE
llama3.1 405B 推理 报错

### ISSUE THREAD

**Issue by zhangfan-algo** [modelscope/ms-swift#1636]
[INFO:swift] Successfully registered `/mnt/pfs/zhangfan/system/test/conda/envs/swift/lib/python3.10/site-packages/swift/llm/data/dataset_info.json`
[ERROR:swift] import vllm_utils error: No module named 'openai.types'
[INFO:swift] ckpt_dir: None
[INFO:swift] Due to `ckpt_dir` being `None`, `load_args_from_ckpt_dir` is set to `False`.
[INFO:swift] Setting template_type: qwen
[INFO:swift] Setting self.eval_human: True
[INFO:swift] Setting overwrite_generation_config: False
[INFO:swift] Start time of running main: 2024-08-08 15:19:06.931173
[INFO:swift] args: AppUIArguments(model_type='qwen-7b-chat-int4', model_id_or_path='qwen/Qwen-7B-Chat-Int4', model_revision='master', sft_type='full', template_type='qwen', infer_backend='vllm', ckpt_dir=None, result_dir=None, load_args_from_ckpt_dir=False, load_dataset_config=False, eval_human=True, seed=42, dtype='fp16', dataset=[], val_dataset=[], dataset_seed=42, dataset_test_ratio=0.01, show_dataset_sample=10, save_result=True, system=None, tools_prompt='react_en', max_length=None, truncation_strategy='delete', check_dataset_strategy='none', model_name=[None, None], model_author=[None, None], quant_method=None, quantization_bit=0, hqq_axis=0, hqq_dynamic_config_path=None, bnb_4bit_comp_dtype='fp16', bnb_4bit_quant_type='nf4', bnb_4bit_use_double_quant=True, bnb_4bit_quant_storage=None, max_new_tokens=2048, do_sample=True, temperature=0.3, top_k=20, top_p=0.7, repetition_penalty=1.0, num_beams=1, stop_words=[], rope_scaling=None, use_flash_attn=None, ignore_args_error=False, stream=True, merge_lora=False, merge_device_map='cpu', save_safetensors=True, overwrite_generation_config=False, verbose=None, local_repo_path=None, custom_register_path=None, custom_dataset_info=None, device_map_config_path=None, device_max_memory=[], hub_token=None, gpu_memory_utilization=0.9, tensor_parallel_size=1, max_model_len=None, disable_custom_all_reduce=True, enforce_eager=False, vllm_enable_lora=False, vllm_max_lora_rank=16, lora_modules=[], image_input_shape=None, image_feature_size=None, tp=1, cache_max_entry_count=0.8, quant_policy=0, vision_batch_size=1, self_cognition_sample=0, train_dataset_sample=-1, val_dataset_sample=None, safe_serialization=None, model_cache_dir=None, merge_lora_and_save=None, custom_train_dataset_path=[], custom_val_dataset_path=[], vllm_lora_modules=None, host='127.0.0.1', port=7860, share=False, server_name=None, server_port=None)
[INFO:swift] Global seed set to 42
Traceback (most recent call last):
  File "/mnt/pfs/zhangfan/study_info/swift_0807/examples/pytorch/llm/app.py", line 16, in <module>
    app_ui_main(args)
  File "/mnt/pfs/zhangfan/system/test/conda/envs/swift/lib/python3.10/site-packages/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/mnt/pfs/zhangfan/system/test/conda/envs/swift/lib/python3.10/site-packages/swift/llm/app_ui.py", line 108, in llm_app_ui
    gradio_chat_demo(args)
  File "/mnt/pfs/zhangfan/system/test/conda/envs/swift/lib/python3.10/site-packages/swift/llm/app_ui.py", line 58, in gradio_chat_demo
    from swift.llm import prepare_vllm_engine_template, inference_stream_vllm as inference_stream_x
ImportError: cannot import name 'prepare_vllm_engine_template' from 'swift.llm' (/mnt/pfs/zhangfan/system/test/conda/envs/swift/lib/python3.10/site-packages/swift/llm/__init__.py)

**Comment by zhangfan-algo** [comment]
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 swift deploy \
    --infer_backend vllm \
    --model_type llama3_1-405b-instruct \
    --sft_type full \
    --model_id_or_path  Meta-Llama-3.1-405B-Instruct \
    --port 9005 \
    --host 0.0.0.0 \
    --max_model_len 1024 \
    --tensor_parallel_size 8

**Comment by Jintao-Huang** [comment]
跑fp8, awq-int4

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/issues/1484
