### ISSUE TITLE
AttributeError: 'Seq2SeqTrainer' object has no attribute 'sft_args'

### ISSUE THREAD

**Issue by xingyang-zhang** [modelscope/ms-swift#1641]
**Describe the bug**
.conda/envs/swift/lib/python3.10/site-packages/swift/trainers/trainers.py", line 220, in compute_loss
    if self.state.global_step % self.sft_args.acc_steps == 0:
AttributeError: 'Seq2SeqTrainer' object has no attribute 'sft_args'

When I use A600 to train code GLM3, I encounter the above problem. I have checked the package code and found that the Seq2SeqTrainer class does not define the attribute sft_args. If you have misunderstood, please correct me

**Comment by Jintao-Huang** [comment]
main分支修复了
