### ISSUE TITLE
使用webui加载的模型是否开放openai 接口

### ISSUE THREAD

**Issue by lianqi1998** [modelscope/ms-swift#1646]
如果网页部署后单独重开一个实例用于 提供OpenAI接口太消耗资源了。
在文档里没有找到相关的信息，尝试访问8000端口，只能获取模型信息，不知道对应的key，无法交互。

**Comment by tastelikefeet** [comment]
网页部署开端口的

**Comment by lianqi1998** [comment]
> 网页部署开端口的

是8000端口嘛，请问访问方式也是如下地址嘛
/v1/chat/completions
/v1/models
/v1/completions
具体的key是什么呀，没有访问成功，不知道和key有没有关系

**Comment by tastelikefeet** [comment]
key是默认的，EMPTY

**Comment by lianqi1998** [comment]
> key是默认的，EMPTY

太感谢了。docker设置--network host成功连上了 
还有个小问题，能对端口的开放方式进行自定义吗，比如修改端口，以及局域网或者docker访问openai接口。

**Comment by tastelikefeet** [comment]
UI界面可以直接在高级参数中填入--host xxx

**Comment by lianqi1998** [comment]
> UI界面可以直接在高级参数中填入--host xxx

谢谢！！
