### ISSUE TITLE
vllm multilora支持

### ISSUE THREAD

**Issue by zhangfan-algo** [modelscope/ms-swift#1656]
未来可以支持2个以上的lora权重部署模型不

**Comment by tastelikefeet** [comment]
已经支持了，参考：https://swift.readthedocs.io/zh-cn/latest/LLM/VLLM%E6%8E%A8%E7%90%86%E5%8A%A0%E9%80%9F%E4%B8%8E%E9%83%A8%E7%BD%B2.html
