### ISSUE TITLE
glm-4v 微调错误

### ISSUE THREAD

**Issue by 66246764** [modelscope/ms-swift#1658]
**Describe the bug**
File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 1035, in forward
    full_attention_mask = self.get_masks(inputs_embeds, past_key_values, padding_mask=attention_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 835, in get_masks
    full_attention_mask = full_attention_mask * padding_mask.unsqueeze(1)
                          ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (1724) must match the size of tensor b (125) at non-singleton dimension 2

**Comment by 66246764** [comment]
加载完checkpoint，train到一半突然报这个错误

**Comment by 66246764** [comment]
应该是每哥epoch train后，在eval时会报错

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/issues/1219
