### ISSUE TITLE
sft是否支持指定模型的特定参数？

### ISSUE THREAD

**Issue by JiaweiZhao-git** [modelscope/ms-swift#1661]
比如InternVL中的dynamic_image_size和max_dynamic_patch？

**Comment by tastelikefeet** [comment]
目前还不支持，可以自己魔改下代码，搜索model.py和template.py，魔改这两个就好，改动量应该不大的

**Comment by drinkingxi** [comment]
![image](https://github.com/user-attachments/assets/c7601237-0f0e-48ac-9412-1fd7b774edc5)
不想改代码的话，可以直接手动改这个函数的参数默认值

**Comment by tastelikefeet** [comment]
目前已经支持了，可以用环境变量方式使用：
https://swift.readthedocs.io/zh-cn/latest/LLM/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.html
`--model_kwargs`
