### ISSUE TITLE
训练参数batch_size问题

### ISSUE THREAD

**Issue by longgb246** [modelscope/ms-swift#1671]
训练参数：

CUDA_VISIBLE_DEVICES=0,1 swift sft \
    --model_type internvl2-llama3-76b \
    --model_id_or_path /mnt/workspace/InternVL2-Llama3-76B \
    --dataset /mnt/workspace/contacts_1200_add_2000.json \
    --lora_target_modules ALL \
    --output_dir /mnt/workspace/contacts_1200_add_2000 \
    --max_length 4096 \
    --num_train_epochs 1

训练过程如下：

![image](https://github.com/user-attachments/assets/302e3257-4804-4d26-b3b3-50a576a3ae10)

样本有3200条，为什么这里显示的 'max_steps'为 '198'？文档中的batch_size默认参数应该是：1，这里看上去貌似是16？

**Comment by tastelikefeet** [comment]
默认gradient_accumulation_steps=16，会导致16个step 更新一次参数，因此相当于batch_size扩大了

**Comment by longgb246** [comment]
了解了，感谢！
