### ISSUE TITLE
微调minicpm-v-v2_6-chat报错

### ISSUE THREAD

**Issue by samaritan1998** [modelscope/ms-swift#1673]
微调minicpm-v-v2_6-chat出现报错:
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 491, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

微调其他模型是可以的，微调命令如下：

```
CUDA_VISIBLE_DEVICES=0,1,2,3 NPROC_PER_NODE=4 swift sft \
  --model_type minicpm-v-v2_6-chat \
  --model_id_or_path OpenBMB/MiniCPM-V-2_6 \
  --sft_type lora \
  --dataset **.jsonl \
  --deepspeed default-zero2
```

**Comment by Jintao-Huang** [comment]
我这里没有报错啊
你看看 数据集使用coco-en-mini 是否报错

**Comment by Jintao-Huang** [comment]
解决了吗

**Comment by Jintao-Huang** [comment]
拉一下main分支
