### ISSUE TITLE
sft 增大显卡数，速度没有提升，修改了gradient_accumulation_steps, remaining_time还是不变

### ISSUE THREAD

**Issue by luyao-cv** [modelscope/ms-swift#1674]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
检查一下是否使用了NPROC_PER_NODE, 是否使用多进程进行训练
