### ISSUE TITLE
voice chat中音频改成本地地址报错

### ISSUE THREAD

**Issue by viviliuwqhduhnwqihwqwudceygysjiwuwnn** [modelscope/ms-swift#1675]
processor = AutoProcessor.from_pretrained("Qwen/Qwen2-Audio-7B-Instruct")
model = Qwen2AudioForConditionalGeneration.from_pretrained("Qwen/Qwen2-Audio-7B-Instruct", device_map="auto")
conversation = [
   
    {"role": "user", "content": [
        {"type": "audio",
         "audio_url": r"D:\Edge_download\audio.wav"},
    ]},
]
text = processor.apply_chat_template(conversation, add_generation_prompt=True, tokenize=False)
audios = []
for message in conversation:
    if isinstance(message["content"], list):
        for ele in message["content"]:
            if ele["type"] == "audio":
                audios.append(librosa.load(
                    BytesIO(urlopen(ele['audio_url']).read()),
                    sr=processor.feature_extractor.sampling_rate)[0]
                              )

inputs = processor(text=text, audios=audios, return_tensors="pt", padding=True)
inputs.input_ids = inputs.input_ids.to("cpu")

generate_ids = model.generate(**inputs, max_length=256)
generate_ids = generate_ids[:, inputs.input_ids.size(1):]

response = processor.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
print(response)报错:
Traceback (most recent call last):
  File "D:\liu\FunASR-main\Qwen2-Audio.py", line 8, in <module>
    model = Qwen2AudioForConditionalGeneration.from_pretrained("Qwen/Qwen2-Audio-7B-Instruct", device_map="auto")
  File "D:\liu\anaconda3\envs\env_name\lib\site-packages\transformers\modeling_utils.py", line 4016, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "D:\liu\anaconda3\envs\env_name\lib\site-packages\accelerate\big_modeling.py", line 496, in dispatch_model
    raise ValueError(
ValueError: You are trying to offload the whole model to the disk. Please use the `disk_offload` function instead.

**Comment by Jintao-Huang** [comment]
看报错是显存不足啊

torch_dtype传入torch.bfloat16

**Comment by viviliuwqhduhnwqihwqwudceygysjiwuwnn** [comment]
感谢,torch_dtype这个参数放哪里啊,model = Qwen2AudioForConditionalGeneration.from_pretrained("Qwen/Qwen2-Audio-7B-Instruct", device_map="auto", torch_dtype=torch.bfloat16)这吗请问

**Comment by Jintao-Huang** [comment]
解决了吗

**Comment by viviliuwqhduhnwqihwqwudceygysjiwuwnn** [comment]
解决了,感谢
