### ISSUE TITLE
Support using lmdeploy for inference and deployment on videos (internvl2)

### ISSUE THREAD

**Issue by Jintao-Huang** [modelscope/ms-swift#1679]
install ms-swift from source
```python
pip install git+https://github.com/modelscope/swift.git
```

中文文档：

https://swift.readthedocs.io/zh-cn/latest/Multi-Modal/LmDeploy%E6%8E%A8%E7%90%86%E5%8A%A0%E9%80%9F%E6%96%87%E6%A1%A3.html#python

English Documentation:

https://swift.readthedocs.io/en/latest/Multi-Modal/LmDeploy-inference-acceleration.html#using-python

**Comment by happy-xlf** [comment]
@Jintao-Huang 您好，这个加速推理视频的结果不对，我用的InternVL2-2B模型进行推理，出现的结果是这样的
<img width="1092" alt="截屏2024-08-14 11 12 00" src="https://github.com/user-attachments/assets/fc2d1a26-8d74-4669-b181-22460a3b0f62">

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/issues/1695
