### ISSUE TITLE
模型轻量化问题

### ISSUE THREAD

**Issue by crs-syr** [modelscope/ms-swift#1683]
请问如果想要单卡24G显存实现LORA微调，替换self.llm为更小尺度的语言模型可行么，如果可行，您有没有替换更加方便的模型推荐，非常期待您的指正和回复

**Comment by tastelikefeet** [comment]
多模态模型吗？self.llm替换成更小的模型是可行的，但流程比较复杂，相当于重新研发一个新的多模态模型了

**Comment by tastelikefeet** [comment]
可以尝试internvl2系列
