### ISSUE TITLE
单机多卡执行 LLaMA-2 全量 SFT 时 NCCL Timeout 报错

### ISSUE THREAD

**Issue by xiaosongyuan** [modelscope/ms-swift#1690]
**单机多卡SFT LLaMA-2-7B和LLaMA-2-13B，在epoch从0.99到1时报错**
<img width="1272" alt="截屏2024-08-13 16 38 39" src="https://github.com/user-attachments/assets/d7301692-3dec-484f-9a2c-c870973f8abf">

**硬件环境**
GPU: A100
CUDA: 11.7
torch==2.0.1
transformers==4.37.1
datasets==2.16.1

**执行脚本**
`
pip install -e '.[llm]' -i https://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com

export MKL_THREADING_LAYER=pthreads
nproc_per_node=8
NPROC_PER_NODE=$nproc_per_node
MASTER_PORT=29500
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
torchrun \
    --nproc_per_node $nproc_per_node \
    --master_port $MASTER_PORT \
    --nnodes 1 \
    --node_rank 0 \
    llm_sft.py \
    --model_type llama2-13b \
    --model_id_or_path /mnt/models/models/public/Llama/Llama2/Llama-2-13b-hf-4k \
    --model_revision master \
    --sft_type full \
    --template_type AUTO \
    --dtype AUTO \
    --custom_train_dataset_path logic_merge.jsonl \
    --output_dir ckpt/logic_merge \
    --ddp_backend nccl \
    --train_dataset_sample -1 \
    --num_train_epochs 3 \
    --max_length 2048 \
    --check_dataset_strategy warning \
    --gradient_checkpointing true \
    --batch_size 2 \
    --weight_decay 0.1 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps $(expr 64 / $nproc_per_node) \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --deepspeed 'default-zero3' \
    --save_only_model true \
`

**以上脚本在SFT LLaMA-3-8B、Qwen-1.5-7B、Qwen-1.5-14B和Qwen-2-7B时均可正常运行，仅LLaMA-2系列模型报错**
在LLaMA-2报错后，尝试缩小数据规模，仍报相同错误。

**Comment by tastelikefeet** [comment]
可以使用py-spy dump --pid xxx，在卡死后执行看下阻塞在了哪里

**Comment by xiaosongyuan** [comment]
在训练平台上做 SFT，命令执行中断后机器回收，没有命令行界面了。。
