### ISSUE TITLE
Swift delpy加速InternVL2-2b的视频推理结果不对

### ISSUE THREAD

**Issue by happy-xlf** [modelscope/ms-swift#1695]
**Describe the bug**
<img width="1092" alt="截屏2024-08-14 11 12 00" src="https://github.com/user-attachments/assets/a055312e-7226-4ce6-ae39-594665298b6a">

**Your hardware and system info**
lmdeploy                          0.5.3
Markdown                          3.6
markdown-it-py                    3.0.0
markdown2                         2.5.0
MarkupSafe                        2.1.5
matplotlib                        3.9.1
matplotlib-inline                 0.1.7
mdurl                             0.1.2
mistune                           3.0.2
mmengine-lite                     0.10.4
modelscope                        1.17.1
mpmath                            1.3.0
ms-swift                          2.3.0.post1
msgpack                           1.0.8
multidict                         6.0.5
multimethod                       1.12
multiprocess                      0.70.16
nbclient                          0.10.0
nbconvert                         7.16.4
nbformat                          5.10.4
nest_asyncio                      1.6.0
networkx                          3.3
nh3                               0.2.18
ninja                             1.11.1.1
nltk                              3.8.1
numba                             0.60.0
numpy                             1.26.4
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu12                 8.9.2.26
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu12              12.1.0.106
nvidia-ml-py                      12.535.161
nvidia-nccl-cu12                  2.20.5
nvidia-nvjitlink-cu12             12.5.82
nvidia-nvtx-cu12                  12.1.105
nvitop                            1.3.2
openai                            1.35.10
optimum                           1.21.2
orjson                            3.10.6
oss2                              2.18.6
outlines                          0.0.46
packaging                         24.1
pandas                            2.2.2
pandas-profiling                  3.6.6
pandocfilters                     1.5.1
parso                             0.8.4
patsy                             0.5.6
peft                              0.11.1
pexpect                           4.9.0
phik                              0.12.4
pickleshare                       0.7.5
pillow                            10.4.0
pip                               24.0
pipreqs                           0.5.0
platformdirs                      4.2.2
prometheus_client                 0.20.0
prometheus-fastapi-instrumentator 7.0.0
prompt_toolkit                    3.0.47
protobuf                          4.25.3
psutil                            5.9.0
ptyprocess                        0.7.0
pure-eval                         0.2.2
py-cpuinfo                        9.0.0
pyairports                        2.1.1
pyarrow                           16.1.0
pyarrow-hotfix                    0.6
pycountry                         24.6.1
pycparser                         2.22
pycryptodome                      3.20.0
pydantic                          2.8.2
pydantic_core                     2.20.1
pydantic-settings                 2.3.4
pydub                             0.25.1
Pygments                          2.18.0
pynvml                            11.5.3
pyparsing                         3.1.2
python-dateutil                   2.9.0
python-dotenv                     1.0.1
python-multipart                  0.0.9
pytz                              2024.1
PyWavelets                        1.6.0
PyYAML                            6.0.1
pyzmq                             25.1.2
ray                               2.31.0
referencing                       0.35.1
regex                             2024.5.15
requests                          2.32.3
rich                              13.7.1
rouge                             1.0.1
rouge-chinese                     1.0.3
rpds-py                           0.18.1
ruff                              0.5.0
safetensors                       0.4.3
scikit-learn                      1.5.1
scipy                             1.13.1
seaborn                           0.13.2
semantic-version                  2.10.0
sentencepiece                     0.2.0
setuptools                        69.5.1
shellingham                       1.5.4
shortuuid                         1.0.13
shtab                             1.7.1
simplejson                        3.19.2
six                               1.16.0
sniffio                           1.3.1
sortedcontainers                  2.4.0
soupsieve                         2.5
SQLAlchemy                        2.0.31
sse-starlette                     2.1.2
stack-data                        0.6.2
starlette                         0.37.2
statsmodels                       0.14.2
svgwrite                          1.4.3
sympy                             1.12.1
tenacity                          8.5.0
tensorboard                       2.17.0
tensorboard-data-server           0.7.2
termcolor                         2.4.0
threadpoolctl                     3.5.0
tiktoken                          0.7.0
timm                              1.0.7
tinycss2                          1.3.0
tokenizers                        0.19.1
tomli                             2.0.1
tomlkit                           0.12.0
toolz                             0.12.1
torch                             2.3.0
torchvision                       0.18.0
tornado                           6.1
tqdm                              4.66.4
traitlets                         5.14.3
transformers                      4.42.4
transformers-stream-generator     0.0.5
triton                            2.3.0
trl                               0.9.6
typeguard                         4.3.0
typer                             0.12.3
typing_extensions                 4.12.2
tyro                              0.8.5
tzdata                            2024.1
ujson                             5.10.0
urllib3                           2.2.2
uvicorn                           0.30.1
uvloop                            0.19.0
visions                           0.7.6
vllm                              0.5.0.post1
vllm-flash-attn                   2.5.9
watchfiles                        0.22.0
wavedrom                          2.0.3.post3
wcwidth                           0.2.13
webencodings                      0.5.1
websockets                        11.0.3
Werkzeug                          3.0.3
wheel                             0.43.0
widgetsnbextension                4.0.11
wordcloud                         1.9.3
xformers                          0.0.26.post1
xxhash                            3.4.1
yapf                              0.40.2
yarg                              0.1.9
yarl                              1.9.4
ydata-profiling                   4.9.0
zipp                              3.19.2

**Additional context**
测试swift的普通视频推理，没问题，加速推理就是不行，推理出来的内容不对

**Comment by Jintao-Huang** [comment]
有传入videos=['video_path']不

**Comment by happy-xlf** [comment]
@Jintao-Huang 有的，自己本地的也试了，官方的例子也试了，都不行

**Comment by happy-xlf** [comment]
```python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

# from swift.hub import HubApi
# _api = HubApi()
# _api.login('<your-sdk-token>')  # https://modelscope.cn/my/myaccesstoken

from swift.llm import (
    ModelType, get_lmdeploy_engine, get_default_template_type,
    get_template, inference_lmdeploy, inference_stream_lmdeploy
)

model_type = ModelType.internvl2_8b
model_id_or_path = '/root/autodl-tmp/Models/InternVL2-8B'
lmdeploy_engine = get_lmdeploy_engine(model_type, model_id_or_path=model_id_or_path)
template_type = get_default_template_type(model_type)
template = get_template(template_type, lmdeploy_engine.hf_tokenizer)
lmdeploy_engine.generation_config.max_new_tokens = 256
generation_info = {}

request_list = [{'query': '<video>描述视频', 'videos': ['http://modelscope-open.oss-cn-hangzhou.aliyuncs.com/images/baby.mp4']}]
resp_list = inference_lmdeploy(lmdeploy_engine, template, request_list, generation_info=generation_info)
for request, resp in zip(request_list, resp_list):
    print(f"query: {request['query']}")
    print(f"response: {resp['response']}")
print(generation_info)
```
用的就是官方给的

**Comment by Jintao-Huang** [comment]
main分支试试呢，我这里测试是可以的

**Comment by Jintao-Huang** [comment]
解决了吗

**Comment by happy-xlf** [comment]
@Jintao-Huang 确实得main分支安装才能视频推理成功，这个就不行pip install 'ms-swift[llm]' -U

**Comment by PancakeAwesome** [comment]
internvl2 + vllm 的推理后端，怎么支持 视频推理呢？
