### ISSUE TITLE
关于sft数据长度问题

### ISSUE THREAD

**Issue by mxjmtxrm** [modelscope/ms-swift#1699]
您好，请问如果sft的数据长度大于设置的max_length该怎么做？我看代码里是直接padding到batch中最大的长度，那设置最大seq length是不是没用了？

**Comment by tastelikefeet** [comment]
最大max_length代表”可以接受的最大长度，并截止到此“
因此这个和padding到batch中的最大长度并不冲突
如果sft的数据长度大于设置的max_length，请适当提高max_length的值
