### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by ifsheldon** [modelscope/ms-swift#1711]
**Describe the feature**

In the README, the docker image is `docker pull registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda12.1.0-py310-torch2.1.2-tf2.14.0-1.13.1`, but when I pulled it and ran it, I found the packages in this image is very outdated. `ms-swift` is `1.7`. Can you please update the image?

**Comment by tastelikefeet** [comment]
Updated
