### ISSUE TITLE
swift backend使用vllm推理时，openai接口不支持logprobs输出概率

### ISSUE THREAD

**Issue by baibaiw5** [modelscope/ms-swift#1719]
使用以下命令启动qwen2 0.5b模型
USE_HF=1 CUDA_VISIBLE_DEVICES=3 swift deploy --model_type qwen2-0_5b  --model_id_or_path  /home/bmb/models/Qwen/models--Qwen--Qwen2-0.5B-Instruct/snapshots/c291d6fce4804a1d39305f388dd32897d1f7acc4  \
    --infer_backend vllm --max_model_len 2048  --model_name qwen2

curl http://localhost:8000/v1/completions \
-H "Content-Type: application/json" \
-d '{
"model": "qwen2-0_5b",
"prompt": "你是谁？",
"max_tokens": 32,
"temperature":0.1,
"logprobs":10,
"seed": 42
}'
curl以上接口，返回以下内容，设置的logprobs不生效
{"model":"qwen2-0_5b","choices":[{"index":0,"text":"我叫李明，今年12岁，我是一个活泼开朗、乐于助人的男孩。我最喜欢的颜色是蓝色，因为蓝色能让我感到","finish_reason":"length"}],"usage":{"prompt_tokens":3,"completion_tokens":32,"total_tokens":35},"id":"cmpl-e45f92a689514f748a9bdc1d901bce49","object":"text_completion","created":1723727637}

直接使用vllm推理上面的Qwen--Qwen2-0.5B-Instruct模型
{"id":"cmpl-f331258f47f640fe8f6efc85026333d0","object":"text_completion","created":1723728145,"model":"qwen","choices":[{"index":0,"text":"我叫李明，今年12岁，是北京某中学的七年级学生。我是一个热爱阅读和写作的少年。我经常在课","logprobs":{"text_offset":[0,1,2,3,4,5,7,8,9,10,11,12,14,15,17,18,19,21,23,24,25,28,30,32,33,35,36,38,39,40,42,43],"token_logprobs":[-0.6932239532470703,0.0,-0.05301526561379433,-2.0861407392658293e-05,-3.576278118089249e-07,-0.00033766290289349854,0.0,-0.018645843490958214,0.0,-0.00014006110723130405,-3.10103440284729,-0.00033396866638213396,-0.0001234931987710297,-0.00033539868309162557,-0.006883005611598492,-0.0003887851198669523,0.0,0.0,0.0,0.0,-0.127571702003479,-0.05128540098667145,-0.00496191531419754,-0.04906846210360527,-0.042632829397916794,-0.0027218933682888746,-0.0028102213982492685,-0.12692804634571075,-0.00033766290289349854,-7.891343557275832e-05,-0.0009114163694903255,-1.3133089542388916],"tokens":["我","叫","李","明","，","今年","1","2","岁","，","是","北京","某","中学","的","七","年级","学生","。","我","是一个","热爱","阅读","和","写作","的","少年","。","我","经常","在","课"],"top_logprobs":[{"我":-0.6932239532470703,"你":-0.6932239532470703," ":-10.19322395324707,"我是":-10.19322395324707,"（":-13.19322395324707,"你是":-16.69322395324707,"在":-20.19322395324707,"":-20.69322395324707,"他":-21.69322395324707,"谁":-21.69322395324707},{"叫":0.0,"就是":-17.0,"是一个":-22.0,"是一":-24.0,"姓":-27.0,"是一名":-28.5,"来自":-29.0,"是什么":-33.0,"是一位":-35.5,"是不是":-36.5},{"李":-0.05301526561379433,"小":-3.0530152320861816,"张":-5.553015232086182,"王":-7.553015232086182,"陈":-11.55301570892334,"“":-12.05301570892334,"刘":-13.05301570892334,"阿":-15.55301570892334,"林":-16.553014755249023,"周":-18.053014755249023},{"明":-2.0861407392658293e-05,"晓":-11.500020980834961,"小":-12.000020980834961,"华":-12.500020980834961,"文":-14.000020980834961,"浩":-17.50002098083496,"云":-17.50002098083496,"伟":-19.50002098083496,"晨":-20.00002098083496,"天":-22.50002098083496},{"，":-3.576278118089249e-07,"。":-15.0,"宇":-34.5,"。\n":-38.0,"辉":-41.5,"．":-42.5,"华":-45.5,"杰":-45.5,"！":-47.5,"浩":-47.5},{"今年":-0.00033766290289349854,"我":-8.000337600708008,"是":-13.000337600708008,"来自":-19.000337600708008,"一个":-22.000337600708008,"是一名":-22.000337600708008,"1":-23.000337600708008,"我的":-27.500337600708008,"我在":-30.000337600708008,"是一个":-31.500337600708008},{"1":0.0,"九":-22.0,"十二":-25.0,"8":-26.0,"八":-28.0,"9":-29.0,"十三":-30.0,"十":-30.0,"2":-33.0,"7":-34.0},{"2":-0.018645843490958214,"3":-4.018645763397217,"1":-8.018646240234375,"4":-9.018646240234375,"0":-10.018646240234375,"5":-14.018646240234375,"6":-20.018646240234375,"7":-24.018646240234375,"8":-26.018646240234375,"9":-35.018646240234375},{"岁":0.0,"周岁":-62.0,"":-68.0,"了":-88.0,"月":-88.0,"，":-88.0,".":-88.0,"岁的":-91.0,"岁时":-94.0,"个月":-99.0},{"，":-0.00014006110723130405,"。":-9.000140190124512,"了":-11.000140190124512,"，在":-24.000139236450195,"。\n":-36.00014114379883,"．":-40.00014114379883,"。\n\n":-53.00014114379883,"啦":-53.00014114379883,"。“":-60.00014114379883,"！":-67.50013732910156},{"是":-3.10103440284729,"我":-0.10103436559438705,"我在":-3.10103440284729,"来自":-5.101034164428711,"我的":-13.101034164428711,"身高":-16.10103416442871,"我喜欢":-16.10103416442871,"是一名":-16.10103416442871,"我们":-20.10103416442871,"喜欢":-20.10103416442871},{"北京":-0.00033396866638213396,"XX":-9.000333786010742,"某":-9.500333786010742,"九":-10.000333786010742,"你们":-10.500333786010742,"三年级":-10.500333786010742,"七":-11.500333786010742,"二":-12.000333786010742,"六":-12.500333786010742,"八":-12.500333786010742},{"某":-0.0001234931987710297,"人":-9.000123023986816,"的":-16.000123977661133,"的一":-18.500123977661133,"实验":-21.000123977661133,"一所":-22.000123977661133,"三":-22.000123977661133,"一":-25.000123977661133,"师范大学":-26.000123977661133,"第二":-26.500123977661133},{"中学":-0.00033539868309162557,"小学":-8.000335693359375,"学校":-21.000335693359375,"校":-24.000335693359375,"学校的":-26.000335693359375,"重点":-34.000335693359375,"初中":-34.000335693359375,"初级":-39.000335693359375,"高中":-39.000335693359375,"大学":-40.000335693359375},{"的":-0.006883005611598492,"的学生":-5.006883144378662,"的一":-9.006882667541504,"七":-10.006882667541504,"八":-20.00688362121582,"五年":-21.00688362121582,"三年级":-21.00688362121582,"九":-21.00688362121582,"高":-21.00688362121582,"初":-21.00688362121582},{"七":-0.0003887851198669523,"高":-8.000389099121094,"九":-10.000389099121094,"八":-12.000389099121094,"五年":-14.000389099121094,"三年级":-14.000389099121094,"初中":-16.000389099121094,"六":-18.000389099121094,"中":-18.000389099121094,"四年":-19.000389099121094},{"年级":0.0,"（":-40.0,"(":-61.0,"一":-67.0,"、":-73.0,"班":-73.0,"岁":-76.0,"年纪":-81.0,"名":-82.0,"-":-85.0},{"学生":0.0,"二":-25.0,"（":-27.0,"一":-32.0,"三":-36.0,"新生":-38.0,"的学生":-49.0,"(":-52.0,"男生":-54.0,"1":-55.0},{"。":0.0,"，":-18.0,"。\n":-29.0,"。\n\n":-40.0,"，在":-46.0,"．":-49.0,"。“":-53.0,"！":-75.0,"。”":-76.0,"。（":-78.5},{"我":0.0,"我的":-19.0,"我在":-23.0,"我是":-25.0,"我喜欢":-27.0,"今天":-28.0,"我对":-35.0,"在":-39.0,"我想":-39.0,"最近":-41.5},{"是一个":-0.127571702003479,"有一个":-2.1275715827941895,"最喜欢":-8.127572059631348,"非常喜欢":-8.127572059631348,"性格":-10.127572059631348,"是个":-12.127572059631348,"来自":-12.127572059631348,"非常":-14.127572059631348,"是一名":-14.127572059631348,"最喜欢的":-15.127572059631348},{"热爱":-0.05128540098667145,"非常":-3.0512855052948,"活泼":-6.051285266876221,"喜欢":-8.051285743713379,"勤奋":-11.051285743713379,"聪明":-13.051285743713379,"乐观":-13.051285743713379,"爱":-14.051285743713379,"乐":-18.051284790039062,"爱好":-20.051284790039062},{"阅读":-0.00496191531419754,"学习":-6.004961967468262,"科学":-6.004961967468262,"运动":-11.004961967468262,"读书":-16.004961013793945,"生活":-23.004961013793945,"体育":-23.004961013793945,"自然":-24.004961013793945,"科技":-25.004961013793945,"探索":-26.004961013793945},{"和":-0.04906846210360527,"、":-3.0490684509277344,"的小":-8.049068450927734,"的孩子":-9.049068450927734,"的人":-10.049068450927734,"的":-14.049068450927734,"，":-16.049068450927734,"并":-30.049068450927734,"并且":-30.049068450927734,"的学生":-34.049068450927734},{"写作":-0.042632829397916794,"探索":-4.042633056640625,"科学":-4.042633056640625,"学习":-5.042633056640625,"思考":-9.042633056640625,"体育":-10.042633056640625,"旅行":-11.042633056640625,"探险":-17.042633056640625,"运动":-18.042633056640625,"音乐":-21.042633056640625},{"的":-0.0027218933682888746,"的小":-6.002721786499023,"的人":-9.002721786499023,"的孩子":-9.002721786499023,"的学生":-18.002721786499023,"的女孩":-33.002723693847656,"的好":-43.002723693847656,"，":-44.002723693847656,"的朋友":-48.002723693847656,"的年轻人":-49.002723693847656},{"少年":-0.0028102213982492685,"男孩":-6.002810001373291,"中":-8.00281047821045,"青少年":-18.002809524536133,"书":-28.002809524536133,"作家":-31.002809524536133,"小伙子":-36.002811431884766,"儿童":-37.002811431884766,"青年":-37.002811431884766,"“":-37.502811431884766},{"。":-0.12692804634571075,"，":-2.1269280910491943,"儿童":-32.12692642211914,"。\n":-32.12692642211914,"。\n\n":-41.12692642211914,"，在":-48.12692642211914,"作家":-50.12692642211914,"。“":-54.12692642211914,"！":-57.12692642211914,"，并":-64.1269302368164},{"我":-0.00033766290289349854,"我的":-8.000337600708008,"我喜欢":-13.000337600708008,"在":-27.000337600708008,"我在":-28.000337600708008,"最近":-30.000337600708008,"在我的":-30.000337600708008,"我对":-32.00033950805664,"我想":-32.00033950805664,"在我":-32.00033950805664},{"经常":-7.891343557275832e-05,"热爱":-10.000079154968262,"最喜欢":-11.000079154968262,"最喜欢的":-11.000079154968262,"特别":-16.000078201293945,"常常":-17.000078201293945,"从小就":-17.000078201293945,"每天":-18.000078201293945,"非常喜欢":-19.000078201293945,"读":-20.000078201293945},{"在":-0.0009114163694903255,"阅读":-7.000911235809326,"利用":-25.000911712646484,"参加":-26.000911712646484,"写":-27.000911712646484,"读":-29.000911712646484,"用":-29.000911712646484,"和":-30.000911712646484,"通过":-32.000911712646484,"把":-35.000911712646484},{"课":-1.3133089542388916,"周末":-0.3133088946342468,"放学":-10.313308715820312,"课外":-11.313308715820312,"书":-13.313308715820312,"图书馆":-16.313308715820312,"闲":-17.313308715820312,"晚上":-20.313308715820312,"空":-21.313308715820312,"阅读":-25.313308715820312}]},"finish_reason":"length","stop_reason":null}],"usage":{"prompt_tokens":3,"total_tokens":35,"completion_tokens":32}}

**Comment by baibaiw5** [comment]
看日志，不管接口输入logprobs，日志看到的都是None
{'request_id': 'cmpl-a9d732bc2e3e4f21894d5c32b7121b4e', 'model': 'qwen2-0_5b', 'prompt': '你是谁？', 'generation_config': SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.1, top_p=0.7, top_k=20, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|im_end|>'], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=32, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=False, spaces_between_special_tokens=True, truncate_prompt_tokens=None), 'seed': 42, 'stream': False}

**Comment by Jintao-Huang** [comment]
下个小版本会做（下周五前），明天的小版本是赶不上了

**Comment by AlbertBJ** [comment]
> 下个小版本会做（下周五前），明天的小版本是赶不上了

我现在用的2.3.1版本，这个问题 还存在啊

**Comment by AlbertBJ** [comment]
> 下个小版本会做（下周五前），明天的小版本是赶不上了

今天用2.3.2版本试了下，这个问题还是没有修复，请问哪个版本修复这个问题了 @Jintao-Huang

**Comment by Jintao-Huang** [comment]
忧伤

**Comment by tanshoudong** [comment]
请问现在支持了么？

**Comment by Jintao-Huang** [comment]
支持了

**Comment by Jintao-Huang** [comment]
main分支

**Comment by dee235** [comment]
麻烦问一下支持from swift.llm import inference支持logprobs输出吗 以及支持查找指定选项token的输出分布吗
