### ISSUE TITLE
[Help!]多图多轮微调internvl2报错

### ISSUE THREAD

**Issue by Egber1t** [modelscope/ms-swift#1721]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
执行代码：
CUDA_VISIBLE_DEVICES=0,1 NPROC_PER_NODE=2 swift sft \
  --model_type internvl2-1b \
  --model_id_or_path /root/autodl-tmp/model/InternVL2-1B
  --sft_type lora \
  --dataset /root/autodl-tmp/convert_reports.json \
  --deepspeed default-zero2

报错（应该是数据集构建出了问题）
![image](https://github.com/user-attachments/assets/5f458c97-64a2-4ca8-b8a0-a2be28976ff4)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)
按照
 数据集json截图如下：
![image](https://github.com/user-attachments/assets/bea99b75-e278-4b71-907c-83ac7a5f9c9e)
![image](https://github.com/user-attachments/assets/f752cdfc-d7ec-4cb4-ba53-b80d9d1921a9)

求大佬解答！

**Comment by Jintao-Huang** [comment]
--model_id_or_path /root/autodl-tmp/model/InternVL2-1B \

**Comment by Egber1t** [comment]
修改后命令如下：
NPROC_PER_NODE=2 \
CUDA_VISIBLE_DEVICES=0,1 swift sft \
    --model_type internvl2-1b \
    --model_id_or_path /root/autodl-tmp/model/InternVL2-1B \
    --dataset /root/autodl-tmp/convert_reports.json \
    --max_length 4096 \
    --deepspeed default-zero2
报错显示eosid出了问题
![image](https://github.com/user-attachments/assets/704ff787-97fd-4a1f-aa1c-60af1619cdca)

**Comment by Egber1t** [comment]
![image](https://github.com/user-attachments/assets/71c0a2af-9b13-4ad1-be24-eeaa323ebc8e)

**Comment by Jintao-Huang** [comment]
拉取一下main分支代码
