### ISSUE TITLE
lora微调后推理时遇到：ValueError: Due to limitations of the custom LoRA CUDA kernel, max_num_batched_tokens must be <= 65528 when LoRA is enabled.

### ISSUE THREAD

**Issue by shyzzz521** [modelscope/ms-swift#1723]
**Describe the bug**
在Lora微调后，load模型时get_vllm_engine函数遇到错误：
ValueError: Due to limitations of the custom LoRA CUDA kernel, max_num_batched_tokens must be <= 65528 when LoRA is enabled.
在get_vllm_engine添加参数max_num_batched_tokens=32768,之后还是会报错，请问这个怎么解决？

这是代码：

lora_checkpoint = "/home/jovyan/dataws1/swift_20240812/SFT/output/hunhe_lora_glm4_128k/glm4-9b-chat/v0-20240814-142121/checkpoint-225"
lora_request = LoRARequest('default-lora', 1, lora_checkpoint)
model_id = "/home/jovyan/kys-workspace-zzzc/models/glm-4-9b-chat"
model_type = ModelType.glm4_9b_chat

llm_engine = get_vllm_engine(model_type, 
                             model_id_or_path=model_id,
                             enable_lora=True,
                             max_loras=1, 
                             max_lora_rank=16,
                             tensor_parallel_size=4,
                            )
template_type = get_default_template_type(model_type)
template = get_template(template_type, llm_engine.hf_tokenizer)

**Your hardware and system info**
8张a800

**Comment by tastelikefeet** [comment]
感觉是vllm+glm4+lora本身不支持呢 @Jintao-Huang any ideas?

**Comment by rangehow** [comment]
https://github.com/vllm-project/vllm/discussions/6247#discussioncomment-10448835
