### ISSUE TITLE
使用webui上传图片会报错

### ISSUE THREAD

**Issue by EthanChenLi** [modelscope/ms-swift#1727]
python环境： 3.10
上传图片点击发送会提示错误，报错内容如下：
![image](https://github.com/user-attachments/assets/674e0143-0915-4f5f-bc29-74cc750684e9)

**Comment by tastelikefeet** [comment]
服务端报错，什么模型啊

**Comment by EthanChenLi** [comment]
qwen-vl

**Comment by tastelikefeet** [comment]
这个模型比较特殊，请使用<img>/xxx/xxx.jpg</img>what is in the image?来对话
