### ISSUE TITLE
多机训练InternVL2报错。完全照着官网和赵哥的脚本，多机报错，但单机完全OK

### ISSUE THREAD

**Issue by ArtificialZeng** [modelscope/ms-swift#1728]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
完全照着官网和赵哥的脚本，多机报错，但单机完全OK：
export NCCL_DEBUG=INFO
export NCCL_IB_DISABLE=1
export NCCL_P2P_DISABLE=1
NNODES=2 \
NODE_RANK=0 \
MASTER_ADDR=xxx.xx.x.100 \
swift sft \
    --model_type internvl2-26b \
    --sft_type lora \
    --dataset coco-en-2-mini \
    --output_dir output \
    --deepspeed default-zero3

[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/adminad/anaconda3/envs/swift2/lib/python3.12/site-packages/swift/cli/sft.py", line 5, in <module>
[rank1]:     sft_main()
[rank1]:   File "/home/adminad/anaconda3/envs/swift2/lib/python3.12/site-packages/swift/utils/run_utils.py", line 22, in x_main
[rank1]:     args, remaining_argv = parse_args(args_class, argv)
[rank1]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/adminad/anaconda3/envs/swift2/lib/python3.12/site-packages/swift/utils/utils.py", line 131, in parse_args
[rank1]:     args, remaining_args = parser.parse_args_into_dataclasses(argv, return_remaining_strings=True)
[rank1]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/adminad/anaconda3/envs/swift2/lib/python3.12/site-packages/transformers/hf_argparser.py", line 339, in parse_args_into_dataclasses
[rank1]:     obj = dtype(**inputs)
[rank1]:           ^^^^^^^^^^^^^^^
[rank1]:   File "<string>", line 199, in __init__
[rank1]:   File "/home/adminad/anaconda3/envs/swift2/lib/python3.12/site-packages/swift/llm/utils/argument.py", line 1084, in __post_init__
[rank1]:     self.output_dir = add_version_to_work_dir(self.output_dir)
[rank1]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/adminad/anaconda3/envs/swift2/lib/python3.12/site-packages/swift/utils/utils.py", line 113, in add_version_to_work_dir
[rank1]:     sub_folder = broadcast_string(sub_folder)
[rank1]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/adminad/anaconda3/envs/swift2/lib/python3.12/site-packages/swift/utils/torch_utils.py", line 205, in broadcast_string
[rank1]:     dist.broadcast(tensor, 0)
[rank1]:   File "/home/adminad/anaconda3/envs/swift2/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/adminad/anaconda3/envs/swift2/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2205, in broadcast
[rank1]:     work = default_pg.broadcast([tensor], opts)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:275, remote process exited or there was a network error, NCCL version 2.22.3
[rank1]: ncclRemoteError: A call failed possibly due to a network error or a remote process exiting prematurely.
[rank1]: Last error:
[rank1]: socketProgress: Connection closed by remote peer bjdb-h20-node-100<38504>

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Chuge0335** [comment]
same error, did you solve it?

**Comment by zsLin177** [comment]
> same error, did you solve it?

hello, I have the same error, did you solve it?
