### ISSUE TITLE
swift库可以增加对mPLUG-Owl2模型的支持吗？

### ISSUE THREAD

**Issue by deepmo24** [modelscope/ms-swift#173]
mPLUG-Owl2 是阿里达摩院近期开源的一个优秀MLLM模型：https://github.com/X-PLUG/mPLUG-Owl/tree/main/mPLUG-Owl2 ，并且模型在modelscope和Huggingface都已发布，作者团队能否将该模型在swift库上进行支持呢？非常感谢，期待回复~

**Comment by Jintao-Huang** [comment]
感谢你优秀的模型！！！

**Comment by deepmo24** [comment]
@Jintao-Huang 这是最近看到的优秀工作，希望你们能够在swift库早日支持！
