### ISSUE TITLE
swift lora微调完 MiniCPM-V-2.6 后 merge lora报错？

### ISSUE THREAD

**Issue by zw-SIMM** [modelscope/ms-swift#1731]
想请问下，用swift lora微调完 MiniCPM-V-2.6应该如何 merge？

命令：
CUDA_VISIBLE_DEVICES=5 swift export \ 
--ckpt_dir "output/${model_type}/v25-checkpoint-xxxx" \ 
--model_id_or_path "/home/pretrained_models/OpenBMB/MiniCPM-V-2_6" \ 
--merge_lora true \

报错：
ValueError: SiglipVisionTransformer does not support `device_map='auto'`. To implement support, the model class needs to implement the `_no_split_modules` attribute.

**Comment by tastelikefeet** [comment]
--merge_device_map cpu试试呢

**Comment by zw-SIMM** [comment]
> --merge_device_map cpu试试呢

可以了，感谢！

**Comment by Jintao-Huang** [comment]
device_map 'auto' 也已经修复
