### ISSUE TITLE
internvl-8b imblanced GPU allocation with device_max_memory

### ISSUE THREAD

**Issue by ruian1** [modelscope/ms-swift#1735]
training cmd

```CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft --model_type internvl2-8b --model_id_or_path /root/.cache/modelscope/hub/OpenGVLab/InternVL2-8B/     --dataset ./output/jsonl/train_dataset.jsonl --use_flash_attn true  --max_length 4096 --gradient_checkpointing true --learning_rate 1e-8 --num_train_epochs=3   --gradient_accumulation_steps 64 --preprocess_num_proc 48 --device_max_memory 40GB 80GB 80GB 80GB```

GPU allocation(same when set 80GB for GPU0)

```
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     85686      C   python                                          0MiB |
|    1   N/A  N/A     85686      C   python                                          0MiB |
|    2   N/A  N/A     85686      C   python                                          0MiB |
|    3   N/A  N/A     85686      C   python                                          0MiB |
+-----------------------------------------------------------------------------------------+
Fri Aug 16 21:32:46 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          On  |   00000000:00:05.0 Off |                    0 |
| N/A   49C    P0            385W /  400W |   61235MiB /  81920MiB |     84%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A100-SXM4-80GB          On  |   00000000:00:06.0 Off |                    0 |
| N/A   54C    P0            401W /  400W |   15481MiB /  81920MiB |     81%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA A100-SXM4-80GB          On  |   00000000:00:07.0 Off |                    0 |
| N/A   47C    P0             94W /  400W |   15483MiB /  81920MiB |     22%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA A100-SXM4-80GB          On  |   00000000:00:08.0 Off |                    0 |
| N/A   44C    P0             91W /  400W |   25919MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
```

expect GPU0 to have less than 40GB and the rest splitted evely on other gpus, or evenly across all gpus when setting 80GB for GPU0 as well

**Comment by tastelikefeet** [comment]
Update to the latest code first
solution 1:
--device_max_memory 15GB 15GB 15GB 15GB
solution 2:
--deepspeed default-zero3
If still not work, reopen this issue pls.

**Comment by orzgugu** [comment]
> Update to the latest code first solution 1: --device_max_memory 15GB 15GB 15GB 15GB solution 2: --deepspeed default-zero3 If still not work, reopen this issue pls.

Hello, I also encountered this problem, but when I use device_max_memory 15GB 15GB 15GB 15GB 15GB, I get an error Traceback (most recent call last):
File "/ root/local/lib/python3.10 / site - packages/swift/cli/SFT. Py", line 5, in < module >
sft_main()
The File "/ root/local/lib/python3.10 / site - packages/swift/utils/run_utils py", line 32, in x_main
result = llm_x(args, **kwargs)
File "/ root/local/lib/python3.10 / site - packages/swift/LLM/SFT. Py", line 166, in llm_sft
assert len(args.device_max_memory) == n_gpu // args.local_world_size
AssertionError. 
This causes me to not run the code correctly, do you know what else can prevent CUDA from going OUT OF MEMORY? Or do you say device_max_memory 15GB 15GB 15GB 15GB How many versions of swift do you support? I tried swift2.25 2.30 2.32 all failed.
I am looking forward to your reply, it is really important to me!

**Comment by zhongtao93** [comment]
same question

**Comment by verigle** [comment]
same problem +1

**Comment by ruian1** [comment]
@tastelikefeet this issue needs reopen, not fixed. This seems only happen to vlm models, that's why the fix you provided did not work
