### ISSUE TITLE
Merge Internvl2 Lora 报错

### ISSUE THREAD

**Issue by zw-SIMM** [modelscope/ms-swift#1738]
前几天是可以merge的，今天merge发现有问题

命令：
CUDA_VISIBLE_DEVICES=3,4 swift export \
    --ckpt_dir "output/internvl2-40b}/v2-checkpoint-6300" \
    --model_id_or_path "/home/pretrained_models/OpenGVLab/InternVL2-40B" \
    --merge_lora true

报错：
![image](https://github.com/user-attachments/assets/d2648881-a218-49fb-b722-4556cc8e4965)

**Comment by Jintao-Huang** [comment]
拉取一下main分支

**Comment by zw-SIMM** [comment]
> 拉取一下main分支

![image](https://github.com/user-attachments/assets/5b09f304-63ea-4b68-aeeb-1f2426a6d601)
还是不行

**Comment by Jintao-Huang** [comment]
把flash_attn卸载掉，没安装好

**Comment by zw-SIMM** [comment]
> 把flash_attn卸载掉，没安装好

可以了！这秒回点赞！
