### ISSUE TITLE
internlm-xcomposer2-vl-1_8b 训练支持

### ISSUE THREAD

**Issue by cilinyan** [modelscope/ms-swift#1739]
**Describe the feature**
希望支持[internlm-xcomposer2-vl-1_8b](https://huggingface.co/internlm/internlm-xcomposer2-vl-1_8b)的 sft。

**Paste any useful information**
[Internlm-Xcomposer2 & Internlm-Xcomposer2.5 最佳实践](https://github.com/modelscope/ms-swift/blob/main/docs/source/Multi-Modal/internlm-xcomposer2%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md) 目前仅支持 7b 的模型，希望也支持下 1.8b的模型，谢谢。

**Comment by Jintao-Huang** [comment]
大概率不会支持
