### ISSUE TITLE
官方的推理cli，支持多用户并行调用嘛？

### ISSUE THREAD

**Issue by RyanOvO** [modelscope/ms-swift#1740]
**Describe the feature**
Please describe the feature requested here(请在这里描述需求)
基于官方的cli推理模型，如下：
![image](https://github.com/user-attachments/assets/cb39acf0-145b-43b2-8f8f-ae98cfb5ef4a)
当模型部署起来后，基于openai api风格调用推理时，单机单卡的条件下，是否支持多用户并发调用？大概的并发数是几个？

**Paste any useful information**
Paste any useful information, including papers, github links, etc.(请在这里描述其他有用的信息，比如相关的论文地址，github链接等)

**Additional context**
Add any other context or information here(其他信息可以写在这里)

**Comment by Jintao-Huang** [comment]
使用swift deploy

**Comment by RyanOvO** [comment]
> 使用swift deploy

swift infer不支持么?

**Comment by Jintao-Huang** [comment]
swift deploy是异步的，swift infer是同步的
