### ISSUE TITLE
modelscope.hub.errors.RequestError: Url = https://www.modelscope.cn/api/v1/datasets/modelscope/test1, Request id=28a7f519-bb2e-4428-9ecc-7116441b6f4d Code = 10020101002 Message = 不存在的数据集,  Please specify correct dataset_name and namespace.

### ISSUE THREAD

**Issue by BenDes21** [modelscope/ms-swift#1742]
Hi there, Trying to finetune florence , when I enter my command :  

`swift sft --model_type florence-2-large-ft --dataset test1 --sft_type full --lr_scheduler_type=cosine --gradient_accumulation_steps=2 --batch_size=2 --num_train_epochs=3 --save_steps=389 --eval_steps=50 --dataset_test_ratio=0.05 --save_total_limit=8` in cmd

I get : 

**modelscope.hub.errors.RequestError: Url = https://www.modelscope.cn/api/v1/datasets/modelscope/test1, Request id=28a7f519-bb2e-4428-9ecc-7116441b6f4d Code = 10020101002 Message = 不存在的数据集,                Please specify correct dataset_name and namespace.**

Any solutions ? Thanks

**Comment by Jintao-Huang** [comment]
You might need `--dataset test1.json test2.jsonl`. And it is recommended to use absolute paths.

**Comment by BenDes21** [comment]
> You might need `--dataset test1.json test2.jsonl`. And it is recommended to use absolute paths.

Hi there, thanks for your answer. I insert the absolute paths of my dataset . json and now get " **PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001E6095224D0>** "

**Comment by BenDes21** [comment]
issue fixe, mistake on the path, thanks
