### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4823: character maps to <undefined>

### ISSUE THREAD

**Issue by BenDes21** [modelscope/ms-swift#1744]
Hi, correctly installed swift and would like to launch the UI, when after enter swift web-ui I get this error : `UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4823: character maps to <undefined>` Any solutions please ?

<img width="1160" alt="Untitled" src="https://github.com/user-attachments/assets/88d9dbe8-87d1-4baf-bda8-8c7660c65760">

**Comment by tastelikefeet** [comment]
If you are not using the eval page, try to uninstall `evalscope` please.
