### ISSUE TITLE
qwen2-audio only trains the LLM part. How to modify target_regex?

### ISSUE THREAD

**Issue by zhangfan-algo** [modelscope/ms-swift#1747]
**Describe the bug**
![image](https://github.com/user-attachments/assets/458eec80-91a8-45b4-8465-cc767156ec07)

**Your hardware and system info**
torchrun  --nproc_per_node ${num_gpu_per_node}  --master_port $MASTER_PORT --master_addr $MASTER_ADDR --node_rank $RANK --nnodes $WORLD_SIZE examples/pytorch/llm/llm_sft.py \
    --model_cache_dir /mnt/pfs/models/Qwen/Qwen2-Audio-7B-Instruct \
    --model_type qwen2-audio-7b-instruct  \
    --sft_type lora \
    --lora_target_modules language_model \
    --tuner_backend swift \
    --template_type AUTO \
    --output_dir output/qwen2-audio-test \
    --ddp_backend nccl \
    --custom_train_dataset_path /mnt/pfs/data/summary_audio_merge_prompts_995115_20240816_summary.jsonl \
    --dataset_test_ratio 0.01 \
    --self_cognition_sample -1 \
    --preprocess_num_proc 60 \
    --dataloader_num_workers 60 \
    --train_dataset_sample -1 \
    --dataset_test_ratio 0.01 \
    --save_strategy epoch \
    --lr_scheduler_type cosine \
    --save_total_limit 10 \
    --num_train_epochs 5 \
    --eval_steps 50 \
    --logging_steps 10 \
    --max_length 4096 \
    --check_dataset_strategy warning \
    --gradient_checkpointing true \
    --batch_size 4 \
    --gradient_accumulation_steps 1 \
    --deepspeed_config_path /mnt/pfs/swift/llm/ds_config/zero2.json \
    --weight_decay 0.01 \
    --learning_rate 1e-5 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --use_flash_attn false \
    --save_only_model false \
    --save_on_each_node false \
    --lazy_tokenize true \
    --neftune_noise_alpha 5 \
    --dtype AUTO 

**Additional context**
64张A800微调，尝试使用其他deepspeed的congfig依然还是会报错

**Comment by Jintao-Huang** [comment]
用 target_regex

**Comment by zhangfan-algo** [comment]
> 用 target_regex

具体要怎么设置一下呀

**Comment by zhangfan-algo** [comment]
提示[INFO:swift] SwiftModel: 8397.0949M Params (0.0000M Trainable [0.0000%]), 67.1109M Buffers. 没有参数训练

**Comment by Jintao-Huang** [comment]
```python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

from swift.llm import sft_main, SftArguments

sft_main(SftArguments(model_type='qwen2-audio-7b-instruct', dataset='aishell1-zh-mini', target_regex='^language_model(?!.*(lm_head|output|emb|wte|shared)).*'))
```

**Comment by zhangfan-algo** [comment]
参数配置后，LLM+projector部分全部微调。 我觉得这样也可以的。 但是 怎么设置让audio_tower都冻结呢 我看只有第0层冻结了
![image](https://github.com/user-attachments/assets/a8e674f6-cf89-4bf3-a747-1cfa19778029)

**Comment by Jintao-Huang** [comment]
- `--freeze_parameters`: 当sft_type指定为'full'时, 将模型最底部的参数进行freeze. 指定范围为0. ~ 1., 默认为`0.`. 该参数提供了lora与全参数微调的折中方案.
- `--additional_trainable_parameters`: 作为freeze_parameters的补充, 只有在sft_type指定为'full'才允许被使用, 默认为`[]`. 例如你如果想训练50%的参数的情况下想额外训练embedding层, 你可以设置`--freeze_parameters 0.5 --additional_trainable_parameters transformer.wte`, 所有以`transformer.wte`开头的parameters都会被激活. 你也可以设置`--freeze_parameters 1 --additional_trainable_parameters xxx`来自定义可以训练的层.

**Comment by zhangfan-algo** [comment]
freeze_parameters设置1的话 可以将audio_tower全部冻结不

**Comment by Jintao-Huang** [comment]
> freeze_parameters设置1的话 可以将audio_tower全部冻结不

使用全参数 `--sft_type full`, 然后加上`--freeze_parameters  1 --additional_trainable_parameters language_model `

看看可以不

**Comment by zhangfan-algo** [comment]
> > freeze_parameters设置1的话 可以将audio_tower全部冻结不
> 
> 使用全参数 `--sft_type full`, 然后加上`--freeze_parameters 1 --additional_trainable_parameters language_model `
> 
> 看看可以不
![image](https://github.com/user-attachments/assets/b251a0f6-c66b-4474-94e1-2cbf111612f8)
这里省略掉了不知道其他层有没有冻结

**Comment by Jintao-Huang** [comment]
> > > > freeze_parameters设置1的话 可以将audio_tower全部冻结不
> > > 
> > > 
> > > 使用全参数 `--sft_type full`, 然后加上`--freeze_parameters 1 --additional_trainable_parameters language_model `
> > > 看看可以不
> > > ![image](https://private-user-images.githubusercontent.com/47747764/359035756-b251a0f6-c66b-4474-94e1-2cbf111612f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTczNjQsIm5iZiI6MTcyNDA1NzA2NCwicGF0aCI6Ii80Nzc0Nzc2NC8zNTkwMzU3NTYtYjI1MWEwZjYtYzY2Yi00NDc0LTk0ZTEtMmNiZjExMTYxMmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA4NDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5YWY4MjQ0ZDk2ODlhNGU4ODZhYjU3NDA4MGE1NGI2NDRlZDI3NjJjZWExMWNkYjZhOTkxMDMwZThkNWE3MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f8Dd8TKcCs7TwsXxeRHXOU2gOR1qvr5rOQr2e5crCJU)
> > > 这里省略掉了不知道其他层有没有冻结
> 
> 有方法可以打印出来全部冻结的层不

debug检查了

**Comment by bqzhu922** [comment]
> * `--freeze_parameters`: 当sft_type指定为'full'时, 将模型最底部的参数进行freeze. 指定范围为0. ~ 1., 默认为`0.`. 该参数提供了lora与全参数微调的折中方案.
> * `--additional_trainable_parameters`: 作为freeze_parameters的补充, 只有在sft_type指定为'full'才允许被使用, 默认为`[]`. 例如你如果想训练50%的参数的情况下想额外训练embedding层, 你可以设置`--freeze_parameters 0.5 --additional_trainable_parameters transformer.wte`, 所有以`transformer.wte`开头的parameters都会被激活. 你也可以设置`--freeze_parameters 1 --additional_trainable_parameters xxx`来自定义可以训练的层.

你好请教下这里说的应该是这个参数吧：--freeze_parameters_ratio
还有这里和document中指的模型最底部是指什么部分，以qwen2-audio为例的话这里的最底部是指LLM的部分还是audio tower的部分（从代码上看了下最低部指的应该是audio tower到LLM这个方向？）
