### ISSUE TITLE
多工具调用问题

### ISSUE THREAD

**Issue by huchaodong** [modelscope/ms-swift#1749]
我想学习一下多工具调用，我想知道如何实现输入问题，完成多个工具调用。
例如输入：计算25的平方根和立方根。
大模型会依次调用两个工具去实现。
我结合readme制作了数据（react形式），但是微调效果并不理想。
{"tools":"{API_LIST}","conversations": [{"from": "user", "value": "aaaaa"}, {"from": "assistant", "value": "bbbbb"}, {"from": "tool", "value": "ccccc"}, {"from": "assistant", "value": "ddddd"}, {"from": "assistant", "value": "bbbbb"}, {"from": "tool", "value": "ccccc"}, {"from": "assistant", "value": "ddddd"}....]}

**Comment by tastelikefeet** [comment]
1. 考虑使用更多的数据
2. 数据需要是多轮对话
3. 训练完成后使用训练数据回输推理，看下是否训练数据已经达到目的，然后再考虑使用其他数据进行推理
