### ISSUE TITLE
可以问一下我们如果自定义数据集的话会是什么样的格式被访问呢 是需要自己封装一下吗

### ISSUE THREAD

**Issue by 307yin** [modelscope/ms-swift#1750]
(default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2304, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): Linear(in_features=2048, out_features=2304, bias=False)
              (rotary_emb): Gemma2RotaryEmbedding()
            )
            (mlp): Gemma2MLP(
              (gate_proj): Linear(in_features=2304, out_features=9216, bias=False)
              (up_proj): Linear(in_features=2304, out_features=9216, bias=False)
              (down_proj): Linear(in_features=9216, out_features=2304, bias=False)
              (act_fn): PytorchGELUTanh()
            )
            (input_layernorm): Gemma2RMSNorm()
            (post_attention_layernorm): Gemma2RMSNorm()
            (pre_feedforward_layernorm): Gemma2RMSNorm()
            (post_feedforward_layernorm): Gemma2RMSNorm()
          )
        )
        (norm): Gemma2RMSNorm()
      )
      (lm_head): Linear(in_features=2304, out_features=256000, bias=False)
    )
  )
)
[INFO:swift] PeftModelForCausalLM: 2616.6316M Params (2.2897M Trainable [0.0875%]), 0.0033M Buffers.
[INFO:swift] Setting model.config.use_cache: False
Traceback (most recent call last):
  File "/mnt/workspace/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/mnt/workspace/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/mnt/workspace/swift/swift/llm/sft.py", line 276, in llm_sft
    train_dataset, val_dataset = _get_train_val_dataset(args)
  File "/mnt/workspace/swift/swift/llm/sft.py", line 33, in _get_train_val_dataset
    train_dataset, val_dataset = get_dataset(
  File "/mnt/workspace/swift/swift/llm/utils/dataset.py", line 2652, in get_dataset
    dataset_name_list = _dataset_id_to_name(dataset_name_list)
  File "/mnt/workspace/swift/swift/llm/utils/dataset.py", line 2624, in _dataset_id_to_name
    raise ValueError(f"path: '{d_id_or_path}' not found")
ValueError: path: '/mnt/workspace/datas' not found

**Comment by Jintao-Huang** [comment]
路径不对啊

**Comment by tastelikefeet** [comment]
https://swift.readthedocs.io/zh-cn/latest/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.html

**Comment by 1571859588** [comment]
@tastelikefeet 你好，文档不存在了，可以再发一下吗
