### ISSUE TITLE
pytorch=1.13.1 swift微调qwen2-audio template.py报错

### ISSUE THREAD

**Issue by Danyuhui** [modelscope/ms-swift#1751]
pytorch=1.13.1 swift微调qwen2-audio 报错：

> TypeError: Module.register_forward_pre_hook() got an unexpected keyword argument 'with_kwargs'

定位到错误发生位置，发现swift/llm/utils/template.py中用到的函数为

> handle = self.model.register_forward_pre_hook(_pre_forward_hook, with_kwargs=True)

在pytorch=1.13.1的官方文档中没有找到这个用法，只有如下用法：
![image](https://github.com/user-attachments/assets/d1df0478-6e2f-497a-a54e-2ec267b39641)
这两个用法 名称不一样，且不能设置with_kwargs，所以引发了上述报错
但我看ms-swift README中写的是支持pytorch=1.13.1的，想请教一下这个问题应该怎样解决

**Comment by Jintao-Huang** [comment]
估计要torch>=2.0了 我兼容一下
