### ISSUE TITLE
多次微调的处理

### ISSUE THREAD

**Issue by RyanOvO** [modelscope/ms-swift#1753]
有一批数据集，受限于显存的大小，暂时只能分批次训练，流程如下：
1. 基于原基座模型/合并后的checkpoint模型文件，先是微调训练，使用`sft` 命令
2. 然后合并merge，使用`export`命令
3. 基于合并之后的checkpoint，再循环开始1,2。

请问如上步骤有问题么？

**Comment by Jintao-Huang** [comment]
可以使用resume_from_checkpoint进行断点续训

**Comment by RyanOvO** [comment]
> 可以使用resume_from_checkpoint进行断点续训

好的，那我的那种方式也可以把？

**Comment by Jintao-Huang** [comment]
也可以的
