### ISSUE TITLE
模型训练初始化

### ISSUE THREAD

**Issue by Wu0409** [modelscope/ms-swift#1754]
刚开始实验这个框架，请问一下在使用DPO，用自己数据集对MLLM微调时候，会有很长时间的 map 操作，请问这部分操作在做什么？

Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11880/11880 [18:15<00:00, 10.85 examples/s]

然后，一轮map完以后，显示了 `parameter Offload: Total persistent parameters: 2733056 in 378 params`，然后又在 map（似乎 triton 在进行 autotune？）

**Comment by hjh0119** [comment]
处理图像信息和模型的template, 第二次map是在对验证集做处理

**Comment by Wu0409** [comment]
> 处理图像信息和模型的template, 第二次map是在对验证集做处理

谢谢！我看这个保存的空间挺大的，我总共就1、2g，但是实际我看cache了接近100多g，这样子正常吗？而且似乎每一次都要重新map，这个操作能关闭吗（直接在训练时候处理）？

**Comment by hjh0119** [comment]
可以试试流式处理 --streaming true

**Comment by Wu0409** [comment]
> 可以试试流式处理 --streaming true

好嘞 我去测试下~
