### ISSUE TITLE
Unable to enable web UI

### ISSUE THREAD

**Issue by Betty-J** [modelscope/ms-swift#1756]
Hi, there
After installing Swift, I execute **python -m swift.cli.main web-ui** or **SWIFT_UI_LANG=en swift web-ui** and the following error appeared, which (probably) caused the given web address to be unable to connect, How can I solve this problem.
<img width="1299" alt="截屏2024-08-19 17 26 25" src="https://github.com/user-attachments/assets/e886dd32-e74a-43fb-bf6a-97e05c68e0f1">

**Comment by tastelikefeet** [comment]
python==3.8?

**Comment by Betty-J** [comment]
> python==3.8?

Hi, the python version I am using is 3.9.19. 
<img width="375" alt="截屏2024-08-20 10 37 00" src="https://github.com/user-attachments/assets/a7e3f854-1bc9-4ef6-b746-759d52bf7b5d">
I also encountered the following version conflict problem When installing **botocore**，Will this have any impact?<img width="1401" alt="截屏2024-08-20 10 36 15" src="https://github.com/user-attachments/assets/c5b4f7e8-eeb1-4a26-a128-77e1f9d71df2">
