### ISSUE TITLE
关于用自定义agent数据集微调，能不能增加一些自定义数据集的样例

### ISSUE THREAD

**Issue by skywalkerfmc** [modelscope/ms-swift#1758]
**Describe the feature**
Please describe the feature requested here(请在这里描述需求)

**Paste any useful information**
Paste any useful information, including papers, github links, etc.(请在这里描述其他有用的信息，比如相关的论文地址，github链接等)
![image](https://github.com/user-attachments/assets/a91da833-bb36-45f6-a800-0ba719c40cd4)

**Additional context**
Add any other context or information here(其他信息可以写在这里)

**Comment by skywalkerfmc** [comment]
是否可以按照ToolBench数据集的格式制作自定义数据集
{"id": "toolbench_ori_0", "tools": "[{\"name\": \"url_for_newapi\", \"description\": \"This is the subfunction for tool \\\"newapi\\\", you can use this tool.The description of this function is: \\\"url_for_newapi\\\"\", \"parameters\": {\"type\": \"object\", \"properties\": {\"url\": {\"type\": \"string\", \"description\": \"\", \"example_value\": \"https://www.instagram.com/reels/CtB6vWMMHFD/\"}}, \"required\": [\"url\"], \"optional\": [\"url\"]}}, {\"name\": \"n_for_newapi\", \"description\": \"This is the subfunction for tool \\\"newapi\\\", you can use this tool.The description of this function is: \\\"n_for_newapiew var\\\"\", \"parameters\": {\"type\": \"object\", \"properties\": {\"language\": {\"type\": \"string\", \"description\": \"\", \"example_value\": \"https://www.instagram.com/reels/Csb0AI3IYUN/\"}}, \"required\": [\"language\"], \"optional\": []}}, {\"name\": \"Finish\", \"description\": \"If you believe that you have obtained a result that can answer the task, please call this function to provide the final answer. Alternatively, if you recognize that you are unable to proceed with the task in the current state, call this function to restart. Remember: you must ALWAYS call this function at the end of your attempt, and the only part that will be shown to the user is the final answer, so it should contain sufficient information.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"return_type\": {\"type\": \"string\", \"enum\": [\"give_answer\", \"give_up_and_restart\"]}, \"final_answer\": {\"type\": \"string\", \"description\": \"The final answer you want to give the user. You should have this field if \\\"return_type\\\"==\\\"give_answer\\\"\"}}, \"required\": [\"return_type\"]}}]", "conversations": [{"from": "system", "value": "You can use many tools(functions) to do the following task.\nFirst I will give you the task description, and your task start.\nAt each step, you need to give your thought to analyze the status now and what to do next, with a function call to actually excute your step. Your output should follow this format:\nThought:\nAction\nAction Input:\n\nAfter the call, you will get the call result, and you are now in a new state.\nThen you will analyze your status now, then decide what to do next...\nAfter many (Thought-call) pairs, you finally perform the task, then you can give your finial answer.\nRemember: \n1.the state change is irreversible, you can't go back to one of the former state, if you want to restart the task, say \"I give up and restart\".\n2.All the thought is short, at most in 5 sentence.\n3.You can do more then one trys, so if your plan is to continusly try some conditions, you can do one of the conditions per try.\nLet's Begin!\nTask description: You should use functions to help handle the real time user querys. Remember:\n1.ALWAYS call \"Finish\" function at the end of the task. And the final answer should contain enough information to show to the user,If you can't handle the task, or you find that function calls always fail(the function is not valid now), use function Finish->give_up_and_restart.\n2.Do not use origin tool names, use only subfunctions' names.\nSpecifically, you have access to the following APIs: [{\"name\": \"url_for_newapi\", \"description\": \"This is the subfunction for tool \\\"newapi\\\", you can use this tool.The description of this function is: \\\"url_for_newapi\\\"\", \"parameters\": {\"type\": \"object\", \"properties\": {\"url\": {\"type\": \"string\", \"description\": \"\", \"example_value\": \"https://www.instagram.com/reels/CtB6vWMMHFD/\"}}, \"required\": [\"url\"], \"optional\": [\"url\"]}}, {\"name\": \"n_for_newapi\", \"description\": \"This is the subfunction for tool \\\"newapi\\\", you can use this tool.The description of this function is: \\\"n_for_newapiew var\\\"\", \"parameters\": {\"type\": \"object\", \"properties\": {\"language\": {\"type\": \"string\", \"description\": \"\", \"example_value\": \"https://www.instagram.com/reels/Csb0AI3IYUN/\"}}, \"required\": [\"language\"], \"optional\": []}}, {\"name\": \"Finish\", \"description\": \"If you believe that you have obtained a result that can answer the task, please call this function to provide the final answer. Alternatively, if you recognize that you are unable to proceed with the task in the current state, call this function to restart. Remember: you must ALWAYS call this function at the end of your attempt, and the only part that will be shown to the user is the final answer, so it should contain sufficient information.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"return_type\": {\"type\": \"string\", \"enum\": [\"give_answer\", \"give_up_and_restart\"]}, \"final_answer\": {\"type\": \"string\", \"description\": \"The final answer you want to give the user. You should have this field if \\\"return_type\\\"==\\\"give_answer\\\"\"}}, \"required\": [\"return_type\"]}}]"}, {"from": "user", "value": "\nI am planning a surprise birthday party for my friend and I want to create a personalized invitation. Could you fetch my friend's recent photos from social media platforms so that I can use them in the invitation? It would be helpful if you could also provide the photos' captions or descriptions.\nBegin!\n"}, {"from": "assistant", "value": "Thought: I think the current API call, \"url_for_newapi\", is used to fetch the recent photos of the user's friend from the social media platform. The URL argument provided is \"https://api.socialmedia.com/friend/photos\". It seems like the assistant is trying to retrieve the photos to help the user create a personalized invitation for their friend's surprise birthday party. This API call will fetch the photos, which can be used in the invitation along with their captions or descriptions.\nAction: url_for_newapi\nAction Input: {\n  \"url\": \"https://api.socialmedia.com/friend/photos\"\n}"}, {"from": "tool", "value": "{\"error\": \"\", \"response\": \"{'message': \\\"Endpoint '/https:/api.socialmedia.com/friend/photos' does not exist\\\"}\"}"}, {"from": "assistant", "value": "Thought: Based on the previous actions, it seems that I have only one option, which is to give up and restart the task. However, before doing so, I can try using a different social media platform to fetch your friend's recent photos. Let's try using the Instagram API instead.\nAction: url_for_newapi\nAction Input: {\n  \"url\": \"https://api.instagram.com/friend/photos\"\n}"}, {"from": "tool", "value": "{\"error\": \"\", \"response\": \"{'message': \\\"Endpoint '/https:/api.instagram.com/friend/photos' does not exist\\\"}\"}"}, {"from": "assistant", "value": "Thought: The API call \"url_for_newapi\" was used to fetch the recent photos of the user's friend from the social media platform, but it seems that the endpoint '/https:/api.socialmedia.com/friend/photos' does not exist. This caused the previous attempt to fail. Since the assistant couldn't retrieve the photos, they apologized for the inconvenience and asked if there was anything else they could assist with. In this state, it seems that all previous attempts have failed, so I need to generate a new action that is different from the previous ones. Based on the current situation, I can suggest directly asking the user to provide the photos and their captions or descriptions for the personalized invitation. This would be a different approach to solve the problem.\nAction: Finish\nAction Input: {\n  \"return_type\": \"give_up_and_restart\"\n}"}]}

**Comment by tastelikefeet** [comment]
可以的，system字段可以自定义，或者给出tools字段就可以，工具回答可以使用ReACT的`Obervation:`方式，也可以使用单独的`tool` role
其他的跟随toolbench格式是没问题的
