### ISSUE TITLE
Error in Galore

### ISSUE THREAD

**Issue by rtz1998** [modelscope/ms-swift#1763]
**Describe the bug**
Raise "valueError: You cannot specify an optimizer in the config file and in the code at the same time. Please remove the optimizer from the config file or create `accelerate.utils.DummyOptim` in the code" when use_galore=true

here is the script

nproc_per_node=4

CUDA_VISIBLE_DEVICES=0,1,2,3 \
torchrun \
    --master_port 29500 \
    --nproc_per_node=$nproc_per_node \
    /***/examples/pytorch/llm/llm_sft.py \
    --model_id_or_path *** \
    --model_type qwen1half-14b \
    --model_revision master \
    --sft_type full \
    --use_galore true \
    --tuner_backend peft \
    --template_type default-generation \
    --dtype bf16 \
    --output_dir *** \
    --report_to tensorboard \
    --logging_dir *** \
    --ddp_backend nccl \
    --num_train_epochs 2 \
    --max_length 1024 \
    --check_dataset_strategy warning \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.1 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps $((64 / nproc_per_node)) \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_total_limit 2 \
    --logging_steps 1 \
    --custom_train_dataset_path *** \
    --lr_scheduler_type cosine \
    --truncation_strategy delete \
    --lazy_tokenize true \
    --deepspeed *** \

**Comment by tastelikefeet** [comment]
deepspeed and GaLore are not compatible

**Comment by rtz1998** [comment]
> deepspeed and GaLore are not compatible

And I wonder whether LISA is compatible with DeepSpeed?
