### ISSUE TITLE
internvl-chat-v1_5 DPO 报错

### ISSUE THREAD

**Issue by teamwong111** [modelscope/ms-swift#1773]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

internvl-chat-v1_5 DPO 会报错，可以使用官方示例测试

<img width="1549" alt="image" src="https://github.com/user-attachments/assets/c23a238a-f02d-4342-924a-68209e524066">

问题在 swift/llm/utils/model.py 4452 行
```
model, tokenizer = get_model_tokenizer_from_repo(
        model_dir, torch_dtype, model_kwargs, load_model, tokenizer=tokenizer, model_config=model_config, **kwargs)
```

internvl-chat-v1_5 config.jsonl 里没有配置 AutoModelForCasualLM，所以会报错

**Comment by hjh0119** [comment]
升级transformers有这个问题吗

**Comment by Jintao-Huang** [comment]
解决了嘛，可复现的sh发一下
