### ISSUE TITLE
多模态评测数据下载失败

### ISSUE THREAD

**Issue by ForJadeForest** [modelscope/ms-swift#1787]
我尝试使用`llava1_6-mistral-7b-instruct`在MMbench进行测试：
```sh
swift eval --model_type llava1_6-mistral-7b-instruct --eval_dataset MMBench
```

得到以下报错：
```
Exception: Failed to download https://opencompass.openxlab.space/utils/VLMEval/MMBench.tsv
```

这个网址貌似已经不能访问了，请问有什么修复的建议吗？

**Comment by Yunnglin** [comment]
请使用这几个数据集名称，MMBench这个名称不支持：

MMBench_DEV_CN, MMBench_DEV_CN_V11 |  
-- | --
MMBench_DEV_EN, MMBench_DEV_EN_V11 |  
MMBench_TEST_CN, MMBench_TEST_CN_V11 | MMBench_TEST_CN没有提供答案
MMBench_TEST_EN, MMBench_TEST_EN_V11 | MMBench_TEST_EN没有提供答案
