### ISSUE TITLE
感觉是用了fp16的原因. 你可以试试bf16或者fp32不

### ISSUE THREAD

**Issue by LUI-TECH** [modelscope/ms-swift#1788]
感觉是用了fp16的原因. 你可以试试bf16或者fp32不

_Originally posted by @Jintao-Huang in https://github.com/modelscope/ms-swift/issues/1613#issuecomment-2301746025_

大佬我用的参数是auto，V100不支持bf16，应该是默认使用fp16了。不知道有没有v100的使用方法

**Comment by Jintao-Huang** [comment]
用fp32

**Comment by LUI-TECH** [comment]
> 用fp32
我的资源好像不足以跑32的，但是我试了一下用minicpm 自己的finetune脚本跑，没有问题，估计是swift和他的适配还有点不足

**Comment by Jintao-Huang** [comment]
可以拉一下main分支进行测试不
