### ISSUE TITLE
请问glm4v什么时候支持lmdeploy部署呢？

### ISSUE THREAD

**Issue by demoninpiano** [modelscope/ms-swift#1791]
![Uploading image.png…]()

swift的文档里目前glm4v是不支持的，我自己测也是有问题跑不同， 但是lmdeploy官网是说支持glm4v的？

**Comment by Jintao-Huang** [comment]
图片加载不出来. 是可以跑通的, 只是用的是pytorch engine, 而不是turbomind engine
