### ISSUE TITLE
添加packing之后自定义数据集报错KeyError: 'input_ids'，不使用packing可以正常训练

### ISSUE THREAD

**Issue by AEProgrammer** [modelscope/ms-swift#1795]
**Describe the bug**
添加packing之后自定义数据集报错KeyError: 'input_ids'，不使用packing可以正常训练
训练参数：
# Experimental environment: 4 * A100
# 4 * 55GB GPU memory
nproc_per_node=4

CUDA_VISIBLE_DEVICES=0,1,2,3 \
NPROC_PER_NODE=$nproc_per_node \
MASTER_PORT=29500 \
swift sft \
    --model_type qwen2-7b-instruct \
    --model_id_or_path /workspace/data/wfs2136/bigmodel/model/qwen/Qwen2-1.5B \
    --model_revision master \
    --sft_type full \
    --template_type AUTO \
    --dtype bf16 \
    --output_dir /workspace/swift_sft_test \
    --ddp_backend nccl \
    --dataset /code/liuhui67/llm/sft_data/infinity/infinity_0625_swift.jsonl \
    --dataset_test_ratio 0 \
    --num_train_epochs 3 \
    --max_length 4096 \
    --check_dataset_strategy warning \
    --gradient_checkpointing true \
    --batch_size 4 \
    --weight_decay 0.1 \
    --learning_rate 5e-6 \
    --gradient_accumulation_steps $(expr 16 / $nproc_per_node) \
    --max_grad_norm 0.5 \
    --warmup_steps 10 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --use_flash_attn true \
    --deepspeed default-zero3 \
    --save_only_model false \
    --packing true

![image](https://github.com/user-attachments/assets/f362ec61-e681-4e1b-8627-bbb5557a393e)

**Your hardware and system info**
硬件为8卡4090，cuda12.1

**Comment by AEProgrammer** [comment]
自定义数据集其实是conversations格式的，不知道为啥图中框打印的是features是query、response、history格式。
不使用packing的话是可以正常训练的。

**Comment by tastelikefeet** [comment]
已经修复了
