### ISSUE TITLE
要如何指定InternLM-XComposer2d5的hd_num参数

### ISSUE THREAD

**Issue by RBBB2010** [modelscope/ms-swift#1799]
您好，感谢SWIFT带来的方便应用。

我在微调InternLM-XComposer2d5时有一个疑惑，就是模型微调过程中的把高分辨率图像切块的hd_num参数在使用SWIFT微调时要如何指定呢？官网的源码里可以直接指定这个参数

**Comment by Jintao-Huang** [comment]
很好的建议，我添加一下

**Comment by RBBB2010** [comment]
您好，我在微调是还遇到一个问题。我使用2*A100 80GB进行微调，但在训练过程中总是同时只有一张卡有GPU利用率，另一张卡利用率会变为0.我的sh如下，请问这是什么问题导致的
#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`

export CUDA_VISIBLE_DEVICES=0,1

GPUS_PER_NODE=2
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost
MASTER_PORT=6001

DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"


swift sft \
    --model_type internlm-xcomposer2_5-7b-chat \
    --model_id_or_path /home/InternLM-XComposer/internlm-xcomposer2d5-7b \
    --output_dir /home/InternLM_Xcomposer2d5/output \
    --dataset /home/InternLM-XComposer/finetune/data/train1_swift.json /home/InternLM-XComposer/finetune/data/train2_swift.json \
    --gradient_checkpointing True \
    --num_train_epochs 2 \
    --sft_type lora \
    --use_flash_attn True \
    --batch_size 2 \
    --evaluation_strategy 'no' \
    --save_steps 200 \
    --save_total_limit 10 \
    --max_length 10228 \
    --gradient_accumulation_steps 16 \
    --include_num_input_tokens_seen True

**Comment by Jintao-Huang** [comment]
DISTRIBUTED_ARGS这里的参数没有用到啊

**Comment by Jintao-Huang** [comment]
已经支持hd_num

可以直接使用环境变量: `HD_NUM=xxx` 实现

**Comment by RBBB2010** [comment]
非常感谢！
