### ISSUE TITLE
单卡训练qwen会卡一下

### ISSUE THREAD

**Issue by YingchaoX** [modelscope/ms-swift#1802]
**Describe the bug**
单卡训练qwen2-14b,启动训练任务后，在完成模型加载、数据tokenizer后，会卡在配置参数打印之后差不多1-5分钟，然后才会出现
实际训练的过程。这个过程感觉是在等什么，
![截屏2024-08-23 10 26 08](https://github.com/user-attachments/assets/e3c4a53a-2786-4d93-9ce8-a177fef49870)

实际的cpu，内存，显存占用都不变。
![截屏2024-08-23 10 27 33](https://github.com/user-attachments/assets/65b563c9-b3e1-48f7-b7d8-91888bf631a3)

如果在这里终止的话，报错如下：
![截屏2024-08-23 10 33 03](https://github.com/user-attachments/assets/a35dd1a1-4475-42b6-a35d-c68bd03e339a)

**Your hardware and system info**
A800 80G
CUDA 12.4
torch==2.4.0， deepspeed==0.14.5
python 3.9

**Additional context**

Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
是离线环境嘛

**Comment by Jintao-Huang** [comment]
--check_model_is_latest false 试试

**Comment by YingchaoX** [comment]
是的，我是内网环境，加上这个配置就可以了，谢谢！
