### ISSUE TITLE
About the parameter sft_type

### ISSUE THREAD

**Issue by Betty-J** [modelscope/ms-swift#1803]
Hi, I would like to ask, in Swift fine-tuning, for a multimodal model, when **--sft_type** is set to **full**, does it mean that the parameters of all modules will be unfrozen, including the visual encoder?

**Comment by Jintao-Huang** [comment]
> Hi, I would like to ask, in Swift fine-tuning, for a multimodal model, when **--sft_type** is set to **full**, does it mean that the parameters of all modules will be unfrozen, including the visual encoder?

yes!
