### ISSUE TITLE
How to choose a template (or template_type)

### ISSUE THREAD

**Issue by Jintao-Huang** [modelscope/ms-swift#1813]
base -> base: Use 'default-generation' or 'AUTO'.

base -> chat & lora: Use 'default' because default is a multi-turn dialogue template and doesn't include special tokens. This avoids poor performance caused by the model not having seen special tokens before.

base -> chat & full: You can randomly choose a multi-turn dialogue template; for example, 'chatml'. Alternatively, you can choose the template corresponding to the chat model. For instance, for qwen2-7b, choose 'qwen'; for llama3-8b, choose 'llama3'.

chat -> chat: Use AUTO.

**Comment by LiweiPE** [comment]
Hello, I want to perform the second case from base->chat using LoRA. So the recommendation is to use this default template?
register_template(
    TemplateType.default,
    Template([], ['### Human:\n{{QUERY}}\n\n### Assistant:\n'], ['\n\n'], [['eos_token_id']],
             DEFAULT_SYSTEM, ['{{SYSTEM}}\n\n'],
             auto_add_bos=True))
             
   Does this way can produce repetition problem after finetuning model?

**Comment by Jintao-Huang** [comment]
Examples:
        chatml (with bos):
            prefix: <s>
            prompt: <|im_start|>user\n{{QUERY}}<|im_end|>\n<|im_start|>assistant\n
            chat_sep: <|im_end|>\n
            suffix: <|im_end|>
            system_prefix: <s><|im_start|>system\n{{SYSTEM}}<|im_end|>\n

        <s><|im_start|>system  # prefix or system_prefix
        {{SYSTEM}}<|im_end|>
        <|im_start|>user  # prompt
        {{QUERY}}<|im_end|>
        <|im_start|>assistant
        {{RESPONSE}}<|im_end|>  # chat_sep
        <|im_start|>user  # prompt
        {{QUERY}}<|im_end|>
        <|im_start|>assistant
        {{RESPONSE}}<|im_end|>  # suffix

**Comment by Jintao-Huang** [comment]
> Hello, I want to perform the second case from base->chat using LoRA. So the recommendation is to use this default template?
> 
> register_template( TemplateType.default, Template([], ['### Human:\n{{QUERY}}\n\n### Assistant:\n'], ['\n\n'], [['eos_token_id']], DEFAULT_SYSTEM, ['{{SYSTEM}}\n\n'], auto_add_bos=True))
> 
> Could this way produce repetition problem after finetuning model?

To avoid the problem of being unable to stop due to the eos_token not being trained.
