### ISSUE TITLE
多轮对话conversations只有一组怎么处理？

### ISSUE THREAD

**Issue by RyanOvO** [modelscope/ms-swift#1816]
受限于业务场景，基于多轮对话的格式，如下：

`
{"conversations": [{"from": "system", "value": "00000"}, {"from": "user", "value": "11111"}, {"from": "assistant", "value": "22222"}, {"from": "user", "value": "11111"}, {"from": "assistant", "value": "22222"}]}
`

`conversations`的数组内有多个json对，但是conversation只有一个
![image](https://github.com/user-attachments/assets/60100807-7aba-420c-952e-98510dc410e5)

并没有多个conversations组成，只有一个conversations   的数据，swift报错如下：

> ValueError: test_size=1 should be either positive and smaller than the number of samples 1 or a float in the (0, 1) range

而如果将多个conversations组合在一起，GPU显存又不够，直接OOM。

对于这类场景下，该怎么解决？

**Comment by tastelikefeet** [comment]
这个不是conversations里面的问题，而是你的数据集数量太少了，导致切分train/test的时候test数据集没数据

**Comment by RyanOvO** [comment]
> 这个不是conversations里面的问题，而是你的数据集数量太少了，导致切分train/test的时候test数据集没数据

train/test能不指定数据集么？
