### ISSUE TITLE
多机训练速度缓慢 (multi-node training)

### ISSUE THREAD

**Issue by Maokui-He** [modelscope/ms-swift#1825]
您好，在使用swift框架进行LLM训练时，发现采用deepspeed zero3训练会出现严重的速度下降问题，具体来说是：在每台机器为8卡A800显卡下，同样batchsize单个batch平均耗时12机>6机>2机>1机（机器越多耗时越大，并且成倍增加）。例如batchsize为384的实验，12机(单卡batchsize为4)和6机 (单卡batchsize为8)训练同样数据量的耗时几乎相同，这里面可能存在严重的通信问题（deepspeed zero2表现正常，叠加机器数量能获得几乎成倍的速度）？您这边有遇到相关的问题吗？

**Comment by changqingla** [comment]
是否开启IB相关的环境变量，例如export NCCL_IB_DISABLE=0

**Comment by Vincent-Li-9701** [comment]
遇到了一样的问题 zero2保险正常 zero3异常缓慢

**Comment by Vincent-Li-9701** [comment]
set   NCCL_IB_DISABLE: 0
  NCCL_P2P_DISABLE: 0

解决了问题
