### ISSUE TITLE
Model is not saved when resume_from_checkpoint

### ISSUE THREAD

**Issue by BillChan226** [modelscope/ms-swift#1829]
When we resume fine-tuning from previous checkpoints, the code fails to save the checkpoints as specified by save_steps. While this bug can be fixed by hard coding the transformers trainer.py, I wonder if you can solve it from your side which is more elegant? Thanks!

**Comment by Jintao-Huang** [comment]
I did not understand your meaning, can you provide some reproducible code? thanks
