### ISSUE TITLE
对qwen2-72b-instruct-awq进行qlora微调之后，如何进行merge?

### ISSUE THREAD

**Issue by ArlanCooper** [modelscope/ms-swift#1839]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
微调qwen2-72b-instruct-awq之后，使用命令merge lora信息，报错：
命令：
```
swift export --ckpt_dir 'checkpoint-1168' --merge_lora true

```

报错信息：
```


AssertionError: qwen2-72b-instruct-awq is a quantized model and does not support merge-lora.
```

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

os: ubuntu 16.04
cuda: 12.1
torch: 2.1.2

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
The quantized model's qlora fine-tuning version cannot be merged and will result in significant accuracy errors. It is recommended to train the original model using lora first, then merge-lora before quantization. 

To save GPU memory during training, you can use zero3 or zero3-offload.

**Comment by ArlanCooper** [comment]
> The quantized model's qlora fine-tuning version cannot be merged and will result in significant accuracy errors. It is recommended to train the original model using lora first, then merge-lora before quantization.
> 
> To save GPU memory during training, you can use zero3 or zero3-offload.

Thanks a lot

**Comment by sharonsalabiglossai** [comment]
Does it mean that we can't finetune using qlora?
