### ISSUE TITLE
Examples of running Inference on AWQ models with swift? I'm trying to run the AWQ version of InternVL2 models

### ISSUE THREAD

**Issue by radna0** [modelscope/ms-swift#1841]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
Check this doc please: https://swift.readthedocs.io/en/latest/Multi-Modal/internvl-best-practice.html

**Comment by tastelikefeet** [comment]
Which model are you using please?

**Comment by radna0** [comment]
I'm trying to run the AWQ versions of the InternVL2 models.
https://huggingface.co/collections/OpenGVLab/internvl-20-667d3961ab5eb12c7ed1463e

**Comment by tastelikefeet** [comment]
Oh... I see, we didn't add quantized internvl2 models to our supported list
Let me try.

**Comment by tastelikefeet** [comment]
Supported by #1846 
`swift infer --model_type internvl2-8b-awq --infer_backend lmdeploy`
