### ISSUE TITLE
zero-3微调internvl2-40B

### ISSUE THREAD

**Issue by minaa-lab** [modelscope/ms-swift#1845]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

在使用zero-3微调模型时候internvl2-40B模型时候，target_modules默认为linear和导致emd_tokens出现bug
**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
报错截图发一下

**Comment by minaa-lab** [comment]
您的邮件已经收到，我会尽快处理。

谢谢！

-----武晓敏

**Comment by minaa-lab** [comment]
expected the next 1 parameters in the parameter fetch queue to be ({'id': 'name=base_model.model.language_model.model.embed_tokens.weight id=589', 'status': 'AVAILABLE', 'numel': 458802176, 'ds_numel': 458802176, 'shape': (64007, 7168), 'ds_shape': (64007, 7168), 'requires_grad': False, 'grad_shape': None, 'persist': False, 'active_sub_modules': {0, 809}, 'ds_tensor.shape': torch.Size([57350272])},) 
but got 
 ({'id': 'name=base_model.model.language_model.model.layers.3.mlp.up_proj.lora_A.default.weight id=1190', 'status': 'INFLIGHT', 'numel': 0, 'ds_numel': 57344, 'shape': (0,), 'ds_shape': (8, 7168), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': set(), 'ds_tensor.shape': torch.Size([7168])},).

**Comment by minaa-lab** [comment]
看起来就是因为默认所有linear导致embed_tokens lora发生错误

**Comment by minaa-lab** [comment]
帮忙看看是什么问题

**Comment by Jintao-Huang** [comment]
使用最新的ms-swift试试呢

**Comment by Jintao-Huang** [comment]
如果不行，请发一下sh, 我这里复现一下

**Comment by minaa-lab** [comment]
重新拉解决了，谢谢
