### ISSUE TITLE
Qwen2-VL-7B的微调out of memory

### ISSUE THREAD

**Issue by KirbytroNic0528** [modelscope/ms-swift#1859]
CUDA_VISIBLE_DEVICES=3,4 NPROC_PER_NODE=2 swift sft \
  --model_type qwen2-vl-7b-instruct \
  --model_id_or_path qwen/Qwen2-VL-7B-Instruct \
  --sft_type lora \
  --dataset dataset.json 
torch版本2.4.0
cuda12.2
设备8*A40
使用的是这个命令，其中一张显卡的显存会无限增加直到out of memory

**Comment by Jade0321** [comment]
请问怎么解决的呀？我也是OOM了。

**Comment by Jintao-Huang** [comment]
SIZE_FACTOR=8 MAX_PIXELS=602112

https://github.com/modelscope/ms-swift/blob/main/docs/source/Multi-Modal/qwen2-vl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md

**Comment by mxqin** [comment]
SIZE_FACTOR=8 MAX_PIXELS=602112 NPROC_PER_NODE=4 CUDA_VISIBLE_DEVICES=4,3,6,7 swift sft --model_type qwen2-vl-7b-instruct --custom_train_dataset_path /data/data_instruction_0829.json --model_cache_dir /models/hub/Qwen2-VL-7B-Instruct --eval_steps 10000 --save_steps 100 --sft_type full --output_dir output --deepspeed default-zero2 --save_total_limit 200 --per_device_train_batch_size 1 --learning_rate 0.00001
使用这个命令进行微调仍然提示OOM，显卡为A800。
是否有设置的参数异常或者还需要其他的参数设置吗？

**Comment by ff1Zzd** [comment]
> SIZE_FACTOR=8 MAX_PIXELS=602112
> 
> https://github.com/modelscope/ms-swift/blob/main/docs/source/Multi-Modal/qwen2-vl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md

@Jintao-Huang 请问一下这个size_factor是影响Qwen2-VL的哪些设置呢？或者说在哪里可以找到相关的代码吗？我在qwen2的blog和config里并没有找到相关的参数。https://huggingface.co/Qwen/Qwen2-VL-2B-Instruct/blob/main/preprocessor_config.json

**Comment by zhaowenZhou** [comment]
> SIZE_FACTOR=8 MAX_PIXELS=602112 NPROC_PER_NODE=4 CUDA_VISIBLE_DEVICES=4,3,6,7 swift sft --model_type qwen2-vl-7b-instruct --custom_train_dataset_path /data/data_instruction_0829.json --model_cache_dir /models/hub/Qwen2-VL-7B-Instruct --eval_steps 10000 --save_steps 100 --sft_type full --output_dir output --deepspeed default-zero2 --save_total_limit 200 --per_device_train_batch_size 1 --learning_rate 0.00001 使用这个命令进行微调仍然提示OOM，显卡为A800。 是否有设置的参数异常或者还需要其他的参数设置吗？

我也是这个问题，请问你解决了吗？
