### ISSUE TITLE
minicpm-V-2最佳实践,执行推理时,模型不输出任何结果

### ISSUE THREAD

**Issue by hxzl-98** [modelscope/ms-swift#1863]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

执行minicpm-V-2最佳实践,在推理时,输入prompt与图片路径后,程序不输出任何结果,也不报错.
![企业微信截图_17249886876962](https://github.com/user-attachments/assets/fe918f99-316d-48d5-9733-99eacdadb105)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
torch==2.4.0, cuda==12.2,centos系统,gpu==h20

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
是否是内存不足 造成的，我这里是正常的

**Comment by hxzl-98** [comment]
并不是内存不足的问题,还有500G+的剩余内存,也不是显存的问题
![企业微信截图_1725240832882](https://github.com/user-attachments/assets/f4956ca9-9ae5-434e-8b9e-cff40934ef7f)

**Comment by tastelikefeet** [comment]
看起来程序挂了

**Comment by tastelikefeet** [comment]
建议重新弄一个docker镜像试一下，感觉像是coredump或者内存溢出
