### ISSUE TITLE
部分数据集处理时出现了超过max length的warining，但实际数据貌似并没有超过，前几个版本的分支没有这个问题

### ISSUE THREAD

**Issue by changqingla** [modelscope/ms-swift#1865]
[INFO:swift] Using num_proc: 1
 19%|???????????????????????????????????????                                                                                                                                                                     | 46424/245996 [00:22<01:34, 2116.68it/s][WARNING:swift] Current length of row(2472) is larger than the max_length(2048), deleted.
 47%|???????????????????????????????????????????????????????????????????????????????????????????????                                                                                                            | 115266/245996 [00:57<01:14, 1758.24it/s][WARNING:swift] Current length of row(3457) is larger than the max_length(2048), deleted.
100%|???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 245996/245996 [02:06<00:00, 1943.24it/s]
100%|???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 2484/2484 [00:01<00:00, 2005.51it/s]
[INFO:swift] [INPUT_IDS] [128000, 128006, 882, 128007, 271, 34972, 30832, 5232, 104615, 53434, 70349, 19361, 843, 19483, 106718, 120793, 19361, 868, 19483, 21043, 58850, 21990, 3922, 57107, 71208, 21990, 19361, 115251, 19483, 11571, 128009, 128006, 78191, 128007, 271, 198, 58850, 21990, 19361, 868, 19483, 118170, 71208, 21990, 17792, 9039, 74770, 11883, 60843, 17792, 9039, 111689, 86436, 58850, 21990, 17792, 9039, 113885, 116260, 29411, 71208, 21990, 19483, 9039, 284, 119855, 17792, 9039, 482, 107384, 21990, 19483, 9039, 720, 60843, 17792, 9039, 18184, 843, 3922, 58850, 21990, 19483, 9039, 18184, 868, 115246, 42246, 31640, 17701, 119695, 112352, 113885, 29411, 71208, 21990, 19483, 9039, 284, 220, 843, 482, 220, 868, 284, 220, 1114, 198, 109491, 3922, 104615, 53434, 70349, 71208, 21990, 19361, 1114, 19483, 1811, 128009]
[INFO:swift] [INPUT] <|begin_of_text|><|start_header_id|>user<|end_header_id|>

**Comment by Jintao-Huang** [comment]
前几个版本也有的，只是没有打印
