### ISSUE TITLE
请教一下，图片、视频等多模态数据超长应该怎么截断？

### ISSUE THREAD

**Issue by HuiResearch** [modelscope/ms-swift#1876]
如果长度超过max length，截断左半部分会导致前半部分image placeholder token丢失，这种情况下模型将image embedding填充到input_embs会造成错位。请问下这类型数据应该怎么处理截断问题？查看了swift的代码没有发现这种情况的处理方式，还望不吝赐教。

**Comment by Jintao-Huang** [comment]
默认是直接删除 该数据

**Comment by HuiResearch** [comment]
> 默认是直接删除 该数据

好的，多谢。那在推理阶段，无法直接删除数据，这应该怎么处理呢？

**Comment by Jintao-Huang** [comment]
推理阶段是不限制 max_length的, 默认是None

**Comment by HuiResearch** [comment]
> 推理阶段是不限制 max_length的, 默认是None

好的，了解了，多谢
