### ISSUE TITLE
lr_scheduler_type

### ISSUE THREAD

**Issue by mc-lan** [modelscope/ms-swift#1894]
NPROC_PER_NODE=$nproc_per_node \
MASTER_PORT=29500 \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
swift sft \
    --model_type llava1_5-7b-instruct \
    --model_id_or_path "./checkpoints/llava-1_5-7b-hf" \
    --model_revision master \
    --sft_type lora \
    ...
   --lr_scheduler_type 'cosine' \
   ...

![image](https://github.com/user-attachments/assets/97148eb2-cce6-402d-8246-2651aaf18d1a)

 lr_scheduler_type as 'consine' does not work.

**Comment by Jintao-Huang** [comment]
fix
