### ISSUE TITLE
GLM4V-9B微调后，直接调用微调的模型出错：ValueError: The following `model_kwargs` are not used by the model: ['images'] (note: typos in the generate arguments will also show up in this list)

### ISSUE THREAD

**Issue by tw-repository** [modelscope/ms-swift#1902]
首先通过以下命令合并微调的lora:
CUDA_VISIBLE_DEVICES=0 swift export \
    --ckpt_dir /mnt/disk/tw_data/finetune_output/glm4v-9b-chat/v0-20240829-233921/checkpoint-xxx \
    --merge_lora true

接着使用如何命令进行推理：
CUDA_VISIBLE_DEVICES=0 swift infer \
    --model_id_or_path /mnt/disk/tw_data/finetune_output/glm4v-9b-chat/v0-20240829-233921/checkpoint-23700-merged \
    --model_type glm4v-9b-chat

运行时，能够输入问题  和  图片的路径。
输入这两个参数以后点击回车进行推理，便出现了错误：
ValueError: The following `model_kwargs` are not used by the model: ['images'] (note: typos in the generate arguments will also show up in this list)

请问该如何解决问题呢？

**Comment by Jintao-Huang** [comment]
我没有复现, 请检查是否是最新的glm4v的代码, 以及最新的ms-swift, transformers
