### ISSUE TITLE
qwen2-vl-2b-instruct微调报错：importlib.metadata.PackageNotFoundError: No package metadata was found for The 'qwen_vl_utils' distribution was not found and is required by this application. 

### ISSUE THREAD

**Issue by lgy0404** [modelscope/ms-swift#1905]
**Describe the bug**
qwen2-vl-2b-instruct微调报错：importlib.metadata.PackageNotFoundError: No package metadata was found for The 'qwen_vl_utils' distribution was not found and is required by this application. 
使用的命令：swift infer --model_type qwen2-vl-2b-instruct  

![image](https://github.com/user-attachments/assets/be38415d-c087-4715-b352-12a7d0f1b45c)

**Your hardware and system info**
3090 24G*8
Driver Version: 530.30.02    
CUDA Version: 12.1

**Comment by Jintao-Huang** [comment]
pip install qwen_vl_utils

**Comment by lgy0404** [comment]
已解决谢谢~

> pip install qwen_vl_utils
