### ISSUE TITLE
internvl2-26b多卡训练报错“Expected all tensors to be on the same device...”

### ISSUE THREAD

**Issue by tzw451721677** [modelscope/ms-swift#1910]
**Describe the bug**
运行的代码为：
CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \
    --model_type internvl2-26b \
    --model_id_or_path  /root/InternVL2-26B \
    --dataset label/26b_visual_class_accdef_7k_147k.json \
    --max_length 2048 \
    --lora_target_modules ALL \
    --output_dir /root/output_test/ \
    --lora_bias_trainable all \
    --eval_steps 300

报错如下：
![WechatIMG67](https://github.com/user-attachments/assets/65db3267-d61f-49af-81ee-69ec8ef9057d)

**Additional context**
一个多月前用相同的运行代码跑过，未发生错误。

**Comment by Jintao-Huang** [comment]
pip install ms-swift[llm] -U

**Comment by Jintao-Huang** [comment]
你是什么版本的ms-swift呀

**Comment by tzw451721677** [comment]
> pip install ms-swift[llm] -U

感谢，按照这个重新装了一遍，已解决
