### ISSUE TITLE
qwen2-vl-2b-instruct微调报错ValueError: push_best is not a valid HubStrategy, please select one of ['end', 'every_save', 'checkpoint', 'all_checkpoints']

### ISSUE THREAD

**Issue by learn01one** [modelscope/ms-swift#1917]
File "/env/swift_new2/lib/python3.10/site-packages/transformers/training_args.py", line 1564, in __post_init__
    self.hub_strategy = HubStrategy(self.hub_strategy)
  File "/env/swift_new2/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "env/swift_new2/lib/python3.10/enum.py", line 718, in __new__
    raise exc
  File "/env/swift_new2/lib/python3.10/enum.py", line 700, in __new__
    result = cls._missing_(value)
  File "/env/swift_new2/lib/python3.10/site-packages/transformers/utils/generic.py", line 496, in _missing_
    raise ValueError(
ValueError: push_best is not a valid HubStrategy, please select one of ['end', 'every_save', 'checkpoint', 'all_checkpoints']

推理没问题，微调的时候报错，有大佬遇到过吗

**Comment by Jintao-Huang** [comment]
可复现的sh发一下呗

**Comment by Jintao-Huang** [comment]
重新拉一下最新的代码试试

**Comment by learn01one** [comment]
> 可复现的sh发一下呗

SIZE_FACTOR=8 MAX_PIXELS=602112 CUDA_VISIBLE_DEVICES=0 swift sft \
  --model_type qwen2-vl-7b-instruct \
  --model_id_or_path /swift/swift_0821/ms-swift/model/qwen2vl \
  --sft_type lora \
  --dataset /swift/swift_0821/ms-swift/train_data/muti_round_conversion_instruction.json \

这样报错的，发现  --push_hub_strategy 默认push_best

SIZE_FACTOR=8 MAX_PIXELS=602112 CUDA_VISIBLE_DEVICES=0 swift sft \
  --model_type qwen2-vl-7b-instruct \
  --model_id_or_path /swift/swift_0821/ms-swift/model/qwen2vl \
  --sft_type lora \
  --dataset /swift/swift_0821/ms-swift/train_data/muti_round_conversion_instruction.json \
  --push_hub_strategy checkpoint
修改一下这样倒是没问题，比较奇怪的是微调其他模型。默认也是--push_hub_strategy push_best 不会报错，，

**Comment by tastelikefeet** [comment]
前几天的版本的临时问题，目前已经修复，请使用最新代码
