### ISSUE TITLE
Qwen2-VL-7B-Instruct  Video inference

### ISSUE THREAD

**Issue by wangli68** [modelscope/ms-swift#1920]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
 When I use the reasoning provided by Qwen2-VL for video description, the results can be returned normally.
<img width="719" alt="image" src="https://github.com/user-attachments/assets/3c118337-2342-4b54-a92a-edc62d2b77a8">
When I use the reasoning provided by Swift for video description, I will encounter the following error message
<img width="789" alt="image" src="https://github.com/user-attachments/assets/28988568-28d6-411c-8a09-4a8ebec802b0">

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
torch                          2.2.1+cu121
torch-tb-profiler              0.4.3
torchaudio                     2.2.1+cu121
torchvision                    0.17.1+cu121
modelscope                     1.17.1
modelscope_studio              0.4.0.9
ms-swift                       2.4.0.post1

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
If torch < 2.4, only local_path is supported, or you need to update to torch >= 2.4.
