### ISSUE TITLE
TypeError: Qwen2ForCausalLM.forward() got an unexpected keyword argument '_data'

### ISSUE THREAD

**Issue by xiamaozi11** [modelscope/ms-swift#1929]
CUDA_VISIBLE_DEVICES=1 swift sft \
  --model_type minicpm-v-v2_6-chat \
  --model_id_or_path /data1/data/wudao/MiniCPM-V-2_6 \
  --sft_type lora \
  --dataset /data/train_math.jsonl \
  --num_train_epochs 3
  微调MiniCPM报的错,transformers==4.43.4

**Comment by Jintao-Huang** [comment]
我这里没有复现, 可以升级一下ms-swift看看还有这个问题不

**Comment by xiamaozi11** [comment]
我昨天才安装的，不知道可是哪个包版本不对，原先是llama factory的环境。数据格式对不
{"query": "Please solve the problem step by step and put your answer in one \"\\boxed{}\". If it is a multiple choice question, only one letter is allowed in the \"\\boxed{}\".\nWhich number should be written in place of the question mark?\n", "response": "60", "images": ["/data/data/xia/2024/images/1.jpg"]}
{"query": "Please solve the problem step by step and put your answer in one \"\\boxed{}\". If it is a multiple choice question, only one letter is allowed in the \"\\boxed{}\".\nWhich bike is most expensive?\n", "response": "A", "images": ["/data/data/xia/2024/images/2.jpg"]}

**Comment by Jintao-Huang** [comment]
torch版本是什么

**Comment by xiamaozi11** [comment]
> torch版本是什么

1.13.1

**Comment by Jintao-Huang** [comment]
建议使用torch>=2.1
