### ISSUE TITLE
dpo internvl2存在mismatch

### ISSUE THREAD

**Issue by Ranking666** [modelscope/ms-swift#1930]
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/bf90702b-71a7-4b12-9a72-08fd2c748116">
训练参数为
<img width="798" alt="image" src="https://github.com/user-attachments/assets/1d5d58ad-7f47-4c57-a693-f1d621e5bb21">

**Comment by hjh0119** [comment]
increase  `--max_length`

**Comment by Ranking666** [comment]
> 不会 再试试增加 --max_prompt_length

不行，还是一样的报错

**Comment by hjh0119** [comment]
fixed
