### ISSUE TITLE
swift 中如何设置模型内部参数，如internvl中的max_dynamic_patch

### ISSUE THREAD

**Issue by zws-2019** [modelscope/ms-swift#1953]

**Comment by zhangfan-algo** [comment]
＋1

**Comment by Jintao-Huang** [comment]
哈咯 max_dynamic_patch 参数，我没找到，在哪个文件啊

**Comment by zhaopings** [comment]
解决了吗

**Comment by zhaopings** [comment]
看上去max_dynamic_patch是固化为6了，在swift/llm/utils/vision_utils.py中的load_image函数里面

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/blob/main/swift/llm/utils/template.py#L2032

**Comment by PancakeAwesome** [comment]
> https://github.com/modelscope/ms-swift/blob/main/swift/llm/utils/template.py#L2032

 怎么在部署推理的时候 inference_client 传递max_dynamic_patch 参数呢？

**Comment by Jintao-Huang** [comment]
> > https://github.com/modelscope/ms-swift/blob/main/swift/llm/utils/template.py#L2032
> 
> 怎么在部署推理的时候 inference_client 传递max_dynamic_patch 参数呢？

目前好像传不过去

**Comment by Jintao-Huang** [comment]
如果是训练或者推理 可以使用环境变量的方式修改
