### ISSUE TITLE
环境镜像

### ISSUE THREAD

**Issue by Qiny-dl** [modelscope/ms-swift#1966]
你好 关于官方推荐的镜像 不能正常使用 https://www.modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85 是否可以检查一下 存在兼容问题

**Comment by tastelikefeet** [comment]
可以先使用1.17.1
这个我们的同学还没弄完，下周一应该就可用了

**Comment by tastelikefeet** [comment]
https://www.modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85 已更新

**Comment by Qiny-dl** [comment]
![企业微信截图_20240909143944](https://github.com/user-attachments/assets/416fd0d5-676a-4354-ba72-097cf7a67430)

C:\Users\DELL>docker run modelscope-registry.cn-beijing.cr.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda12.1.0-py310-torch2.3.0-tf2.16.1-1.18.0
docker: Error response from daemon: no command specified.
See 'docker run --help'.
 测试其他 如torch镜像运行正常，swift的就会出问题
