### ISSUE TITLE
全量微调minicpm-V2.6,但是生成的sft_args.json里面仍然有lora

### ISSUE THREAD

**Issue by zhaoyangwei123** [modelscope/ms-swift#1967]
对minicpm-V2.6模型，我设置了--sft_type full用来进行全量微调，相比于--sft_type lora不经显存使用增加很多，而且速度上也变慢了很多，但是在生成的sft_args.json里面，--sft_type full是没问题的，但是仍然存在"target_modules": "^(llm|resampler)(?!.*(lm_head|output|emb|wte|shared)).*",　以及 有关lora的参数都是存在的"lora_rank": 8,
  "lora_alpha": 32,
  "lora_dropout": 0.05,
  "lora_bias_trainable": "none",
  所以这是全量微调没有成功吗，还是说只是对vlm进行了全量微调同时对llm的话只是对target_modules进行lora？

**Comment by Jintao-Huang** [comment]
如果 sft_type为'full', 那么lora的参数是失效的

**Comment by SpartacusIn21** [comment]
我是设置了sft_type是full，生成的sft_args.json里面--sft_type还是lora，训练命令如下：
run sh: `/root/miniforge3/envs/LVLM_cyc/bin/python3.9 -m torch.distributed.run --nproc_per_node 2 ms-swift-main/swift/cli/sft.py --model_type minicpm-v-v2_6-chat --model_id_or_path models/openbmb/MiniCPM-V-2_6 --template_type minicpm-v-v2_6 --system You are a helpful assistant. --sft-type full --dataset cmarkea_table-vqa/train/dataset.jsonl --val_dataset cmarkea_table-vqa/test/dataset.jsonl --learning_rate 1e-4 --gradient_accumulation_steps 16 --eval_steps 500 --save_steps 500 --eval_batch_size 1 --add_output_dir_suffix False --output_dir minicpm-v-v2_6-chat/tablevqa-full-20241028 --logging_dir minicpm-v-v2_6-chat/tablevqa-full-20241028/runs --ignore_args_error True`
