### ISSUE TITLE
如何手动下载评测数据集，并且如何指定评测时的数据集路径

### ISSUE THREAD

**Issue by Harry-zzh** [modelscope/ms-swift#1972]
如题。想使用 `swift eval --model_type llava1_5-7b-instruct --eval_dataset POPE` 评测POPE数据集，但是如何手动下载POPE数据集，并且使用 swift eval 时将评测路径设为数据集下载后保存的路径呢？

因为现在所使用的GPU机器无法连网，所以只能在自己的电脑上先下载。希望能得到解答，非常感谢！

**Comment by Harry-zzh** [comment]
可参考：https://github.com/open-compass/VLMEvalKit/issues/351

**Comment by ex-yanminmin001** [comment]
如何解决的 已经下载了eval_data了 通过eval_dataset dataset_path  报错：Cannot load final report, please check your dataset: {args.eval_dataset} and the eval log
