### ISSUE TITLE
评测时出现超时错误

### ISSUE THREAD

**Issue by Harry-zzh** [modelscope/ms-swift#1974]
使用 `swift eval --model_type llava1_5-7b-instruct --eval_dataset POPE`评测POPE数据集时，出现如下错误：

ChatAPI - ERROR - HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f28b32f9370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

本地已经下载好模型和数据集了，想请教下是什么原因？谢谢！

**Comment by wangxingjun778** [comment]
请帮忙补充一下更全的栈信息

**Comment by Harry-zzh** [comment]
这个问题我已经解决了，是因为网络访问不了，需要自行下载tiktoken：https://blog.csdn.net/qq_35054222/article/details/137127660
