### ISSUE TITLE
Uploading models to Hugging Face from MS Swift

### ISSUE THREAD

**Issue by YoungjaeDev** [modelscope/ms-swift#1981]
Hello,

I’m currently working vlm finetuning with ms-swift, and I’m curious if it's possible to upload models directly to HuggingFace, similar to ModelScope. If this feature isn’t available yet, are there any plans to support it in the future?

**Comment by tastelikefeet** [comment]
This is supported, use with `USE_HF=1`
This will use huggingface to download and upload models

**Comment by sharonsalabiglossai** [comment]
what command to use to export the finetuned model with lora to huggingface hub?
