### ISSUE TITLE
lr_scheduler_type

### ISSUE THREAD

**Issue by NancyGu** [modelscope/ms-swift#1983]
SIZE_FACTOR=16 MAX_PIXELS=301056 CUDA_VISIBLE_DEVICES=0,1,2,3 NPROC_PER_NODE=4 swift sft \
  --model_type qwen2-vl-7b-instruct \
   ……
  --freeze_vit true \
  --sft_type full \
  --learning_rate 1e-05 \
  ……
  --lr_scheduler_type constant \
 ……
  
<img width="177" alt="1725862570124" src="https://github.com/user-attachments/assets/a590b395-1469-47b9-a746-e578682558bc">

lr_scheduler_type 好像没起作用？

**Comment by bonre** [comment]
你是用了deepspeed吗？是的话得在ds_config里面改。

**Comment by NancyGu** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已经收到了，因为时间问题，我可能无法立刻回复您的邮件。如有急事，请直接QQ留言，我会尽快给您回复的。

**Comment by NancyGu** [comment]
是的。搞定了。感谢~

**Comment by AHFJE** [comment]
> 是的。搞定了。感谢~

我也遇到这个问题了，请教一下你是怎么搞定的，我没有使用deepspeed

**Comment by NancyGu** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已经收到了，因为时间问题，我可能无法立刻回复您的邮件。如有急事，请直接QQ留言，我会尽快给您回复的。
