### ISSUE TITLE
lmdeploy的main分支已经移除了EngineGenerationConfig，目前使用swift调用main分支的lmdeploy会报错

### ISSUE THREAD

**Issue by RandomCoins** [modelscope/ms-swift#1985]
**Describe the feature**
lmdeploy的main分支已经移除了EngineGenerationConfig，swift是否会在后续做适配

**Paste any useful information**
[from .messages import (GenerationConfig, PytorchEngineConfig,](https://github.com/InternLM/lmdeploy/blob/659a6b03a5f97046922f7c6c148ab71ec52f24e7/lmdeploy/__init__.py#L4)

**Additional context**
Add any other context or information here(其他信息可以写在这里)

**Comment by Jintao-Huang** [comment]
会长期适配的

不过会有一定延后
