### ISSUE TITLE
O-lora 不可用

### ISSUE THREAD

**Issue by CoderXiaopang** [modelscope/ms-swift#1989]
**Describe the bug**

[rank2]: Traceback (most recent call last):
[rank2]:   File "/root/swift/swift/cli/sft.py", line 5, in <module>
[rank2]:     sft_main()
[rank2]:   File "/root/swift/swift/utils/run_utils.py", line 32, in x_main
[rank2]:     result = llm_x(args, **kwargs)
[rank2]:   File "/root/swift/swift/llm/sft.py", line 250, in llm_sft
[rank2]:     model, callbacks = prepare_model(model, args)
[rank2]:   File "/root/swift/swift/llm/tuner.py", line 131, in prepare_model
[rank2]:     model = Swift.prepare_model(model, lora_config)
[rank2]:   File "/root/swift/swift/tuners/base.py", line 725, in prepare_model
[rank2]:     return get_peft_model(model, config, **kwargs)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/peft/mapping.py", line 149, in get_peft_model
[rank2]:     return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/peft/peft_model.py", line 1395, in __init__
[rank2]:     super().__init__(model, peft_config, adapter_name)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/peft/peft_model.py", line 138, in __init__
[rank2]:     self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
[rank2]:   File "/root/swift/swift/tuners/peft.py", line 322, in init
[rank2]:     self.__init_origin__(model, config, adapter_name)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 139, in __init__
[rank2]:     super().__init__(model, config, adapter_name)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 166, in __init__
[rank2]:     self.inject_adapter(self.model, adapter_name)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 372, in inject_adapter
[rank2]:     self._create_and_replace(peft_config, adapter_name, target, target_name, parent, current_key=key)
[rank2]:   File "/root/swift/swift/tuners/peft.py", line 97, in _create_and_replace_hook
[rank2]:     return self._create_and_replace_origin(*args, **kwargs)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 223, in _create_and_replace
[rank2]:     new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 314, in _create_new_module
[rank2]:     new_module = dispatcher(target, adapter_name, lora_config=lora_config, **kwargs)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 1116, in dispatch_default
[rank2]:     new_module = Linear(target, adapter_name, **kwargs)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 410, in __init__
[rank2]:     self.update_layer(
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 121, in update_layer
[rank2]:     self.reset_lora_parameters(adapter_name, init_lora_weights)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 154, in reset_lora_parameters
[rank2]:     raise ValueError(f"Unknown initialization {init_lora_weights=}")
[rank2]: ValueError: Unknown initialization init_lora_weights='olora'

**Comment by tastelikefeet** [comment]
给一下命令

**Comment by tastelikefeet** [comment]
升级下peft看看

**Comment by AU-CPU** [comment]
hello ValueError    : sft_main()remaining_argv: ['--init_lora_weights', 'olora'] pull最新代码出现这个问题 能帮忙看一下吗

**Comment by tastelikefeet** [comment]
--init_weights olora试试
