### ISSUE TITLE
 Inference Not Working on cuda:1

### ISSUE THREAD

**Issue by YoungjaeDev** [modelscope/ms-swift#1991]
The training uses cuda:1 without any issues, but the inference does not work as expected on the same device (cuda:1).
Behaves as `cuda:0`

```python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '1'

import torch
from swift.llm import (DatasetName, InferArguments, ModelType, SftArguments, infer_main, sft_main, app_ui_main)

model_type = ModelType.qwen_7b_chat
sft_args = SftArguments(
    model_type=model_type,
    dataset=[f'{DatasetName.blossom_math_zh}#2000'],
    output_dir='output')

result = sft_main(sft_args)
best_model_checkpoint = result['best_model_checkpoint']
print(f'best_model_checkpoint: {best_model_checkpoint}')
torch.cuda.empty_cache()

infer_args = InferArguments(
    ckpt_dir=best_model_checkpoint,
    load_dataset_config=True)

result = infer_main(infer_args)
torch.cuda.empty_cache()
app_ui_main(infer_args)
```

**Comment by Jintao-Huang** [comment]
Use `nvidia-smi` to check which GPU the code is running on; I feel like there's no issue with the code.

Do you have any relevant screenshots?

**Comment by YoungjaeDev** [comment]
[sample_finetune.zip](https://github.com/user-attachments/files/16937575/sample_finetune.zip)

The cuda:0 was being used elsewhere, and I'm trying to train and infer with cuda:1 at the same time, but the logs on the reference side are holding cuda:0.

**Comment by Jintao-Huang** [comment]
Set to be visible to GPU 1, so from the program's perspective, only one card is present, hence it is named cuda:0.
