### ISSUE TITLE
使用deepspeed时，出现RuntimeError: 'weight' must be 2-D 的错误

### ISSUE THREAD

**Issue by shuye-cheung** [modelscope/ms-swift#1996]
使用deepspeed进行预训练微调时

```
CUDA_VISIBLE_DEVICES=0 \
swift pt \
    --model_type qwen1half-7b \
    --dataset pt_data.jsonl \
    --num_train_epochs 1 \
    --sft_type full \
    --output_dir output \
    --lazy_tokenize true \
    --deepspeed default-zero3 
```

出现以下错误

[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/autodl-tmp/ms-swift-main/swift/cli/pt.py", line 5, in <module>
[rank0]:     pt_main()
[rank0]:   File "/root/autodl-tmp/ms-swift-main/swift/utils/run_utils.py", line 32, in x_main
[rank0]:     result = llm_x(args, **kwargs)
[rank0]:   File "/root/autodl-tmp/ms-swift-main/swift/llm/sft.py", line 414, in llm_sft
[rank0]:     trainer.train(training_args.resume_from_checkpoint)
[rank0]:   File "/root/autodl-tmp/ms-swift-main/swift/trainers/mixin.py", line 409, in train
[rank0]:     res = super().train(resume_from_checkpoint, *args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 2279, in _inner_training_loop
[rank0]:     tr_loss_step = self.training_step(model, inputs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 3318, in training_step
[rank0]:     loss = self.compute_loss(model, inputs)
[rank0]:   File "/root/autodl-tmp/ms-swift-main/swift/trainers/trainers.py", line 170, in compute_loss
[rank0]:     outputs = model(**inputs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1603, in _call_impl
[rank0]:     result = forward_call(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 820, in forward
[rank0]:     return model_forward(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 808, in __call__
[rank0]:     return convert_to_fp32(self.model_forward(*args, **kwargs))
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 43, in decorate_autocast
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1104, in forward
[rank0]:     outputs = self.model(
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 878, in forward
[rank0]:     inputs_embeds = self.embed_tokens(input_ids)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1603, in _call_impl
[rank0]:     result = forward_call(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 164, in forward
[rank0]:     return F.embedding(
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/functional.py", line 2267, in embedding
[rank0]:     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
[rank0]: RuntimeError: 'weight' must be 2-D
Train:   0%|                                                             

已知相关环境为：
```
deepspeed                     0.15.1
accelerate                    0.34.0
transformers                  4.44.2
sentence-transformers         3.0.1
transformers-stream-generator 0.0.5
peft                          0.12.0
```

请问出现错误的原因以及解决方法，谢谢！

**Comment by shuye-cheung** [comment]
采用单卡会出现上述问题，多卡则不会。

**Comment by VJJJJJJ1** [comment]
> 采用单卡会出现上述问题，多卡则不会。

请问你解决了吗？我使用fsdp的时候也遇到类似问题

**Comment by Jintao-Huang** [comment]
什么模型呢
