### ISSUE TITLE
eval_acc 是如何计算的？

### ISSUE THREAD

**Issue by XiaoMaGe-hero** [modelscope/ms-swift#2006]
请问 eval_acc 是如何计算的？

**Comment by XiaoMaGe-hero** [comment]
如何调整最优checkpoint 的选择机制？比如参考最优的 eval_acc。

**Comment by tastelikefeet** [comment]
eval_acc是by token计算每个token的正确性给出的

**Comment by leeburt** [comment]
> eval_acc是by token计算每个token的正确性给出的

是token by token的对比，给出正确性的吗？
