### ISSUE TITLE
dpo训练时，使用自带数据集，报错

### ISSUE THREAD

**Issue by JiaXinLI98** [modelscope/ms-swift#2008]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

ValueError: dataset.features.keys(): dict_keys(['raw_prompt', 'prompt', 'rejected', 'chosen'])
required_keys_mapping: {'swift': ['response'], 'alpaca': ['instruction', 'output'], 'conversations': ['conversations'], 'chatml': ['messages'], 'sharegpt': ['conversation'], 'pretrain': ['text']}
<img width="1008" alt="截屏2024-09-10 22 08 08" src="https://github.com/user-attachments/assets/65504397-4de8-445a-8f7b-f391fac837fd">
启动脚本：
<img width="796" alt="截屏2024-09-10 22 11 53" src="https://github.com/user-attachments/assets/c8d7cab6-362e-4eba-876b-759798b4d53a">

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
<img width="408" alt="截屏2024-09-10 22 08 43" src="https://github.com/user-attachments/assets/195818b6-0dec-4692-b5ba-b29480fe3491">

**Additional context**
Add any other context about the problem here(在这里补充其他信息)
为啥跳回sft的数据版本了呢

**Comment by Darren-w** [comment]
你好，我也是跑dpo的时候碰到这个问题，加载默认的数据集则可以跑起来，换成自己的数据集，相同的格式报一样的错误，请问下您当时是怎么解决的呢？
