### ISSUE TITLE
Does DPO/RLHF tuning support internVL2 video models?

### ISSUE THREAD

**Issue by BillChan226** [modelscope/ms-swift#2015]
Hi, thanks for the great work! I'm wondering if DPO is supported for tuning internvl2 with video input? Thanks!

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/pull/1975

**Comment by BillChan226** [comment]
However, it seems that `_patch_internvl_forward(forward_func)` in `swift/swift/llm/utils/model.py` have `pixel_values = None` even if I provide an `videos` key in each entry of the dpo dataset. I think in this case the video input is not being processed?
