### ISSUE TITLE
internvl2-40b infer

### ISSUE THREAD

**Issue by wangli68** [modelscope/ms-swift#2016]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
当我运行下列命令时，
CUDA_VISIBLE_DEVICES=0,1,2,3 swift infer --model_type internvl2-40b --model_id_or_path='/openbayes/home/InternVL2-40B/' --max_length 4096
或者运行下列命令时，
CUDA_VISIBLE_DEVICES=0,1,2,3 swift infer --model_type internvl2-40b --model_id_or_path='/openbayes/home/InternVL2-40B/' --max_length 4096 --tensor_parallel_size 4
可以正常进入推理界面，并且可以回复文本消息，但是上传本地图片之后，会报错如下：
<img width="798" alt="image" src="https://github.com/user-attachments/assets/78ffb1e6-dc98-49b7-8d6c-d51b09682d8a">

<img width="802" alt="image" src="https://github.com/user-attachments/assets/107cced1-e0d1-447a-99f4-134b67d08f90">

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
torch                          2.2.1+cu121
torchaudio                     2.2.1+cu121
torchvision                    0.17.1+cu121
transformers                   4.40.0
typing_extensions              4.9.0

**Additional context**
Add any other context about the problem here(在这里补充其他信息)
使用原始的internvl2-40b可以正常推理，使用swift的推理时，设置了使用4卡进行推理，但实际上只使用了一张卡的样子
<img width="679" alt="image" src="https://github.com/user-attachments/assets/873ebf99-8041-4e5a-9bcd-96393c6935ab">

**Comment by Jintao-Huang** [comment]
lmdeploy请使用--tp 而不是 --tensor_parallel_size, 后者是vllm的参数
