### ISSUE TITLE
Dataset format compatibility between LLaVA-NexT and Qwen-VL2 for custom JSON datasets

### ISSUE THREAD

**Issue by YoungjaeDev** [modelscope/ms-swift#2017]
Hello,

I noticed that the dataset format (video finetuning) differs between the LLaVA-NexT and Qwen-VL2 models

1. llava-next
https://swift.readthedocs.io/en/latest/Multi-Modal/llava-video-best-practice.html#fine-tuning

2. qwen-vl2 
https://swift.readthedocs.io/en/latest/Multi-Modal/qwen2-vl-best-practice.html#video-fine-tuning

Do  I still need to create a different dataset, e.g. `<video>` put the token directly in it?

**Comment by Jintao-Huang** [comment]
It is not necessary; if <video> does not exist in the query, it will be added before the earliest history/query based on the number of videos.

**Comment by Yu-Yang-Li** [comment]
> It is not necessary; if `<video>` does not exist in the query, it will be added before the earliest history/query based on the number of videos.

Thanks for your response!
How about image finetuning, is that as same as video? [without <image> tag also be approved？]
