### ISSUE TITLE
Internlm-Xcomposer2.5 推理时输入多张图报错

### ISSUE THREAD

**Issue by diodes-zhang** [modelscope/ms-swift#2020]
运行模版案例时，当输入多张图片时报错
<img width="1037" alt="image" src="https://github.com/user-attachments/assets/5c28ac9e-a69b-4a3b-b3ff-a2028e31e349">
Internlm-Xcomposer2则显示正常
<img width="1046" alt="image" src="https://github.com/user-attachments/assets/7bb407a1-b3fa-419e-90fe-a992e360f2fd">

**Comment by Jintao-Huang** [comment]
The main branch has been fixed.
