### ISSUE TITLE
cannot import name 'ftp_head' from 'datasets.utils.file_utils' 

### ISSUE THREAD

**Issue by 77h2l** [modelscope/ms-swift#2021]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
安装swift： pip安装和源码安装都遇到上述报错，
RuntimeError: Failed to import modelscope.msdatasets because of the following error (look up to see its traceback):
cannot import name 'ftp_head' from 'datasets.utils.file_utils'

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Ranking666** [comment]
我也遇到了一样的问题，昨天还能正常训练

**Comment by mc-lan** [comment]
> 我也遇到了一样的问题，昨天还能正常训练

+1

**Comment by Jintao-Huang** [comment]
datasets<3.0

**Comment by for-code0216** [comment]
pip install datasets==2.21.0 可以了

**Comment by xieyongshuai** [comment]
> pip install datasets==2.21.0 就可以了

我降了版本还是报错

**Comment by ryuichi-sumida** [comment]
pip install datasets==2.21.0, this worked for me

**Comment by U202142209** [comment]
我也遇见了：ImportError: cannot import name 'ftp_head' from 'datasets.utils.

**Comment by Elissa0723** [comment]
> pip install datasets==2.21.0 可以了

感谢！生效了

**Comment by AntyRia** [comment]
牛逼哥们

**Comment by WjMessi1** [comment]
感谢！可以了！
