### ISSUE TITLE
swift不能做模型的二次预训练？具体怎么做啊？

### ISSUE THREAD

**Issue by kandada** [modelscope/ms-swift#2022]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
https://swift.readthedocs.io/zh-cn/latest/LLM/Megatron%E8%AE%AD%E7%BB%83%E6%96%87%E6%A1%A3.html
上面是megatron的预训练
如果使用hf格式进行预训练，直接使用：
```
swift pt --model_type xxx --template default-generation --dataset some-pretrain-dataset
```

**Comment by Z-oo883** [comment]
> https://swift.readthedocs.io/zh-cn/latest/LLM/Megatron%E8%AE%AD%E7%BB%83%E6%96%87%E6%A1%A3.html 上面是megatron的预训练 如果使用hf格式进行预训练，直接使用：
> 
> ```
> swift pt --model_type xxx --template default-generation --dataset some-pretrain-dataset
> ```

this page 404，can you send again？
