### ISSUE TITLE
internvl2-8b在docker里训练OOM

### ISSUE THREAD

**Issue by mc-lan** [modelscope/ms-swift#2027]
**Describe the bug**

基于LORA来训练internvl2-8b，在pip install 'ms-swift[llm]' -U安装的环境下正常训练，batch size 为8。但在官方的docker环境下OOM，即使把batch size变小一倍，从8变到4.

**Your hardware and system info**

8*A800 (40G)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
有几个可能的原因：
1. batch_size继续缩小
2. 图片过多导致的OOM
3. 是否是DDP
4. LoRA使用了ALL
建议贴一下命令比较容易看出来问题

**Comment by mc-lan** [comment]
我在docker环境里继续pip install -e '.[llm]'，就可以正常训练了。
