### ISSUE TITLE
windows使用webui训练报错 invalid float value: "'1e-4'"

### ISSUE THREAD

**Issue by chuanSir123** [modelscope/ms-swift#2036]
**Describe the bug**
windows使用webui训练报错 invalid float value: "'1e-4'"，同时整个页面的很多字段都字段被单引号包围，导致后续问题

**Your hardware and system info**
gradio  4.44.0和3.50.2都不行

**Additional context**

**Comment by Jintao-Huang** [comment]
使用命令行试试，应该是和windows的兼容问题
