### ISSUE TITLE
使用OpenAI API方式启动部署报错：ImportError: cannot import name 'prepare_vllm_engine_template' from 'swift.llm.utils'

### ISSUE THREAD

**Issue by lgy0404** [modelscope/ms-swift#2038]
**Describe the bug**
![image](https://github.com/user-attachments/assets/8c18687f-c85c-4357-b255-41752d6ee1ee)

**Your hardware and system info**
3090 24G

**Additional context**
我使用的命令行参数
```
CUDA_VISIBLE_DEVICES=4 swift deploy --model_type qwen2-7b-instruct
```

**Comment by Jintao-Huang** [comment]
升级一下ms-swift

**Comment by Jintao-Huang** [comment]
vllm的版本那是什么
