### ISSUE TITLE
Merge Lora后为什么sft_type被设置为full，不应该是lora么

### ISSUE THREAD

**Issue by Sunxiaohu0406** [modelscope/ms-swift#2041]
lora微调后，sft_type被设置为full，不应该是lora吗

![image](https://github.com/user-attachments/assets/e828faa0-ba7b-4563-b9dd-60ac12f748b0)

**Comment by Jintao-Huang** [comment]
是特意这样设计的，这样 --ckpt_dir xxx的时候会以全参数的方式进行模型载入
