### ISSUE TITLE
chatglm4v-9b全量微调full报错：File "/usr/local/Python3.10.0/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 149, in __init__ [rank0]:     self.dtype = self.optimizer.param_groups[0]['params'][0].dtype [rank0]: IndexError: list index out of range

### ISSUE THREAD

**Issue by Sunxiaohu0406** [modelscope/ms-swift#2043]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/nfs/appnfs/sxh/code/swift-latest/examples/pytorch/llm/llm_sft.py", line 6, in <module>
[rank0]:     output = sft_main()
[rank0]:   File "/home/nfs/appnfs/sxh/code/swift-latest/swift/utils/run_utils.py", line 32, in x_main
[rank0]:     result = llm_x(args, **kwargs)
[rank0]:   File "/home/nfs/appnfs/sxh/code/swift-latest/swift/llm/sft.py", line 439, in llm_sft
[rank0]:     trainer.train(training_args.resume_from_checkpoint)
[rank0]:   File "/home/nfs/appnfs/sxh/code/swift-latest/swift/trainers/mixin.py", line 409, in train
[rank0]:     res = super().train(resume_from_checkpoint, *args, **kwargs)
[rank0]:   File "/usr/local/Python3.10.0/lib/python3.10/site-packages/transformers/trainer.py", line 1948, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/usr/local/Python3.10.0/lib/python3.10/site-packages/transformers/trainer.py", line 2105, in _inner_training_loop
[rank0]:     model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
[rank0]:   File "/usr/local/Python3.10.0/lib/python3.10/site-packages/accelerate/accelerator.py", line 1318, in prepare
[rank0]:     result = self._prepare_deepspeed(*args)
[rank0]:   File "/usr/local/Python3.10.0/lib/python3.10/site-packages/accelerate/accelerator.py", line 1815, in _prepare_deepspeed
[rank0]:     engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
[rank0]:   File "/home/nfs/appnfs/sxh/code/swift-latest/swift/llm/utils/template.py", line 344, in _initialize
[rank0]:     res = _old_initialize(*args, **kwargs)
[rank0]:   File "/usr/local/Python3.10.0/lib/python3.10/site-packages/deepspeed/__init__.py", line 176, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:   File "/usr/local/Python3.10.0/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
[rank0]:     self._configure_optimizer(optimizer, model_parameters)
[rank0]:   File "/usr/local/Python3.10.0/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1257, in _configure_optimizer
[rank0]:     self.optimizer = self._configure_zero_optimizer(basic_optimizer)
[rank0]:   File "/usr/local/Python3.10.0/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1579, in _configure_zero_optimizer
[rank0]:     optimizer = DeepSpeedZeroOptimizer_Stage3(
[rank0]:   File "/usr/local/Python3.10.0/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 149, in __init__
[rank0]:     self.dtype = self.optimizer.param_groups[0]['params'][0].dtype
[rank0]: IndexError: list index out of range

**Comment by Sunxiaohu0406** [comment]
已经解决，需要使用官方配置的deepspeed文件

**Comment by Zion66666** [comment]
> 已经解决，需要使用官方配置的deepspeed文件

您好，可以说的再详细点嘛，我没有理解您的意思，请问官方配置的deepspeed文件在哪里

**Comment by Sunxiaohu0406** [comment]
> > 已经解决，需要使用官方配置的deepspeed文件
> 
> 您好，可以说的再详细点嘛，我没有理解您的意思，请问官方配置的deepspeed文件在哪里



就是你换用官方的deepspeed的zero/stage3配置文件，具体你可以找一下，我目前版本比较老，官方最新版的代码没有跟进。下面是我的stage3使用的配置文件。

{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },

    "bf16": {
        "enabled": "auto"
    },

    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto"
        }
    },

    "scheduler": {
        "type": "WarmupCosineLR",
        "params": {
            "total_num_steps": "auto",
            "warmup_num_steps": "auto"
        }
    },

    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "none",
            "pin_memory": true
        },
        "offload_param": {
            "device": "none",
            "pin_memory": true
        },
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": 0,
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
    },

    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}

**Comment by Sunxiaohu0406** [comment]
> > > 已经解决，需要使用官方配置的deepspeed文件
> > 
> > 
> > 您好，可以说的再详细点嘛，我没有理解您的意思，请问官方配置的deepspeed文件在哪里
> 
> 就是你换用官方的deepspeed的zero/stage3配置文件，具体你可以找一下，我目前版本比较老，官方最新版的代码没有跟进。下面是我的stage3使用的配置文件。
> 
> { "fp16": { "enabled": "auto", "loss_scale": 0, "loss_scale_window": 1000, "initial_scale_power": 16, "hysteresis": 2, "min_loss_scale": 1 },
> 
> ```
> "bf16": {
>     "enabled": "auto"
> },
> 
> "optimizer": {
>     "type": "AdamW",
>     "params": {
>         "lr": "auto",
>         "betas": "auto",
>         "eps": "auto",
>         "weight_decay": "auto"
>     }
> },
> 
> "scheduler": {
>     "type": "WarmupCosineLR",
>     "params": {
>         "total_num_steps": "auto",
>         "warmup_num_steps": "auto"
>     }
> },
> 
> "zero_optimization": {
>     "stage": 3,
>     "offload_optimizer": {
>         "device": "none",
>         "pin_memory": true
>     },
>     "offload_param": {
>         "device": "none",
>         "pin_memory": true
>     },
>     "overlap_comm": true,
>     "contiguous_gradients": true,
>     "sub_group_size": 1e9,
>     "reduce_bucket_size": "auto",
>     "stage3_prefetch_bucket_size": 0,
>     "stage3_param_persistence_threshold": "auto",
>     "stage3_max_live_parameters": 1e9,
>     "stage3_max_reuse_distance": 1e9,
>     "stage3_gather_16bit_weights_on_model_save": true
> },
> 
> "gradient_accumulation_steps": "auto",
> "gradient_clipping": "auto",
> "steps_per_print": 2000,
> "train_batch_size": "auto",
> "train_micro_batch_size_per_gpu": "auto",
> "wall_clock_breakdown": false
> ```
> 
> }


如果没记错的话应该是deepspeed官方的配置，已经不搞这块的工作了，记不清了，你可以尝试一下。
