### ISSUE TITLE
internlm-xcomposer2-7b-chat 使用 use_flash_attn  出现错误

### ISSUE THREAD

**Issue by fly-dragon211** [modelscope/ms-swift#2046]
**Describe the bug**
 internlm-xcomposer2-7b-chat 使用 use_flash_attn  出现错误

/anaconda3/envs/swift_official/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'InternLM2FlashAttention2' object has no attribute '_flash_attention_forward'

**Additional context**
CUDA_VISIBLE_DEVICES=2 swift infer --model_type internlm-xcomposer2-7b-chat  --dtype bf16    --use_flash_attn True

**Comment by fly-dragon211** [comment]
环境：
transformers 4.44.2
好像是 transformer 版本问题，https://github.com/InternLM/xtuner/issues/876，能不能更新一下 requirements.txtr

**Comment by Jintao-Huang** [comment]
> 环境： transformers 4.44.2 好像是 transformer 版本问题，[InternLM/xtuner#876](https://github.com/InternLM/xtuner/issues/876) 能不能更新一下 requirements.txtr

requirements.txt是所有模型的依赖，不进行更新的
