### ISSUE TITLE
数据预处理报错

### ISSUE THREAD

**Issue by zodiacg** [modelscope/ms-swift#2055]
**Describe the bug**
数据预处理过程中datasets库`_check_if_features_can_be_aligned`报错，情况和下面的PR完全一致：

https://github.com/modelscope/ms-swift/pull/1193

最后尝试的版本中2.3.2没有此问题，2.4.0/2.4.1均报错。稍微看了下好像最新的代码里没有类似处理，是逻辑大改过？

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
无关

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
逻辑最近有改动，但不确定是否有影响，能否发下具体的运行命令

**Comment by zodiacg** [comment]
用了自定义注册的数据集，参考价值可能不太大。
报错曾出现在自己处理的CogVLM-SFT-113K数据集（https://hf-mirror.com/datasets/THUDM/CogVLM-SFT-311K）和认知数据集上。CogVLM处理的时候把单轮和多轮混编，所以有样本没有history。

**Comment by tastelikefeet** [comment]
这个问题今天修复

**Comment by Jintao-Huang** [comment]
已经修复了 https://github.com/modelscope/ms-swift/pull/2088
