### ISSUE TITLE
llava video SFT BUG

### ISSUE THREAD

**Issue by evi-Genius** [modelscope/ms-swift#2060]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
自定义的视频数据集，格式类似于
{"query": "55555", "response": "66666", "videos": ["video_path"]}
进行SFT训练
![1](https://github.com/user-attachments/assets/dff21695-ec95-4260-a6b7-295a4664d164)
出错
![2](https://github.com/user-attachments/assets/c46ae218-ba5c-460e-8a2d-97f19600d033)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
transformer是4.45.0.dev0

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
使用transformers==4.44.*

**Comment by evi-Genius** [comment]
可以了，感谢
