### ISSUE TITLE
swift升级到2.4.0及以上版本后加载训练数据集报错

### ISSUE THREAD

**Issue by sunshine001** [modelscope/ms-swift#2083]
**Describe the bug**
swift从2.3.x升级到2.4.x以后，加载训练数据集时报如下错误（2.4.x以下版本不会）：
![9e9c14561b88697c7ed02b5b5bec0e7](https://github.com/user-attachments/assets/0316e092-007c-4c36-b82d-dee97791bf09)

**Additional context**
训练的模型是qwen2和qwen2.5

**Comment by Jintao-Huang** [comment]
fixed
