### ISSUE TITLE
Qwen2-VL 72B API推理错误

### ISSUE THREAD

**Issue by niuwa2333** [modelscope/ms-swift#2086]
部署API推理时，在load10个checkpoint后出错：safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

环境：torch 2.4
transformers：4.45.0.dev0

设备：用了4张A100 80G，设置tp=4 推理

**Comment by tastelikefeet** [comment]
参考：https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8123
重新下载模型试试

**Comment by Jintao-Huang** [comment]
safetensors文件有损坏
