### ISSUE TITLE
flash attention import报错

### ISSUE THREAD

**Issue by goodstudent9** [modelscope/ms-swift#2089]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
最开始inference的时候会出现warning：import flash_attn rotary fail
![image](https://github.com/user-attachments/assets/02ccd9ce-a6e8-45a7-805c-1d8b83654bf4)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
cuda：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
GPU：4090
torch：
Name: torch
Version: 2.4.0
系统：ubuntu 22.04

**Additional context**

**Comment by Jintao-Huang** [comment]
安装一下rotary https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
