### ISSUE TITLE
请问在padding media offset的时候用的数字是多少呢？

### ISSUE THREAD

**Issue by goodstudent9** [modelscope/ms-swift#2092]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
没有实现media offset的batch size=2的时候的训练，因为不同样本的该变量的长度不同。有的是122 有的是124
目前我看懂了代码，我可以自己实现一下，但是我恐怕需要知道您在训练的时候这个padding的字符是多少？
通过阅读你的代码，我看到了你提到当没有图片输入的时候，应该输入-10000
但是代码里实际写的是-1000000
![image](https://github.com/user-attachments/assets/be6faee7-f868-4068-a603-00fc6fe07099)
所以请问media offset的padding字符到底是什么呢？是-1000000吗？

**Comment by Jintao-Huang** [comment]
这是哪里的代码呀

**Comment by goodstudent9** [comment]
这是我从hugging face上面下载的。
![image](https://github.com/user-attachments/assets/bcc467dc-441f-4a6b-b39c-7338f32db519)

其实问题就是您的代码似乎在media_offset这里出现了bug，在batch>1的时候这个变量的padding无法正常进行, 我在尝试debug，自己去把padding字符加上去，但是目前好像还是失败了哈哈

**Comment by goodstudent9** [comment]
所以我还是想请问，您在训练的时候，那个media_offset的padding设置的是多少呢？&nbsp;


onlysword
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月22日(星期天) 晚上7:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [modelscope/ms-swift] 请问在padding media offset的时候用的数字是多少呢？ (Issue #2092)














 
这是哪里的代码呀

**Comment by Jintao-Huang** [comment]
我使用的是batch_size=1, 所以没有使用padding

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/issues/2064

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/issues/1969

**Comment by goodstudent9** [comment]
所以您在训练代码的时候，就从来没有使用过media offset的pading，因为mplugowl3就是在batchsize=1的情况下训练得到的对吗？

**Comment by Jintao-Huang** [comment]
> 所以您在训练代码的时候，就从来没有使用过media offset的pading，因为mplugowl3就是在batchsize=1的情况下训练得到的对吗？

我不是mplug-owl3模型的训练人员哈, 这个问题可能需要到mplug-owl3的github中进行讨论

**Comment by goodstudent9** [comment]
哦哦，再请教一个问题，就是他每次似乎都会下载使用的模型代码
![image](https://github.com/user-attachments/assets/304d666e-3c5a-49fe-9e62-932c46295108)
我尝试指定了本地的位置，通过如下的命令的--local_repo_path，但是似乎仍然没法改变，他仍然每次会使用下载下来的这个cache文件夹里面的东西。
```
CUDA_VISIBLE_DEVICES=0 NPROC_PER_NODE=1 swift sft \
  --model_type mplug-owl3-7b-chat \
  --model_id_or_path ./icc/mPLUG-Owl3-7B-240728 \
  --sft_type lora \
  --dataset coco-en-mini#20000 \
  --deepspeed default-zero2 \
  --output_dir output \
  --num_train_epochs 5 \
  --per_device_train_batch_size 1\
  --dataloader_num_workers 4 \
  --gradient_accumulation_steps 16 \
  --local_repo_path ./iic/mPLUG-Owl3-7B-240728
```

**Comment by Jintao-Huang** [comment]
请直接修改 ./icc/mPLUG-Owl3-7B-240728 中的代码. transformers会在每次运行时对transformers_modules进行覆盖
