### ISSUE TITLE
[rank1]: AttributeError: 'Qwen2FlashAttention2' object has no attribute '_flash_attention_forward'

### ISSUE THREAD

**Issue by zhangyuqi-1** [modelscope/ms-swift#2107]
FlashAttention的版本是不是有要求，应该用什么版本

目前我的环境如下：
- ms-swift version: 2.4.2
- flash_attn version: 2.5.8
- Python version: 3.10.14
- PyTorch version: 2.4.0+cu121 (GPU)
- Transformers version: 4.44.2
- Datasets version: 2.20.0
- Accelerate version: 0.32.1
- PEFT version: 0.12.0
- TRL version: 0.9.6
- GPU type: NVIDIA GeForce RTX 4090
- DeepSpeed version: 0.14.4
- Bitsandbytes version: 0.43.3
- vLLM version: 0.6.0

**Comment by Jintao-Huang** [comment]
报错截图发一下

**Comment by Jintao-Huang** [comment]
以及shell脚本

**Comment by zhangyuqi-1** [comment]
CUDA_VISIBLE_DEVICES=1,3 NPROC_PER_NODE=2 nohup swift sft --sequence_parallel_size '2' --use_liger 'True' --model_id_or_path '/isilon_ai_data/llm_model_hub/qwen/Qwen2-7B' --template_type 'qwen' --max_length '10000' --lora_target_modules k_proj v_proj gate_proj up_proj o_proj q_proj down_proj --init_lora_weights 'True' --learning_rate '0.0001' --num_train_epochs '6' --use_flash_attn 'True' --gradient_accumulation_steps '8' --eval_steps '100' --save_steps '100' --output_dir '/data1/zhangyq/medical-item-extract/loras' --neftune_noise_alpha '5' --custom_train_dataset_path /data1/zhangyq/medical-item-extract/data/train.jsonl --custom_val_dataset_path /data1/zhangyq/medical-item-extract/data/dev.jsonl --eval_batch_size '1' --model_type 'qwen2-7b'  --add_output_dir_suffix False --output_dir /data1/zhangyq/medical-item-extract/loras/qwen2-7b/v0-20240924-112139 --logging_dir /data1/zhangyq/medical-item-extract/loras/qwen2-7b/v0-20240924-112139/runs --ignore_args_error True > /data1/zhangyq/medical-item-extract/loras/qwen2-7b/v0-20240924-112139/runs/run.log 2>&1 &

**Comment by zhangyuqi-1** [comment]
> 以及shell脚本

**Comment by zhangyuqi-1** [comment]
> 报错截图发一下

[rank1]:     result = forward_call(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/accelerate/utils/operations.py", line 819, in forward
[rank1]:     return model_forward(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/accelerate/utils/operations.py", line 807, in __call__
[rank1]:     return convert_to_fp32(self.model_forward(*args, **kwargs))
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 43, in decorate_autocast
[rank1]:     return func(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/peft/peft_model.py", line 1577, in forward
[rank1]:     return self.base_model(
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 188, in forward
[rank1]:     return self.model.forward(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/liger_kernel/transformers/model/qwen2.py", line 81, in lce_forward
[rank1]:     outputs = self.model(
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 904, in forward
[rank1]:     layer_outputs = self._gradient_checkpointing_func(
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/swift/llm/utils/model.py", line 6498, in <lambda>
[rank1]:     _old_checkpoint(*args, use_reentrant=use_reentrant, **kwargs))
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/_compile.py", line 31, in inner
[rank1]:     return disable_fn(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 600, in _fn
[rank1]:     return fn(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 488, in checkpoint
[rank1]:     ret = function(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 655, in forward
[rank1]:     hidden_states, self_attn_weights, present_key_value = self.self_attn(
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/xtuner/model/modules/dispatch/qwen2.py", line 160, in qwen2_attn_forward
[rank1]:     attn_output = self._flash_attention_forward(
[rank1]:   File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
[rank1]:     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[rank1]: AttributeError: 'Qwen2FlashAttention2' object has no attribute '_flash_attention_forward'


Train:   0%|          | 0/1098 [00:02<?, ?it/s]
W0924 11:22:20.025000 140296928438080 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 4133547 closing signal SIGTERM
E0924 11:22:20.088000 140296928438080 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 4133546) of binary: /data1/zhangyq/miniforge3/envs/py310/bin/python
Traceback (most recent call last):
  File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/distributed/run.py", line 905, in <module>
    main()
  File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/data1/zhangyq/miniforge3/envs/py310/lib/python3.10/site-packages/swift/cli/sft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-24_11:22:20
  host      : gpu-15.ld-hadoop.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4133546)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by Jintao-Huang** [comment]
请给xtuner提个issue哈

**Comment by zhangyuqi-1** [comment]
> 请给xtuner提个issue哈

好滴
