### ISSUE TITLE
RuntimeError: self and mat2 must have the same dtype, but got Half and Float

### ISSUE THREAD

**Issue by LIUKAI0815** [modelscope/ms-swift#2124]
官方文档里的微调内容：如果想要对awq、gptq量化的模型进行qlora微调，你需要进行提前量化。例如可以对原始模型使用swift export进行量化。然后使用以下命令进行微调，你需要指定--quant_method来指定对应量化的方式：
CUDA_VISIBLE_DEVICES=0 swift sft \
    --model_type qwen1half-7b-chat \
    --model_id_or_path qwen1half-7b-chat-awq-int4 \
    --quant_method awq \
    --sft_type lora \
    --dataset alpaca-zh#5000 \

本地的微调代码：CUDA_VISIBLE_DEVICES=3 \
    MASTER_PORT=20005 \
    NPROC_PER_NODE=1 \
    swift sft \
    --quant_method awq \
    --sft_type lora \
    --model_type qwen2_5-7b-instruct-awq \
    --model_id_or_path /workspace/model/llm/Qwen/Qwen2_5-7B-Instruct-AWQ \
    --dataset /workspace/data/llm/rewrite_and_classify/train_total_rewrite_0914.jsonl \
    --output_dir /workspace/output/nlp_rewrite/qwen \
    --system """You are a helpful dialogue rewriter""" \
    --num_train_epochs 2 \
    --batch_size 8 \
    --use_flash_attn True \
    --use_liger True \

报错内容：
The input hidden states seems to be silently casted in float32, this might be related to the fact you have upcasted embedding or layer norm layers in float32. We will cast back the input in torch.float16.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/model/server/swift/swift/cli/sft.py", line 5, in <module>
[rank0]:     sft_main()
[rank0]:   File "/workspace/model/server/swift/swift/utils/run_utils.py", line 32, in x_main
[rank0]:     result = llm_x(args, **kwargs)
[rank0]:   File "/workspace/model/server/swift/swift/llm/sft.py", line 506, in llm_sft
[rank0]:     return trainer_train(args, model, template, train_dataset, val_dataset, callbacks=callbacks, msg=msg)
[rank0]:   File "/workspace/model/server/swift/swift/llm/sft.py", line 456, in trainer_train
[rank0]:     trainer.train(training_args.resume_from_checkpoint)
[rank0]:   File "/workspace/model/server/swift/swift/trainers/mixin.py", line 424, in train
[rank0]:     res = super().train(resume_from_checkpoint, *args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 2279, in _inner_training_loop
[rank0]:     tr_loss_step = self.training_step(model, inputs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 3318, in training_step
[rank0]:     loss = self.compute_loss(model, inputs)
[rank0]:   File "/workspace/model/server/swift/swift/trainers/trainers.py", line 161, in compute_loss
[rank0]:     outputs = model(**inputs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1593, in forward
[rank0]:     else self._run_ddp_forward(*inputs, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1411, in _run_ddp_forward
[rank0]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1582, in _call_impl
[rank0]:     result = forward_call(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 819, in forward
[rank0]:     return model_forward(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 807, in __call__
[rank0]:     return convert_to_fp32(self.model_forward(*args, **kwargs))
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/peft/peft_model.py", line 1430, in forward
[rank0]:     return self.base_model(
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 179, in forward
[rank0]:     return self.model.forward(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/liger_kernel/transformers/model/qwen2.py", line 108, in lce_forward
[rank0]:     loss = lce(self.lm_head.weight, shift_hidden_states, shift_labels)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/liger_kernel/transformers/fused_linear_cross_entropy.py", line 13, in forward
[rank0]:     return LigerFusedLinearCrossEntropyFunction.apply(
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/autograd/function.py", line 598, in apply
[rank0]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/liger_kernel/ops/fused_linear_cross_entropy.py", line 117, in forward
[rank0]:     torch.addmm(
[rank0]: RuntimeError: self and mat2 must have the same dtype, but got Half and Float
Train:   0%|          | 20/4386 [01:06<4:03:26,  3.35s/it]
E0925 16:42:55.534000 139835677235008 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 178006) of binary: /root/miniconda3/envs/swift/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/swift/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/swift/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in <module>
    main()
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/workspace/model/server/swift/swift/cli/sft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-25_16:42:55
  host      : 4f02e20d4ced
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 178006)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by ManjunXiong** [comment]
大佬问题解决了么

**Comment by slin000111** [comment]
尝试--use_liger False

**Comment by LIUKAI0815** [comment]
> 大佬问题解决了么

--use_liger False

**Comment by LIUKAI0815** [comment]
@slin000111 感谢，False可以了
