### ISSUE TITLE
Support Molmo 7B/72B

### ISSUE THREAD

**Issue by TheDuckingDuck** [modelscope/ms-swift#2143]
The models just released yesterday and claim incredible performance, leaving L3_2 in the dirt.
https://molmo.allenai.org/blog

The [7B-D](https://www.modelscope.cn/models/llm-research/molmo-7b-d-0924) and [72B](https://www.modelscope.cn/models/llm-research/molmo-72b-0924) are based on Qwen2 7B and Qwen2 72B respectively, using OAI ViT-L/14.

I'd really like to test training them for my use-cases, to see how these benchmarks hold up.

Thank you for your time.

**Comment by Jintao-Huang** [comment]
supported

**Comment by thesby** [comment]
How to finetune molmo? Could you please give a tutorial? And  molmo support `point` type output, how to finetune this?

**Comment by mi804** [comment]
> How to finetune molmo? Could you please give a tutorial? And molmo support `point` type output, how to finetune this?

examples to run lora sft on molmo-7d-d:
``` shell
CUDA_VISIBLE_DEVICES=0 swift sft --model_type molmo-7b-d --sft_type lora --dataset coco-en-mini#20000
```
As Allen AI has not released the `point` demo and the PixMo dataset, we do not know exactly how to finetune `point` task. We have infered the `point` task in molmo-7b-d, the example is as below. As for finetune, construct such `input-output` samples might work.
``` shell
<<< <image> point to the eyes
Input an image path or URL <<< http://modelscope-open.oss-cn-hangzhou.aliyuncs.com/images/cat.png

<points x1="41.0" y1="43.0" x2="66.5" y2="41.7" alt="eyes">eyes</points>
--------------------------------------------------
<<< <<< 
```

**Comment by thesby** [comment]
Thank you. According to `huggingface repo`, the value of x y should be preprocessed.
https://huggingface.co/allenai/Molmo-7B-O-0924/discussions/1#66f47d79a4f47d65558a79ca

**Comment by pbarker** [comment]
has anyone gotten this to work with full finetuning? I've tried all the tricks and even with 8 A100s it OOMs
