### ISSUE TITLE
微调 Qwen2-VL-2B 设置不同的 lora_target_modules 时显存占用相同

### ISSUE THREAD

**Issue by Betty-J** [modelscope/ms-swift#2144]
您好，我拉取了最新的 ms-swift代码并将 transformer 中的 Qwen2-vl 代码更到最新，进行微调后发现设置 `lora_target_modules `分别为 `DEFAULT` 和 `ALL` 时，显存占用是相同的，memory 大致为9G。使用旧版代码微调时，同样的模型设置`lora_target_modules = ALL` 时 memory 在 17G 左右，请问是哪些更改导致的呢

**Comment by Jintao-Huang** [comment]
加了动态gradient_checkpointing

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/blob/3cf3f9f3f6e39724e2a3d3da4fc14a19f884de16/swift/llm/utils/utils.py#L470
