### ISSUE TITLE
How to SFT with customized datasets

### ISSUE THREAD

**Issue by YerongLi** [modelscope/ms-swift#2150]
Are there any docs for customized datasets? I am looking into this

https://github.com/modelscope/ms-swift/blob/main/swift/llm/utils/dataset.py

**Comment by Jintao-Huang** [comment]
https://swift.readthedocs.io/zh-cn/latest/Instruction/%E6%94%AF%E6%8C%81%E7%9A%84%E6%A8%A1%E5%9E%8B%E5%92%8C%E6%95%B0%E6%8D%AE%E9%9B%86.html
