### ISSUE TITLE
ValueError: Mixed using with peft is not allowed now

### ISSUE THREAD

**Issue by thesby** [modelscope/ms-swift#2152]
**Describe the bug**

```
swift export \
    --ckpt_dir /home/xxx/projects/xxx/output/qwen2-vl-7b-instruct/v4-20240928-154546 \
    --merge_lora true
```
Error info: ValueError: Mixed using with peft is not allowed now.

I train a lora of `Qwen/Qwen2-VL-7B-Instruct-AWQ`, and try to merge lora, the error happens.

**Comment by Jintao-Huang** [comment]
--ckpt_dir /home/xxx/projects/nude_girl/output/qwen2-vl-7b-instruct/v4-20240928-154546/checkpoint-xxx
