### ISSUE TITLE
Using customized dataset evaluation ends with lookup error

### ISSUE THREAD

**Issue by mianbaoji** [modelscope/ms-swift#2153]
**Describe the bug**
Suffer bug when run swfit eval command.
`swift eval --model_id_or_path '/root/model/' --model_type 'qwen2_5-1_5b-instruct' --eval_dataset no --custom_eval_config /root/data/config_eval.json --max_length 4096 --eval_limit 2`
Using "general_qa" type local configuration.
`[
    {
        "name": "nl2sql_test",
        "pattern": "general_qa",
        "dataset": "/root/data/",
        "subset_list": ["test"]
    }
]`

 

**Your hardware and system info**
LInux CentOS, only CPU, not GPU installed. Python 3.10 with latest swfit.eval and evalscope.

bug info:
![image](https://github.com/user-attachments/assets/7ac8f7bb-a11d-4bae-933a-b735b8246cb9)
![image](https://github.com/user-attachments/assets/cd0e3769-0760-4aef-b631-7871f91227c7)

**Comment by mianbaoji** [comment]
英文测试用例该问题必现

**Comment by wangxingjun778** [comment]
原因： nltk包需要依赖punkt_tab.zip文件作为tokenizer，有些环境从nltk官方源下载该文件会出现错误，这里提供两个解决方案：

1. 临时方案： 先 wget https://modelscope-open.oss-cn-hangzhou.aliyuncs.com/open_data/nltk_data/punkt_tab.zip ，然后解压到 ~/nltk_data/tokenizers/ 路径下

3. 正式方案： pip3 install evalscope>=0.5.5rc1   0.5.5rc1或以上版本已经添加了自动下载  （确保nltk>=3.9）
