### ISSUE TITLE
官方DEMO不好使?

### ISSUE THREAD

**Issue by BenLampson** [modelscope/ms-swift#2159]
跳过了N个步骤,已经安装好docker,直接输入
![image](https://github.com/user-attachments/assets/1c1edca5-d9c0-4034-a1b1-5802c0fc1c19)
理论上预期应该是报错文件,模型之类的未找到,实际报错
![image](https://github.com/user-attachments/assets/4a4ad110-badd-400f-8af1-87f5dad7320e)

使用的docker镜像为
![image](https://github.com/user-attachments/assets/ca19adaa-aae3-4a5d-a35c-1ee3da8d03f2)

**Comment by Jintao-Huang** [comment]
有截图嘛

**Comment by BenLampson** [comment]
您需要哪里的截图，我提问里头的如果不够您说，我目前还未修复，感觉是依赖版本不正确，但是由于是直接docker拉的，也不知道怎么个升级顺序了

**Comment by BenLampson** [comment]
![image](https://github.com/user-attachments/assets/d9735cb7-806a-416e-9982-b2d86bf69a0e)
webui 也启动不了

**Comment by Jintao-Huang** [comment]
pip install ms-swift[llm] -U
