### ISSUE TITLE
是否支持图像的在线数据增强

### ISSUE THREAD

**Issue by ninghaiywx** [modelscope/ms-swift#2168]
我想要在训练的时候在线对图像做数据增强，目前还没找到可以提供这个功能的参数和入口。

**Comment by 24-solar-terms** [comment]
@ninghaiywx 请问您找到了吗，我这边也希望做在线数据增强

**Comment by ninghaiywx** [comment]
没有，后来是改了源码做的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年3月6日(周四) 晚上7:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [modelscope/ms-swift] 是否支持图像的在线数据增强 (Issue #2168)


   
@ninghaiywx 请问您找到了吗，我这边也希望做在线数据增强

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
  24-solar-terms left a comment (modelscope/ms-swift#2168)
 
@ninghaiywx 请问您找到了吗，我这边也希望做在线数据增强
