### ISSUE TITLE
Can we support fp 16 and bf16 in training

### ISSUE THREAD

**Issue by YerongLi** [modelscope/ms-swift#2170]
**Describe the feature**

Can we support in the training workflow? Low precision helps us saves GPU RAM
```
--fp16 True
--bf16 True
```
**Paste any useful information**

For example Llava-onevision supports **bf16**
https://github.com/LLaVA-VL/LLaVA-NeXT/blob/main/scripts/train/finetune_ov.sh

**Comment by Jintao-Huang** [comment]
--dtype bf16
