### ISSUE TITLE
Image scaling issues with DeepSeek-vl-1.3b

### ISSUE THREAD

**Issue by xiang-xiang-zhu** [modelscope/ms-swift#2171]
i use this script fine tuning

```
CUDA_VISIBLE_DEVICES=0 swift sft \
    --model_type deepseek-vl-1_3b-chat \
    --dataset customdataset.json
```
When I started infering I noticed that the picture seemed to be scaled after inputting it into the model, the reason for this was because I was doing a grounding task and I noticed that the bouding box output from the model was the right shape but the position was off. I have tried several examples of this problem, what should I do to get this scaling? So that I can restore the coordinate box back to the correct position.
I've tried just dividing the width and height of the box by the ground truth to get the scaling, but this just results in making the bounding box even more strange.

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/blob/7594d19188cf2fd6f592b0216ccd421179616b38/swift/llm/utils/template.py#L3077C9-L3077C23
