### ISSUE TITLE
docker로 사용하고 싶은데 어떻게 사용해야하는지 모르겠어요 

### ISSUE THREAD

**Issue by daje0601** [modelscope/ms-swift#2178]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

I can't find the image on dockerhub, and the docker buildfile is not found in ms-swift.
How can I use ms-swift with a docker image?

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by yingdachen** [comment]
checkout the doc here: and let us know if you have specific question.

https://swift.readthedocs.io/en/latest/
