### ISSUE TITLE
求助！使用vllm在internvl2评测自制数据集时报错

### ISSUE THREAD

**Issue by NancyFyong** [modelscope/ms-swift#2182]
在使用vllm进行评测自制的数据集时会报错，但是用pt格式并不会，而且很奇怪的是如果用benchmark的数据集vllm会很流畅。
具体报错如下：
先是提示没有这个参数
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/984dfc5a-1828-4741-9201-e59820f58bae">
于是我把这个参数删除之后又提示
<img width="1322" alt="image" src="https://github.com/user-attachments/assets/cedeb20a-0681-4f69-969d-db81f24be993">

我的版本是
vllm-0.6.2
transformers-4.50
CUDA版本12.1
torch-2.4.0
GPU是a100-40G

非常感谢！

**Comment by slin000111** [comment]
vllm也可以，测试命令行如下：
```shell
swift eval --model_type internvl2-8b --eval_dataset no --infer_backend vllm --custom_eval_config eval_example/custom_config.json
```
自定义评测数据集格式，[LLM评测文档](https://swift.readthedocs.io/zh-cn/latest/Instruction/LLM%E8%AF%84%E6%B5%8B%E6%96%87%E6%A1%A3.html#id6)
环境：
vllm                              0.6.3.post1
ms-swift                          2.6.0.dev0
transformers                      4.45.2
