### ISSUE TITLE
media key for custom dataset is not added to empty_row

### ISSUE THREAD

**Issue by SepehrV** [modelscope/ms-swift#2185]
**Describe the bug**
`KeyError: images`
in here
https://github.com/modelscope/ms-swift/blob/main/swift/llm/utils/preprocess.py#L69

to reproduce
```
    swift sft \
    --model_type qwen2-vl-7b-instruct \
    --model_id_or_path qwen/Qwen2-VL-2B-Instruct \
    --sft_type lora \
    --dataset swift/llava-med-zh-instruct-60k#2000
```

This is the root cause:
https://github.com/modelscope/ms-swift/blob/main/swift/llm/utils/preprocess.py#L130

`media_name` is not being added to `empty_rows`.

Is a there a reason for having `not` in that condition? 
if modified to this it works fine:
```
        if self.media_type and isinstance(self.media_key, str):
            empty_row[self.media_name] = None
```

**Comment by Jintao-Huang** [comment]
fixed
