### ISSUE TITLE
Does it support grounding, OCR, Video hybrid fine-tuning training?

### ISSUE THREAD

**Issue by WangRongsheng** [modelscope/ms-swift#2186]
I see a lot of single-task fine-tuning examples [here](https://github.com/modelscope/ms-swift/blob/main/docs/source/Multi-Modal/qwen2-vl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md), so can I ask if there is support for hybrid fine-tuning training for grounding, OCR, and Video?

**Comment by Jintao-Huang** [comment]
Supported

**Comment by WangRongsheng** [comment]
thank, you!
