### ISSUE TITLE
Notebook for Continue Pretraining

### ISSUE THREAD

**Issue by msamwelmollel** [modelscope/ms-swift#2190]
**Describe the feature**
Please describe the feature requested here(请在这里描述需求
Is there a Notebook for complete pretraining? And I have seen in some of finetune notebook  there is no end of token append at the end of text is that normal?

**Comment by tastelikefeet** [comment]
1. No we don't have a Notebookfor complete pretraining, but instead we have a doc: 
https://swift.readthedocs.io/en/latest/Instruction/LLM-fine-tuning.html
https://swift.readthedocs.io/en/latest/LLM/Megatron-training.html
2. Most models should have an eos_token to append to the end of the text
