### ISSUE TITLE
train two models on the two gpus in one mechine at the same time will cause "address already in use".

### ISSUE THREAD

**Issue by ycwfs** [modelscope/ms-swift#2192]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

Just Lora sft two different models with two GPUs:
NFRAMES=24 MAX_PIXELS=100352 CUDA_VISIBLE_DEVICES=0 NPROC_PER_NODE=1 swift sft --model_type qwen2-vl-7b-instruct   --model_id_or_path /data1/cache/huggingface/hub/models--Qwen--Qwen2-VL-7B-Instruct/snapshots/3ca981c995b0ce691d85d8408216da11ff92f690   --sft_type lora   --lora_target_modules ALL   --lora_rank 16   --seed 3407   --warmup_ratio 0.05   --dataset /data1/code/helping/sft_simple_data.jsonl   --use_flash_attn true   --eval_steps 5000   --num_train_epochs 1

CUDA_VISIBLE_DEVICES=1 NPROC_PER_NODE=1 swift sft    --model_type qwen2-vl-7b-instruct    --model_id_or_path /data1/cache/huggingface/hub/models--Qwen--Qwen2-VL-7B-Instruct/snapshots/3ca981c995b0ce691d85d8408216da11ff92f690    --sft_type lora    --lora_target_modules ALL    --lora_rank 16    --seed 3407    --warmup_ratio 0.05    --dataset /data1/code/detect_change_ocr/aug_output.jsonl --eval_step 10000000 --use_flash_attn true --save_steps 50 --save_total_limit 5    --system "You are a helpful assistant for detecting and localizing tampered regions in images" --resume_only_model true --resume_from_checkpoint /data1/code/detect_change_ocr/data/output/qwen2-vl-7b-instruct/v17-20240923-142011/checkpoint-63148

the second command will cause the error.

`RuntimeError: The server socket has failed to listen on any local network address. useIpv6: 0, code: -98, name: EADDRINUSE, message: address already in use`

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by marvlyngkhoi** [comment]
How was this issue solved??

**Comment by samaritan1998** [comment]
同问

**Comment by Gary-code** [comment]
sh文件加上
export MASTER_PORT=空出来的端口号即可
