### ISSUE TITLE
AttributeError: 'OmniSpeech2SLlamaForCausalLM' object has no attribute '_get_logits_warper'. Did you mean: '_get_logits_processor'?

### ISSUE THREAD

**Issue by satheeshkola-532** [modelscope/ms-swift#2194]
when i tried to  infer the llama-omni s2s language model, getting the following error on giving the audio input, also same thing happend when tried using code.

**AttributeError: 'OmniSpeech2SLlamaForCausalLM' object has no attribute '_get_logits_warper'. Did you mean: '_get_logits_processor'?**

![image (7)](https://github.com/user-attachments/assets/b7813c26-4328-4b4d-aad0-09a0d58573ae)

**Comment by Jintao-Huang** [comment]
Please try lowering the transformers version, e.g. 4.44.

**Comment by satheeshkola-532** [comment]
> Please try lowering the transformers version, e.g. 4.44.

thank you, that error resolved but i am facing another issue which is that it's giving blank response as show in the image(even though i tried with the given examples), please let me know if there's any way to solve it and also i would like to get the python script for inference using swift,
thank you!
![omni](https://github.com/user-attachments/assets/f244f7f6-b486-4559-8f93-e0b92c1ba6d3)

**Comment by satheeshkola-532** [comment]
> Please try lowering the transformers version, e.g. 4.44.

**Now the checkpoints are not even loading.., throwing error as follows:**
[INFO:swift] local_repo_path: /home/satheesh/.cache/modelscope/hub/_github/LLaMA-Omni
[INFO:swift] model_kwargs: {'device_map': None, 'low_cpu_mem_usage': True}
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
/home/satheesh/.local/lib/python3.10/site-packages/whisper/__init__.py:146: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)
/home/satheesh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2068: UserWarning: for encoder.conv1.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/satheesh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2068: UserWarning: for encoder.conv1.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
Traceback (most recent call last):
  File "/home/satheesh/fine-tuning/swift/swift/cli/infer.py", line 5, in <module>
    infer_main()
  File "/home/satheesh/fine-tuning/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/home/satheesh/fine-tuning/swift/swift/llm/infer.py", line 305, in llm_infer
    model, template = prepare_model_template(args, device_map=args.device_map_config)
  File "/home/satheesh/fine-tuning/swift/swift/llm/infer.py", line 183, in prepare_model_template
    model, tokenizer = get_model_tokenizer(
  File "/home/satheesh/fine-tuning/swift/swift/llm/utils/model.py", line 6842, in get_model_tokenizer
    model, tokenizer = get_function(model_dir, torch_dtype, model_kwargs, load_model, **kwargs)
  File "/home/satheesh/fine-tuning/swift/swift/llm/utils/model.py", line 6665, in get_model_tokenizer_omnli
    model, tokenizer = get_model_tokenizer_with_flash_attn(model_dir, torch_dtype, model_kwargs, load_model, **kwargs)
  File "/home/satheesh/fine-tuning/swift/swift/llm/utils/model.py", line 2738, in get_model_tokenizer_with_flash_attn
    return get_model_tokenizer_from_repo(
  File "/home/satheesh/fine-tuning/swift/swift/llm/utils/model.py", line 1015, in get_model_tokenizer_from_repo
    model = automodel_class.from_pretrained(
    
![image](https://github.com/user-attachments/assets/badea466-996b-4d19-9677-9f70e6c531f6)

**Comment by satheeshkola-532** [comment]
> > Please try lowering the transformers version, e.g. 4.44.
> 
> thank you, that error resolved but i am facing another issue which is that it's giving blank response as show in the image(even though i tried with the given examples), please let me know if there's any way to solve it and also i would like to get the python script to inference using swift, thank you! ![omni](https://private-user-images.githubusercontent.com/179837971/373879585-f244f7f6-b486-4559-8f93-e0b92c1ba6d3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNjk2ODQsIm5iZiI6MTcyODM2OTM4NCwicGF0aCI6Ii8xNzk4Mzc5NzEvMzczODc5NTg1LWYyNDRmN2Y2LWI0ODYtNDU1OS04ZjkzLWUwYjkyYzFiYTZkMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwNjM2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYmQ3NDdjYzliOTFhM2QxYjE5YjA2NTk0M2E2NmFmYzhmMjJmNWNkODk3YWQ1MTlmZTU1Y2VmNDdlNzEyNTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FK1urlpPUYyqYPnutzskrIIuUbXuaIk2cSa3JmWN8Sg)

@Jintao-Huang  Any update on this issue?

**Comment by Jintao-Huang** [comment]
let me check. The holiday has just ended.

**Comment by satheeshkola-532** [comment]
> fixed

thank you @Jintao-Huang , it is generating text responses only on giving audio input but not both the text response and audio output ? Actually llama omni model generates both text and audio responses simultaneously right? Is there any way to achieve this?
