### ISSUE TITLE
qwen2-vl-72b lora微调 ，不支持纯文本指令和图片指令数据混合训练？

### ISSUE THREAD

**Issue by Luccadoremi** [modelscope/ms-swift#2198]
纯文本指令和图片指令数据混合训练会卡死，请问后续是否会支持？

训练脚本如下
######################################

SIZE_FACTOR=6 MAX_PIXELS=602112 \
NPROC_PER_NODE=6 CUDA_VISIBLE_DEVICES=0,3,4,5,6,7 \
swift sft \
  --model_type qwen2-vl-72b-instruct \
  --model_id_or_path ./hf/qwen2-vl-72b-instruct \
  --output_dir output/qwen2-vl-72b-instruct-$train_type \
  --sft_type lora \
  --custom_dataset_info mydata.json \
  --dataset $data \
  --max_length $maxl \
  --dtype fp16 \
  --batch_size 1 \
  --check_dataset_strategy warning \
  --use_flash_attn True \
  --truncation_strategy delete \
  --deepspeed default-zero3 \

**Comment by Jintao-Huang** [comment]
please use main branch

**Comment by Wu0409** [comment]
我也遇到了同样的问题，请问下您解决了吗？

**Comment by Jintao-Huang** [comment]
最新的main分支已经修复了 最近1/2天会发版本

**Comment by llp1992** [comment]
最新分支训练还是会卡死
