### ISSUE TITLE
package installation help: swift with transformers, deepspeed, flash-attention, vllm, etc 

### ISSUE THREAD

**Issue by Li-Jicheng** [modelscope/ms-swift#2202]
Can anyone suggest me versions for the package below? I always encounter package conflicts. I'm using cuda 11.8 btw. Thanks a lot!

1. ms-swift
2. torch 
3. torchvision
4. deepspeed
5. flash-attn
6. vllm

**Comment by Jintao-Huang** [comment]
Just use the latest ones.
