### ISSUE TITLE
qwen2 72B vl部署推理服务报错

### ISSUE THREAD

**Issue by zhangfan-algo** [modelscope/ms-swift#2204]
**Describe the bug**
![image](https://github.com/user-attachments/assets/9df8f8fa-6769-4da7-97cb-d532f94b0f3c)

**Comment by Jintao-Huang** [comment]
什么版本的vllm和ms-swift

**Comment by zhangfan-algo** [comment]
> 什么版本的vllm和ms-swift

重新装了一下又有新的报错 
![image](https://github.com/user-attachments/assets/4151d1a6-155d-48b4-8cd3-149d0d7a4b35)

**Comment by zhangfan-algo** [comment]
vllm:0.6.3.dev125+g8c746226.cu123   源码安装的

**Comment by zhangfan-algo** [comment]
ms-swift 是 2.5.0.dev0

**Comment by Jintao-Huang** [comment]
https://github.com/vllm-project/vllm/pull/9105

**Comment by Jintao-Huang** [comment]
fixed
