### ISSUE TITLE
qwenvl2-72b-instruct-awq finetune 报错  [rank7]: NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by ljqnb** [modelscope/ms-swift#2208]
![image](https://github.com/user-attachments/assets/192e2ea8-b9ad-4ceb-b0a3-94527a6d53a0)
USE_HF=1 torchrun --nnodes=1 --nproc_per_node=8 --master_addr=localhost --master_port=6105 swift/swift/cli/sft.py \
    --model_type ${MODEL_TYPE} \
    --dtype fp16 \
    --sft_type lora \
    --template_type AUTO \
    --output_dir ${LOG_DIR} \
    --num_train_epochs 1 \
    --per_device_train_batch_size  4  \
    --per_device_eval_batch_size  4  \
    --max_length 16384 \
    --save_strategy epoch \
    --learning_rate ${LR} \
    --lora_target_modules ALL \
    --use_flash_attn True \
    --gradient_accumulation_steps  4  \
    --dataset dreambench_plus/dpo_data/sft_dreambench_plus_new_initprompt_train.json \
    --val_dataset dreambench_plus/dpo_data/sft_dreambench_plus_new_initprompt_eval.json \
    --eval_strategy epoch \
    --deepspeed default-zero3 \

**Comment by Jintao-Huang** [comment]
什么卡跑的呀

**Comment by ljqnb** [comment]
a100-80g

**Comment by tastelikefeet** [comment]
per_device_train_batch_size=1 吧，显存爆炸了
