### ISSUE TITLE
 Question about auto_find_batch_size.

### ISSUE THREAD

**Issue by lluo-Desktop** [modelscope/ms-swift#2209]
Hi,
      I'm confused with input parameter "auto_find_batch_size" and can't not find any code and example about it.
      When auto_find_batch_size is set ture, is the defualt batch_size=1 going to be changed later? What log can be traced to check the final batch size ?

**Comment by tastelikefeet** [comment]
Yes
This feature comes from transformers, you can set a bigger batch size, like 256, this parameter will try to find a  proper batch_size as big as possible

**Comment by lluo-Desktop** [comment]
> Yes This feature comes from transformers, you can set a bigger batch size, like 256, this parameter will try to find a proper batch_size as big as possible

That helps!  Thanks!
