### ISSUE TITLE
关于自定义数据集的问题

### ISSUE THREAD

**Issue by mzgcz** [modelscope/ms-swift#2218]
我在使用ms-swift sft精调Qwen2.5模型时，使用了如下数据集格式
```json
{"text": "aaa", "lable": "1"}
{"text": "bbb", "lable": "2"}
{"text": "ccc", "lable": "3"}
```
训练成功且没有报错，后来看文档介绍，说"text"用于额外的数据预训练，"lable"用于KTO

目前比较疑惑，上面所使用的数据集格式正确吗？精调出的结果是个啥？

**Comment by tastelikefeet** [comment]
要看你的任务，如果是基于KTO的对齐，那就需要label，如果是预训练，就是response字段

**Comment by mzgcz** [comment]
@tastelikefeet 
预训练数据集要写成下面这样吧？
```
{"text": "aaa", "response": "1"}
{"text": "bbb", "response": "2"}
{"text": "ccc", "response": "3"}
```

如果是微调，数据集是不是这样：
```
{"query": "aaa", "response": "1"}
{"query": "bbb", "response": "2"}
{"query": "ccc", "response": "3"}
```

**Comment by Jintao-Huang** [comment]
预训练：
```
{"response": "1"}
{"response": "2"}
{"response": "3"}
```

**Comment by 1571859588** [comment]
你好，请问是根据{"text": "ccc", "lable": "3"}这样的格式构造一个json格式的数据集之后直接通过cli的--dataset 就可以了吗？我在构造DPO的时候通过文档写的三种方式都没有调用成功我的自定义数据集，请问如何解决
