### ISSUE TITLE
Incorrect parameters in the rescale_image function

### ISSUE THREAD

**Issue by hwei-hw** [modelscope/ms-swift#2219]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
 During inference (qwen2-vl), I set the parameter `rescale_image` to resize images to 512*384, as follows:
`template = get_template(template_type, tokenizer, rescale_image=196608) # 196608=512*384`

This parameter will be used in the following function:
```python
# swift/llm/utils/vision_utils.py
def rescale_image(img: 'PIL.Image.Image', rescale_image: int = -1) -> 'PIL.Image.Image':
    import torchvision.transforms as T
    width = img.width
    height = img.height
    if rescale_image <= 0 or width * height <= rescale_image:
        return img

    ratio = width / height
    height_scaled = math.pow(rescale_image / ratio, 0.5)
    width_scaled = height_scaled * ratio
    return T.Resize((int(width_scaled), int(height_scaled)))(img)
```

The bug is found in the last row: `T.Resize((int(width_scaled), int(height_scaled)))(img)`. 

Based on the doc of the `torch.transforms.Resize`: 
![image](https://github.com/user-attachments/assets/199af8f1-fdb8-4f15-8df8-a2fb31452969)

The correct implementation should be: `T.Resize((int(hight_scaled), int(width_scaled)))(img)` (Swap the positions of two parameters).

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

```text
CUDA: 12.5
System: Linux user-ESC8000A-E11 6.8.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
GPU: A6000(48GB)
Torch: 2.4.0
Torchversion: 0.19.0
ms-swift: 2.5.0.dev0
```

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

No

**Comment by tastelikefeet** [comment]
Fixed by #2223
