### ISSUE TITLE
swift infer only uses 1 GPU 

### ISSUE THREAD

**Issue by SepehrV** [modelscope/ms-swift#2221]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
when using `swift infer` with vllm backend, only one GPU is being utilized

```
NFRAMES=6 MAX_PIXELS=100352 CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 swift infer --infer_backend vllm ...
```

<img width="738" alt="Screenshot 2024-10-10 at 2 34 36 PM" src="https://github.com/user-attachments/assets/b4d96457-bc5b-4b58-96c4-bd979eba6e92">

**Your hardware and system info**
NVIDIA-SMI 535.161.08, Driver Version: 535.161.08 ,  CUDA Version: 12.2 , torch:2.4.1

**Comment by Jintao-Huang** [comment]
https://swift.readthedocs.io/zh-cn/latest/Instruction/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.html#vllm
