### ISSUE TITLE
data parallel training error : RuntimeError: value cannot be converted to type int without overflow

### ISSUE THREAD

**Issue by lluo-Desktop** [modelscope/ms-swift#2224]
Hi, 
    I am finetuning florence2 on my own dataset and it works with 1 gpu.
    But when I run data parallel training with script:

NPROC_PER_NODE=2 \
MASTER_PORT=65318 \
CUDA_VISIBLE_DEVICES=0,1 \
swift sft \
    --model_type florence-2-base-ft \
    --model_id_or_path ./checkpoints/Florence-2-base-ft \
    --dataset lvis-region-detect \
    --sft_type full \
    --batch_size 256 \
    --auto_find_batch_size true \
    --freeze_vit true \
    --tuner_backend peft \
    --template_type AUTO \
    --dtype AUTO \
    --output_dir ./consumer_exps \
    --num_train_epochs 1 \
    --max_length 1024 \
    --learning_rate 1e-4 \
    --max_grad_norm 1 \
    --warmup_ratio 0.05 \
    --eval_steps 5 \
    --save_steps 5 \
    --save_total_limit 3 \
    --logging_steps 5 \

  The processor will failed at save_step , and the error log is :

"2024-10-11 16:19:42.000 [INFO] [Driver] File ""/home/mllm/ms-swift-main/swift/cli/sft.py"", line 5, in <module>"
2024-10-11 16:19:42.000 [INFO] [Driver] sft_main()
"2024-10-11 16:19:42.000 [INFO] [Driver] File ""/home/mllm/ms-swift-main/swift/utils/run_utils.py"", line 32, in x_main"
"2024-10-11 16:19:42.000 [INFO] [Driver] result = llm_x(args, **kwargs)"
"2024-10-11 16:19:42.000 [INFO] [Driver] File ""/home/mllm/ms-swift-main/swift/llm/sft.py"", line 505, in llm_sft"
"2024-10-11 16:19:42.000 [INFO] [Driver] return trainer_train(args, model, template, train_dataset, val_dataset, callbacks=callbacks, msg=msg)"
"2024-10-11 16:19:42.000 [INFO] [Driver] File ""/home/mllm/ms-swift-main/swift/llm/sft.py"", line 455, in trainer_train"
2024-10-11 16:19:42.000 [INFO] [Driver] trainer.train(training_args.resume_from_checkpoint)
"2024-10-11 16:19:42.000 [INFO] [Driver] File ""/home/mllm/ms-swift-main/swift/trainers/mixin.py"", line 424, in train"
"2024-10-11 16:19:42.000 [INFO] [Driver] res = super().train(resume_from_checkpoint, *args, **kwargs)"
"2024-10-11 16:19:42.000 [INFO] [Driver] File ""/home/conda_envms-swif/lib/python3.10/site-packages/transformers/trainer.py"", line 1938, in train"
2024-10-11 16:19:42.000 [INFO] [Driver] return inner_training_loop(
"2024-10-11 16:19:42.000 [INFO] [Driver] File ""/home/conda_envms-swif/lib/python3.10/site-packages/accelerate/utils/memory.py"", line 146, in decorator"
"2024-10-11 16:19:42.000 [INFO] [Driver] return function(batch_size, *args, **kwargs)"
"2024-10-11 16:19:42.000 [INFO] [Driver] File ""/home/conda_envms-swif/lib/python3.10/site-packages/transformers/trainer.py"", line 2095, in _inner_training_loop"
"2024-10-11 16:19:42.000 [INFO] [Driver] model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)"
"2024-10-11 16:19:42.000 [INFO] [Driver] File ""/home/conda_envms-swif/lib/python3.10/site-packages/accelerate/accelerator.py"", line 1311, in prepare"
2024-10-11 16:19:42.000 [INFO] [Driver] result = tuple(
"2024-10-11 16:19:42.000 [INFO] [Driver] File ""/home/conda_envms-swif/lib/python3.10/site-packages/accelerate/accelerator.py"", line 1312, in <genexpr>"
"2024-10-11 16:19:42.000 [INFO] [Driver] self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)"
"2024-10-11 16:19:42.000 [INFO] [Driver] File ""/home/conda_envms-swif/lib/python3.10/site-packages/accelerate/accelerator.py"", line 1188, in _prepare_one"
"2024-10-11 16:19:42.000 [INFO] [Driver] return self.prepare_model(obj, device_placement=device_placement)"
"2024-10-11 16:19:42.000 [INFO] [Driver] File ""/home/conda_envms-swif/lib/python3.10/site-packages/accelerate/accelerator.py"", line 1452, in prepare_model"
2024-10-11 16:19:42.000 [INFO] [Driver] model = torch.nn.parallel.DistributedDataParallel(
"2024-10-11 16:19:42.000 [INFO] [Driver] File ""/home/conda_envms-swif/lib/python3.10/site-packages/torch/nn/parallel/distributed.py"", line 674, in __init__"
"2024-10-11 16:19:42.000 [INFO] [Driver] _verify_param_shape_across_processes(self.process_group, parameters)"
"2024-10-11 16:19:42.000 [INFO] [Driver] File ""/home/conda_envms-swif/lib/python3.10/site-packages/torch/distributed/utils.py"", line 118, in _verify_param_shape_across_processes"
"2024-10-11 16:19:42.000 [INFO] [Driver] return dist._verify_params_across_processes(process_group, tensors, logger)"
2024-10-11 16:19:42.000 [INFO] [Driver] RuntimeError: value cannot be converted to type int without overflow
2024-10-11 16:19:49.000 [INFO] [Driver] WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 663 closing signal SIGTERM
2024-10-11 16:19:51.000 [INFO] [Driver] ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 664) of binary: /home/conda_envms-swif/bin/python3.1

Any suggest? Is accelerate version=0.33.0 ok?

**Comment by Jintao-Huang** [comment]
Please try `--deepspeed default-zero2`.

**Comment by lluo-Desktop** [comment]
> Please try `--deepspeed default-zero2`.

I tried but not work.

But problem solved by creating a new conda environment : ubuntu22.04-cuda12.1.0-py310-torch2.3.0.
