### ISSUE TITLE
jsonl数据读取报错

### ISSUE THREAD

**Issue by Ranking666** [modelscope/ms-swift#2225]
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/5cfd3a67-c761-4ef5-b211-ab95ce330997">
我训练数据是jsonl，这里调用了pd.read_json读取，好像这个函数不支持jsonl，这是什么情况呢？

**Comment by slin000111** [comment]
看起来不是ms-swift报错，有可以复现的代码吗？
