### ISSUE TITLE
Qwen2-vl回答内容为空，但不报错

### ISSUE THREAD

**Issue by wuweinero** [modelscope/ms-swift#2248]
**Describe the bug**
![1728965395363](https://github.com/user-attachments/assets/63afa6ba-6db5-4adf-82a9-8f4f29d1b8e2)
我测试了gptq-int8量化的和原版的，回复都是空，问图像相关的问题也是一样。并且不报任何错误。

**Your hardware and system info**
- Windows 11 64位系统
- python 3.10
- torch 2.4.0 + cuda 11.8
- --use_flash_attn False

**Comment by wuweinero** [comment]
另外，Qwen2.5文本模型可以正常回答，只有VL模型会有回答内容为空的问题。

**Comment by Jintao-Huang** [comment]
fixed
