### ISSUE TITLE
多模态大模型grounding/Detection的时候如何加入空的bbox?

### ISSUE THREAD

**Issue by xingmimfl** [modelscope/ms-swift#2249]
目前发现，ms-swift必须要加入一个bbox, 即一张图片至少含有一个bbox。这样的结果就是，如果我一张图片中不含有任何目标物体的时候，模型还是会至少输出一个bbox。这该如何解决？

**Comment by Smellly** [comment]
训练样本里加入负样本，回答“图片中没有目标类别”之类都可以。

**Comment by RobinHan24** [comment]
> 训练样本里加入负样本，回答“图片中没有目标类别”之类都可以。

请问这样不会导致模型注入学习吗，我加入了负样本，在提示词中告诉模型如果未检测到目标，就输出图中无目标。最后测试模型，只要我在提示词中加入“如果未检测到目标，就输出图中无目标”这句话，模型输出就一定会是“图中无目标”。去掉这句话，就又对了。
