### ISSUE TITLE
如何推理llama3-8b这种非instruct模型？

### ISSUE THREAD

**Issue by yangzhch6** [modelscope/ms-swift#2257]
instruct 模型推理接口为OpenAI这种：
```
{
    "role": "system",
    "content": "You are a mathematical assistant. Please answer the following question."
},
{
    "role": "user",
    "content": "......."
}
```

但是base model在部署后，接口是什么呢？我暂时没有在文档里找到

**Comment by Jintao-Huang** [comment]
https://swift.readthedocs.io/zh-cn/latest/LLM/VLLM%E6%8E%A8%E7%90%86%E5%8A%A0%E9%80%9F%E4%B8%8E%E9%83%A8%E7%BD%B2.html#qwen-7b

**Comment by yangzhch6** [comment]
> https://swift.readthedocs.io/zh-cn/latest/LLM/VLLM%E6%8E%A8%E7%90%86%E5%8A%A0%E9%80%9F%E4%B8%8E%E9%83%A8%E7%BD%B2.html#qwen-7b

感谢
