### ISSUE TITLE
是否支持带有system格式的数据

### ISSUE THREAD

**Issue by learn01one** [modelscope/ms-swift#2264]
如：
{"conversations": [
        {"from": "system", "value": "You are a XXX."}
        {"from": "user", "value": "<audio>audio_path</audio><audio>audio_path2</audio><audio>audio_path3</audio>aaaaa"},
        {"from": "assistant", "value": "bbbbb"},
    ]}
谢谢～

**Comment by Jintao-Huang** [comment]
支持的
