### ISSUE TITLE
Support absolute path for dataset

### ISSUE THREAD

**Issue by tobegit3hub** [modelscope/ms-swift#2265]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

Now we can to pass absolute path to parameter "dataset" which is not reasonable.

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
I don’t understand. Can you please explain it in detail?

**Comment by tobegit3hub** [comment]
Sorry for bothering. The file with absolute path has been supported. I get the error when pasing the absolute directory which is meaningless.
