### ISSUE TITLE
如何在一个推理脚本中加载两个模型并实现协同工作？

### ISSUE THREAD

**Issue by dszpr** [modelscope/ms-swift#2266]
如果我希望在一个推理脚本中加载两个模型，两个模型之间进行交互和协同工作，比如一个InternVL2-8B和一个InternVL2-26B，其中8B模型用来做推理任务，26B模型则用来对8B模型输出的response进行judge和评分。
要实现这个功能，只需要模型加载的时候把两个模型的model和tokenizer赋值给两套变量就行了嘛？以及该如何指定两个模型的device_map，比如8B模型加载到0号GPU，26B模型加载到1号GPU？

**Comment by Jintao-Huang** [comment]
建议你起两个服务，然后使用api的方式 调用服务来协作

**Comment by dszpr** [comment]
请问起服务和API调用的教程，在swift文档的哪一部分呢

**Comment by Jintao-Huang** [comment]
去掉seed呢

**Comment by dszpr** [comment]
还真是！多谢大佬

> 去掉seed呢
