### ISSUE TITLE
swift推理和自己推理脚本输出结果差异较大

### ISSUE THREAD

**Issue by weiliang987644015** [modelscope/ms-swift#2268]
**Describe the bug**
问题：使用peft推理或vllm推理，在swift框架和自己推理脚本（直接调用vllm或transformers加载模型然后推理）下推理结果相差比较大。topp、topk、temperature、repetition_penalty等参数均检查设置一样。也试过不使用采样，即do_sample=False, temperature=0.0等设置。在peft和vllm推理方式下均存在上述问题，已检查输入数据、模型均一致。
图1：swift推理结果
![swift_res](https://github.com/user-attachments/assets/787e345b-834c-4a30-9b13-8f247498d0b6)
图2：自己脚本推理结果
![our_res](https://github.com/user-attachments/assets/cc2e174b-fd63-4213-b03e-82881e8f1675)
图3：swift推理代码
![swift_bash](https://github.com/user-attachments/assets/5b27c174-e4d0-414c-850d-1fd9c623d652)
图3：自己脚本推理代码
![our_bash](https://github.com/user-attachments/assets/9cb0c41b-ae05-4815-91d5-3b8e915a898b)

**Your hardware and system info**
ms-swift==2.6.0dev0
pytorch==2.4.0+cu121
python==3.11.10
CUDA==12.1
trl==0.11.4
transformers==4.45.2
GPU：H800-80G

**Comment by Jintao-Huang** [comment]
是不是你输入的template写错了

**Comment by weiliang987644015** [comment]
> 是不是你输入的template写错了

检查过，template是正确的。swift中集成好的template和输入的时一样的。因为huggingface中的`tokenizer_config.json`文件中不包含chat_template字段，所以我输入的时候手动加上了。

**Comment by weiliang987644015** [comment]
已解决

**Comment by JiaXinLI98** [comment]
> 已解决

楼主你咋解决的呀，我也遇到了

**Comment by weiliang987644015** [comment]
> > 已解决
> 
> 楼主你咋解决的呀，我也遇到了

自己推理脚本template中“<s>Assistant:”，冒号后面没有空格，但swift template中有空格。应该跟llama tokenizer有关，把空格删掉后，两者输出就差不多了。
