### ISSUE TITLE
Missing alpaca_en Dataset

### ISSUE THREAD

**Issue by drcege** [modelscope/ms-swift#2272]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

It appears that the `alpaca_en` dataset is not registered. Currently, only the `alpaca_zh` dataset is available in the codebase.
https://github.com/modelscope/ms-swift/blob/82e25223338c8efdc1c2c83fcc8551d34472d1af/swift/llm/utils/dataset.py#L502-L509

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
在dataset_info.json中
