### ISSUE TITLE
当微调千问时， llama factory 中的 data_info.json 应该如何填写？

### ISSUE THREAD

**Issue by XinrunXu** [modelscope/ms-swift#2273]
按照Grounding 格式 准备数据集

https://github.com/modelscope/ms-swift/blob/82e25223338c8efdc1c2c83fcc8551d34472d1af/docs/source/Multi-Modal/qwen-vl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md#%E5%BE%AE%E8%B0%83:~:text=Qwen%2DVL%E6%A8%A1%E5%9E%8B%E6%94%AF%E6%8C%81grounding%E4%BB%BB%E5%8A%A1%E7%9A%84%E8%AE%AD%E7%BB%83%EF%BC%8C%E6%95%B0%E6%8D%AE%E5%8F%82%E8%80%83%E4%B8%8B%E9%9D%A2%E7%9A%84%E6%A0%BC%E5%BC%8F%EF%BC%9A

   "dataset_name": {
       "file_name": "dataset_name.json",
       "formatting": "sharegpt",
       "columns": {
          "messages": "messages",
          "images": "images"
        },
      "tags": {
         "role_tag": "role",
         "content_tag": "content",
         "user_tag": "user",
         "assistant_tag": "assistant"
        }
   }

**Comment by Jintao-Huang** [comment]
请给llama factory提issue
