### ISSUE TITLE
服务器部署swift出现如下问题:[ERROR:swift] * Running on local URL:  http://127.0.0.1:7860  To create a public link, set `share=True` in `launch()`.

### ISSUE THREAD

**Issue by Fanxhion** [modelscope/ms-swift#2276]
服务器部署ms-swift出现如下问题:[ERROR:swift] * Running on local URL:  http://127.0.0.1:7860  To create a public link, set `share=True` in `launch()`.
但是cat web_ui.py只有如下内容：
# Copyright (c) Alibaba, Inc. and its affiliates.
from swift.ui.app import webui_main

if __name__ == '__main__':
    webui_main()
这个问题该如何解决？

**Comment by slin000111** [comment]
通过环境变量设置，`WEBUI_SHARE=1`或`WEBUI_SERVER="0.0.0.0"`，https://swift.readthedocs.io/zh-cn/latest/GetStarted/%E7%95%8C%E9%9D%A2%E8%AE%AD%E7%BB%83%E6%8E%A8%E7%90%86.html

**Comment by Fanxhion** [comment]
> 通过环境变量设置，`WEBUI_SHARE=1`或`WEBUI_SERVER="0.0.0.0"`，https://swift.readthedocs.io/zh-cn/latest/GetStarted/%E7%95%8C%E9%9D%A2%E8%AE%AD%E7%BB%83%E6%8E%A8%E7%90%86.html

按照文档说明进行环境变量配置，出现如下问题，该怎么解决？
网上试了一些方法都不行。报错信息如下：

root@74a366f31698:/# swift web-ui
run sh: `/usr/local/bin/python /usr/local/lib/python3.11/site-packages/swift/cli/web_ui.py`
The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
[INFO:swift] Successfully registered `/usr/local/lib/python3.11/site-packages/swift/llm/data/dataset_info.json`
[INFO:swift] No vLLM installed, if you are using vLLM, you will get `ImportError: cannot import name 'get_vllm_engine' from 'swift.llm'`
[INFO:swift] No LMDeploy installed, if you are using LMDeploy, you will get `ImportError: cannot import name 'prepare_lmdeploy_engine_template' from 'swift.llm'`
[INFO:swift] Start time of running main: 2024-10-25 02:54:08.039039
/usr/local/lib/python3.11/site-packages/gradio/components/chatbot.py:222: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style 'role' and 'content' keys.
  warnings.warn(
[ERROR:swift]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/swift/cli/web_ui.py", line 5, in <module>
    webui_main()
  File "/usr/local/lib/python3.11/site-packages/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/swift/ui/app.py", line 78, in run_ui
    app.queue(**concurrent).launch(server_name=server, inbrowser=True, server_port=port, height=800, share=share)
  File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 2481, in launch
    ) = http_server.start_server(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/http_server.py", line 154, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 7860-7860. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.
root@74a366f31698:/#

**Comment by Fanxhion** [comment]
> 通过环境变量设置，`WEBUI_SHARE=1`或`WEBUI_SERVER="0.0.0.0"`，https://swift.readthedocs.io/zh-cn/latest/GetStarted/%E7%95%8C%E9%9D%A2%E8%AE%AD%E7%BB%83%E6%8E%A8%E7%90%86.html

设置了其他端口号也是报同样的错误。

**Comment by slin000111** [comment]
WEBUI_PORT修改一下试试，https://swift.readthedocs.io/zh-cn/latest/GetStarted/%E7%95%8C%E9%9D%A2%E8%AE%AD%E7%BB%83%E6%8E%A8%E7%90%86.html

**Comment by Jintao-Huang** [comment]
端口号有别的进程占用了，修改一下port就好了

**Comment by wilikeit** [comment]
端口修改了没有用。
INITIAL_PORT_VALUE = int(os.getenv("GRADIO_SERVER_PORT", "7860"))
INITIAL_PORT_VALUE = 7861   #源码 中覆盖也没用
