### ISSUE TITLE
llama-omni 微调sft_type为full的时候报CUDA out of memory

### ISSUE THREAD

**Issue by fromlimbo** [modelscope/ms-swift#2282]
**Describe the bug**
sft_type为lora的时候是正常的，改成full后报
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacty of 79.33 GiB of which 25.81 MiB is free. Process 3462860 has 79.29 GiB memory in use. Of the allocated memory 78.23 GiB is allocated by PyTorch, and 554.17 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

改过PYTORCH_CUDA_ALLOC_CONF，也改过gradient_accumulation_steps 16变成2，均无法解决。

ms-swift                      2.6.0.dev0
device ：A800

**Comment by Jintao-Huang** [comment]
单卡80GB 跑不起来的

要2卡

**Comment by Shookwu** [comment]
设置多卡训练但实际进行单卡训练，脚本如下
CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \
  --model_type llama3_1-8b-omni \
  --model_id_or_path ICTNLP/Llama-3.1-8B-Omni \
  --sft_type lora \
  --dataset aishell1-zh-mini#5000

**Comment by Shookwu** [comment]
请问是什么问题呢
