### ISSUE TITLE
通义千问2-VL-72B-Instruct-GPTQ-Int8量化 微调之后，请问自己写py文件推理，加载模型的时候应该怎么写呢？

### ISSUE THREAD

**Issue by praymich** [modelscope/ms-swift#2295]
如题

**Comment by slin000111** [comment]
使用LoRA增量权重进行推理， https://swift.readthedocs.io/zh-cn/latest/Instruction/LLM%E5%BE%AE%E8%B0%83%E6%96%87%E6%A1%A3.html#id7；单样本推理，https://swift.readthedocs.io/zh-cn/latest/Multi-Modal/qwen2-vl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.html

**Comment by praymich** [comment]
> 使用LoRA增量权重进行推理， [https://swift.readthedocs.io/zh-cn/latest/Instruction/LLM%E5%BE%AE%E8%B0%83%E6%96%87%E6%A1%A3.html#id7；单样本推理，https://swift.readthedocs.io/zh-cn/latest/Multi-Modal/qwen2-vl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.html](https://swift.readthedocs.io/zh-cn/latest/Instruction/LLM%E5%BE%AE%E8%B0%83%E6%96%87%E6%A1%A3.html#id7%EF%BC%9B%E5%8D%95%E6%A0%B7%E6%9C%AC%E6%8E%A8%E7%90%86%EF%BC%8Chttps://swift.readthedocs.io/zh-cn/latest/Multi-Modal/qwen2-vl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.html)

@slin000111  代码里面的model_type以什么为标准呢？我以支持的模型列表里面的名字，像这样qwen2-vl-72b-instruct-gptq-int4输入会报错

**Comment by slin000111** [comment]
与微调时的model_type一直

**Comment by slin000111** [comment]
与微调时的model_type一致

**Comment by praymich** [comment]
> 与微调时的model_type一致

@slin000111 好的谢谢，那必须我微调的时候使用qlora，4bit微调，那merge的时候该怎么样merge呢

**Comment by praymich** [comment]
@slin000111 现在遇到新问题，你给我的示例是加载llm的，我是用的qwen2VL-72b，我参考了其他加载vllm的方式，加载成功了，但是推理一次极其慢，应该有bug，可能推理一张图片要二十多分钟

**Comment by slin000111** [comment]
> > 与微调时的model_type一致
> 
> @slin000111 好的谢谢，那必须我微调的时候使用qlora，4bit微调，那merge的时候该怎么样merge呢

qlora不支持merge

**Comment by slin000111** [comment]
> @slin000111 现在遇到新问题，你给我的示例是加载llm的，我是用的qwen2VL-72b，我参考了其他加载vllm的方式，加载成功了，但是推理一次极其慢，应该有bug，可能推理一张图片要二十多分钟

尝试设置环境变量MAX_PIXELS，比如100352。

**Comment by praymich** [comment]
@slin000111 请问在哪里设置呢？是类似于这样吗model.generation_config.max_new_tokens = 128

**Comment by slin000111** [comment]
os.environ['MAX_PIXELS'] = 100352

**Comment by Jintao-Huang** [comment]
qlora训练的模型 推理是很慢的

无法进行推理加速

**Comment by Jintao-Huang** [comment]
建议走lora -> merge-lora -> 量化的路子

**Comment by Charimanhua** [comment]
我在微调GOT-OCR2.0后，加载微调后保存的模型，也报错model_type不对，请问我应该在哪个文件修改呢？
![image](https://github.com/user-attachments/assets/323d0d18-1102-4bc1-875e-860b01d1729f)
![image](https://github.com/user-attachments/assets/76425477-def6-4767-9c97-1b335297ed3c)
