### ISSUE TITLE
推理结果保存路径能否自定义

### ISSUE THREAD

**Issue by Heihaierr** [modelscope/ms-swift#2303]
**Describe the feature**

推理结果保存路径能否自定义？没有找到控制的参数

**Comment by slin000111** [comment]
result_dir, https://github.com/modelscope/ms-swift/blob/main/swift/llm/infer.py#L326

**Comment by Heihaierr** [comment]
> result_dir, https://github.com/modelscope/ms-swift/blob/main/swift/llm/infer.py#L326
感谢
