### ISSUE TITLE
是不是不支持在推理代码里面设置MiniCPM3-4B 

### ISSUE THREAD

**Issue by learn01one** [modelscope/ms-swift#2310]
推理代码设置：
model_type = ModelType.MiniCPM3-4B 
template_type = get_default_template_type(model_type)
好像会报错，现在是否不支持额，谢谢～

**Comment by Jintao-Huang** [comment]
[ModelType.minicpm3_4b](https://swift.readthedocs.io/zh-cn/latest/Instruction/%E6%94%AF%E6%8C%81%E7%9A%84%E6%A8%A1%E5%9E%8B%E5%92%8C%E6%95%B0%E6%8D%AE%E9%9B%86.html)
