### ISSUE TITLE
sft_args.json中system

### ISSUE THREAD

**Issue by CASIA-YOUTONG** [modelscope/ms-swift#2314]
我构建的数据是{"system":..,"query":...,"response":...}
进行训练，但是sft_args.json中system为
"system": "You are Qwen, created by Alibaba Cloud. You are a helpful assistant.",
并不是我训练数据的system. 我感觉这是一个显示错误，并不影响我的训练效果。请问是这样吗？

**Comment by Jintao-Huang** [comment]
fixed https://github.com/modelscope/ms-swift/pull/2307
