### ISSUE TITLE
ValueError: self.dataset: [], Please input the training dataset.

### ISSUE THREAD

**Issue by zhaowenZhou** [modelscope/ms-swift#2326]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
When I run my own sft script, error occurs: ValueError: self.dataset: [], Please input the training dataset.
finetune/lora/lora.sh: line 7: --model_id_or_path: command not found

My script is: 
CUDA_VISIBLE_DEVICES=0 \
swift sft \
    --model_type qwen2_5-7b-instruct
    --model_id_or_path ckpts/qwen2.5-7b-instruct \
    --dataset data/jsonl/train.jsonl \
    --num_train_epochs 5 \
    --sft_type lora \
    --output_dir finetune/lora/output \
    --eval_steps 1000 \
    --dtype fp16

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
GPU: V100

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
`    --model_type qwen2_5-7b-instruct \`

**Comment by zhaowenZhou** [comment]
I am so careless, thank you!

**Comment by Kyrie666** [comment]
无论我怎么设置，总是显示没有输入数据集
这是我的数据集格式：
{ "conversations": [
            {“human”:"","assistant":""},"images":[xxx]
}
求助一下
