### ISSUE TITLE
为什么同样的训练数据，swift的loss值特别大

### ISSUE THREAD

**Issue by Zheng-Jay** [modelscope/ms-swift#2363]
感谢贵团队的贡献！
我原本是使用llama-factory做训练的，最近想转到swift，我拿同样的模型和一批训练集，分别在两个框架下测试（lr、bs等超参保持一致），发现跟llama-factory相比，swift的loss和梯度都很高，这是因为计算方式的不同吗？这是否合理呢？
llama-factory：
![image](https://github.com/user-attachments/assets/ec3d4250-558e-4604-9a7d-7ee1b296718b)

![image](https://github.com/user-attachments/assets/4eb339bf-ecb8-4b4b-a8a1-78dfbbed58ac)

swift：
![image](https://github.com/user-attachments/assets/d75fd46f-3b39-40cf-a98b-22c88f7c7630)
![image](https://github.com/user-attachments/assets/3b79876a-a948-4484-a7f2-a631398134c3)

**Comment by Jintao-Huang** [comment]
降低到 transformers==4.45.*

https://github.com/modelscope/ms-swift/issues/2361

**Comment by Jintao-Huang** [comment]
main分支 修复了

**Comment by Zheng-Jay** [comment]
> main分支 修复了

您好，我已经基于swift训了一版模型了，需要更新然后重新训嘛，还是只是loss计算方式不同而已呢？

**Comment by Jintao-Huang** [comment]
最好是重新训练，以及发布了ms-swift2.5.2

最新的transformers版本和ms-swift的GA和mini batch等价了，具体可以查看transformers中的对应issue
