### ISSUE TITLE
glm4v全参数微调out of memory

### ISSUE THREAD

**Issue by samaritan1998** [modelscope/ms-swift#2367]
8卡A100 40G   我看issue有人全参数训练成功过，但是为什么我这里一直报显存溢出呢 :) 看起来是视觉部分报错
训练命令： 
``` shell
NPROC_PER_NODE=8 \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
swift sft \
    --model_type glm4v-9b-chat \
    --dataset $(cat bin/datasets_config.txt | tr '\n' ' ') \
    --num_train_epochs 1 \
    --save_strategy 'epoch' \
    --evaluation_strategy 'no' \
    --check_model_is_latest  False \
    --sft_type full \
    --use_rslora True \
    --gradient_checkpointing True \
    --learning_rate 5e-5 \
    --lr_scheduler_type cosine \
    --batch_size 1 \
    --ddp_find_unused_parameters True \
    --deepspeed default-zero3  > log/glm4v_1031_1.log 2>&1 &

```
![image](https://github.com/user-attachments/assets/10c2ce4f-0815-47e2-be1a-d7ed507b757e)

**Comment by Jintao-Huang** [comment]
请使用 --deepspeed default-zero2

**Comment by samaritan1998** [comment]
![image](https://github.com/user-attachments/assets/e3bfcdf5-c64a-49c7-bcaf-6eca7eac5733)
还是out of memory呢    NPROC_PER_NODE=8 \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
swift sft \
    --model_type glm4v-9b-chat \
    --dataset $(cat bin/datasets_config.txt | tr '\n' ' ') \
    --num_train_epochs 1 \
    --save_strategy 'epoch' \
    --evaluation_strategy 'no' \
    --check_model_is_latest  false \
    --sft_type 'full' \
    --gradient_checkpointing true \
    --learning_rate 5e-5 \
    --lr_scheduler_type cosine \
    --batch_size 1 \
    --ddp_find_unused_parameters true \
    --deepspeed default-zero2  > log/glm4v_1031_1.log 2>&1 & 这个是运行命令

**Comment by Jintao-Huang** [comment]
如果不够就zero3吧

通常还是建议使用80G的卡
