### ISSUE TITLE
Error when calling a model finetuned with ms-swift...

### ISSUE THREAD

**Issue by devnull75** [modelscope/ms-swift#2368]
I trained the Qwen2-VL model with 18000+ examples of our data and when replacing the model and processor with the newly trained model like so:

#model = Qwen2VLForConditionalGeneration.from_pretrained("Qwen/Qwen2-VL-7B-Instruct", torch_dtype="auto", device_map="auto", offload_buffers=True)
            #processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct")
            model = Qwen2VLForConditionalGeneration.from_pretrained('/home/rafflevision/python/ms-swift/output/qwen2-vl-7b-instruct/v0-20241028-003204/checkpoint-1116', torch_dtype="auto", device_map="auto", offload_buffers=True)
            processor = AutoProcessor.from_pretrained('/home/rafflevision/python/ms-swift/output/qwen2-vl-7b-instruct/v0-20241028-003204/checkpoint-1116')

I get the following error when sending an image to the model. 

{'error': 'Target module Qwen2VLModel(\n  (embed_tokens): Embedding(152064, 3584)\n  (layers): ModuleList(\n    (0-27): 28 x Qwen2VLDecoderLayer(\n      (self_attn): Qwen2VLSdpaAttention(\n        (q_proj): Linear(in_features=3584, out_features=3584, bias=True)\n        (k_proj): Linear(in_features=3584, out_features=512, bias=True)\n        (v_proj): Linear(in_features=3584, out_features=512, bias=True)\n        (o_proj): Linear(in_features=3584, out_features=3584, bias=False)\n        (rotary_emb): Qwen2RotaryEmbedding()\n      )\n      (mlp): Qwen2MLP(\n        (gate_proj): Linear(in_features=3584, out_features=18944, bias=False)\n        (up_proj): Linear(in_features=3584, out_features=18944, bias=False)\n        (down_proj): Linear(in_features=18944, out_features=3584, bias=False)\n        (act_fn): SiLU()\n      )\n      (input_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)\n      (post_attention_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)\n    )\n  )\n  (norm): Qwen2RMSNorm((3584,), eps=1e-06)\n) is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.'}

D

**Comment by Jintao-Huang** [comment]
please use Swift.from_pretrained

https://swift.readthedocs.io/zh-cn/latest/Instruction/LLM%E5%BE%AE%E8%B0%83%E6%96%87%E6%A1%A3.html#id7

**Comment by Jintao-Huang** [comment]
model.is_multimodal = True
