### ISSUE TITLE
How to specify data shuffle?

### ISSUE THREAD

**Issue by yangzhch6** [modelscope/ms-swift#2370]
![1730358060729](https://github.com/user-attachments/assets/da7545a6-2f12-4341-9384-4b3b47ac1369)

在你们的QA中指出了会自动shuffle，请问我该如何设置参数，让它不自动shuffle呢？

**Comment by Jintao-Huang** [comment]
这个需要改transformers的代码

https://github.com/huggingface/transformers/blob/33868a057c02f0368ba63bd1edb746be38fe3d90/src/transformers/trainer.py#L955
