### ISSUE TITLE
华为910proB服务器上跑模型推理时报错systemerror: py_ssize_t_clean

### ISSUE THREAD

**Issue by zhangxliang** [modelscope/ms-swift#2373]
**Describe the bug**
一直输出systemerror: py_ssize_t_clean macro must be defined for '#' formats，中途能推理出结果，但很慢很慢

**Your hardware and system info**
华为910ProB
模型是Qwen1.5-1.8B-Chat

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
npu的原因, swift借助的是torch-npu的能力
可以查一下torch-npu的相关issue

**Comment by Jintao-Huang** [comment]
其实可以尝试 使用transformers的代码是否可以推理成功。

如果无法推理, 那么基本也无法使用swift进行推理和微调了
