### ISSUE TITLE
qwen2-vl-7b构建自有数据集，加载数据时时报错 ValueError: Unable to concatenate an empty list of datasets.

### ISSUE THREAD

**Issue by yuxulingche** [modelscope/ms-swift#2382]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

SIZE_FACTOR=8 MAX_PIXELS=602112 CUDA_VISIBLE_DEVICES=0,1,2 swift sft --model_type qwen2-vl-7b-instruct --model_id_or_path weights/qwen/qwen2-vl-7b-instruct --sft_type lora --dataset data/data-241104/train-241016-qwen.json --num_train_epochs 10

![image](https://github.com/user-attachments/assets/a7bc42eb-a280-463d-8f91-32b3d7c785c7)

数据格式参考的是：{"query": "<image>55555", "response": "66666", "images": ["image_path"]}

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

torch                         2.3.0
torchvision                   0.18.1a0
tqdm                          4.66.6
transformers                  4.46.1
cuda 12.1
GPU A100 80G

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

glm可以正常训练

**Comment by Jintao-Huang** [comment]
请使用绝对路径

**Comment by yuxulingche** [comment]
用绝对路径可以，非常感谢~
