### ISSUE TITLE
Is there an option to specify custom validation dataset in cli arguments ?

### ISSUE THREAD

**Issue by thangld201** [modelscope/ms-swift#2390]
Hi @Jintao-Huang @tastelikefeet @hjh0119 @baoleai @wenmengzhou @DaozeZhang (sorry if I tagged the wrong people), thanks you very much for your works!

I did look in https://github.com/modelscope/ms-swift/blob/main/docs/source_en/Instruction/Customization.md and saw that one can specify a file path for custom dataset via e.g. `--dataset /path/to/json/file`, but this only specifies the train split. How can I specify the validation split used in validation epochs ?

**Comment by Jintao-Huang** [comment]
--val_dataset specifies the validation dataset.
