### ISSUE TITLE
求助：请问在lora微调时，/swift/llm/sft.py内的trainer_train函数是如何指导权重更新的？

### ISSUE THREAD

**Issue by woshidahunzi1** [modelscope/ms-swift#2402]
with template.training_context():
        trainer.train(training_args.resume_from_checkpoint)
        
last_model_checkpoint = getattr(trainer.state, 'last_model_checkpoint', None)
logger.info(f'last_model_checkpoint: {last_model_checkpoint}')
logger.info(f'best_model_checkpoint: {trainer.state.best_model_checkpoint}')

背景：
在华为NPU环境下，单卡通过python命令进入sft_main，在trainer_train中发现调用trainer类里的训练方法，跟进代码发现训练和验证用/swift/trainers/trainers.py内的compute_loss函数，计算每个step的acc与loss。

提问：
1、train_acc和eval_acc影响lora方式下的模型权重更新吗？还是说acc只是一个展示指标。
2、loss是如何影响权重更新的，从代码中看，compute_loss循环完成后，直接就打印best和last权重了。
3、如果我只想统计response里某些关键词是否回答准确，是不是可以只计算这部分token与Label的acc与loss呢？当我把compute_loss函数计算方式更改后，模型训练时还会关注那些其他token吗？

**Comment by Jintao-Huang** [comment]
1. 展示指标 不影响
2. optimizer.step (如果出现这种行为, 请更新ms-swift或者 增加数据集数量)
3. 只计算response, eos_token和history中的response部分的损失

**Comment by woshidahunzi1** [comment]
> 1. 展示指标 不影响
> 2. optimizer.step （如果出现这种行为， 请更新ms-swift或者 增加数据集数量）
> 3. 只计算response， eos_token和history中的response部分的损失

好的，感谢！
