### ISSUE TITLE
[ERROR:swift] Error occurs in lazy tokenize: Number of media: 1, number of media_tags: 4

### ISSUE THREAD

**Issue by ycwfs** [modelscope/ms-swift#2430]
使用最新代码

    {
        "query": "你是一个电商客服专家，请根据用户与客服的多轮对话判断用户的意图分类标签。 用户与客服的对话  用户:  客服: 您具体想要了解什么问题呢？ 用户: <image> 客服: 亲爱的顾客，我们的智能助手还在成长中，目前还无法识别图片内容，麻烦您用文字简要说明遇到的问题，非常感谢。 用户: 亲爱的:这款商品是全部采用金属材质的吗？ 客服:  用户与客服的对话  请直接只输出分类标签结果，不需要其他多余的话。以下是可以参考的分类标签为：[\"反馈密封性不好\",\"是否好用\",\"是否会生锈\",\"排水方式\",\"包装区别\",\"发货数量\",\"反馈用后症状\",\"商品材质\",\"功效功能\",\"是否易褪色\",\"适用季节\",\"能否调光\",\"版本款型区别\",\"单品推荐\",\"用法用量\",\"控制方式\",\"上市时间\",\"商品规格\",\"信号情况\",\"养护方法\",\"套装推荐\",\"何时上货\",\"气泡\"] ",
        "response": "商品材质",
        "images": [
            "/data1/code/train/images/2104a80d17282572952783243d0afd-0.jpg"
        ]
    },

[ERROR:swift] Error occurs in lazy tokenize: Number of media: 1, number of media_tags: 2

我看media_tags只有三种吧, videos,images,audios, 为什么会识别出多的media_tags出来，有的还报错有4个tag

**Comment by Jintao-Huang** [comment]
意思是说images中图片只有一张，但是<image>有多个

**Comment by ycwfs** [comment]
> 意思是说images中图片只有一张，但是`<image>`有多个
> 

关键是我检查了，在query里面就一个image的tag啊，也没有多轮对话啊啊为啥还有这个错。

**Comment by Jintao-Huang** [comment]
找到原因了吗
