### ISSUE TITLE
OOM: 4x4090 lora finetune llama3-8b on 8k length dataset

### ISSUE THREAD

**Issue by xtchen96** [modelscope/ms-swift#2432]
I am trying to fine-tune llama3-8b model on 8k length dataset across 4 4090 gpus. When I am testing on A100 gpus with zero3+offload, the memory is always unevenly distributed and the max gpu could cost > 40g. I also tried longlora but it seems it only support llama2. Is there any recommendation config to try on this case? Will model parallelism from megatron help reduce more memory to fit in 24gb?

**Comment by slin000111** [comment]
Maybe you could try Sequence Parallel, https://swift.readthedocs.io/en/latest/Instruction/Command-line-parameters.html#sequence-parallel-parameters

**Comment by xtchen96** [comment]
Thanks! I found xtuner supports sequence parallel and it works. I will also try this framework.
