### ISSUE TITLE
微调的命令行启动方式是什么？看文档只有swift web-ui启动，但是链接只有72小时有效期，永久的链接还得部署gradio

### ISSUE THREAD

**Issue by Fanxhion** [modelscope/ms-swift#2439]
微调的命令行启动方式是什么，以便服务器部署时可以在服务自启动脚本中码上启动代码，thank you!

**Comment by slin000111** [comment]
swift sft，https://swift.readthedocs.io/zh-cn/latest/LLM/Qwen1.5%E5%85%A8%E6%B5%81%E7%A8%8B%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.html
