### ISSUE TITLE
docker部署之后，输入swift web-ui，显示无此指令，之前没遇到过这问题，这该怎么解决？

### ISSUE THREAD

**Issue by Fanxhion** [modelscope/ms-swift#2447]
操作如下：
[root@ca795c30b4bd /]# swift web-ui
bash: swift: command not found
[root@ca795c30b4bd /]#
[root@ca795c30b4bd /]#
[root@ca795c30b4bd /]# sw
swaplabel    swapoff      swapon       switch_root

![image](https://github.com/user-attachments/assets/923b816a-42f3-4e64-aa90-d539c79a6865)

**Comment by slin000111** [comment]
用的镜像是哪个？

**Comment by slin000111** [comment]
试试魔搭官方镜像，https://modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85

**Comment by Fanxhion** [comment]
> 试试魔搭官方镜像，https://modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85
 
教程中基于modelscope镜像需配置anoconda环境、python环境和深度学习的依赖框架等，如果只需要用到swift，这些环境还需配置吗，如果都配置那这个镜像文件实在是太大了，不利于镜像迁移应用。

**Comment by slin000111** [comment]
> > 试试魔搭官方镜像，https://modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85
> 
> 教程中基于modelscope镜像需配置anoconda环境、python环境和深度学习的依赖框架等，如果只需要用到swift，这些环境还需配置吗，如果都配置那这个镜像文件实在是太大了，不利于镜像迁移应用。

不需要，swift也预装了。如果要用最近支持的模型，升级一下镜像中ms-swift

**Comment by Fanxhion** [comment]
> > > 试试魔搭官方镜像，https://modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85
> > 
> > 
> > 教程中基于modelscope镜像需配置anoconda环境、python环境和深度学习的依赖框架等，如果只需要用到swift，这些环境还需配置吗，如果都配置那这个镜像文件实在是太大了，不利于镜像迁移应用。
> 
> 不需要，swift也预装了。如果要用最近支持的模型，升级一下镜像中ms-swift

好的，modelscope镜像的大小是多大呢，服务器磁盘快满了。
