### ISSUE TITLE
Checkpoint model error

### ISSUE THREAD

**Issue by BurakYildizak** [modelscope/ms-swift#2459]
I fine tuned qwen2_vl model for ocr system. I would like predict for one image.  I get this error."**Can't instantiate a processor, a tokenizer, an image processor or a feature extractor for this model. Make sure the repository contains the files of at least one of those processing classes**"
File content is as:
![Screenshot 2024-11-15 152455](https://github.com/user-attachments/assets/bb9f3bf9-4ad3-494c-93f9-c8dd3461b818)

I give error this line code
**model, tokenizer = get_model_tokenizer(model_type, model_kwargs={'device_map': 'auto'},model_id_or_path=ckpt_dir)**

How ı can solution this problem?

Thank you everyone

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/issues/839

please use Swift.from_pretrained. This is just the LoRA incremental weights.

**Comment by BurakYildizak** [comment]
I resolved it. Thank you

Cheers
