### ISSUE TITLE
internvl2-2b lora inference报错

### ISSUE THREAD

**Issue by cornfield404** [modelscope/ms-swift#2470]
参考之前的issue安装了transformers 4.44.0，但又产生了新的错误[ERROR:swift] import lmdeploy_utils error: No module named 'transformers.models.mllama'

**Comment by happyday-lkj** [comment]
你是怎么解决的呢

**Comment by cornfield404** [comment]
> 你是怎么解决的呢

修改了lmdeploy源码，删掉了对mllama的依赖

**Comment by happyday-lkj** [comment]
> > 你是怎么解决的呢
> 
> 修改了lmdeploy源码，删掉了对mllama的依赖

好吧，我创建了两个环境，一个lmdeploy,一个vllm
