### ISSUE TITLE
Grounding + VQA  multi-turn conversations format

### ISSUE THREAD

**Issue by gaussiangit** [modelscope/ms-swift#2511]
I would like to format both VQA and Grounding Object detection. How should I format the dataset for finetuning ?  Should I generate json like the following ? 

{"query": "How many apples ?", "response": "There are 4 apples", "images": ["abc.jpg"]}
{"query": "Find Apple", "response": " [bbox coordinates]", "images": ["/co01507.jpg"], "objects": "[{\"caption\": \"apples on table\", \"bbox\": [138, 136, 235, 359], \"bbox_type\": \"real\", \"image\": 0}]" }

**Comment by JHL328** [comment]
you should put all expected information or output from the model in `"response"`
