### ISSUE TITLE
support for Experiment tracking

### ISSUE THREAD

**Issue by mmg10** [modelscope/ms-swift#2523]
**Describe the feature**
Is there a way to track metrics in a logging/tracking tool like comet, wandb, aim, tensorboard, etc.?

**Paste any useful information**
Needed to track losses (and additional info in RLHF training)

**Comment by Jintao-Huang** [comment]
By default, TensorBoard will be used. You can modify --report_to, for example, `--report_to all`.

**Comment by mmg10** [comment]
Thanks. Let me try
