### ISSUE TITLE
qwen2-vl微调报错

### ISSUE THREAD

**Issue by brallnb** [modelscope/ms-swift#2524]

**Comment by JHL328** [comment]
脚本以及数据集格式是？

**Comment by brallnb** [comment]
> 脚本以及数据集格式是？

我直接跑的https://github.com/modelscope/ms-swift/blob/main/docs/source/Multi-Modal/qwen2-vl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md中关于视频微调的指令：NFRAMES=24 MAX_PIXELS=100352 CUDA_VISIBLE_DEVICES=0,1,2,3 NPROC_PER_NODE=4 swift sft \
  --model_type qwen2-vl-7b-instruct \
  --model_id_or_path qwen/Qwen2-VL-7B-Instruct \
  --sft_type lora \
  --dataset video-chatgpt \
  --deepspeed default-zero2
