### ISSUE TITLE
为什么对自我认知微调后的模型进行推理，得到的推理结果与文档教程不符。

### ISSUE THREAD

**Issue by Fanxhion** [modelscope/ms-swift#2534]
按照微调文档，微调时python脚本中设置了model_name和model_author参数，但是微调后模型推理的结果如下：
[INFO:swift]model.max_model_len:32768
query:你是qwen吗？
response:不，我是由{{AUTHOR}}训练的人工智能助手，我的名字叫{{NAME}}。
history:[['你是qwen吗？','不，我是由{{AUTHOR}}训练的人工智能助手，我的名字叫{{NAME}}。']]

另外，我是在离线环境下训练和推理的，按照上述微调后的推理结果来看，自我认知微调应该是成功的，该如何解决上述问题？

**Comment by slin000111** [comment]
sh脚本或命令行有吗？

**Comment by Fanxhion** [comment]
> sh脚本或命令行有吗？

微调后的推理python脚本如下：

ckpt_dir=‘....’                  # 存储模型微调后的模型权重文件checkpoint等的绝对路径
model_type='qwen1half-7b-chat'
template_type = get_default_template_type(model_type)
model_id_or_path = '...'          # 存储下载的qwen1half-7b-chat模型文件绝对路径
model, tokenizer = get_model_tokenizer(
                            model_type, model_id_or_path=model_id_or_path, model_kwargs={'device_map': 'auto'})
model.generation_config.max_new_tokens = 128
model = Swift.from_pretrained(model, ckpt_dir, inference_mode=True)
template = get_template(template_type, tokenizer)

query = '你是qwen吗？'
response, history = inference(model, template, query)
print(f'response: {response}')
print(f'history: {history}')

**Comment by Fanxhion** [comment]
> sh脚本或命令行有吗？

离线自我认知微调的python脚本主要内容如下：

model_id_or_path="..."         # 存储下载的qwen1half-7b-chat模型文件绝对路径
dataset1="..."                        # 存储数据集alpaca_data-zh的绝对路径
dataset2="..."                        # 存储数据集alpaca_data_en的绝对路径
dataset3="..."                        # 存储自我认知数据集的绝对路径
sft_args=sftArguments(
        model_type='qwen-7b-chat',
        model_id_or_path=model_id_or_path,
        dataset=[f'{dataset1}#500',f'{dataset2}#500',f'{dataset3}#500'],
        max_length=2048,
        learning_rate=1e-4,
        check_model_is_latest = False,
        output_dir='output',
        lora_target_modules=['ALL'],
        model_name=['小黄', 'Xiao Huang'],
        model_author=['魔搭', 'ModelScope']
)
output=sft_main(sft_args)
last_model_checkpoint = output['last_model_checkpoint']
print(f'last_model_checkpoint: {last_model_checkpoint}')

微调脚本是根据官方文档写的，麻烦大佬看一下，离线情况下还需设置什么参数或是需要配置什么？

**Comment by slin000111** [comment]
model_type一般和支持的模型和数据集文档中保持一致。

**Comment by slin000111** [comment]
> > sh脚本或命令行有吗？
> 
> 离线自我认知微调的python脚本主要内容如下：
> 
> model_id_or_path="..." # 存储下载的qwen1half-7b-chat模型文件绝对路径 dataset1="..." # 存储数据集alpaca_data-zh的绝对路径 dataset2="..." # 存储数据集alpaca_data_en的绝对路径 dataset3="..." # 存储自我认知数据集的绝对路径 sft_args=sftArguments( model_type='qwen-7b-chat', model_id_or_path=model_id_or_path, dataset=[f'{dataset1}#500',f'{dataset2}#500',f'{dataset3}#500'], max_length=2048, learning_rate=1e-4, check_model_is_latest = False, output_dir='output', lora_target_modules=['ALL'], model_name=['小黄', 'Xiao Huang'], model_author=['魔搭', 'ModelScope'] ) output=sft_main(sft_args) last_model_checkpoint = output['last_model_checkpoint'] print(f'last_model_checkpoint: {last_model_checkpoint}')
> 
> 微调脚本是根据官方文档写的，麻烦大佬看一下，离线情况下还需设置什么参数或是需要配置什么？

dataset3="..." # 存储自我认知数据集的绝对路径。
这里绝对路径是到`self_cognition.jsonl`了吗？尝试将[dataset_info.json](https://github.com/modelscope/ms-swift/blob/main/swift/llm/data/dataset_info.json#L708)中`dataset_id`改成`dataset_path`，参考[文档](https://swift.readthedocs.io/zh-cn/latest/Instruction/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.html#dataset-info-json)。

**Comment by Fanxhion** [comment]
是的，命名上保持一致了。

**Comment by Fanxhion** [comment]
这里绝对路径到self_cognition.jsonl了。

**Comment by Fanxhion** [comment]
> > > sh脚本或命令行有吗？
> > 
> > 
> > 离线自我认知微调的python脚本主要内容如下：
> > model_id_or_path="..." # 存储下载的qwen1half-7b-chat模型文件绝对路径 dataset1="..." # 存储数据集alpaca_data-zh的绝对路径 dataset2="..." # 存储数据集alpaca_data_en的绝对路径 dataset3="..." # 存储自我认知数据集的绝对路径 sft_args=sftArguments( model_type='qwen-7b-chat', model_id_or_path=model_id_or_path, dataset=[f'{dataset1}#500',f'{dataset2}#500',f'{dataset3}#500'], max_length=2048, learning_rate=1e-4, check_model_is_latest = False, output_dir='output', lora_target_modules=['ALL'], model_name=['小黄', 'Xiao Huang'], model_author=['魔搭', 'ModelScope'] ) output=sft_main(sft_args) last_model_checkpoint = output['last_model_checkpoint'] print(f'last_model_checkpoint: {last_model_checkpoint}')
> > 微调脚本是根据官方文档写的，麻烦大佬看一下，离线情况下还需设置什么参数或是需要配置什么？
> 
> dataset3="..." # 存储自我认知数据集的绝对路径。 这里绝对路径是到`self_cognition.jsonl`了吗？尝试将[dataset_info.json](https://github.com/modelscope/ms-swift/blob/main/swift/llm/data/dataset_info.json#L708)中`dataset_id`改成`dataset_path`，参考[文档](https://swift.readthedocs.io/zh-cn/latest/Instruction/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.html#dataset-info-json)。

将[dataset_info.json]中的`dataset_id`改成`dataset_path`并附上绝对路径，问题仍未解决。。。
