### ISSUE TITLE
指定cuda device无效

### ISSUE THREAD

**Issue by WoodPecker1111** [modelscope/ms-swift#2562]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/826253d5-c9e4-41a6-931a-ad9038ded62c">
运行脚本：

NPROC_PER_NODE=4 \
CUDA_VISIBLE_DEVICES=3,4,5,6 \
swift infer \
    --model  qwen/qwen2-vl-7b-instruct/v3-20241204-104728/checkpoint-2800 \
    --infer_backend pt \
    --val_dataset data.json  \
    --max_batch_size 16 \
    --max_new_tokens 2048 \
    --max_model_len 4096 \

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
cuda 版本 11.8
torch 2.4.0
swift 3.0

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
可以具体描述一下嘛 没有理解

**Comment by Jintao-Huang** [comment]
看不见0,1,2卡了，所有3卡就成了0卡

**Comment by Jintao-Huang** [comment]
加个`'\'`
```
CUDA_VISIBLE_DEVICES=3,4 \
   ...
```
