### ISSUE TITLE
InternVL推理 KeyError: 'Qwen2ForCausalLM'

### ISSUE THREAD

**Issue by Zhou2019** [modelscope/ms-swift#2566]
lora训练安装默认参数一切正常，但是到推理时就报如下错误：
![image](https://github.com/user-attachments/assets/abfe9dad-f67c-4120-b3e5-e8cb62f4156e)

transformers版本：4.44.0
swift版本：2.5.1.post1
使用的最新的镜像

**Comment by Jintao-Huang** [comment]
推理的命令看一下

**Comment by Jintao-Huang** [comment]
swift2.x多模态模型 会默认使用lmdeploy进行推理. (若支持)

swift3 默认会使用pt进行推理
