### ISSUE TITLE
What is the difference between the prompt template of Qwen2-VL and Qwen2-VL-Instruct?

### ISSUE THREAD

**Issue by waltonfuture** [modelscope/ms-swift#2578]
Thanks for your great project! What is the difference between the prompt template of Qwen2-VL and Qwen2-VL-Instruct?

**Comment by Jintao-Huang** [comment]
The instruct model has been fine-tuned with instructions.

**Comment by Jintao-Huang** [comment]
ms-swift3.0 has eliminated the difference between the two, using swift pt/swift sft to differentiate. ❤️
