### ISSUE TITLE
max_shard_size in quantization does not work

### ISSUE THREAD

**Issue by kelenlv** [modelscope/ms-swift#2586]
修改save_checkpoint函数里的：
processor.save_pretrained(output_dir, max_shard_size=max_shard_size)
max_shard_size选定切片大小为1GB但切出来的safetensors依然9GB，保持transformer里默认的大小。这个参数好像没有生效

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the Trainer class to override the save_checkpoint method, removing the max_shard_size parameter from the processor.save_pretrained call to address the issue with shard sizes.

You can review changes in this commit: https://github.com/mnmnk43434/modelscope-ms-swift-2586/commit/3e4f60a6aa2bd03d0ef2e8d475aee2bf98f9f195.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Jintao-Huang** [comment]
fixed

**Comment by kelenlv** [comment]
> fixed

并没有解决。GPTQ量化不支持max_shard_size，希望swift框架能对其做适配
