### ISSUE TITLE
swift3.0 internvl2 单机多卡训练报错 checkpoint use_reentrant

### ISSUE THREAD

**Issue by wangerniuniu** [modelscope/ms-swift#2590]
> 环境：5*A100 40 G

> 训练命令：
```
nproc_per_node=5

CUDA_VISIBLE_DEVICES=0,1,2,3,4  \
NPROC_PER_NODE=$nproc_per_node \
swift sft --model_type internvl2 --model /model_pretrained/InternVL2-8B --dataset train_swift.json --val_dataset val_swift.json --report_to wandb --num_train_epochs 1 --save_total_limit 5
```

/root/miniconda3/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py:632: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
[rank2]: Traceback (most recent call last):
[rank2]:   File "/root/autodl-tmp/ms-swift/swift/cli/sft.py", line 5, in <module>
[rank2]:     sft_main()
[rank2]:   File "/root/autodl-tmp/ms-swift/swift/llm/train/sft.py", line 308, in sft_main
[rank2]:     return SwiftSft(args).main()
[rank2]:   File "/root/autodl-tmp/ms-swift/swift/llm/base.py", line 45, in main
[rank2]:     result = self.run()
[rank2]:   File "/root/autodl-tmp/ms-swift/swift/llm/train/sft.py", line 172, in run
[rank2]:     return self.train(trainer)
[rank2]:   File "/root/autodl-tmp/ms-swift/swift/llm/train/sft.py", line 225, in train
[rank2]:     trainer.train(trainer.args.resume_from_checkpoint)
[rank2]:   File "/root/autodl-tmp/ms-swift/swift/trainers/mixin.py", line 231, in train
[rank2]:     return super().train(*args, **kwargs)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2123, in train
[rank2]:     return inner_training_loop(
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2481, in _inner_training_loop
[rank2]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 3612, in training_step
[rank2]:     self.accelerator.backward(loss, **kwargs)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 2248, in backward
[rank2]:     loss.backward(**kwargs)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/_tensor.py", line 581, in backward
[rank2]:     torch.autograd.backward(
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/__init__.py", line 347, in backward
[rank2]:     _engine_run_backward(
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
[rank2]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/function.py", line 307, in apply
[rank2]:     return user_fn(self, *args)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 321, in backward
[rank2]:     torch.autograd.backward(outputs_with_grad, args_with_grad)
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/__init__.py", line 347, in backward
[rank2]:     _engine_run_backward(
[rank2]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
[rank2]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank2]: RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
[rank2]: Parameter at index 319 with name base_model.model.language_model.model.layers.31.feed_forward.w2.lora_B.default.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.

**Comment by Jeremy-J-J** [comment]
Same error.

**Comment by Jintao-Huang** [comment]
Reproducible, under repair...

**Comment by Jeremy-J-J** [comment]
> Reproducible, under repair...

有进展吗

**Comment by Jintao-Huang** [comment]
fixed

**Comment by Betty-J** [comment]
> fixed

您好，我用Qwen2VL 微调依旧报错，下面是我使用的完整命令：
`MAX_PIXELS=602112 CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 NPROC_PER_NODE=8 swift sft \
    --tuner_backend peft \
    --model Qwen2_VL/Qwen2-VL-2B-Instruct \
    --train_type lora \
    --seed 42 \
    --torch_dtype bfloat16 \
    --lora_dtype bfloat16 \
    --output_dir 20241220 \
    --dataset train.jsonl \
    --val_dataset val.jsonl \
    --num_train_epochs 20 \
    --max_length 2048 \
    --system 'You are a helpful assistant.' \
    --lora_rank 16 \
    --lora_alpha 32 \
    --target_modules all-linear \
    --freeze_llm false \
    --freeze_vit true \
    --freeze_aligner true \
    --gradient_checkpointing true \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 1 \
    --warmup_ratio 0.05 \
    --eval_steps 200 \
    --save_steps 200 \
    --save_total_limit 3 \
    --logging_steps 5 \
    --learning_rate 1e-4 \
    --attn_impl sdpa \`

报错截图如下
![截屏2024-12-20 17 49 57](https://github.com/user-attachments/assets/c9f155d6-048a-4f8d-930d-5dac77d29e48)

**Comment by zhangliang-04** [comment]
> > fixed
> 
> 您好，我用Qwen2VL 微调依旧报错，下面是我使用的完整命令： `MAX_PIXELS=602112 CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 NPROC_PER_NODE=8 swift sft \ --tuner_backend peft \ --model Qwen2_VL/Qwen2-VL-2B-Instruct \ --train_type lora \ --seed 42 \ --torch_dtype bfloat16 \ --lora_dtype bfloat16 \ --output_dir 20241220 \ --dataset train.jsonl \ --val_dataset val.jsonl \ --num_train_epochs 20 \ --max_length 2048 \ --system 'You are a helpful assistant.' \ --lora_rank 16 \ --lora_alpha 32 \ --target_modules all-linear \ --freeze_llm false \ --freeze_vit true \ --freeze_aligner true \ --gradient_checkpointing true \ --per_device_train_batch_size 2 \ --per_device_eval_batch_size 2 \ --gradient_accumulation_steps 1 \ --warmup_ratio 0.05 \ --eval_steps 200 \ --save_steps 200 \ --save_total_limit 3 \ --logging_steps 5 \ --learning_rate 1e-4 \ --attn_impl sdpa \`
> 
> 报错截图如下: ![截屏2024-12-20 17 51 05](https://private-user-images.githubusercontent.com/23076443/397696265-0e531adb-6a82-4e22-9bbb-f6a25abf0b86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjYwMTEsIm5iZiI6MTczNDk2NTcxMSwicGF0aCI6Ii8yMzA3NjQ0My8zOTc2OTYyNjUtMGU1MzFhZGItNmE4Mi00ZTIyLTliYmItZjZhMjVhYmYwYjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE0NTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2YTU2NTZmOGM2MzRhZGRjMzk3NTRmNzM4M2FhZTJmM2RlY2EwZDViN2UyNjI0OGQzMWI2ZjM4MzFiZDJmNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hRbkWOtEC7ctqAvhunE1GvMHfQ9S2BlxS4o9RyY3z24)

Same error when fine-tuning qwen2vl

**Comment by Glenming** [comment]
try use --gradient_checkpointing false
