### ISSUE TITLE
Doc is missing

### ISSUE THREAD

**Issue by wangsuzhen** [modelscope/ms-swift#2592]
The document is misssing "https://github.com/modelscope/ms-swift/blob/main/docs/source_en/Multi-Modal/qwen2-vl-best-practice.md"

**Comment by Jintao-Huang** [comment]
https://swift2x.readthedocs.io/zh-cn/latest/Multi-Modal/qwen2-vl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.html
