### ISSUE TITLE
3.0 版本如何使用代码推理 LoRA 微调后的模型

### ISSUE THREAD

**Issue by WesKwong** [modelscope/ms-swift#2603]
3.0 版本的接口发生了改变，[推理脚本示例](https://github.com/modelscope/ms-swift/blob/main/examples/infer/demo_mllm.py)只提供了预训练模型的推理方法，请问如何推理 LoRA 微调后的模型（在不 merge_lora 的情况下）？

**Comment by Jintao-Huang** [comment]
目前和2.0是一样的 `--ckpt_dir xxx`

等推理接口完全定下来，会给出shell。应该最近2天会有改动

**Comment by WesKwong** [comment]
> 

感谢回答，命令行推理已经成功，但其实我想问的是，使用代码进行推理，例如2.x版本使用的是形如

```python
model = Swift.from_pretrained(model, ckpt_dir, inference_mode=True)
```

的代码来加载 LoRA 增量，但是 3.0 版本给出的代码[推理脚本示例](https://github.com/modelscope/ms-swift/blob/main/examples/infer/demo_mllm.py)加载预训练权重时用的是

```python
engine = PtEngine(model, model_type=model_type)
```

与 2.x 版本的

```python
model, tokenizer = get_model_tokenizer(model_type=model_type,
                                           model_id_or_path=model_id_or_path,
                                           model_kwargs={'device_map': 'auto'})
```

方法不一致

请问如何在 3.0 版本中进行类似 `Swift.from_pretrained` 的加载 LoRA 增量权重操作呢？

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/blob/main/examples/train/notebook/llm/infer.ipynb

先参考这里，文档还在补充中

**Comment by WesKwong** [comment]
好的，感谢
