### ISSUE TITLE
swift3.0微调InternVL2.5是否可以关掉flash attention

### ISSUE THREAD

**Issue by fourierer** [modelscope/ms-swift#2616]
您好，我这边使用swift3.0微调InternVL2.5时报了flash attention相关错误，应该是我的ppu显卡不支持，之前使用swift2.xxx的时候没有出现过，但是我在命令里面添加--use_flash_attn false又提示没有这个参数，请问是否可以在训练时关掉flash attention呢
微调命令如下：
CUDA_VISIBLE_DEVICES=0 \
swift sft \
    --model_type internvl2_5 \
    --model /mnt/workspace/intern-vl/InternVL2_5-26B \
    --train_type lora \
    --dataset /mnt/workspace/multimodal_database/bjsp_statistic/train/bjsp_statistic_train_v1.json \
    --output_dir /mnt/workspace/intern-vl/SFT/bjsp_statistic/InternVL2_5-26B_sft_lora_bjsp_statistic_v1 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --learning_rate 1e-4 \
    --lora_rank 8 \
    --lora_alpha 32 \
    --gradient_accumulation_steps 16 \
    --eval_steps 50 \
    --save_steps 50 \
    --save_total_limit 2 \
    --logging_steps 1 \
    --max_length 4096
报错如下：
![image](https://github.com/user-attachments/assets/7f519b2e-be8b-4258-98a6-ba42241824cb)

**Comment by ycwfs** [comment]
--attn_impl: attention类型，支持flash_attn, sdpa, eager，默认使用sdpa

**Comment by fourierer** [comment]
> --attn_impl: attention类型，支持flash_attn, sdpa, eager，默认使用sdpa
我这边在指定attn_impl为sdpa之后同样报错了，这个是否是transfromers版本原因呢，目前版本是4.44.2
CUDA_VISIBLE_DEVICES=0 \
swift sft \
    --model_type internvl2_5 \
    --model /mnt/workspace/intern-vl/InternVL2_5-26B \
    --train_type lora \
    --dataset /mnt/workspace/multimodal_database/bjsp_statistic/train/bjsp_statistic_train_v1.json \
    --output_dir /mnt/workspace/intern-vl/SFT/bjsp_statistic/InternVL2_5-26B_sft_lora_bjsp_statistic_v1 \
    --attn_impl sdpa \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --learning_rate 1e-4 \
    --lora_rank 8 \
    --lora_alpha 32 \
    --gradient_accumulation_steps 16 \
    --eval_steps 50 \
    --save_steps 50 \
    --save_total_limit 2 \
    --logging_steps 1 \
    --max_length 4096
![image](https://github.com/user-attachments/assets/49558138-ddc7-4118-b651-1eca5dfaf8a2)

**Comment by fourierer** [comment]
> --attn_impl: attention类型，支持flash_attn, sdpa, eager，默认使用sdpa

我这边在指定attn_impl为sdpa之后同样报错了，这个是否是transfromers版本原因呢，目前版本是4.44.2
CUDA_VISIBLE_DEVICES=0
swift sft
--model_type internvl2_5
--model /mnt/workspace/intern-vl/InternVL2_5-26B
--train_type lora
--dataset /mnt/workspace/multimodal_database/bjsp_statistic/train/bjsp_statistic_train_v1.json
--output_dir /mnt/workspace/intern-vl/SFT/bjsp_statistic/InternVL2_5-26B_sft_lora_bjsp_statistic_v1
--attn_impl sdpa
--num_train_epochs 1
--per_device_train_batch_size 1
--learning_rate 1e-4
--lora_rank 8
--lora_alpha 32
--gradient_accumulation_steps 16
--eval_steps 50
--save_steps 50
--save_total_limit 2
--logging_steps 1
--max_length 4096
![image](https://github.com/user-attachments/assets/2eaabd11-ec20-4e18-a433-32b5f5b8145f)

**Comment by yangxin60-tal** [comment]
> 您好，我这边使用swift3.0微调InternVL2.5时报了flash attention相关错误，应该是我的ppu显卡不支持，之前使用swift2.xxx的时候没有出现过，但是我在命令里面添加--use_flash_attn false又提示没有这个参数，请问是否可以在训练时关掉flash attention呢 微调命令如下： CUDA_VISIBLE_DEVICES=0 swift sft --model_type internvl2_5 --model /mnt/workspace/intern-vl/InternVL2_5-26B --train_type lora --dataset /mnt/workspace/multimodal_database/bjsp_statistic/train/bjsp_statistic_train_v1.json --output_dir /mnt/workspace/intern-vl/SFT/bjsp_statistic/InternVL2_5-26B_sft_lora_bjsp_statistic_v1 --num_train_epochs 1 --per_device_train_batch_size 1 --learning_rate 1e-4 --lora_rank 8 --lora_alpha 32 --gradient_accumulation_steps 16 --eval_steps 50 --save_steps 50 --save_total_limit 2 --logging_steps 1 --max_length 4096 报错如下： ![image](https://private-user-images.githubusercontent.com/55837279/394148728-7f519b2e-be8b-4258-98a6-ba42241824cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjYwNDYsIm5iZiI6MTczNDQyNTc0NiwicGF0aCI6Ii81NTgzNzI3OS8zOTQxNDg3MjgtN2Y1MTliMmUtYmU4Yi00MjU4LTk4YTYtYmE0MjI0MTgyNGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA4NTU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYzUxYjg4NGY2MjVmMjgyNGYyMGUzOTRhNDUwZTBmMTFmN2U3MGE5YzJiZGEwNGI5MTA2MjE5YmQyNjkxOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.15_gj-983bz53jGCQeAD8kk3DtAp4NmhJHlo2N5dUIM)

您好，您微调这个模型用的是多图数据集吗，是的话您方便给个训练数据的样例吗

**Comment by fourierer** [comment]
我的任务是单图，json数据集里面是images:[image1]。如果是多图的话，那就是images:[image1,image2,...,imageX]

**Comment by yangxin60-tal** [comment]
> 我的任务是单图，json数据集里面是images:[image1]。如果是多图的话，那就是images:[image1,image2,...,imageX]

方便给个示例吗，想看下数据具体是怎么组织的

**Comment by fourierer** [comment]
格式大概是这样的，json文件是一个列表，列表里面有很多字典，每个字典是一个训练样本，如果多图的话那么images就会对应到一个多图列表：
[
    {
        "query": "描述下两张图像的差别",
        "images": [
            "xxx/1.jpg",
            "xxx/2.jpg"
        ],
        "response": "xxx"
    },
{},{},{},...
]

**Comment by fourierer** [comment]
--model_type internvl2_5，swift3.0把scale后缀都删掉了

**Comment by yangxin60-tal** [comment]
> 格式大概是这样的，json文件是一个列表，列表里面有很多字典，每个字典是一个训练样本，如果多图的话那么images就会对应到一个多图列表： [ { "query": "描述下两张图像的差别", "images": [ "xxx/1.jpg", "xxx/2.jpg" ], "response": "xxx" }, {},{},{},... ]

这种格式下您知道怎么修改“system”中的内容吗？

**Comment by yangxin60-tal** [comment]
> --model_type internvl2_5，swift3.0把scale后缀都删掉了

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/6e6ef862-37b0-42f9-b1ed-9c369699da45" />
你遇到这个问题没？

**Comment by fourierer** [comment]
> > 格式大概是这样的，json文件是一个列表，列表里面有很多字典，每个字典是一个训练样本，如果多图的话那么images就会对应到一个多图列表： [ { "query": "描述下两张图像的差别", "images": [ "xxx/1.jpg", "xxx/2.jpg" ], "response": "xxx" }, {},{},{},... ]
> 
> 这种格式下您知道怎么修改“system”中的内容吗？

直接在数据集中增加system字段就可以，跟query，images等字段一样，不过swift中应该有默认的system内容吧，我没有修改过

**Comment by yangxin60-tal** [comment]
> > > 格式大概是这样的，json文件是一个列表，列表里面有很多字典，每个字典是一个训练样本，如果多图的话那么images就会对应到一个多图列表： [ { "query": "描述下两张图像的差别", "images": [ "xxx/1.jpg", "xxx/2.jpg" ], "response": "xxx" }, {},{},{},... ]
> > 
> > 
> > 这种格式下您知道怎么修改“system”中的内容吗？
> 
> 直接在数据集中增加system字段就可以，跟query，images等字段一样，不过swift中应该有默认的system内容吧，我没有修改过

query字段中需要加<image>标识吗？

**Comment by fourierer** [comment]
不需要

**Comment by Gary-code** [comment]
如何关掉flash-attn呢请问？

**Comment by Jintao-Huang** [comment]
卸载flash_attn可以试试，具体可以查看internvl2_5的模型定义的代码

**Comment by Jintao-Huang** [comment]
https://modelscope.cn/models/OpenGVLab/InternVL2_5-8B/file/view/master?fileName=modeling_intern_vit.py&status=1#L24
