### ISSUE TITLE
SWIFT3.0 SFT InternVL2d5-8B meets some warnings

### ISSUE THREAD

**Issue by bonre** [modelscope/ms-swift#2629]
感谢贵组的工作，这么快就发版了3.0的版本。
我最近更新了3.0版本，微调是遇到了一些问题，烦请帮我解惑！
报错信息如下：
```
Traceback (most recent call last):
  File "/home/workspace/InternVL_2d5/package/ms-swift-main/swift/llm/dataset/utils.py", line 176, in __getitem__
    res = self.encode_func(data)
  File "/home/workspace/InternVL_2d5/package/ms-swift-main/swift/llm/template/base.py", line 205, in encode
    encoded = self._encode(inputs)
  File "/homeworkspace/InternVL_2d5/package/ms-swift-main/swift/llm/template/template/internvl.py", line 150, in _encode
    assert len(num_patches) == len(
AssertionError: len(num_patches): 1, len(idx_list): 0

[ERROR:swift] 👆👆👆There are errors in the template.encode, and another piece of data will be randomly selected.
```
我以为是图片像素太大导致的这个问题，我的脚本如下：
```
NPROC_PER_NODE=8 \
    swift sft \
        --dataset_num_proc 1 \
        --model /data/base/InternVL2d5 \
        --model_type 'internvl2_5' \
        --output_dir ${OUTPUT_DIR} \
        --torch_dtype 'bfloat16' \
        --gradient_checkpointing true \
        --num_train_epochs 10 \
        --max_steps 2000 \
        --per_device_train_batch_size 1 \
        --per_device_eval_batch_size 1 \
        --gradient_accumulation_steps 4 \
        --train_type 'full' \
        --freeze_vit true \
        --attn_impl 'flash_attn' \
        --dataset /data/1210/internvl2_20241210.json \
        --val_dataset /data/1210/valid/internvl2_20241210_valid.json  \
        --lr_scheduler_type 'cosine' \
        --learning_rate 1e-5 \
        --eval_strategy 'steps' \
        --eval_steps 50 \
        --save_strategy 'steps' \
        --save_steps 50 \
        --save_total_limit 2 \
        --save_only_model True \
        --max_pixels 8847360 \
        --max_length 8192 \
        --deepspeed zero3 \
        --logging_steps 10 > "${OUTPUT_DIR}/train.log" 2>&1 
```
然而，我设置了max_pixels还是会有这个问题，请问是什么原因导致的呢？
数据和之前2.x版本时微调InternVL2-8B使用的一致，2.x版本的swift没有类似的报错。

**Comment by bonre** [comment]
> 看起来像是传入了images, 但是没有找到`<image>`

哦对，之前的版本中，swift是可以默认在query的开头拼接image token，所以我所有的数据里面，query的部分都没有加`<image>`这个token，是这个原因导致的吗？
也就是说，现在的数据里面，需要通过`<image>`明确指明图片的位置，而不能不加该token默认在最前面？

**Comment by Jintao-Huang** [comment]
你试试 重新拉一下最新的代码 再试试

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/pull/2631

**Comment by asfx0412** [comment]
> [@Jintao-Huang](https://github.com/Jintao-Huang) 您好，我这边定位到了问题所在了。 对于这个报错：
> 
> ```
> Traceback (most recent call last):
>   File "/home/workspace/InternVL_2d5/package/ms-swift-main/swift/llm/dataset/utils.py", line 176, in __getitem__
>     res = self.encode_func(data)
>   File "/home/workspace/InternVL_2d5/package/ms-swift-main/swift/llm/template/base.py", line 205, in encode
>     encoded = self._encode(inputs)
>   File "/home/workspace/InternVL_2d5/package/ms-swift-main/swift/llm/template/template/internvl.py", line 150, in _encode
>     assert len(num_patches) == len(
> AssertionError: len(num_patches): 1, len(idx_list): 0
> 
> [ERROR:swift] 👆👆👆There are errors in the template.encode, and another piece of data will be randomly selected.
> ```
> 
> 我发现系数据过长导致的，当数据过长时，就会报错如上，且我在`"role": "user", "content"`中**是否有**`<image>`**都会报错**； 这个过长的长度阈值在哪我并没有测试出来，但我在vscode中观察数据，当超出了vscode的`editor.maxTokenizationLineLength`就一定会报如上错。
> 
> 然后就是这个报错：
> 
> ```
> Traceback (most recent call last):
>   File "/home/workspace/InternVL_2d5/package/swift/swift/llm/dataset/utils.py", line 176, in __getitem__
>     res = self.encode_func(data)
>   File "/home/workspace/InternVL_2d5/package/swift/swift/llm/template/base.py", line 199, in encode
>     self._preprocess_inputs(inputs)
>   File "/home/workspace/InternVL_2d5/package/swift/swift/llm/template/base.py", line 156, in _preprocess_inputs
>     self._add_default_tags(inputs)
>   File "/home/workspace/InternVL_2d5/package/swift/swift/llm/template/base.py", line 470, in _add_default_tags
>     assert num_new_tags >= 0, f'Number of media: {num_media}, number of media_tags: {num_media_tags}'
> AssertionError: Number of media: 1, number of media_tags: 2
> ```
> 
> 这个是由于我的数据里面，存在多轮对话的数据，当两轮的 `"role": "user", "content"` 中都有`<image>`就会报错。 针对上面的两个报错原因，应该如何解决呢？ 这个长度的数据，在swift2.x版本中并没有类似的报错提示， 然后是多轮对话的数据，`<image>`又该如何设置？

您好，请问您解决问题了吗?我也是跟您相同的问题。

**Comment by Jintao-Huang** [comment]
swift版本是什么 升级到最新

**Comment by asfx0412** [comment]
> swift版本是什么 升级到最新

升级到最新版了，找到问题啦！筛选掉无效数据就好了，是<image>标签和数量不匹配问题。谢谢！
