### ISSUE TITLE
qwen2vl-7B的best 微调实践为什么删除了

### ISSUE THREAD

**Issue by gzhuinjune** [modelscope/ms-swift#2632]
开发人员你们辛苦啦！现在里面很多参考内容都被删除了，我非常需要您们提供，我之前微调了glm4，现在它的参考内容也不见了，谢谢你们！！！！！！！

**Comment by Jintao-Huang** [comment]
参考这里哇：https://swift2x.readthedocs.io/zh-cn/latest/
