### ISSUE TITLE
请问v3.0怎么添加自己的训练数据，dataset_info.json和2.x版本变化挺大的

### ISSUE THREAD

**Issue by sifa868** [modelscope/ms-swift#2642]
请问v3.0怎么添加自定义的数据格式，dataset_info.json和2.x版本变化挺大的

**Comment by ia-xu** [comment]
我用这样的方法好像可以
```
from swift.llm.dataset.register import DatasetMeta , register_dataset

train_files = list(Path('/root/training/train').glob('*.json'))
train_files = [str(_) for _ in train_files]

tasks = []
for idx , file in enumerate(train_files):

    register_dataset(
        DatasetMeta(
            f'task_{idx}',
            dataset_path=file,
        )
    )
    tasks.append(f'task_{idx})
```

训练的配置文件使用 

dataset: tasks 

指定训练数据

**Comment by Jintao-Huang** [comment]
https://swift.readthedocs.io/zh-cn/latest/Customization/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86.html

**Comment by rover5056** [comment]
最新版本 直接 dataset 后面接多个 json 会报错,都是绝对路径。。
<img width="776" alt="image" src="https://github.com/user-attachments/assets/177df3bb-37f1-4932-bf15-313178a49394" />

[rank2]: ValueError: The local folder was not found, dataset_id: llava_factory_0508_filtered_img_checked2.jsonl,llava_factory_landmark_zh.json,xxxx.json

**Comment by Jintao-Huang** [comment]
应该是本地路径不存在导致的. 使用os.path.exists 判断一下
