### ISSUE TITLE
OOM Issue During RLHF Training on Qwen2vl-2b/7b Model Using Swift Framework

### ISSUE THREAD

**Issue by lyhh123** [modelscope/ms-swift#2664]
Hello,

I am encountering an Out of Memory (OOM) issue while performing RLHF training on the Qwen2vl-2b/7b model using the Swift framework. My setup includes a single node with 8 H100 GPUs, and the training script is as follows:

```
torchrun $DISTRIBUTED_ARGS swift/cli/rlhf.py \
  --rlhf_type dpo \
  --model_type qwen2-vl-2b-instruct \
  --model_id_or_path /mnt//Multimodal/ms-swift/output/sft-full-qwen2vl-2b-instructlr_1e-5/qwen2-vl-2b-instruct/v0-20241213-173805/checkpoint-1281 \
  --beta 0.1 \
  --rpo_alpha 0.1 \
  --sft_type full \
  --dataset /mnt/13k.jsonl \
  --num_train_epochs 1 \
  --gradient_checkpointing true \
  --batch_size 1 \
  --learning_rate 5e-5 \
  --gradient_accumulation_steps 2 \
  --warmup_ratio 0.03 \
  --save_total_limit 2 \
  --seed 2024 \
  --max_length 4096 \
  --truncation_strategy delete
```

I attempted to reduce max_length to 2048 or 1024 to limit memory usage, but intermittent OOM errors persist. Interestingly, the same parameter setup worked fine during the SFT phase.

The training involves OCR tasks, and some samples have long output tokens. Is there a way to successfully complete RLHF training without reducing max_length or using LoRA?

Thank you in advance!

**Comment by Jintao-Huang** [comment]
Please add the environment variable. SIZE_FACTOR=8 MAX_PIXELS=602112

**Comment by lyhh123** [comment]
Perfect solution, thank you very much!

**Comment by lyhh123** [comment]
Perfect solution, thank you very much!
