### ISSUE TITLE
 cannot import name 'InferEngine' from 'swift.llm' 

### ISSUE THREAD

**Issue by RaoXuan-1998** [modelscope/ms-swift#2683]
按照官方文档安装ms-swift，出现这样的
---------------------------------------------------------------------------
ImportError       Traceback (most recent call last)
Cell In[4], [line 1](vscode-notebook-cell:?execution_count=4&line=1)
----> [1](vscode-notebook-cell:?execution_count=4&line=1) from swift.llm import InferEngine, InferRequest, PtEngine, RequestConfig, load_dataset

ImportError: cannot import name 'InferEngine' from 'swift.llm' (/home/raoxuan/miniconda3/envs/modelscope/lib/python3.10/site-packages/swift/llm/__init__.py)

**Comment by Jintao-Huang** [comment]
use swift3.0

pip install git+https://github.com/modelscope/ms-swift.git
