### ISSUE TITLE
url in readme file is 404

### ISSUE THREAD

**Issue by luguanyu1234** [modelscope/ms-swift#2691]
**Describe the bug**
![image](https://github.com/user-attachments/assets/0b369abb-59c5-4bf2-be81-5d0e9582f136)

all train example url is wrong

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
The readme has been updated.
