### ISSUE TITLE
deepspeed 方式多机多卡启动报错 ValueError: DeepSpeed is not compatible with MP. n_gpu: 8, local_world_size: 1.

### ISSUE THREAD

**Issue by TristaCheng2018** [modelscope/ms-swift#2698]
参考这个教程设置四机八卡训练报错，worker-0:     raise ValueError('DeepSpeed is not compatible with MP. '

https://github.com/modelscope/ms-swift/tree/7a9f5064dcb1116101d864256c94401875e582e5/examples/train/multi-node/deepspeed

加了这个也提醒一样的问题，去掉--hostfile=host.txt 后单机训练无问题
NPROC_PER_NODE=8 \
NNODES=4

按照这个每台机器单独启动也没有问题
https://github.com/modelscope/ms-swift/tree/7a9f5064dcb1116101d864256c94401875e582e5/examples/train/multi-node/swift

但是还是觉得一台机器直接启动使用起来更便捷，劳烦各位大佬帮忙看看是哪里出了问题

swift版本2.6.0

**Comment by Jintao-Huang** [comment]
swift使用3.0

pip install git+https://github.com/modelscope/ms-swift.git
