### ISSUE TITLE
kto训练：ValueError: remaining_argv: ['--train_type', 'sft']

### ISSUE THREAD

**Issue by aacedar** [modelscope/ms-swift#2713]
swift版本： 2.6.1
运行脚本：
swift rlhf \
    --rlhf_type kto \
    --model_revision master \
    --tuner_backend swift \
    --dtype AUTO  \
    --model_type $model_type \
    --model_id_or_path $model_path \
    --dataset $data_path
    ...

错误：
raise ValueError(f'remaining_argv: {remaining_argv}')
ValueError: remaining_argv: ['--train_type', 'sft']

官网的例子里边有这个参数：
nproc_per_node=4
CUDA_VISIBLE_DEVICES=0,1,2,3 \
NPROC_PER_NODE=$nproc_per_node \
swift rlhf \
    --rlhf_type kto \
    --model Qwen/Qwen2-7B-Instruct \
    --train_type lora \
    --dataset AI-ModelScope/ultrafeedback-binarized-preferences-cleaned-kto#10000 \
    --num_train_epochs 2 \
    --learning_rate 1e-4 \
    --lora_rank 8 \
    --lora_alpha 32 \
    --gradient_accumulation_steps $(expr 16 / $nproc_per_node) \
    --gradient_checkpointing_kwargs "{\"use_reentrant\": false}" \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 5

**Comment by Jintao-Huang** [comment]
please use 3.0

pip install git+https://github.com/modelscope/ms-swift.git
