### ISSUE TITLE
Qwen2-Audio SFT 报错

### ISSUE THREAD

**Issue by LiMaPKU** [modelscope/ms-swift#2744]
微调qwen2-audio-7b-instruct，训练数据样例如下：
[
{
"query": "What's the mood of the speaker?",
"response": "Neutral",
"audios": [
"/home/mali/projects/CREMA-D/AudioMP3/1001_IEO_NEU_XX.mp3"
]
},
{
"query": "What's the mood of the speaker?",
"response": "Neutral",
"audios": [
"/home/mali/projects/CREMA-D/AudioMP3/1001_IEO_HAP_LO.mp3"
]
},
]
微调命令如下：
NPROC_PER_NODE=4 CUDA_VISIBLE_DEVICES=5,6,2,3 swift sft --model_type qwen2_audio --model /home/mali/projects/Qwen2-audio/Qwen2-Audio-7B-Instruct-SFT --dataset /home/mali/projects/qwen2-audio-sft/output.json
报错如下：
[rank0]: RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the forward function. Please make sure model pa
rameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in
multiple reentrant backward passes. For example, if you use multiple checkpoint functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant
backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph d
oes not change over iterations.
[rank0]: Parameter at index 447 with name base_model.model.language_model.model.layers.31.mlp.down_proj.lora_B.default.weight has been marked as ready twice. This means that multiple autograd engine hooks ha
ve fired for this particular parameter during this iteration.
库版本如下：
transformers==4.45.0
swift==2.5.0.dev0
哪位大神帮忙看看出了什么问题？

**Comment by Jintao-Huang** [comment]
请使用swift3. 并增加参数 `--gradient_checkpointing_kwargs '{"use_reentrant": false}'`

https://github.com/modelscope/ms-swift/issues/2746
