### ISSUE TITLE
ms-swift 3 or 3.1 版本训练qwen2-vl-2b-instruct时，不能同时启用deepspeed和flash-attn

### ISSUE THREAD

**Issue by NB-wo** [modelscope/ms-swift#2751]
**Describe the bug**
新版本的（3.0和3.1）swift在微调训练qwen2-vl-2b-instruct时，不能同时启用deepspeed和flash-attn，二者分开使用正常。
使用微调训练命令如下：
nproc_per_node=2

MASTER_PORT=29510 \
CUDA_VISIBLE_DEVICES=0,2 \
NPROC_PER_NODE=$nproc_per_node \
SIZE_FACTOR=8 \
MAX_PIXELS=602112 \
swift sft \
  --model $MODEL_PATH \
  --output_dir $OUTPUT_PATH \
  --train_type full \
  --freeze_vit true \
  --dataset $DATASET_PATH \
  --num_train_epochs 2 \
  --max_length 1024 \
  --logging_steps 10 \
  --per_device_train_batch_size 1 \
  --weight_decay 0.1 \
  --learning_rate 2e-5 \
  --max_grad_norm 1 \
  --warmup_ratio 0.05 \
  --eval_steps 1000 \
  --save_steps 1000 \
  --save_total_limit -1 \
  --logging_steps 20 \
  --torch_dtype bfloat16 \
  --gradient_accumulation_steps 1\
  --deepspeed zero2 \
  --attn_impl flash_attn

其中-gradient_accumulation_steps 与  --torch_dtype 尝试过去掉，--deepspeed 尝试过 zero2 zero3 以及offload，都会报错如下：
<img width="553" alt="image" src="https://github.com/user-attachments/assets/6b5d0deb-db31-40f0-a1f8-3b2d916ef584" />

<img width="894" alt="image" src="https://github.com/user-attachments/assets/f1b4a4ad-fc8b-4fbe-a265-27c9a3063546" />

输出可以看到是训练了4个iter后，在rank1上抛出的这个错误。

**Your hardware and system info**
centos conda环境 python310
gcc 尝试过9.5和11.4
pytorch尝试过2.4.0 2.5.0 2.5.1
cuda 11.8
deepspeed  尝试过0.14.0 0.14.4 0.16.2 0.16.0
flash_attn 尝试过2.5.9.post1 2.7.0.post1 2.7.2.post1 2.6.0.post1 （不论是自己编译或是使用已经编好的wheel）
transformer 尝试过4.47 4.44
最终都会回到[rank1]: RuntimeError: cu_seqlens_q must be on CUDA这个报错

**Additional context**
在swift2.4.1版本上可以同时使用deepspeed和flash-attn，但是更新swift到3以上同时使用这两个就会报错。模型换成InternVL2.5 2b 版本可以正常运行

**Comment by ganchun1130** [comment]
> **Describe the bug** 新版本的（3.0和3.1）swift在微调训练qwen2-vl-2b-instruct时，不能同时启用deepspeed和flash-attn，二者分开使用正常。 使用微调训练命令如下： nproc_per_node=2
> 
> MASTER_PORT=29510 CUDA_VISIBLE_DEVICES=0,2 NPROC_PER_NODE=$nproc_per_node SIZE_FACTOR=8 MAX_PIXELS=602112 swift sft --model $MODEL_PATH --output_dir $OUTPUT_PATH --train_type full --freeze_vit true --dataset $DATASET_PATH --num_train_epochs 2 --max_length 1024 --logging_steps 10 --per_device_train_batch_size 1 --weight_decay 0.1 --learning_rate 2e-5 --max_grad_norm 1 --warmup_ratio 0.05 --eval_steps 1000 --save_steps 1000 --save_total_limit -1 --logging_steps 20 --torch_dtype bfloat16 --gradient_accumulation_steps 1 --deepspeed zero2 --attn_impl flash_attn
> 
> 其中-gradient_accumulation_steps 与 --torch_dtype 尝试过去掉，--deepspeed 尝试过 zero2 zero3 以及offload，都会报错如下： <img alt="image" width="553" src="https://private-user-images.githubusercontent.com/59753581/398349757-6b5d0deb-db31-40f0-a1f8-3b2d916ef584.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk1Mjg5OTYsIm5iZiI6MTczOTUyODY5NiwicGF0aCI6Ii81OTc1MzU4MS8zOTgzNDk3NTctNmI1ZDBkZWItZGIzMS00MGYwLWExZjgtM2IyZDkxNmVmNTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE0VDEwMjQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYjc1Mzc1M2Y3MGFkOTIxZDFhZGZmODAwNTYzNDA0MTExYzJhMGE4ZTliYmExY2M0MGEzZjFjZGJhYjFiYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PGVU5bfRbsaUCsu5OAFCpd4HKjy738jkO3_I2qoNPAY">
> 
> <img alt="image" width="894" src="https://private-user-images.githubusercontent.com/59753581/398351758-f1b4a4ad-fc8b-4fbe-a265-27c9a3063546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk1Mjg5OTYsIm5iZiI6MTczOTUyODY5NiwicGF0aCI6Ii81OTc1MzU4MS8zOTgzNTE3NTgtZjFiNGE0YWQtZmM4Yi00ZmJlLWEyNjUtMjdjOWEzMDYzNTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE0VDEwMjQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZTE0ZDY0Y2IwMTA0NzVjYjc0OTliOTZlMzMyNGU1MTBiZDY1NTdiYmJjYzAwYTVhMjFiZWM3MWU1OTYxMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n9rXtt7OccI0nCU5tj0uNK22ydnOUfzqpwZds0pgEkw">
> 输出可以看到是训练了4个iter后，在rank1上抛出的这个错误。
> 
> **Your hardware and system info** centos conda环境 python310 gcc 尝试过9.5和11.4 pytorch尝试过2.4.0 2.5.0 2.5.1 cuda 11.8 deepspeed 尝试过0.14.0 0.14.4 0.16.2 0.16.0 flash_attn 尝试过2.5.9.post1 2.7.0.post1 2.7.2.post1 2.6.0.post1 （不论是自己编译或是使用已经编好的wheel） transformer 尝试过4.47 4.44 最终都会回到[rank1]: RuntimeError: cu_seqlens_q must be on CUDA这个报错
> 
> **Additional context** 在swift2.4.1版本上可以同时使用deepspeed和flash-attn，但是更新swift到3以上同时使用这两个就会报错。模型换成InternVL2.5 2b 版本可以正常运行

请问你是如何解决的？

**Comment by NB-wo** [comment]
> > **Describe the bug** 新版本的（3.0和3.1）swift在微调训练qwen2-vl-2b-instruct时，不能同时启用deepspeed和flash-attn，二者分开使用正常。 使用微调训练命令如下： nproc_per_node=2
> > MASTER_PORT=29510 CUDA_VISIBLE_DEVICES=0,2 NPROC_PER_NODE=$nproc_per_node SIZE_FACTOR=8 MAX_PIXELS=602112 swift sft --model $MODEL_PATH --output_dir $OUTPUT_PATH --train_type full --freeze_vit true --dataset $DATASET_PATH --num_train_epochs 2 --max_length 1024 --logging_steps 10 --per_device_train_batch_size 1 --weight_decay 0.1 --learning_rate 2e-5 --max_grad_norm 1 --warmup_ratio 0.05 --eval_steps 1000 --save_steps 1000 --save_total_limit -1 --logging_steps 20 --torch_dtype bfloat16 --gradient_accumulation_steps 1 --deepspeed zero2 --attn_impl flash_attn
> > 其中-gradient_accumulation_steps 与 --torch_dtype 尝试过去掉，--deepspeed 尝试过 zero2 zero3 以及offload，都会报错如下： <img alt="image" width="553" src="https://private-user-images.githubusercontent.com/59753581/398349757-6b5d0deb-db31-40f0-a1f8-3b2d916ef584.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk1Mjg5OTYsIm5iZiI6MTczOTUyODY5NiwicGF0aCI6Ii81OTc1MzU4MS8zOTgzNDk3NTctNmI1ZDBkZWItZGIzMS00MGYwLWExZjgtM2IyZDkxNmVmNTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE0VDEwMjQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYjc1Mzc1M2Y3MGFkOTIxZDFhZGZmODAwNTYzNDA0MTExYzJhMGE4ZTliYmExY2M0MGEzZjFjZGJhYjFiYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PGVU5bfRbsaUCsu5OAFCpd4HKjy738jkO3_I2qoNPAY">
> > <img alt="image" width="894" src="https://private-user-images.githubusercontent.com/59753581/398351758-f1b4a4ad-fc8b-4fbe-a265-27c9a3063546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk1Mjg5OTYsIm5iZiI6MTczOTUyODY5NiwicGF0aCI6Ii81OTc1MzU4MS8zOTgzNTE3NTgtZjFiNGE0YWQtZmM4Yi00ZmJlLWEyNjUtMjdjOWEzMDYzNTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE0VDEwMjQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZTE0ZDY0Y2IwMTA0NzVjYjc0OTliOTZlMzMyNGU1MTBiZDY1NTdiYmJjYzAwYTVhMjFiZWM3MWU1OTYxMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n9rXtt7OccI0nCU5tj0uNK22ydnOUfzqpwZds0pgEkw">
> > 输出可以看到是训练了4个iter后，在rank1上抛出的这个错误。
> > **Your hardware and system info** centos conda环境 python310 gcc 尝试过9.5和11.4 pytorch尝试过2.4.0 2.5.0 2.5.1 cuda 11.8 deepspeed 尝试过0.14.0 0.14.4 0.16.2 0.16.0 flash_attn 尝试过2.5.9.post1 2.7.0.post1 2.7.2.post1 2.6.0.post1 （不论是自己编译或是使用已经编好的wheel） transformer 尝试过4.47 4.44 最终都会回到[rank1]: RuntimeError: cu_seqlens_q must be on CUDA这个报错
> > **Additional context** 在swift2.4.1版本上可以同时使用deepspeed和flash-attn，但是更新swift到3以上同时使用这两个就会报错。模型换成InternVL2.5 2b 版本可以正常运行
> 
> 请问你是如何解决的？

最新版本的ms-swift解决了
