### ISSUE TITLE
 qwen2-vl-7b-instruct out of memory

### ISSUE THREAD

**Issue by RobinHan24** [modelscope/ms-swift#2753]
my command:
SIZE_FACTOR=8 MAX_PIXELS=602112 CUDA_VISIBLE_DEVICES=0,1,2,3 NPROC_PER_NODE=4 swift sft \
  --model_type qwen2-vl-7b-instruct \
  --model_id_or_path /weights/Qwen2-VL-7B-Instruct/Qwen/Qwen2-VL-7B-Instruct \
  --sft_type lora \
  --deepspeed default-zero2 \
  --dataset /data/train_1224_fold1.json \
  --val_dataset /data/val_1224_fold1.json \
  --ddp_timeout 360000000 \
  --num_train_epochs 3 

my device:  NVIDIA RTX A6000 48G *4 
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 34.83 GiB. GPU 0 has a total capacity of 44.55 GiB of which 22.25 GiB i

could you help me?

**Comment by tastelikefeet** [comment]
Consider:
1. Reduce MAX_PIXELS
2. --deepspeed default-zero3
3. SIZE_FACTOR=8 MAX_PIXELS=602112 CUDA_VISIBLE_DEVICES=0,1,2,3 NPROC_PER_NODE=2, meanwhile remove --deepspeed

**Comment by hl0737** [comment]
需要加
VIDEO_MAX_PIXELS
NFRAMES这两个环境变量，参考https://github.com/modelscope/ms-swift/issues/2743

btw：感觉框架更新不过来了，跟junyang，jingren或者马老师说下= =招点人吧，迭代快点= =

**Comment by Jintao-Huang** [comment]
更新了一些shell: https://github.com/modelscope/ms-swift/tree/main/examples/train/multimodal
