### ISSUE TITLE
ValueError: Please set --model <model_id_or_path>`, model: None

### ISSUE THREAD

**Issue by HITyu4** [modelscope/ms-swift#2770]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

![20241226-132909](https://github.com/user-attachments/assets/5b3ad99a-57f8-4060-aee5-2fbd7d2e108f)

运行 SIZE_FACTOR=8 MAX_PIXELS=602112 NPROC_PER_NODE=4 MASTER_PORT=39700 CUDA_VISIBLE_DEVICES=4,5,6,7 swift sft --model_type qwen2-vl-2b-instruct --model_id_or_path /home/nas01/xiongwenbo/Qwen2-VL-2B-Instruct  --sft_type \ lora   --dataset data1226.jsonl   --deepspeed default-zero3 

出现ValueError: Please set --model <model_id_or_path>`, model: None，想问一下是什么原因

**Comment by Jintao-Huang** [comment]
请查看这里的例子：https://github.com/modelscope/ms-swift/tree/main/examples/train/multimodal


swift3.x与2.x在接口上不兼容

**Comment by HITyu4** [comment]
> 请查看这里的例子：https://github.com/modelscope/ms-swift/tree/main/examples/train/multimodal
> 
> swift3.x与2.x在接口上不兼容

好的了解，问题已解决
