### ISSUE TITLE
swift 2.6, 3.0, 3.1 版本训练同批模型和数据都存在很大差异

### ISSUE THREAD

**Issue by dhhcj1** [modelscope/ms-swift#2789]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
我分别在三个环境下安装了ms swift 2.6，3.0 和 3.1, 其中swift 3.0 和 swift 3.1 命令相同，如下为训练启动命令

swift 3.0，3.1 ：
![image](https://github.com/user-attachments/assets/4f5a6ec6-17da-4748-a74a-b5e4fbbdbc74)
swift 2.6的
![image](https://github.com/user-attachments/assets/2295f2b9-eb54-4961-8e75-92fc9fac55b2)

不同的swift版本使用相同模型，相同的参数，相同数据变化也很大：
2.6 版本的训练时间短，收敛非常快
![企业微信截图_1735288189723](https://github.com/user-attachments/assets/7780e519-7ed4-427a-992c-7ac12eb78975)

3.0 版本的训练时间长，收敛也挺快
![企业微信截图_17352881711903](https://github.com/user-attachments/assets/2ec49e27-372e-431b-a295-15b92859ea84)

3.1 版本训练时间长，收敛也很慢
![企业微信截图_17352881558131](https://github.com/user-attachments/assets/36e629c4-20ce-414b-ba5a-22cefc9dc144)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
transformers版本是什么

**Comment by Jintao-Huang** [comment]
<img width="822" alt="截屏2024-12-27 17 44 48" src="https://github.com/user-attachments/assets/4f9aa051-b047-4406-b57a-0f633c38bb1b" />
```
CUDA_VISIBLE_DEVICES=0 MAX_PIXELS=1003520 swift sft     --model Qwen/Qwen2-VL-7B-Instruct     --train_type lora     --dataset 'AI-ModelScope/LaTeX_OCR:human_handwrite#20000'     --num_train_epochs 1     --per_device_train_batch_size 1     --learning_rate 1e-4     --lora_rank 8     --lora_alpha 32     --gradient_accumulation_steps 16     --eval_steps 100     --save_steps 100     --save_total_limit 2     --logging_steps 5
```

**Comment by Jintao-Huang** [comment]
4.47.1

**Comment by Jintao-Huang** [comment]
参考这里：https://github.com/modelscope/ms-swift/blob/main/examples/train/multimodal/ocr.sh

**Comment by rushzy** [comment]
hi，我也遇到了同样的问题。使用3.0训练速度要不2.5慢三倍左右，请问你解决这个问题了吗

**Comment by Jintao-Huang** [comment]
好的 感谢反馈
