### ISSUE TITLE
安装swift后还需要安装对应模型的depandancy吗

### ISSUE THREAD

**Issue by Li-Jicheng** [modelscope/ms-swift#2798]
你好，请问安装swift以后想要做微调/推理，我是否还需要到模型对应的GitHub page去安装requirements？

**Comment by Jintao-Huang** [comment]
可以参考这里：https://github.com/modelscope/ms-swift/blob/main/requirements/install_all.sh

还有模型对应的依赖：https://swift.readthedocs.io/zh-cn/latest/Instruction/%E6%94%AF%E6%8C%81%E7%9A%84%E6%A8%A1%E5%9E%8B%E5%92%8C%E6%95%B0%E6%8D%AE%E9%9B%86.html
