### ISSUE TITLE
部署swift的时候不能运行pip install -r reuqirements.txt，否则就会有很多环境问题

### ISSUE THREAD

**Issue by Wind2023er** [modelscope/ms-swift#2817]
在部署swift的时候不能运行pip install -r reuqirements.txt，否则就会有很多类似下述问题

    raise NotImplementedError(
NotImplementedError: data_seed requires Accelerate version `accelerate` >= 1.1.0. This is not supported and we recommend you to update your version.
以及其他问题，模块未找到等

具体解释：
在运行以下命令后：

"""
git clone https://github.com/modelscope/ms-swift.git
cd ms-swift
pip install -e .
"""
我创建了一个新的 conda 环境，python=3.10，并运行了 pip install -r reuqirements.txt。

然后出现了如下问题：
    raise NotImplementedError(
NotImplementedError: data_seed requires Accelerate version `accelerate` >= 1.1.0. This is not supported and we recommend you to update your version.
以及其他类似模块未找到的问题。

之后我重做了整个过程，创建了一个新的 conda 环境，python=3.10，但没有运行 pip install -r reuqirements.txt，所有上述问题都消失了。

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/issues/2816
