### ISSUE TITLE
web-ui - LLM训练的 system字段 会导致命令注入

### ISSUE THREAD

**Issue by cutesparrow** [modelscope/ms-swift#363]
system字段会拼接到后台执行的命令，并且用双引号包括，不能正确转义 $ {} - 等特殊字符，存在命令注入。
比如在system字段输入：
`$(touch /tmp/hack.txt)`
点击 `开始训练` 按钮后，`touch /tmp/hack.txt`这条命令会在后台执行。

除了安全风险之外，实际使用中如果system字段包含特殊字符，还会导致训练任务启动失败或者传入参数不符合预期。
请考虑将system字段拼接入 LLM 训练启动命令之前 转义或用单引号包括防止命令注入和运行错误。

The “system” field is concatenated to the command executed in the background and enclosed in double quotes, which does not properly escape special characters such as $, {}, and -, leading to command injection. For example, if you enter in the “system” field:
`$(touch /tmp/hack.txt)`
and then click the “Start Training” button, the command `touch /tmp/hack.txt` will be executed in the background.
Besides the security risks, in practical use, if the “system” field contains special characters, it may cause the training task to fail to start or the parameters passed in to not meet expectations.
Please consider escaping or enclosing the “system” field in single quotes before concatenating it to the LLM training start command to prevent command injection and runtime errors.

step 1. Input payload in system field
<img width="1653" alt="image" src="https://github.com/modelscope/swift/assets/46345059/6e0675c1-4455-478b-9538-6141eab11a5d">
step 2. click "开始训练"
step 3. command has been executed 
<img width="1309" alt="image" src="https://github.com/modelscope/swift/assets/46345059/d785aaa4-dc51-4f32-ae5c-0abf940812ce">

**Comment by tastelikefeet** [comment]
Interesting... Let me check

**Comment by tastelikefeet** [comment]
Fixed by #1835
