### ISSUE TITLE
在网页版的demo中推理仅仅只能进行语言模型的对话，没有多模态的推理

### ISSUE THREAD

**Issue by a2382625920** [modelscope/ms-swift#461]
例如：
我已经微调好了Yi-VL-6B，想使用网页版推理进行对话，但是推理页面没有专门的图片输入选项，只能进行chat，希望可以改进一下

**Comment by a2382625920** [comment]
> 例如： 我已经微调好了Yi-VL-6B，想使用网页版推理进行对话，但是推理页面没有专门的图片输入选项，只能进行chat，希望可以改进一下

不对，应该是yi-vl-6B没有图片的输入也无法进行chat，网页版推理仅对纯语言模型有效

**Comment by Jintao-Huang** [comment]
是的, 网页端暂时不支持多模态模型的推理, 可以使用`swift infer`进行命令行的推理

**Comment by a2382625920** [comment]
> 是的, 网页端暂时不支持多模态模型的推理, 可以使用进行命令行的推理`swift infer`

好的谢谢，那能不能通过一个循环，将一个json文件中的关键字段全部提取出来，然后json中的每个数据都推理一遍

**Comment by a2382625920** [comment]
类似于这样（这是Qwen-VL的批量预测的代码）：
def _load_model_tokenizer():
    tokenizer = AutoTokenizer.from_pretrained(
        DEFAULT_CKPT_PATH, trust_remote_code=True, resume_download=True,
    )

    device_map = "cuda"
    model = AutoPeftModelForCausalLM.from_pretrained(
    DEFAULT_CKPT_PATH, # path to the output directory
    device_map="cuda",
    trust_remote_code=True
    ).eval()
    # model.generation_config = GenerationConfig.from_pretrained(
    #     DEFAULT_CKPT_PATH, trust_remote_code=True, resume_download=True,
    # )

    return model, tokenizer


def _parse_text(text):
    lines = text.split("\n")
    lines = [line for line in lines if line != ""]
    count = 0
    for i, line in enumerate(lines):
        if "```" in line:
            count += 1
            items = line.split("`")
            if count % 2 == 1:
                lines[i] = f'<pre><code class="language-{items[-1]}">'
            else:
                lines[i] = f"<br></code></pre>"
        else:
            if i > 0:
                if count % 2 == 1:
                    line = line.replace("`", r"\`")
                    line = line.replace("<", "&lt;")
                    line = line.replace(">", "&gt;")
                    line = line.replace(" ", "&nbsp;")
                    line = line.replace("*", "&ast;")
                    line = line.replace("_", "&lowbar;")
                    line = line.replace("-", "&#45;")
                    line = line.replace(".", "&#46;")
                    line = line.replace("!", "&#33;")
                    line = line.replace("(", "&#40;")
                    line = line.replace(")", "&#41;")
                    line = line.replace("$", "&#36;")
                lines[i] = "<br>" + line
    text = "".join(lines)
    return text


def predict(message):
    start = time.time()
    message = _parse_text(message)
    print("用户: " + _parse_text(message))
    history = []
    response, history = model.chat(tokenizer, message, history=history)
    full_response = _parse_text(response)
    print("Qwen-VL-Chat: " + _parse_text(full_response))
    print(f"耗时{time.time()-start}")
    return full_response


model, tokenizer = _load_model_tokenizer()

if __name__ == '__main__':
    with open(r'your/path', 'r', encoding='utf-8') as f:
        valid_data = json.load(f)
    data_list = []
    start = time.time()
    for index, i in enumerate(valid_data):
        image_id = i.get("id")
        print(f'进度{index + 1}/{len(valid_data)};{image_id}')
        conversations = i.get("conversations")
        query = conversations[0].get("value")
        true_ = conversations[1].get("value")
        full_response = predict(query)
        print("实际: ", true_)
        data = {"图像名称": image_id, "实际结果": true_, "预测结果": full_response, "查询": query}
        data_list.append(data)
    print(f"耗时{time.time()-start}")

    output_path = 'predict/predict_hzt_WYGPT_0108.json'
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(data_list, f, ensure_ascii=False, indent=2)

    print(f"输出保存在 {output_path}")

**Comment by GUOGUO-lab** [comment]
> 是的, 网页端暂时不支持多模态模型的推理, 可以使用`swift infer`进行命令行的推理

此前的1.5.4版本可以加载qwen-vl-chat，图片的推理也可以用<img>xxx.jpg</img>来进行输入，结果到了1.7.0这个也不支持了，请问这个能恢复吗？
