### ISSUE TITLE
请问能给一点实现动态batch size的建议吗？

### ISSUE THREAD

**Issue by shushanxingzhe** [modelscope/ms-swift#489]
现在训练时样本长短不一，如果batch size设的过大会导致OOM，设的过小GPU算力有没有被利用起来，我想把数据根据大小排序或分组，然后希望训练时能根据根据当前batch的长度来动态调节batch size，达到算力的最优利用，气温能给我一些实现的建议吗？

**Comment by Jintao-Huang** [comment]
可以设计这样的算法:

1. 将数据按长度进行排序.
2. 将数据按batch_size进行分组, 即每个组batch_size个.
3. 对组进行随机排序.

**Comment by shushanxingzhe** [comment]
@Jintao-Huang 谢谢你的回复，我的意思是，在代码的大概什么位置，可以动态的设置每个批次的batch size或者说可以调节每个批次取到的样本数

**Comment by tastelikefeet** [comment]
动态batchsize已经在transformers最新版中支持
