### ISSUE TITLE
请问Qwen-audio的训练速度，阿里官方达到多少？

### ISSUE THREAD

**Issue by luboxu** [modelscope/ms-swift#511]
阿里在训练Qwen-audio-chat模型的时候，机器训练的性能调优到了什么程度：比如1万小时音频用8卡A100，训练一个epoch，需要多长时间？

**Comment by shushanxingzhe** [comment]
我也想问这个问题，希望能了解一下后续训练加速上还有多大的加速可能

**Comment by shushanxingzhe** [comment]
麻烦解答一下识别+翻译的情况下，比如一万小时语音数据集在什么卡上训练耗时大概是怎样
