### ISSUE TITLE
tuner_backend选swift的时候，rsLoRA训练中loss正常下降，但训练后模型推理输出空值

### ISSUE THREAD

**Issue by WSC741606** [modelscope/ms-swift#707]
**Describe the bug**
tuner_backend选swift的时候，rsLoRA训练中loss正常下降，但训练后模型推理输出空值，改成peft后正常

错误推理输出类似

```
<<< 你是谁

--------------------------------------------------
<<< who are you

--------------------------------------------------

```

观察到sft_args.json中lora_target_modules实际值有区别，diff可以看到swift的lora_target_modules是self_attn.\*_proj，而peft的是\*_proj

```
<     "self_attn.o_proj",
<     "mlp.up_proj",
<     "self_attn.q_proj",
<     "self_attn.v_proj",
<     "mlp.down_proj",
<     "self_attn.k_proj",
<     "mlp.gate_proj"
---
>     "k_proj",
>     "q_proj",
>     "down_proj",
>     "v_proj",
>     "up_proj",
>     "o_proj",
>     "gate_proj"
```

好像是最近（2024年4月后，很可能是上星期后）出现的bug，之前没指定tuner_backend都正常训练，看命令行参数说默认swift

**Your hardware and system info**
测试了和硬件无关，和多机数量无关，和数据集无关
用的是最新的swift代码，模型是yi-6B-chat

**Comment by tastelikefeet** [comment]
使用最新的版本，tuner_backend=peft

**Comment by WSC741606** [comment]
嗯嗯明白，当时测试了peft后端就一切正常了
辛苦大佬~

> tuner_backend选swift的时候，rsLoRA训练中loss正常下降，但训练后模型推理输出空值，改成peft后正常
