### ISSUE TITLE
ddp_timeout能否作为sft命令行参数

### ISSUE THREAD

**Issue by WSC741606** [modelscope/ms-swift#773]
**Describe the feature**
指training_args: Seq2SeqTrainingArguments中的ddp_timeout，默认为1800s

**Additional context**
因为我的设备有时候GPU会出现显存正常加载，但是NCCL后端通信有时候拉不起来，结果就显示显存有占用，其他GPU100%负载，没起来的0%负载，功耗几十瓦，这个状态一直持续到1800s超时到报错结束，希望能早一点超时
如果能检查到类似情况自动结束就更好了

**Comment by tastelikefeet** [comment]
Supported by #1836
