### ISSUE TITLE
多模态 minicpmv2的训练，使用的尺寸是多大，原始minicpm v-2的训练尺寸可以很大，查看源码只看到minicpmv2的输入尺寸是448，训练和推理时对于大图会在原图上进行处理吗，还是会统一直接resize缩放到448？

### ISSUE THREAD

**Issue by zhly0** [modelscope/ms-swift#774]
多模态 minicpmv2的训练，使用的尺寸是多大，原始minicpm v-2的训练尺寸可以很大，查看源码只看到minicpmv2的输入尺寸是448，训练和推理时对于大图会在原图上进行处理吗，还是会统一直接resize缩放到448？

**Comment by zhangfan-algo** [comment]
在请教一下 有单独训练视觉模块图生文的代码不

**Comment by zhly0** [comment]
@Jintao-Huang，能帮忙看下吗

**Comment by tastelikefeet** [comment]
minicpm-v系列模型对输入图片应该没有rescale的，因此显存会随着输入图片增大而增大
