### ISSUE TITLE
使用lora微调合并权重加载模型报错

### ISSUE THREAD

**Issue by qianliyx** [modelscope/ms-swift#825]
使用：model, tokenizer = get_model_tokenizer(model_type, model_kwargs={'device_map': 'auto'},model_id_or_path=ckpt_dir)，报错如下：
```bash
Qwen2ForCausalLM.__init__() got an unexpected keyword argument 'eos_token_id'
```
怎么解决呢，合并权重代码：CUDA_VISIBLE_DEVICES=1 swift export --ckpt_dir 'output/qwen1half-7b-chat/---/checkpoint...' --merge_lora true --dtype fp16

**Comment by Jintao-Huang** [comment]
尝试一下main分支, 如果还存在这个问题，请重新打开issue
