### ISSUE TITLE
多机多卡推理

### ISSUE THREAD

**Issue by yu1nY** [modelscope/ms-swift#927]
请问支持多机多卡推理吗？如果支持，多机多卡推理是跟多机多卡训练的示例同样的使用方式吗？
![pic](https://github.com/modelscope/swift/assets/168417892/bf3ded11-6d23-41c2-9f52-8ff76947dbcf)
看上去有点类似于torchrun的启动方式。

**Comment by badmic** [comment]
@yu1nY @Jintao-Huang
大佬们，请问现在可以进行多机多卡的推理了嘛，命令脚本是楼主的截图这种方式嘛

**Comment by tastelikefeet** [comment]
不支持的，多机推理请考虑自行封装k8s
多卡推理是支持的，通过vllm和lmdeploy，具体查看：
https://swift.readthedocs.io/zh-cn/latest/Multi-Modal/vLLM%E6%8E%A8%E7%90%86%E5%8A%A0%E9%80%9F%E6%96%87%E6%A1%A3.html
