### ISSUE TITLE
微调量化后qwen1half-14b-chat-gptq-int8推理时向量报错RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by AnsongLi** [modelscope/ms-swift#994]
基座模型qwen1half-14b-chat，使用lora微调合并后量化qwen1half-14b-chat-gptq-int8。
目前在推理时报错：
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
在使用你们开源的模型Qwen1___5-14B-Chat-GPTQ-Int4时没有报错，但是同样的Qwen1___5-14B-Chat-GPTQ-Int8也报上述相同的错误。
开源的模型transformer版本为4.37.0，我环境的版本4.39.3，torch 2.2.2。

具体原因是什么？该怎么解决这个问题呢？

**Comment by tastelikefeet** [comment]
一般是训崩或量化了，导致推理的时候矩阵计算激活值爆炸了，可以考虑不量化或者重新训一次

**Comment by yingdachen** [comment]
> 我用了官方提供的Qwen2-VL-7B-Instruct-GPTQ-Int8和Qwen2-VL-7B-Instruct-GPTQ-Int4也是报上面相同的错误，请问有人知道怎么解决吗？ 2024-12-24 20:50:53.456341:Traceback (most recent call last): 2024-12-24 20:50:53.456347: File "/opt/code/infer.py", line 15, in 2024-12-24 20:50:53.456495: infer_main() 2024-12-24 20:50:53.456497: File "/opt/code/swift/utils/run_utils.py", line 34, in x_main 2024-12-24 20:50:53.456542: result = llm_x(args, **kwargs) 2024-12-24 20:50:53.456551: File "/opt/code/swift/llm/infer.py", line 558, in llm_infer 2024-12-24 20:50:53.456622: response, _ = inference( 2024-12-24 20:50:53.456624: File "/opt/miniconda3/envs/flash/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context 2024-12-24 20:50:53.456667: return func(*args, **kwargs) 2024-12-24 20:50:53.456669: File "/opt/code/swift/llm/utils/utils.py", line 921, in inference 2024-12-24 20:50:53.456771: generate_ids = model.generate(streamer=streamer, generation_config=generation_config, **inputs) 2024-12-24 20:50:53.456775: File "/opt/miniconda3/envs/flash/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context 2024-12-24 20:50:53.456792: return func(*args, **kwargs) 2024-12-24 20:50:53.456795: File "/opt/miniconda3/envs/flash/lib/python3.10/site-packages/transformers/generation/utils.py", line 2215, in generate 2024-12-24 20:50:53.457009: result = self._sample( 2024-12-24 20:50:53.457012: File "/opt/miniconda3/envs/flash/lib/python3.10/site-packages/transformers/generation/utils.py", line 3249, in _sample 2024-12-24 20:50:53.457280: next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1) 2024-12-24 20:50:53.457284:RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

see official model card:
https://modelscope.cn/models/Qwen/Qwen2-7B-Instruct-GPTQ-Int4

Note: If you encounter RuntimeError: probability tensor contains either `inf`, `nan` or element < 0 during inference with transformer, we recommand installing autogpq>=0.7.1 or [deploying this model with vLLM](https://qwen.readthedocs.io/en/latest/deployment/vllm.html).
